using Element34.StringMetrics;

namespace Element34Tests.Phonetic
{
    [TestClass]
    public class BasicNYSIISTests
    {
        private bool BasicNYSIISTest(string sInput, string sExpected)
        {
            NYSIIS nYSIIS = new NYSIIS();
            return nYSIIS.Encode(sInput) == sExpected;
        }

        [TestMethod] public void NYSIISTest001() { Assert.IsTrue(BasicNYSIISTest("communication", "CANANA[CATAN]")); }
        [TestMethod] public void NYSIISTest002() { Assert.IsTrue(BasicNYSIISTest("worships", "WARSAP")); }
        [TestMethod] public void NYSIISTest003() { Assert.IsTrue(BasicNYSIISTest("televisionhome", "TALAFA[SANAN]")); }
        [TestMethod] public void NYSIISTest004() { Assert.IsTrue(BasicNYSIISTest("bumi", "BAN")); }
        [TestMethod] public void NYSIISTest005() { Assert.IsTrue(BasicNYSIISTest("shortbread", "SHARTB[RAD]")); }
        [TestMethod] public void NYSIISTest006() { Assert.IsTrue(BasicNYSIISTest("slice", "SLAC")); }
        [TestMethod] public void NYSIISTest007() { Assert.IsTrue(BasicNYSIISTest("reint", "RAD")); }
        [TestMethod] public void NYSIISTest008() { Assert.IsTrue(BasicNYSIISTest("Florence", "FLARAN[C]")); }
        [TestMethod] public void NYSIISTest009() { Assert.IsTrue(BasicNYSIISTest("fawzi", "FAS")); }
        [TestMethod] public void NYSIISTest010() { Assert.IsTrue(BasicNYSIISTest("sname", "SNAN")); }
        [TestMethod] public void NYSIISTest011() { Assert.IsTrue(BasicNYSIISTest("modano", "MADAN")); }
        [TestMethod] public void NYSIISTest012() { Assert.IsTrue(BasicNYSIISTest("stumpage", "STANPA[G]")); }
        [TestMethod] public void NYSIISTest013() { Assert.IsTrue(BasicNYSIISTest("clears", "CLAR")); }
        [TestMethod] public void NYSIISTest014() { Assert.IsTrue(BasicNYSIISTest("ciods", "CAD")); }
        [TestMethod] public void NYSIISTest015() { Assert.IsTrue(BasicNYSIISTest("deseos", "DAS")); }
        [TestMethod] public void NYSIISTest016() { Assert.IsTrue(BasicNYSIISTest("dippin", "DAPAN")); }
        [TestMethod] public void NYSIISTest017() { Assert.IsTrue(BasicNYSIISTest("aranna", "ARAN")); }
        [TestMethod] public void NYSIISTest018() { Assert.IsTrue(BasicNYSIISTest("borse", "BARS")); }
        [TestMethod] public void NYSIISTest019() { Assert.IsTrue(BasicNYSIISTest("subic", "SABAC")); }
        [TestMethod] public void NYSIISTest020() { Assert.IsTrue(BasicNYSIISTest("Vidrio", "VADR")); }
        [TestMethod] public void NYSIISTest021() { Assert.IsTrue(BasicNYSIISTest("inserters", "INSART[AR]")); }
        [TestMethod] public void NYSIISTest022() { Assert.IsTrue(BasicNYSIISTest("perature", "PARATA[R]")); }
        [TestMethod] public void NYSIISTest023() { Assert.IsTrue(BasicNYSIISTest("msacideas", "MSACAD")); }
        [TestMethod] public void NYSIISTest024() { Assert.IsTrue(BasicNYSIISTest("cougs", "CAG")); }
        [TestMethod] public void NYSIISTest025() { Assert.IsTrue(BasicNYSIISTest("kittens", "CATAN")); }
        [TestMethod] public void NYSIISTest026() { Assert.IsTrue(BasicNYSIISTest("imperiously", "INPARA[SLY]")); }
        [TestMethod] public void NYSIISTest027() { Assert.IsTrue(BasicNYSIISTest("boccanegra", "BACANA[GR]")); }
        [TestMethod] public void NYSIISTest028() { Assert.IsTrue(BasicNYSIISTest("sextet", "SAXTAT")); }
        [TestMethod] public void NYSIISTest029() { Assert.IsTrue(BasicNYSIISTest("setattributes", "SATATR[ABAT]")); }
        [TestMethod] public void NYSIISTest030() { Assert.IsTrue(BasicNYSIISTest("dsnt", "DSD")); }
        [TestMethod] public void NYSIISTest031() { Assert.IsTrue(BasicNYSIISTest("chubby", "CHABY")); }
        [TestMethod] public void NYSIISTest032() { Assert.IsTrue(BasicNYSIISTest("ooda", "OAD")); }
        [TestMethod] public void NYSIISTest033() { Assert.IsTrue(BasicNYSIISTest("Bressman", "BRASNA[N]")); }
        [TestMethod] public void NYSIISTest034() { Assert.IsTrue(BasicNYSIISTest("calendarnew", "CALAND[ARN]")); }
        [TestMethod] public void NYSIISTest035() { Assert.IsTrue(BasicNYSIISTest("duhon", "DAHAN")); }
        [TestMethod] public void NYSIISTest036() { Assert.IsTrue(BasicNYSIISTest("nchen", "NCAN")); }
        [TestMethod] public void NYSIISTest037() { Assert.IsTrue(BasicNYSIISTest("betjemans", "BATJAN[AN]")); }
        [TestMethod] public void NYSIISTest038() { Assert.IsTrue(BasicNYSIISTest("Mangum", "MANGAN")); }
        [TestMethod] public void NYSIISTest039() { Assert.IsTrue(BasicNYSIISTest("cabac", "CABAC")); }
        [TestMethod] public void NYSIISTest040() { Assert.IsTrue(BasicNYSIISTest("pantys", "PANTY")); }
        [TestMethod] public void NYSIISTest041() { Assert.IsTrue(BasicNYSIISTest("cofactors", "CAFACT[AR]")); }
        [TestMethod] public void NYSIISTest042() { Assert.IsTrue(BasicNYSIISTest("clickz", "CLAC")); }
        [TestMethod] public void NYSIISTest043() { Assert.IsTrue(BasicNYSIISTest("chiap", "CHAP")); }
        [TestMethod] public void NYSIISTest044() { Assert.IsTrue(BasicNYSIISTest("Dalpiaz", "DALP")); }
        [TestMethod] public void NYSIISTest045() { Assert.IsTrue(BasicNYSIISTest("philosophically", "FFALAS[AFACALY]")); }
        [TestMethod] public void NYSIISTest046() { Assert.IsTrue(BasicNYSIISTest("backfill", "BACFAL")); }
        [TestMethod] public void NYSIISTest047() { Assert.IsTrue(BasicNYSIISTest("Murders", "MARDAR")); }
        [TestMethod] public void NYSIISTest048() { Assert.IsTrue(BasicNYSIISTest("ecartis", "ECART")); }
        [TestMethod] public void NYSIISTest049() { Assert.IsTrue(BasicNYSIISTest("vede", "VAD")); }
        [TestMethod] public void NYSIISTest050() { Assert.IsTrue(BasicNYSIISTest("usoe", "US")); }
        [TestMethod] public void NYSIISTest051() { Assert.IsTrue(BasicNYSIISTest("ostara", "OSTAR")); }
        [TestMethod] public void NYSIISTest052() { Assert.IsTrue(BasicNYSIISTest("labourer", "LABARA[R]")); }
        [TestMethod] public void NYSIISTest053() { Assert.IsTrue(BasicNYSIISTest("speir", "SPAR")); }
        [TestMethod] public void NYSIISTest054() { Assert.IsTrue(BasicNYSIISTest("durchaus", "DARC")); }
        [TestMethod] public void NYSIISTest055() { Assert.IsTrue(BasicNYSIISTest("inetformfiller", "INATFA[RNFALAR]")); }
        [TestMethod] public void NYSIISTest056() { Assert.IsTrue(BasicNYSIISTest("itrs", "ITR")); }
        [TestMethod] public void NYSIISTest057() { Assert.IsTrue(BasicNYSIISTest("Tennant", "TANAD")); }
        [TestMethod] public void NYSIISTest058() { Assert.IsTrue(BasicNYSIISTest("bashore", "BASAR")); }
        [TestMethod] public void NYSIISTest059() { Assert.IsTrue(BasicNYSIISTest("lemurian", "LANARA[N]")); }
        [TestMethod] public void NYSIISTest060() { Assert.IsTrue(BasicNYSIISTest("dungannon", "DANGAN[AN]")); }
        [TestMethod] public void NYSIISTest061() { Assert.IsTrue(BasicNYSIISTest("epl", "EPL")); }
        [TestMethod] public void NYSIISTest062() { Assert.IsTrue(BasicNYSIISTest("grader", "GRADAR")); }
        [TestMethod] public void NYSIISTest063() { Assert.IsTrue(BasicNYSIISTest("synchronise", "SYNCRA[NAS]")); }
        [TestMethod] public void NYSIISTest064() { Assert.IsTrue(BasicNYSIISTest("gondorian", "GANDAR[AN]")); }
        [TestMethod] public void NYSIISTest065() { Assert.IsTrue(BasicNYSIISTest("cvnet", "CVNAT")); }
        [TestMethod] public void NYSIISTest066() { Assert.IsTrue(BasicNYSIISTest("Centers", "CANTAR")); }
        [TestMethod] public void NYSIISTest067() { Assert.IsTrue(BasicNYSIISTest("soaks", "SAC")); }
        [TestMethod] public void NYSIISTest068() { Assert.IsTrue(BasicNYSIISTest("gogllle", "GAGL")); }
        [TestMethod] public void NYSIISTest069() { Assert.IsTrue(BasicNYSIISTest("peotone", "PATAN")); }
        [TestMethod] public void NYSIISTest070() { Assert.IsTrue(BasicNYSIISTest("Sharp", "SHARP")); }
        [TestMethod] public void NYSIISTest071() { Assert.IsTrue(BasicNYSIISTest("mawer", "MAR")); }
        [TestMethod] public void NYSIISTest072() { Assert.IsTrue(BasicNYSIISTest("Morasca", "MARASC")); }
        [TestMethod] public void NYSIISTest073() { Assert.IsTrue(BasicNYSIISTest("ticknor", "TACNAR")); }
        [TestMethod] public void NYSIISTest074() { Assert.IsTrue(BasicNYSIISTest("beaverdale", "BAVARD[AL]")); }
        [TestMethod] public void NYSIISTest075() { Assert.IsTrue(BasicNYSIISTest("caledonianew", "CALADA[NAN]")); }
        [TestMethod] public void NYSIISTest076() { Assert.IsTrue(BasicNYSIISTest("wellnessdicke", "WALNAS[DAC]")); }
        [TestMethod] public void NYSIISTest077() { Assert.IsTrue(BasicNYSIISTest("Rodin", "RADAN")); }
        [TestMethod] public void NYSIISTest078() { Assert.IsTrue(BasicNYSIISTest("bluffer", "BLAFAR")); }
        [TestMethod] public void NYSIISTest079() { Assert.IsTrue(BasicNYSIISTest("joey", "JY")); }
        [TestMethod] public void NYSIISTest080() { Assert.IsTrue(BasicNYSIISTest("unbekannter", "UNBACA[NTAR]")); }
        [TestMethod] public void NYSIISTest081() { Assert.IsTrue(BasicNYSIISTest("Baylor", "BAYLAR")); }
        [TestMethod] public void NYSIISTest082() { Assert.IsTrue(BasicNYSIISTest("striplib", "STRAPL[AB]")); }
        [TestMethod] public void NYSIISTest083() { Assert.IsTrue(BasicNYSIISTest("boquete", "BAGAT")); }
        [TestMethod] public void NYSIISTest084() { Assert.IsTrue(BasicNYSIISTest("geylang", "GAYLAN[G]")); }
        [TestMethod] public void NYSIISTest085() { Assert.IsTrue(BasicNYSIISTest("Lavi", "LAV")); }
        [TestMethod] public void NYSIISTest086() { Assert.IsTrue(BasicNYSIISTest("moldovans", "MALDAV[AN]")); }
        [TestMethod] public void NYSIISTest087() { Assert.IsTrue(BasicNYSIISTest("linq", "LANG")); }
        [TestMethod] public void NYSIISTest088() { Assert.IsTrue(BasicNYSIISTest("Kenworthy", "CANWAR[TY]")); }
        [TestMethod] public void NYSIISTest089() { Assert.IsTrue(BasicNYSIISTest("Steckman", "STACNA[N]")); }
        [TestMethod] public void NYSIISTest090() { Assert.IsTrue(BasicNYSIISTest("czechoslovakian", "CSACAS[LAVACAN]")); }
        [TestMethod] public void NYSIISTest091() { Assert.IsTrue(BasicNYSIISTest("marmora", "MARNAR")); }
        [TestMethod] public void NYSIISTest092() { Assert.IsTrue(BasicNYSIISTest("Carvill", "CARVAL")); }
        [TestMethod] public void NYSIISTest093() { Assert.IsTrue(BasicNYSIISTest("chihiro", "CHAHAR")); }
        [TestMethod] public void NYSIISTest094() { Assert.IsTrue(BasicNYSIISTest("hctc", "HCTC")); }
        [TestMethod] public void NYSIISTest095() { Assert.IsTrue(BasicNYSIISTest("nolde", "NALD")); }
        [TestMethod] public void NYSIISTest096() { Assert.IsTrue(BasicNYSIISTest("aerosolized", "AARASA[LASAD]")); }
        [TestMethod] public void NYSIISTest097() { Assert.IsTrue(BasicNYSIISTest("canterbury", "CANTAR[BARY]")); }
        [TestMethod] public void NYSIISTest098() { Assert.IsTrue(BasicNYSIISTest("jss", "JS")); }
        [TestMethod] public void NYSIISTest099() { Assert.IsTrue(BasicNYSIISTest("rmn", "RN")); }
        [TestMethod] public void NYSIISTest100() { Assert.IsTrue(BasicNYSIISTest("mazlish", "MASL")); }
        [TestMethod] public void NYSIISTest101() { Assert.IsTrue(BasicNYSIISTest("faites", "FAT")); }
        [TestMethod] public void NYSIISTest102() { Assert.IsTrue(BasicNYSIISTest("foyer", "FAYAR")); }
        [TestMethod] public void NYSIISTest103() { Assert.IsTrue(BasicNYSIISTest("ductions", "DACTAN")); }
        [TestMethod] public void NYSIISTest104() { Assert.IsTrue(BasicNYSIISTest("Rambo", "RANB")); }
        [TestMethod] public void NYSIISTest105() { Assert.IsTrue(BasicNYSIISTest("Curnutte", "CARNAT")); }
        [TestMethod] public void NYSIISTest106() { Assert.IsTrue(BasicNYSIISTest("Feltus", "FALT")); }
        [TestMethod] public void NYSIISTest107() { Assert.IsTrue(BasicNYSIISTest("forbairt", "FARBAD")); }
        [TestMethod] public void NYSIISTest108() { Assert.IsTrue(BasicNYSIISTest("southerners", "SATARN[AR]")); }
        [TestMethod] public void NYSIISTest109() { Assert.IsTrue(BasicNYSIISTest("hypnotists", "HYPNAT[AST]")); }
        [TestMethod] public void NYSIISTest110() { Assert.IsTrue(BasicNYSIISTest("euphony", "EAFANY")); }
        [TestMethod] public void NYSIISTest111() { Assert.IsTrue(BasicNYSIISTest("mhpa", "MHP")); }
        [TestMethod] public void NYSIISTest112() { Assert.IsTrue(BasicNYSIISTest("matteotti", "MATAT")); }
        [TestMethod] public void NYSIISTest113() { Assert.IsTrue(BasicNYSIISTest("Klande", "CLAND")); }
        [TestMethod] public void NYSIISTest114() { Assert.IsTrue(BasicNYSIISTest("Trudgeon", "TRADGA[N]")); }
        [TestMethod] public void NYSIISTest115() { Assert.IsTrue(BasicNYSIISTest("schoolhill", "SSALAL")); }
        [TestMethod] public void NYSIISTest116() { Assert.IsTrue(BasicNYSIISTest("equalizer", "EGALAS[AR]")); }
        [TestMethod] public void NYSIISTest117() { Assert.IsTrue(BasicNYSIISTest("xnet", "XNAT")); }
        [TestMethod] public void NYSIISTest118() { Assert.IsTrue(BasicNYSIISTest("Thell", "THAL")); }
        [TestMethod] public void NYSIISTest119() { Assert.IsTrue(BasicNYSIISTest("Canel", "CANAL")); }
        [TestMethod] public void NYSIISTest120() { Assert.IsTrue(BasicNYSIISTest("vmetro", "VNATR")); }
        [TestMethod] public void NYSIISTest121() { Assert.IsTrue(BasicNYSIISTest("burgtheater", "BARGTA[TAR]")); }
        [TestMethod] public void NYSIISTest122() { Assert.IsTrue(BasicNYSIISTest("Berlinger", "BARLAN[GAR]")); }
        [TestMethod] public void NYSIISTest123() { Assert.IsTrue(BasicNYSIISTest("crehan", "CRAHAN")); }
        [TestMethod] public void NYSIISTest124() { Assert.IsTrue(BasicNYSIISTest("abysses", "ABYS")); }
        [TestMethod] public void NYSIISTest125() { Assert.IsTrue(BasicNYSIISTest("Hipolito", "HAPALA[T]")); }
        [TestMethod] public void NYSIISTest126() { Assert.IsTrue(BasicNYSIISTest("splintered", "SPLANT[ARAD]")); }
        [TestMethod] public void NYSIISTest127() { Assert.IsTrue(BasicNYSIISTest("maintenace", "MANTAN[AC]")); }
        [TestMethod] public void NYSIISTest128() { Assert.IsTrue(BasicNYSIISTest("decency", "DACANC[Y]")); }
        [TestMethod] public void NYSIISTest129() { Assert.IsTrue(BasicNYSIISTest("quantz", "QANT")); }
        [TestMethod] public void NYSIISTest130() { Assert.IsTrue(BasicNYSIISTest("wette", "WAT")); }
        [TestMethod] public void NYSIISTest131() { Assert.IsTrue(BasicNYSIISTest("Feary", "FARY")); }
        [TestMethod] public void NYSIISTest132() { Assert.IsTrue(BasicNYSIISTest("Cuchiara", "CACAR")); }
        [TestMethod] public void NYSIISTest133() { Assert.IsTrue(BasicNYSIISTest("Arbon", "ARBAN")); }
        [TestMethod] public void NYSIISTest134() { Assert.IsTrue(BasicNYSIISTest("shyness", "SHYNAS")); }
        [TestMethod] public void NYSIISTest135() { Assert.IsTrue(BasicNYSIISTest("Salin", "SALAN")); }
        [TestMethod] public void NYSIISTest136() { Assert.IsTrue(BasicNYSIISTest("Zicafoose", "ZACAFA[S]")); }
        [TestMethod] public void NYSIISTest137() { Assert.IsTrue(BasicNYSIISTest("Menn", "MAN")); }
        [TestMethod] public void NYSIISTest138() { Assert.IsTrue(BasicNYSIISTest("funker", "FANCAR")); }
        [TestMethod] public void NYSIISTest139() { Assert.IsTrue(BasicNYSIISTest("santillan", "SANTAL[AN]")); }
        [TestMethod] public void NYSIISTest140() { Assert.IsTrue(BasicNYSIISTest("punani", "PANAN")); }
        [TestMethod] public void NYSIISTest141() { Assert.IsTrue(BasicNYSIISTest("basa", "BAS")); }
        [TestMethod] public void NYSIISTest142() { Assert.IsTrue(BasicNYSIISTest("bluefin", "BLAFAN")); }
        [TestMethod] public void NYSIISTest143() { Assert.IsTrue(BasicNYSIISTest("cc", "CC")); }
        [TestMethod] public void NYSIISTest144() { Assert.IsTrue(BasicNYSIISTest("zipgenius", "ZAPGAN")); }
        [TestMethod] public void NYSIISTest145() { Assert.IsTrue(BasicNYSIISTest("Kirchen", "CARCAN")); }
        [TestMethod] public void NYSIISTest146() { Assert.IsTrue(BasicNYSIISTest("commentaar", "CANANT[AR]")); }
        [TestMethod] public void NYSIISTest147() { Assert.IsTrue(BasicNYSIISTest("expansive", "EXPANS[AV]")); }
        [TestMethod] public void NYSIISTest148() { Assert.IsTrue(BasicNYSIISTest("castlebar", "CASTLA[BAR]")); }
        [TestMethod] public void NYSIISTest149() { Assert.IsTrue(BasicNYSIISTest("lft", "LFT")); }
        [TestMethod] public void NYSIISTest150() { Assert.IsTrue(BasicNYSIISTest("robla", "RABL")); }
        [TestMethod] public void NYSIISTest151() { Assert.IsTrue(BasicNYSIISTest("zarontin", "ZARANT[AN]")); }
        [TestMethod] public void NYSIISTest152() { Assert.IsTrue(BasicNYSIISTest("nawc", "NAC")); }
        [TestMethod] public void NYSIISTest153() { Assert.IsTrue(BasicNYSIISTest("resolvconf", "RASALV[CANF]")); }
        [TestMethod] public void NYSIISTest154() { Assert.IsTrue(BasicNYSIISTest("networker", "NATWAR[CAR]")); }
        [TestMethod] public void NYSIISTest155() { Assert.IsTrue(BasicNYSIISTest("airlins", "AARLAN")); }
        [TestMethod] public void NYSIISTest156() { Assert.IsTrue(BasicNYSIISTest("Piskel", "PASCAL")); }
        [TestMethod] public void NYSIISTest157() { Assert.IsTrue(BasicNYSIISTest("hilson", "HALSAN")); }
        [TestMethod] public void NYSIISTest158() { Assert.IsTrue(BasicNYSIISTest("deco", "DAC")); }
        [TestMethod] public void NYSIISTest159() { Assert.IsTrue(BasicNYSIISTest("cents", "CANT")); }
        [TestMethod] public void NYSIISTest160() { Assert.IsTrue(BasicNYSIISTest("award", "AWAD")); }
        [TestMethod] public void NYSIISTest161() { Assert.IsTrue(BasicNYSIISTest("reykjanes", "RAYCJA[N]")); }
        [TestMethod] public void NYSIISTest162() { Assert.IsTrue(BasicNYSIISTest("perona", "PARAN")); }
        [TestMethod] public void NYSIISTest163() { Assert.IsTrue(BasicNYSIISTest("epistle", "EPASTL")); }
        [TestMethod] public void NYSIISTest164() { Assert.IsTrue(BasicNYSIISTest("insound", "INSAD")); }
        [TestMethod] public void NYSIISTest165() { Assert.IsTrue(BasicNYSIISTest("qantas", "QANT")); }
        [TestMethod] public void NYSIISTest166() { Assert.IsTrue(BasicNYSIISTest("wholey", "WHALY")); }
        [TestMethod] public void NYSIISTest167() { Assert.IsTrue(BasicNYSIISTest("aragona", "ARAGAN")); }
        [TestMethod] public void NYSIISTest168() { Assert.IsTrue(BasicNYSIISTest("Vancheri", "VANCAR")); }
        [TestMethod] public void NYSIISTest169() { Assert.IsTrue(BasicNYSIISTest("allocution", "ALACAT[AN]")); }
        [TestMethod] public void NYSIISTest170() { Assert.IsTrue(BasicNYSIISTest("volodya", "VALADY")); }
        [TestMethod] public void NYSIISTest171() { Assert.IsTrue(BasicNYSIISTest("enunciate", "ENANCA[T]")); }
        [TestMethod] public void NYSIISTest172() { Assert.IsTrue(BasicNYSIISTest("uuuu", "U")); }
        [TestMethod] public void NYSIISTest173() { Assert.IsTrue(BasicNYSIISTest("Louato", "LAT")); }
        [TestMethod] public void NYSIISTest174() { Assert.IsTrue(BasicNYSIISTest("Marquitta", "MARGAT")); }
        [TestMethod] public void NYSIISTest175() { Assert.IsTrue(BasicNYSIISTest("surmountable", "SARNAN[TABL]")); }
        [TestMethod] public void NYSIISTest176() { Assert.IsTrue(BasicNYSIISTest("gaultier", "GALTAR")); }
        [TestMethod] public void NYSIISTest177() { Assert.IsTrue(BasicNYSIISTest("dafoe", "DAF")); }
        [TestMethod] public void NYSIISTest178() { Assert.IsTrue(BasicNYSIISTest("Claudio", "CLAD")); }
        [TestMethod] public void NYSIISTest179() { Assert.IsTrue(BasicNYSIISTest("ritva", "RATV")); }
        [TestMethod] public void NYSIISTest180() { Assert.IsTrue(BasicNYSIISTest("spunky", "SPANCY")); }
        [TestMethod] public void NYSIISTest181() { Assert.IsTrue(BasicNYSIISTest("npov", "NPAV")); }
        [TestMethod] public void NYSIISTest182() { Assert.IsTrue(BasicNYSIISTest("eurythmics", "EARYTN[AC]")); }
        [TestMethod] public void NYSIISTest183() { Assert.IsTrue(BasicNYSIISTest("skittish", "SCAT")); }
        [TestMethod] public void NYSIISTest184() { Assert.IsTrue(BasicNYSIISTest("scooter", "SCATAR")); }
        [TestMethod] public void NYSIISTest185() { Assert.IsTrue(BasicNYSIISTest("unfermented", "UNFARN[ANTAD]")); }
        [TestMethod] public void NYSIISTest186() { Assert.IsTrue(BasicNYSIISTest("kerridge", "CARADG")); }
        [TestMethod] public void NYSIISTest187() { Assert.IsTrue(BasicNYSIISTest("scenography", "SCANAG[RAFY]")); }
        [TestMethod] public void NYSIISTest188() { Assert.IsTrue(BasicNYSIISTest("sahalee", "SAHALY")); }
        [TestMethod] public void NYSIISTest189() { Assert.IsTrue(BasicNYSIISTest("spooktacular", "SPACTA[CALAR]")); }
        [TestMethod] public void NYSIISTest190() { Assert.IsTrue(BasicNYSIISTest("boissons", "BASAN")); }
        [TestMethod] public void NYSIISTest191() { Assert.IsTrue(BasicNYSIISTest("arbete", "ARBAT")); }
        [TestMethod] public void NYSIISTest192() { Assert.IsTrue(BasicNYSIISTest("Norrick", "NARAC")); }
        [TestMethod] public void NYSIISTest193() { Assert.IsTrue(BasicNYSIISTest("Sonnier", "SANAR")); }
        [TestMethod] public void NYSIISTest194() { Assert.IsTrue(BasicNYSIISTest("gnomeui", "GNAN")); }
        [TestMethod] public void NYSIISTest195() { Assert.IsTrue(BasicNYSIISTest("milian", "MALAN")); }
        [TestMethod] public void NYSIISTest196() { Assert.IsTrue(BasicNYSIISTest("blackplanetcom", "BLACPL[ANATCAN]")); }
        [TestMethod] public void NYSIISTest197() { Assert.IsTrue(BasicNYSIISTest("tuned", "TANAD")); }
        [TestMethod] public void NYSIISTest198() { Assert.IsTrue(BasicNYSIISTest("Salone", "SALAN")); }
        [TestMethod] public void NYSIISTest199() { Assert.IsTrue(BasicNYSIISTest("marathon", "MARATA[N]")); }
        [TestMethod] public void NYSIISTest200() { Assert.IsTrue(BasicNYSIISTest("layoffs", "LAYAF")); }
        [TestMethod] public void NYSIISTest201() { Assert.IsTrue(BasicNYSIISTest("hotek", "HATAC")); }
        [TestMethod] public void NYSIISTest202() { Assert.IsTrue(BasicNYSIISTest("emme", "EN")); }
        [TestMethod] public void NYSIISTest203() { Assert.IsTrue(BasicNYSIISTest("amarasinghe", "ANARAS[ANG]")); }
        [TestMethod] public void NYSIISTest204() { Assert.IsTrue(BasicNYSIISTest("midas", "MAD")); }
        [TestMethod] public void NYSIISTest205() { Assert.IsTrue(BasicNYSIISTest("inhaltsangabe", "INALTS[ANGAB]")); }
        [TestMethod] public void NYSIISTest206() { Assert.IsTrue(BasicNYSIISTest("smow", "SN")); }
        [TestMethod] public void NYSIISTest207() { Assert.IsTrue(BasicNYSIISTest("policing", "PALACA[NG]")); }
        [TestMethod] public void NYSIISTest208() { Assert.IsTrue(BasicNYSIISTest("usmf", "USNF")); }
        [TestMethod] public void NYSIISTest209() { Assert.IsTrue(BasicNYSIISTest("inferred", "INFARA[D]")); }
        [TestMethod] public void NYSIISTest210() { Assert.IsTrue(BasicNYSIISTest("Eaglen", "EAGLAN")); }
        [TestMethod] public void NYSIISTest211() { Assert.IsTrue(BasicNYSIISTest("dralle", "DRAL")); }
        [TestMethod] public void NYSIISTest212() { Assert.IsTrue(BasicNYSIISTest("kalmus", "CALN")); }
        [TestMethod] public void NYSIISTest213() { Assert.IsTrue(BasicNYSIISTest("nork", "NARC")); }
        [TestMethod] public void NYSIISTest214() { Assert.IsTrue(BasicNYSIISTest("Waterston", "WATARS[TAN]")); }
        [TestMethod] public void NYSIISTest215() { Assert.IsTrue(BasicNYSIISTest("penalised", "PANALA[SAD]")); }
        [TestMethod] public void NYSIISTest216() { Assert.IsTrue(BasicNYSIISTest("Lupacchino", "LAPACA[N]")); }
        [TestMethod] public void NYSIISTest217() { Assert.IsTrue(BasicNYSIISTest("getgid", "GATGAD")); }
        [TestMethod] public void NYSIISTest218() { Assert.IsTrue(BasicNYSIISTest("kever", "CAFAR")); }
        [TestMethod] public void NYSIISTest219() { Assert.IsTrue(BasicNYSIISTest("pallavicini", "PALAVA[CAN]")); }
        [TestMethod] public void NYSIISTest220() { Assert.IsTrue(BasicNYSIISTest("Pais", "P")); }
        [TestMethod] public void NYSIISTest221() { Assert.IsTrue(BasicNYSIISTest("youghiogheny", "YAGAGA[NY]")); }
        [TestMethod] public void NYSIISTest222() { Assert.IsTrue(BasicNYSIISTest("Catherina", "CATARA[N]")); }
        [TestMethod] public void NYSIISTest223() { Assert.IsTrue(BasicNYSIISTest("Givant", "GAVAD")); }
        [TestMethod] public void NYSIISTest224() { Assert.IsTrue(BasicNYSIISTest("koffi", "CAF")); }
        [TestMethod] public void NYSIISTest225() { Assert.IsTrue(BasicNYSIISTest("troutbeck", "TRATBA[C]")); }
        [TestMethod] public void NYSIISTest226() { Assert.IsTrue(BasicNYSIISTest("moreelse", "MARALS")); }
        [TestMethod] public void NYSIISTest227() { Assert.IsTrue(BasicNYSIISTest("seacrest", "SACRAS[T]")); }
        [TestMethod] public void NYSIISTest228() { Assert.IsTrue(BasicNYSIISTest("ufj", "UFJ")); }
        [TestMethod] public void NYSIISTest229() { Assert.IsTrue(BasicNYSIISTest("dereferences", "DARAFA[RANC]")); }
        [TestMethod] public void NYSIISTest230() { Assert.IsTrue(BasicNYSIISTest("sarena", "SARAN")); }
        [TestMethod] public void NYSIISTest231() { Assert.IsTrue(BasicNYSIISTest("Kurt", "CAD")); }
        [TestMethod] public void NYSIISTest232() { Assert.IsTrue(BasicNYSIISTest("comanche", "CANANC")); }
        [TestMethod] public void NYSIISTest233() { Assert.IsTrue(BasicNYSIISTest("chersoness", "CHARSA[NAS]")); }
        [TestMethod] public void NYSIISTest234() { Assert.IsTrue(BasicNYSIISTest("cd", "CD")); }
        [TestMethod] public void NYSIISTest235() { Assert.IsTrue(BasicNYSIISTest("merzky", "MARSCY")); }
        [TestMethod] public void NYSIISTest236() { Assert.IsTrue(BasicNYSIISTest("Nordsiek", "NARDSA[C]")); }
        [TestMethod] public void NYSIISTest237() { Assert.IsTrue(BasicNYSIISTest("samus", "SAN")); }
        [TestMethod] public void NYSIISTest238() { Assert.IsTrue(BasicNYSIISTest("tougher", "TAGAR")); }
        [TestMethod] public void NYSIISTest239() { Assert.IsTrue(BasicNYSIISTest("monodoc", "MANADA[C]")); }
        [TestMethod] public void NYSIISTest240() { Assert.IsTrue(BasicNYSIISTest("deepings", "DAPANG")); }
        [TestMethod] public void NYSIISTest241() { Assert.IsTrue(BasicNYSIISTest("datel", "DATAL")); }
        [TestMethod] public void NYSIISTest242() { Assert.IsTrue(BasicNYSIISTest("Stockett", "STACAT")); }
        [TestMethod] public void NYSIISTest243() { Assert.IsTrue(BasicNYSIISTest("bryum", "BRYAN")); }
        [TestMethod] public void NYSIISTest244() { Assert.IsTrue(BasicNYSIISTest("surveyed", "SARVAY[AD]")); }
        [TestMethod] public void NYSIISTest245() { Assert.IsTrue(BasicNYSIISTest("microcephaly", "MACRAC[AFALY]")); }
        [TestMethod] public void NYSIISTest246() { Assert.IsTrue(BasicNYSIISTest("trimoxazole", "TRANAX[ASAL]")); }
        [TestMethod] public void NYSIISTest247() { Assert.IsTrue(BasicNYSIISTest("bastide", "BASTAD")); }
        [TestMethod] public void NYSIISTest248() { Assert.IsTrue(BasicNYSIISTest("lipo", "LAP")); }
        [TestMethod] public void NYSIISTest249() { Assert.IsTrue(BasicNYSIISTest("Bosket", "BASCAT")); }
        [TestMethod] public void NYSIISTest250() { Assert.IsTrue(BasicNYSIISTest("oroms", "ORAN")); }
        [TestMethod] public void NYSIISTest251() { Assert.IsTrue(BasicNYSIISTest("vandenburg", "VANDAN[BARG]")); }
        [TestMethod] public void NYSIISTest252() { Assert.IsTrue(BasicNYSIISTest("wirtschaftsforschung", "WARTSA[FTSFARSANG]")); }
        [TestMethod] public void NYSIISTest253() { Assert.IsTrue(BasicNYSIISTest("lilypond", "LALYPA[D]")); }
        [TestMethod] public void NYSIISTest254() { Assert.IsTrue(BasicNYSIISTest("mouthfeel", "MATFAL")); }
        [TestMethod] public void NYSIISTest255() { Assert.IsTrue(BasicNYSIISTest("wwwunibancocombr", "WWANAB[ANCACANBR]")); }
        [TestMethod] public void NYSIISTest256() { Assert.IsTrue(BasicNYSIISTest("Worster", "WARSTA[R]")); }
        [TestMethod] public void NYSIISTest257() { Assert.IsTrue(BasicNYSIISTest("Ahmad", "AHNAD")); }
        [TestMethod] public void NYSIISTest258() { Assert.IsTrue(BasicNYSIISTest("sweetser", "SWATSA[R]")); }
        [TestMethod] public void NYSIISTest259() { Assert.IsTrue(BasicNYSIISTest("vsepr", "VSAPR")); }
        [TestMethod] public void NYSIISTest260() { Assert.IsTrue(BasicNYSIISTest("dput", "DPAT")); }
        [TestMethod] public void NYSIISTest261() { Assert.IsTrue(BasicNYSIISTest("austlit", "AASTLA[T]")); }
        [TestMethod] public void NYSIISTest262() { Assert.IsTrue(BasicNYSIISTest("Clemen", "CLANAN")); }
        [TestMethod] public void NYSIISTest263() { Assert.IsTrue(BasicNYSIISTest("phrva", "FFRV")); }
        [TestMethod] public void NYSIISTest264() { Assert.IsTrue(BasicNYSIISTest("weipa", "WAP")); }
        [TestMethod] public void NYSIISTest265() { Assert.IsTrue(BasicNYSIISTest("Schrantz", "SSRANT")); }
        [TestMethod] public void NYSIISTest266() { Assert.IsTrue(BasicNYSIISTest("meany", "MANY")); }
        [TestMethod] public void NYSIISTest267() { Assert.IsTrue(BasicNYSIISTest("hodgepodge", "HADGAP[ADG]")); }
        [TestMethod] public void NYSIISTest268() { Assert.IsTrue(BasicNYSIISTest("knuble", "NNABL")); }
        [TestMethod] public void NYSIISTest269() { Assert.IsTrue(BasicNYSIISTest("caniglia", "CANAGL")); }
        [TestMethod] public void NYSIISTest270() { Assert.IsTrue(BasicNYSIISTest("blowjobsasics", "BLAJAB[SASAC]")); }
        [TestMethod] public void NYSIISTest271() { Assert.IsTrue(BasicNYSIISTest("flyjacket", "FLYJAC[AT]")); }
        [TestMethod] public void NYSIISTest272() { Assert.IsTrue(BasicNYSIISTest("galatian", "GALATA[N]")); }
        [TestMethod] public void NYSIISTest273() { Assert.IsTrue(BasicNYSIISTest("hotsel", "HATSAL")); }
        [TestMethod] public void NYSIISTest274() { Assert.IsTrue(BasicNYSIISTest("autorun", "AATARA[N]")); }
        [TestMethod] public void NYSIISTest275() { Assert.IsTrue(BasicNYSIISTest("cocoon", "CACAN")); }
        [TestMethod] public void NYSIISTest276() { Assert.IsTrue(BasicNYSIISTest("kooks", "CAC")); }
        [TestMethod] public void NYSIISTest277() { Assert.IsTrue(BasicNYSIISTest("endocrinol", "ENDACR[ANAL]")); }
        [TestMethod] public void NYSIISTest278() { Assert.IsTrue(BasicNYSIISTest("mesages", "MASAG")); }
        [TestMethod] public void NYSIISTest279() { Assert.IsTrue(BasicNYSIISTest("Disney", "DASNY")); }
        [TestMethod] public void NYSIISTest280() { Assert.IsTrue(BasicNYSIISTest("speedline", "SPADLA[N]")); }
        [TestMethod] public void NYSIISTest281() { Assert.IsTrue(BasicNYSIISTest("gabaldon", "GABALD[AN]")); }
        [TestMethod] public void NYSIISTest282() { Assert.IsTrue(BasicNYSIISTest("margaux", "MARGAX")); }
        [TestMethod] public void NYSIISTest283() { Assert.IsTrue(BasicNYSIISTest("housecalls", "HASACA[L]")); }
        [TestMethod] public void NYSIISTest284() { Assert.IsTrue(BasicNYSIISTest("siltation", "SALTAT[AN]")); }
        [TestMethod] public void NYSIISTest285() { Assert.IsTrue(BasicNYSIISTest("automatic", "AATANA[TAC]")); }
        [TestMethod] public void NYSIISTest286() { Assert.IsTrue(BasicNYSIISTest("freakshow", "FRACS")); }
        [TestMethod] public void NYSIISTest287() { Assert.IsTrue(BasicNYSIISTest("gorojovsky", "GARAJA[VSCY]")); }
        [TestMethod] public void NYSIISTest288() { Assert.IsTrue(BasicNYSIISTest("milwaukie", "MALWAC[Y]")); }
        [TestMethod] public void NYSIISTest289() { Assert.IsTrue(BasicNYSIISTest("wwwgap", "WWGAP")); }
        [TestMethod] public void NYSIISTest290() { Assert.IsTrue(BasicNYSIISTest("autm", "AATN")); }
        [TestMethod] public void NYSIISTest291() { Assert.IsTrue(BasicNYSIISTest("borromini", "BARANA[N]")); }
        [TestMethod] public void NYSIISTest292() { Assert.IsTrue(BasicNYSIISTest("zpp", "ZP")); }
        [TestMethod] public void NYSIISTest293() { Assert.IsTrue(BasicNYSIISTest("Penovich", "PANAVA[C]")); }
        [TestMethod] public void NYSIISTest294() { Assert.IsTrue(BasicNYSIISTest("domine", "DANAN")); }
        [TestMethod] public void NYSIISTest295() { Assert.IsTrue(BasicNYSIISTest("caves", "CAV")); }
        [TestMethod] public void NYSIISTest296() { Assert.IsTrue(BasicNYSIISTest("uato", "UAT")); }
        [TestMethod] public void NYSIISTest297() { Assert.IsTrue(BasicNYSIISTest("tiltonsville", "TALTAN[SVAL]")); }
        [TestMethod] public void NYSIISTest298() { Assert.IsTrue(BasicNYSIISTest("Ken", "CAN")); }
        [TestMethod] public void NYSIISTest299() { Assert.IsTrue(BasicNYSIISTest("Delonais", "DALAN")); }
        [TestMethod] public void NYSIISTest300() { Assert.IsTrue(BasicNYSIISTest("conniption", "CANAPT[AN]")); }
        [TestMethod] public void NYSIISTest301() { Assert.IsTrue(BasicNYSIISTest("Wenske", "WANSC")); }
        [TestMethod] public void NYSIISTest302() { Assert.IsTrue(BasicNYSIISTest("cautery", "CATARY")); }
        [TestMethod] public void NYSIISTest303() { Assert.IsTrue(BasicNYSIISTest("barbourville", "BARBAR[VAL]")); }
        [TestMethod] public void NYSIISTest304() { Assert.IsTrue(BasicNYSIISTest("departamentos", "DAPART[ANANT]")); }
        [TestMethod] public void NYSIISTest305() { Assert.IsTrue(BasicNYSIISTest("weaponry", "WAPANR[Y]")); }
        [TestMethod] public void NYSIISTest306() { Assert.IsTrue(BasicNYSIISTest("Haggett", "HAGAT")); }
        [TestMethod] public void NYSIISTest307() { Assert.IsTrue(BasicNYSIISTest("martinville", "MARTAN[VAL]")); }
        [TestMethod] public void NYSIISTest308() { Assert.IsTrue(BasicNYSIISTest("stina", "STAN")); }
        [TestMethod] public void NYSIISTest309() { Assert.IsTrue(BasicNYSIISTest("Rubottom", "RABATA[N]")); }
        [TestMethod] public void NYSIISTest310() { Assert.IsTrue(BasicNYSIISTest("Soyke", "SAYC")); }
        [TestMethod] public void NYSIISTest311() { Assert.IsTrue(BasicNYSIISTest("corse", "CARS")); }
        [TestMethod] public void NYSIISTest312() { Assert.IsTrue(BasicNYSIISTest("totalling", "TATALA[NG]")); }
        [TestMethod] public void NYSIISTest313() { Assert.IsTrue(BasicNYSIISTest("kuppam", "CAPAN")); }
        [TestMethod] public void NYSIISTest314() { Assert.IsTrue(BasicNYSIISTest("ftpadmin", "FTPADN[AN]")); }
        [TestMethod] public void NYSIISTest315() { Assert.IsTrue(BasicNYSIISTest("Forst", "FARST")); }
        [TestMethod] public void NYSIISTest316() { Assert.IsTrue(BasicNYSIISTest("Ashauer", "ASAR")); }
        [TestMethod] public void NYSIISTest317() { Assert.IsTrue(BasicNYSIISTest("ashtanga", "ASTANG")); }
        [TestMethod] public void NYSIISTest318() { Assert.IsTrue(BasicNYSIISTest("alonissos", "ALANAS")); }
        [TestMethod] public void NYSIISTest319() { Assert.IsTrue(BasicNYSIISTest("Chimilio", "CHANAL")); }
        [TestMethod] public void NYSIISTest320() { Assert.IsTrue(BasicNYSIISTest("deafbazon", "DAFBAS[AN]")); }
        [TestMethod] public void NYSIISTest321() { Assert.IsTrue(BasicNYSIISTest("psmb", "PSNB")); }
        [TestMethod] public void NYSIISTest322() { Assert.IsTrue(BasicNYSIISTest("Ferraraccio", "FARARA[C]")); }
        [TestMethod] public void NYSIISTest323() { Assert.IsTrue(BasicNYSIISTest("fractionated", "FRACTA[NATAD]")); }
        [TestMethod] public void NYSIISTest324() { Assert.IsTrue(BasicNYSIISTest("rrd", "RD")); }
        [TestMethod] public void NYSIISTest325() { Assert.IsTrue(BasicNYSIISTest("luminosities", "LANANA[SAT]")); }
        [TestMethod] public void NYSIISTest326() { Assert.IsTrue(BasicNYSIISTest("Platzer", "PLATSA[R]")); }
        [TestMethod] public void NYSIISTest327() { Assert.IsTrue(BasicNYSIISTest("modulator", "MADALA[TAR]")); }
        [TestMethod] public void NYSIISTest328() { Assert.IsTrue(BasicNYSIISTest("tyneside", "TYNASA[D]")); }
        [TestMethod] public void NYSIISTest329() { Assert.IsTrue(BasicNYSIISTest("nonuser", "NANASA[R]")); }
        [TestMethod] public void NYSIISTest330() { Assert.IsTrue(BasicNYSIISTest("haspel", "HASPAL")); }
        [TestMethod] public void NYSIISTest331() { Assert.IsTrue(BasicNYSIISTest("cortex", "CARTAX")); }
        [TestMethod] public void NYSIISTest332() { Assert.IsTrue(BasicNYSIISTest("vechicle", "VACACL")); }
        [TestMethod] public void NYSIISTest333() { Assert.IsTrue(BasicNYSIISTest("epinions", "EPANAN")); }
        [TestMethod] public void NYSIISTest334() { Assert.IsTrue(BasicNYSIISTest("wwwusmintgov", "WWASNA[NTGAV]")); }
        [TestMethod] public void NYSIISTest335() { Assert.IsTrue(BasicNYSIISTest("katies", "CAT")); }
        [TestMethod] public void NYSIISTest336() { Assert.IsTrue(BasicNYSIISTest("aminosalicylic", "ANANAS[ALACYLAC]")); }
        [TestMethod] public void NYSIISTest337() { Assert.IsTrue(BasicNYSIISTest("mmegi", "MNAG")); }
        [TestMethod] public void NYSIISTest338() { Assert.IsTrue(BasicNYSIISTest("sbir", "SBAR")); }
        [TestMethod] public void NYSIISTest339() { Assert.IsTrue(BasicNYSIISTest("learned", "LARNAD")); }
        [TestMethod] public void NYSIISTest340() { Assert.IsTrue(BasicNYSIISTest("supris", "SAPR")); }
        [TestMethod] public void NYSIISTest341() { Assert.IsTrue(BasicNYSIISTest("mozarteum", "MASART[AN]")); }
        [TestMethod] public void NYSIISTest342() { Assert.IsTrue(BasicNYSIISTest("selzer", "SALSAR")); }
        [TestMethod] public void NYSIISTest343() { Assert.IsTrue(BasicNYSIISTest("tmug", "TNAG")); }
        [TestMethod] public void NYSIISTest344() { Assert.IsTrue(BasicNYSIISTest("Kisto", "CAST")); }
        [TestMethod] public void NYSIISTest345() { Assert.IsTrue(BasicNYSIISTest("iib", "IAB")); }
        [TestMethod] public void NYSIISTest346() { Assert.IsTrue(BasicNYSIISTest("wwwincredimail", "WWANCR[ADANAL]")); }
        [TestMethod] public void NYSIISTest347() { Assert.IsTrue(BasicNYSIISTest("izpack", "ISPAC")); }
        [TestMethod] public void NYSIISTest348() { Assert.IsTrue(BasicNYSIISTest("gaymovie", "GAYNAV[Y]")); }
        [TestMethod] public void NYSIISTest349() { Assert.IsTrue(BasicNYSIISTest("Buchholz", "BACHAL")); }
        [TestMethod] public void NYSIISTest350() { Assert.IsTrue(BasicNYSIISTest("culcairn", "CALCAR[N]")); }
        [TestMethod] public void NYSIISTest351() { Assert.IsTrue(BasicNYSIISTest("barys", "BARY")); }
        [TestMethod] public void NYSIISTest352() { Assert.IsTrue(BasicNYSIISTest("burets", "BARAT")); }
        [TestMethod] public void NYSIISTest353() { Assert.IsTrue(BasicNYSIISTest("Sorce", "SARC")); }
        [TestMethod] public void NYSIISTest354() { Assert.IsTrue(BasicNYSIISTest("chimique", "CHANAG")); }
        [TestMethod] public void NYSIISTest355() { Assert.IsTrue(BasicNYSIISTest("kitada", "CATAD")); }
        [TestMethod] public void NYSIISTest356() { Assert.IsTrue(BasicNYSIISTest("Engeman", "ENGANA[N]")); }
        [TestMethod] public void NYSIISTest357() { Assert.IsTrue(BasicNYSIISTest("raveendran", "RAVAND[RAN]")); }
        [TestMethod] public void NYSIISTest358() { Assert.IsTrue(BasicNYSIISTest("Bendele", "BANDAL")); }
        [TestMethod] public void NYSIISTest359() { Assert.IsTrue(BasicNYSIISTest("Pawlitschek", "PALATS[AC]")); }
        [TestMethod] public void NYSIISTest360() { Assert.IsTrue(BasicNYSIISTest("hogfather", "HAGFAT[AR]")); }
        [TestMethod] public void NYSIISTest361() { Assert.IsTrue(BasicNYSIISTest("eyedrum", "EYADRA[N]")); }
        [TestMethod] public void NYSIISTest362() { Assert.IsTrue(BasicNYSIISTest("Ferrara", "FARAR")); }
        [TestMethod] public void NYSIISTest363() { Assert.IsTrue(BasicNYSIISTest("zhuh", "ZHAH")); }
        [TestMethod] public void NYSIISTest364() { Assert.IsTrue(BasicNYSIISTest("zodiak", "ZADAC")); }
        [TestMethod] public void NYSIISTest365() { Assert.IsTrue(BasicNYSIISTest("pchcom", "PCAN")); }
        [TestMethod] public void NYSIISTest366() { Assert.IsTrue(BasicNYSIISTest("conferees", "CANFAR")); }
        [TestMethod] public void NYSIISTest367() { Assert.IsTrue(BasicNYSIISTest("Decillis", "DACAL")); }
        [TestMethod] public void NYSIISTest368() { Assert.IsTrue(BasicNYSIISTest("downloar", "DANLAR")); }
        [TestMethod] public void NYSIISTest369() { Assert.IsTrue(BasicNYSIISTest("shard", "SHAD")); }
        [TestMethod] public void NYSIISTest370() { Assert.IsTrue(BasicNYSIISTest("fajr", "FAJR")); }
        [TestMethod] public void NYSIISTest371() { Assert.IsTrue(BasicNYSIISTest("quisque", "QASG")); }
        [TestMethod] public void NYSIISTest372() { Assert.IsTrue(BasicNYSIISTest("winterizing", "WANTAR[ASANG]")); }
        [TestMethod] public void NYSIISTest373() { Assert.IsTrue(BasicNYSIISTest("referate", "RAFARA[T]")); }
        [TestMethod] public void NYSIISTest374() { Assert.IsTrue(BasicNYSIISTest("nuxone", "NAXAN")); }
        [TestMethod] public void NYSIISTest375() { Assert.IsTrue(BasicNYSIISTest("Racheal", "RACAL")); }
        [TestMethod] public void NYSIISTest376() { Assert.IsTrue(BasicNYSIISTest("bizben", "BASBAN")); }
        [TestMethod] public void NYSIISTest377() { Assert.IsTrue(BasicNYSIISTest("musictalk", "MASACT[ALC]")); }
        [TestMethod] public void NYSIISTest378() { Assert.IsTrue(BasicNYSIISTest("ogoal", "OGAL")); }
        [TestMethod] public void NYSIISTest379() { Assert.IsTrue(BasicNYSIISTest("Skoff", "SCAF")); }
        [TestMethod] public void NYSIISTest380() { Assert.IsTrue(BasicNYSIISTest("Seehusen", "SAHASA[N]")); }
        [TestMethod] public void NYSIISTest381() { Assert.IsTrue(BasicNYSIISTest("Reim", "RAN")); }
        [TestMethod] public void NYSIISTest382() { Assert.IsTrue(BasicNYSIISTest("Yoh", "YAH")); }
        [TestMethod] public void NYSIISTest383() { Assert.IsTrue(BasicNYSIISTest("gapi", "GAP")); }
        [TestMethod] public void NYSIISTest384() { Assert.IsTrue(BasicNYSIISTest("Brightbill", "BRAGTB[AL]")); }
        [TestMethod] public void NYSIISTest385() { Assert.IsTrue(BasicNYSIISTest("shuey", "SHY")); }
        [TestMethod] public void NYSIISTest386() { Assert.IsTrue(BasicNYSIISTest("posium", "PASAN")); }
        [TestMethod] public void NYSIISTest387() { Assert.IsTrue(BasicNYSIISTest("Falknor", "FALNAR")); }
        [TestMethod] public void NYSIISTest388() { Assert.IsTrue(BasicNYSIISTest("ucat", "UCAT")); }
        [TestMethod] public void NYSIISTest389() { Assert.IsTrue(BasicNYSIISTest("properspace", "PRAPAR[SPAC]")); }
        [TestMethod] public void NYSIISTest390() { Assert.IsTrue(BasicNYSIISTest("showimg", "SHANG")); }
        [TestMethod] public void NYSIISTest391() { Assert.IsTrue(BasicNYSIISTest("Montecillo", "MANTAC[AL]")); }
        [TestMethod] public void NYSIISTest392() { Assert.IsTrue(BasicNYSIISTest("sajak", "SAJAC")); }
        [TestMethod] public void NYSIISTest393() { Assert.IsTrue(BasicNYSIISTest("maturbation", "MATARB[ATAN]")); }
        [TestMethod] public void NYSIISTest394() { Assert.IsTrue(BasicNYSIISTest("Lettie", "LATY")); }
        [TestMethod] public void NYSIISTest395() { Assert.IsTrue(BasicNYSIISTest("clauss", "CLAS")); }
        [TestMethod] public void NYSIISTest396() { Assert.IsTrue(BasicNYSIISTest("scheiber", "SSABAR")); }
        [TestMethod] public void NYSIISTest397() { Assert.IsTrue(BasicNYSIISTest("matp", "MATP")); }
        [TestMethod] public void NYSIISTest398() { Assert.IsTrue(BasicNYSIISTest("mervtormel", "MARVTA[RNAL]")); }
        [TestMethod] public void NYSIISTest399() { Assert.IsTrue(BasicNYSIISTest("guanahani", "GANAHA[N]")); }
        [TestMethod] public void NYSIISTest400() { Assert.IsTrue(BasicNYSIISTest("citement", "CATANA[D]")); }
        [TestMethod] public void NYSIISTest401() { Assert.IsTrue(BasicNYSIISTest("immu", "IN")); }
        [TestMethod] public void NYSIISTest402() { Assert.IsTrue(BasicNYSIISTest("virulence", "VARALA[NC]")); }
        [TestMethod] public void NYSIISTest403() { Assert.IsTrue(BasicNYSIISTest("kussa", "CAS")); }
        [TestMethod] public void NYSIISTest404() { Assert.IsTrue(BasicNYSIISTest("gso", "GS")); }
        [TestMethod] public void NYSIISTest405() { Assert.IsTrue(BasicNYSIISTest("webviajes", "WABVAJ")); }
        [TestMethod] public void NYSIISTest406() { Assert.IsTrue(BasicNYSIISTest("ldwork", "LDWARC")); }
        [TestMethod] public void NYSIISTest407() { Assert.IsTrue(BasicNYSIISTest("verses", "VARS")); }
        [TestMethod] public void NYSIISTest408() { Assert.IsTrue(BasicNYSIISTest("sondes", "SAND")); }
        [TestMethod] public void NYSIISTest409() { Assert.IsTrue(BasicNYSIISTest("freshpair", "FRASPA[R]")); }
        [TestMethod] public void NYSIISTest410() { Assert.IsTrue(BasicNYSIISTest("licorne", "LACARN")); }
        [TestMethod] public void NYSIISTest411() { Assert.IsTrue(BasicNYSIISTest("Vanis", "VAN")); }
        [TestMethod] public void NYSIISTest412() { Assert.IsTrue(BasicNYSIISTest("Buena", "BAN")); }
        [TestMethod] public void NYSIISTest413() { Assert.IsTrue(BasicNYSIISTest("Tauares", "TAR")); }
        [TestMethod] public void NYSIISTest414() { Assert.IsTrue(BasicNYSIISTest("ikus", "IC")); }
        [TestMethod] public void NYSIISTest415() { Assert.IsTrue(BasicNYSIISTest("genrebox", "GANRAB[AX]")); }
        [TestMethod] public void NYSIISTest416() { Assert.IsTrue(BasicNYSIISTest("rth", "RT")); }
        [TestMethod] public void NYSIISTest417() { Assert.IsTrue(BasicNYSIISTest("Spaun", "SPAN")); }
        [TestMethod] public void NYSIISTest418() { Assert.IsTrue(BasicNYSIISTest("wiersbe", "WARSB")); }
        [TestMethod] public void NYSIISTest419() { Assert.IsTrue(BasicNYSIISTest("dad", "DAD")); }
        [TestMethod] public void NYSIISTest420() { Assert.IsTrue(BasicNYSIISTest("tus", "T")); }
        [TestMethod] public void NYSIISTest421() { Assert.IsTrue(BasicNYSIISTest("Weidert", "WADAD")); }
        [TestMethod] public void NYSIISTest422() { Assert.IsTrue(BasicNYSIISTest("rijke", "RAJC")); }
        [TestMethod] public void NYSIISTest423() { Assert.IsTrue(BasicNYSIISTest("fischbein", "FASBAN")); }
        [TestMethod] public void NYSIISTest424() { Assert.IsTrue(BasicNYSIISTest("fbeye", "FBAY")); }
        [TestMethod] public void NYSIISTest425() { Assert.IsTrue(BasicNYSIISTest("hagerty", "HAGART[Y]")); }
        [TestMethod] public void NYSIISTest426() { Assert.IsTrue(BasicNYSIISTest("Hollendonner", "HALAND[ANAR]")); }
        [TestMethod] public void NYSIISTest427() { Assert.IsTrue(BasicNYSIISTest("Huitzacua", "HATSAC")); }
        [TestMethod] public void NYSIISTest428() { Assert.IsTrue(BasicNYSIISTest("subjunctive", "SABJAN[CTAV]")); }
        [TestMethod] public void NYSIISTest429() { Assert.IsTrue(BasicNYSIISTest("implored", "INPLAR[AD]")); }
        [TestMethod] public void NYSIISTest430() { Assert.IsTrue(BasicNYSIISTest("pompeius", "PANP")); }
        [TestMethod] public void NYSIISTest431() { Assert.IsTrue(BasicNYSIISTest("afleet", "AFLAT")); }
        [TestMethod] public void NYSIISTest432() { Assert.IsTrue(BasicNYSIISTest("iacc", "IAC")); }
        [TestMethod] public void NYSIISTest433() { Assert.IsTrue(BasicNYSIISTest("sabalos", "SABAL")); }
        [TestMethod] public void NYSIISTest434() { Assert.IsTrue(BasicNYSIISTest("Abdi", "ABD")); }
        [TestMethod] public void NYSIISTest435() { Assert.IsTrue(BasicNYSIISTest("microinsurance", "MACRAN[SARANC]")); }
        [TestMethod] public void NYSIISTest436() { Assert.IsTrue(BasicNYSIISTest("audiobook", "AADABA[C]")); }
        [TestMethod] public void NYSIISTest437() { Assert.IsTrue(BasicNYSIISTest("fulpmes", "FALPN")); }
        [TestMethod] public void NYSIISTest438() { Assert.IsTrue(BasicNYSIISTest("registreren", "RAGAST[RARAN]")); }
        [TestMethod] public void NYSIISTest439() { Assert.IsTrue(BasicNYSIISTest("megapath", "MAGAPA[T]")); }
        [TestMethod] public void NYSIISTest440() { Assert.IsTrue(BasicNYSIISTest("prestidigitation", "PRASTA[DAGATATAN]")); }
        [TestMethod] public void NYSIISTest441() { Assert.IsTrue(BasicNYSIISTest("wby", "WBY")); }
        [TestMethod] public void NYSIISTest442() { Assert.IsTrue(BasicNYSIISTest("vorschau", "VARS")); }
        [TestMethod] public void NYSIISTest443() { Assert.IsTrue(BasicNYSIISTest("Albertha", "ALBART")); }
        [TestMethod] public void NYSIISTest444() { Assert.IsTrue(BasicNYSIISTest("aspalpha", "ASPALF")); }
        [TestMethod] public void NYSIISTest445() { Assert.IsTrue(BasicNYSIISTest("Belden", "BALDAN")); }
        [TestMethod] public void NYSIISTest446() { Assert.IsTrue(BasicNYSIISTest("deterministic", "DATARN[ANASTAC]")); }
        [TestMethod] public void NYSIISTest447() { Assert.IsTrue(BasicNYSIISTest("philosophique", "FFALAS[AFAG]")); }
        [TestMethod] public void NYSIISTest448() { Assert.IsTrue(BasicNYSIISTest("kleinen", "CLANAN")); }
        [TestMethod] public void NYSIISTest449() { Assert.IsTrue(BasicNYSIISTest("logouri", "LAGAR")); }
        [TestMethod] public void NYSIISTest450() { Assert.IsTrue(BasicNYSIISTest("xbl", "XBL")); }
        [TestMethod] public void NYSIISTest451() { Assert.IsTrue(BasicNYSIISTest("iz", "I")); }
        [TestMethod] public void NYSIISTest452() { Assert.IsTrue(BasicNYSIISTest("throckmorton", "THRACN[ARTAN]")); }
        [TestMethod] public void NYSIISTest453() { Assert.IsTrue(BasicNYSIISTest("condesa", "CANDAS")); }
        [TestMethod] public void NYSIISTest454() { Assert.IsTrue(BasicNYSIISTest("Mook", "MAC")); }
        [TestMethod] public void NYSIISTest455() { Assert.IsTrue(BasicNYSIISTest("medseek", "MADSAC")); }
        [TestMethod] public void NYSIISTest456() { Assert.IsTrue(BasicNYSIISTest("chugalug", "CHAGAL[AG]")); }
        [TestMethod] public void NYSIISTest457() { Assert.IsTrue(BasicNYSIISTest("olms", "OLN")); }
        [TestMethod] public void NYSIISTest458() { Assert.IsTrue(BasicNYSIISTest("bogo", "BAG")); }
        [TestMethod] public void NYSIISTest459() { Assert.IsTrue(BasicNYSIISTest("essing", "ESANG")); }
        [TestMethod] public void NYSIISTest460() { Assert.IsTrue(BasicNYSIISTest("rarden", "RARDAN")); }
        [TestMethod] public void NYSIISTest461() { Assert.IsTrue(BasicNYSIISTest("mittlere", "MATLAR")); }
        [TestMethod] public void NYSIISTest462() { Assert.IsTrue(BasicNYSIISTest("Borsa", "BARS")); }
        [TestMethod] public void NYSIISTest463() { Assert.IsTrue(BasicNYSIISTest("Ainslie", "AANSLY")); }
        [TestMethod] public void NYSIISTest464() { Assert.IsTrue(BasicNYSIISTest("Ganska", "GANSC")); }
        [TestMethod] public void NYSIISTest465() { Assert.IsTrue(BasicNYSIISTest("miv", "MAV")); }
        [TestMethod] public void NYSIISTest466() { Assert.IsTrue(BasicNYSIISTest("concessions", "CANCAS[AN]")); }
        [TestMethod] public void NYSIISTest467() { Assert.IsTrue(BasicNYSIISTest("distinguished", "DASTAN[GASAD]")); }
        [TestMethod] public void NYSIISTest468() { Assert.IsTrue(BasicNYSIISTest("cano", "CAN")); }
        [TestMethod] public void NYSIISTest469() { Assert.IsTrue(BasicNYSIISTest("plumper", "PLANPA[R]")); }
        [TestMethod] public void NYSIISTest470() { Assert.IsTrue(BasicNYSIISTest("mindoro", "MANDAR")); }
        [TestMethod] public void NYSIISTest471() { Assert.IsTrue(BasicNYSIISTest("cephalopod", "CAFALA[PAD]")); }
        [TestMethod] public void NYSIISTest472() { Assert.IsTrue(BasicNYSIISTest("Klunk", "CLANC")); }
        [TestMethod] public void NYSIISTest473() { Assert.IsTrue(BasicNYSIISTest("Bumbrey", "BANBRY")); }
        [TestMethod] public void NYSIISTest474() { Assert.IsTrue(BasicNYSIISTest("causeless", "CASALA[S]")); }
        [TestMethod] public void NYSIISTest475() { Assert.IsTrue(BasicNYSIISTest("Lothrop", "LATRAP")); }
        [TestMethod] public void NYSIISTest476() { Assert.IsTrue(BasicNYSIISTest("bodystyles", "BADYST[YL]")); }
        [TestMethod] public void NYSIISTest477() { Assert.IsTrue(BasicNYSIISTest("beaatiality", "BATALA[TY]")); }
        [TestMethod] public void NYSIISTest478() { Assert.IsTrue(BasicNYSIISTest("Bobrowski", "BABRAS[C]")); }
        [TestMethod] public void NYSIISTest479() { Assert.IsTrue(BasicNYSIISTest("erudition", "ERADAT[AN]")); }
        [TestMethod] public void NYSIISTest480() { Assert.IsTrue(BasicNYSIISTest("huttner", "HATNAR")); }
        [TestMethod] public void NYSIISTest481() { Assert.IsTrue(BasicNYSIISTest("wwwaskjeevescom", "WWASCJ[AFASCAN]")); }
        [TestMethod] public void NYSIISTest482() { Assert.IsTrue(BasicNYSIISTest("Duross", "DARAS")); }
        [TestMethod] public void NYSIISTest483() { Assert.IsTrue(BasicNYSIISTest("Colemen", "CALANA[N]")); }
        [TestMethod] public void NYSIISTest484() { Assert.IsTrue(BasicNYSIISTest("Duncomb", "DANCAN[B]")); }
        [TestMethod] public void NYSIISTest485() { Assert.IsTrue(BasicNYSIISTest("tripe", "TRAP")); }
        [TestMethod] public void NYSIISTest486() { Assert.IsTrue(BasicNYSIISTest("dorrigo", "DARAG")); }
        [TestMethod] public void NYSIISTest487() { Assert.IsTrue(BasicNYSIISTest("Mascall", "MASCAL")); }
        [TestMethod] public void NYSIISTest488() { Assert.IsTrue(BasicNYSIISTest("jetplane", "JATPLA[N]")); }
        [TestMethod] public void NYSIISTest489() { Assert.IsTrue(BasicNYSIISTest("nswrl", "NSWRL")); }
        [TestMethod] public void NYSIISTest490() { Assert.IsTrue(BasicNYSIISTest("didates", "DADAT")); }
        [TestMethod] public void NYSIISTest491() { Assert.IsTrue(BasicNYSIISTest("Jena", "JAN")); }
        [TestMethod] public void NYSIISTest492() { Assert.IsTrue(BasicNYSIISTest("kctu", "CCT")); }
        [TestMethod] public void NYSIISTest493() { Assert.IsTrue(BasicNYSIISTest("cualquiera", "CALGAR")); }
        [TestMethod] public void NYSIISTest494() { Assert.IsTrue(BasicNYSIISTest("plutella", "PLATAL")); }
        [TestMethod] public void NYSIISTest495() { Assert.IsTrue(BasicNYSIISTest("Liebig", "LABAG")); }
        [TestMethod] public void NYSIISTest496() { Assert.IsTrue(BasicNYSIISTest("Llorens", "LLARAN")); }
        [TestMethod] public void NYSIISTest497() { Assert.IsTrue(BasicNYSIISTest("mraz", "MR")); }
        [TestMethod] public void NYSIISTest498() { Assert.IsTrue(BasicNYSIISTest("shadyac", "SHADYA[C]")); }
        [TestMethod] public void NYSIISTest499() { Assert.IsTrue(BasicNYSIISTest("lossphentermine", "LASFAN[TARNAN]")); }
        [TestMethod] public void NYSIISTest500() { Assert.IsTrue(BasicNYSIISTest("Dreith", "DRAT")); }

    }
}