using Element34.StringMetrics;

namespace Element34Tests.Phonetic
{
    [TestClass]
    public class BasicSoundExTests
    {
        private bool BasicSoundExTest(string sInput, string sExpected)
        {
            SoundEx soundEx = new SoundEx();
            return soundEx.Encode(sInput) == sExpected;
        }
        [TestMethod] public void BasicSoundExTest001() { Assert.IsTrue(BasicSoundExTest("communication", "C552")); }
        [TestMethod] public void BasicSoundExTest002() { Assert.IsTrue(BasicSoundExTest("worships", "W621")); }
        [TestMethod] public void BasicSoundExTest003() { Assert.IsTrue(BasicSoundExTest("televisionhome", "T412")); }
        [TestMethod] public void BasicSoundExTest004() { Assert.IsTrue(BasicSoundExTest("bumi", "B500")); }
        [TestMethod] public void BasicSoundExTest005() { Assert.IsTrue(BasicSoundExTest("shortbread", "S631")); }
        [TestMethod] public void BasicSoundExTest006() { Assert.IsTrue(BasicSoundExTest("slice", "S420")); }
        [TestMethod] public void BasicSoundExTest007() { Assert.IsTrue(BasicSoundExTest("reint", "R530")); }
        [TestMethod] public void BasicSoundExTest008() { Assert.IsTrue(BasicSoundExTest("Florence", "F465")); }
        [TestMethod] public void BasicSoundExTest009() { Assert.IsTrue(BasicSoundExTest("fawzi", "F200")); }
        [TestMethod] public void BasicSoundExTest010() { Assert.IsTrue(BasicSoundExTest("sname", "S550")); }
        [TestMethod] public void BasicSoundExTest011() { Assert.IsTrue(BasicSoundExTest("modano", "M350")); }
        [TestMethod] public void BasicSoundExTest012() { Assert.IsTrue(BasicSoundExTest("stumpage", "S351")); }
        [TestMethod] public void BasicSoundExTest013() { Assert.IsTrue(BasicSoundExTest("clears", "C462")); }
        [TestMethod] public void BasicSoundExTest014() { Assert.IsTrue(BasicSoundExTest("ciods", "C320")); }
        [TestMethod] public void BasicSoundExTest015() { Assert.IsTrue(BasicSoundExTest("deseos", "D220")); }
        [TestMethod] public void BasicSoundExTest016() { Assert.IsTrue(BasicSoundExTest("dippin", "D150")); }
        [TestMethod] public void BasicSoundExTest017() { Assert.IsTrue(BasicSoundExTest("aranna", "A650")); }
        [TestMethod] public void BasicSoundExTest018() { Assert.IsTrue(BasicSoundExTest("borse", "B620")); }
        [TestMethod] public void BasicSoundExTest019() { Assert.IsTrue(BasicSoundExTest("subic", "S120")); }
        [TestMethod] public void BasicSoundExTest020() { Assert.IsTrue(BasicSoundExTest("Vidrio", "V360")); }
        [TestMethod] public void BasicSoundExTest021() { Assert.IsTrue(BasicSoundExTest("inserters", "I526")); }
        [TestMethod] public void BasicSoundExTest022() { Assert.IsTrue(BasicSoundExTest("perature", "P636")); }
        [TestMethod] public void BasicSoundExTest023() { Assert.IsTrue(BasicSoundExTest("msacideas", "M223")); }
        [TestMethod] public void BasicSoundExTest024() { Assert.IsTrue(BasicSoundExTest("cougs", "C200")); }
        [TestMethod] public void BasicSoundExTest025() { Assert.IsTrue(BasicSoundExTest("kittens", "K352")); }
        [TestMethod] public void BasicSoundExTest026() { Assert.IsTrue(BasicSoundExTest("imperiously", "I516")); }
        [TestMethod] public void BasicSoundExTest027() { Assert.IsTrue(BasicSoundExTest("boccanegra", "B252")); }
        [TestMethod] public void BasicSoundExTest028() { Assert.IsTrue(BasicSoundExTest("sextet", "S233")); }
        [TestMethod] public void BasicSoundExTest029() { Assert.IsTrue(BasicSoundExTest("setattributes", "S336")); }
        [TestMethod] public void BasicSoundExTest030() { Assert.IsTrue(BasicSoundExTest("dsnt", "D253")); }
        [TestMethod] public void BasicSoundExTest031() { Assert.IsTrue(BasicSoundExTest("chubby", "C100")); }
        [TestMethod] public void BasicSoundExTest032() { Assert.IsTrue(BasicSoundExTest("ooda", "O300")); }
        [TestMethod] public void BasicSoundExTest033() { Assert.IsTrue(BasicSoundExTest("Bressman", "B625")); }
        [TestMethod] public void BasicSoundExTest034() { Assert.IsTrue(BasicSoundExTest("calendarnew", "C453")); }
        [TestMethod] public void BasicSoundExTest035() { Assert.IsTrue(BasicSoundExTest("duhon", "D500")); }
        [TestMethod] public void BasicSoundExTest036() { Assert.IsTrue(BasicSoundExTest("nchen", "N250")); }
        [TestMethod] public void BasicSoundExTest037() { Assert.IsTrue(BasicSoundExTest("betjemans", "B325")); }
        [TestMethod] public void BasicSoundExTest038() { Assert.IsTrue(BasicSoundExTest("Mangum", "M525")); }
        [TestMethod] public void BasicSoundExTest039() { Assert.IsTrue(BasicSoundExTest("cabac", "C120")); }
        [TestMethod] public void BasicSoundExTest040() { Assert.IsTrue(BasicSoundExTest("pantys", "P532")); }
        [TestMethod] public void BasicSoundExTest041() { Assert.IsTrue(BasicSoundExTest("cofactors", "C123")); }
        [TestMethod] public void BasicSoundExTest042() { Assert.IsTrue(BasicSoundExTest("clickz", "C420")); }
        [TestMethod] public void BasicSoundExTest043() { Assert.IsTrue(BasicSoundExTest("chiap", "C100")); }
        [TestMethod] public void BasicSoundExTest044() { Assert.IsTrue(BasicSoundExTest("Dalpiaz", "D412")); }
        [TestMethod] public void BasicSoundExTest045() { Assert.IsTrue(BasicSoundExTest("philosophically", "P421")); }
        [TestMethod] public void BasicSoundExTest046() { Assert.IsTrue(BasicSoundExTest("backfill", "B214")); }
        [TestMethod] public void BasicSoundExTest047() { Assert.IsTrue(BasicSoundExTest("Murders", "M636")); }
        [TestMethod] public void BasicSoundExTest048() { Assert.IsTrue(BasicSoundExTest("ecartis", "E263")); }
        [TestMethod] public void BasicSoundExTest049() { Assert.IsTrue(BasicSoundExTest("vede", "V300")); }
        [TestMethod] public void BasicSoundExTest050() { Assert.IsTrue(BasicSoundExTest("usoe", "U200")); }
        [TestMethod] public void BasicSoundExTest051() { Assert.IsTrue(BasicSoundExTest("ostara", "O236")); }
        [TestMethod] public void BasicSoundExTest052() { Assert.IsTrue(BasicSoundExTest("labourer", "L166")); }
        [TestMethod] public void BasicSoundExTest053() { Assert.IsTrue(BasicSoundExTest("speir", "S160")); }
        [TestMethod] public void BasicSoundExTest054() { Assert.IsTrue(BasicSoundExTest("durchaus", "D622")); }
        [TestMethod] public void BasicSoundExTest055() { Assert.IsTrue(BasicSoundExTest("inetformfiller", "I531")); }
        [TestMethod] public void BasicSoundExTest056() { Assert.IsTrue(BasicSoundExTest("itrs", "I362")); }
        [TestMethod] public void BasicSoundExTest057() { Assert.IsTrue(BasicSoundExTest("Tennant", "T553")); }
        [TestMethod] public void BasicSoundExTest058() { Assert.IsTrue(BasicSoundExTest("bashore", "B260")); }
        [TestMethod] public void BasicSoundExTest059() { Assert.IsTrue(BasicSoundExTest("lemurian", "L565")); }
        [TestMethod] public void BasicSoundExTest060() { Assert.IsTrue(BasicSoundExTest("dungannon", "D525")); }
        [TestMethod] public void BasicSoundExTest061() { Assert.IsTrue(BasicSoundExTest("epl", "E140")); }
        [TestMethod] public void BasicSoundExTest062() { Assert.IsTrue(BasicSoundExTest("grader", "G636")); }
        [TestMethod] public void BasicSoundExTest063() { Assert.IsTrue(BasicSoundExTest("synchronise", "S526")); }
        [TestMethod] public void BasicSoundExTest064() { Assert.IsTrue(BasicSoundExTest("gondorian", "G536")); }
        [TestMethod] public void BasicSoundExTest065() { Assert.IsTrue(BasicSoundExTest("cvnet", "C153")); }
        [TestMethod] public void BasicSoundExTest066() { Assert.IsTrue(BasicSoundExTest("Centers", "C536")); }
        [TestMethod] public void BasicSoundExTest067() { Assert.IsTrue(BasicSoundExTest("soaks", "S200")); }
        [TestMethod] public void BasicSoundExTest068() { Assert.IsTrue(BasicSoundExTest("gogllle", "G240")); }
        [TestMethod] public void BasicSoundExTest069() { Assert.IsTrue(BasicSoundExTest("peotone", "P350")); }
        [TestMethod] public void BasicSoundExTest070() { Assert.IsTrue(BasicSoundExTest("Sharp", "S610")); }
        [TestMethod] public void BasicSoundExTest071() { Assert.IsTrue(BasicSoundExTest("mawer", "M600")); }
        [TestMethod] public void BasicSoundExTest072() { Assert.IsTrue(BasicSoundExTest("Morasca", "M620")); }
        [TestMethod] public void BasicSoundExTest073() { Assert.IsTrue(BasicSoundExTest("ticknor", "T256")); }
        [TestMethod] public void BasicSoundExTest074() { Assert.IsTrue(BasicSoundExTest("beaverdale", "B163")); }
        [TestMethod] public void BasicSoundExTest075() { Assert.IsTrue(BasicSoundExTest("caledonianew", "C435")); }
        [TestMethod] public void BasicSoundExTest076() { Assert.IsTrue(BasicSoundExTest("wellnessdicke", "W452")); }
        [TestMethod] public void BasicSoundExTest077() { Assert.IsTrue(BasicSoundExTest("Rodin", "R350")); }
        [TestMethod] public void BasicSoundExTest078() { Assert.IsTrue(BasicSoundExTest("bluffer", "B416")); }
        [TestMethod] public void BasicSoundExTest079() { Assert.IsTrue(BasicSoundExTest("joey", "J000")); }
        [TestMethod] public void BasicSoundExTest080() { Assert.IsTrue(BasicSoundExTest("unbekannter", "U512")); }
        [TestMethod] public void BasicSoundExTest081() { Assert.IsTrue(BasicSoundExTest("Baylor", "B460")); }
        [TestMethod] public void BasicSoundExTest082() { Assert.IsTrue(BasicSoundExTest("striplib", "S361")); }
        [TestMethod] public void BasicSoundExTest083() { Assert.IsTrue(BasicSoundExTest("boquete", "B230")); }
        [TestMethod] public void BasicSoundExTest084() { Assert.IsTrue(BasicSoundExTest("geylang", "G452")); }
        [TestMethod] public void BasicSoundExTest085() { Assert.IsTrue(BasicSoundExTest("Lavi", "L100")); }
        [TestMethod] public void BasicSoundExTest086() { Assert.IsTrue(BasicSoundExTest("moldovans", "M431")); }
        [TestMethod] public void BasicSoundExTest087() { Assert.IsTrue(BasicSoundExTest("linq", "L520")); }
        [TestMethod] public void BasicSoundExTest088() { Assert.IsTrue(BasicSoundExTest("Kenworthy", "K563")); }
        [TestMethod] public void BasicSoundExTest089() { Assert.IsTrue(BasicSoundExTest("Steckman", "S325")); }
        [TestMethod] public void BasicSoundExTest090() { Assert.IsTrue(BasicSoundExTest("czechoslovakian", "C224")); }
        [TestMethod] public void BasicSoundExTest091() { Assert.IsTrue(BasicSoundExTest("marmora", "M656")); }
        [TestMethod] public void BasicSoundExTest092() { Assert.IsTrue(BasicSoundExTest("Carvill", "C614")); }
        [TestMethod] public void BasicSoundExTest093() { Assert.IsTrue(BasicSoundExTest("chihiro", "C600")); }
        [TestMethod] public void BasicSoundExTest094() { Assert.IsTrue(BasicSoundExTest("hctc", "H232")); }
        [TestMethod] public void BasicSoundExTest095() { Assert.IsTrue(BasicSoundExTest("nolde", "N430")); }
        [TestMethod] public void BasicSoundExTest096() { Assert.IsTrue(BasicSoundExTest("aerosolized", "A624")); }
        [TestMethod] public void BasicSoundExTest097() { Assert.IsTrue(BasicSoundExTest("canterbury", "C536")); }
        [TestMethod] public void BasicSoundExTest098() { Assert.IsTrue(BasicSoundExTest("jss", "J000")); }
        [TestMethod] public void BasicSoundExTest099() { Assert.IsTrue(BasicSoundExTest("rmn", "R500")); }
        [TestMethod] public void BasicSoundExTest100() { Assert.IsTrue(BasicSoundExTest("mazlish", "M242")); }
        [TestMethod] public void BasicSoundExTest101() { Assert.IsTrue(BasicSoundExTest("faites", "F320")); }
        [TestMethod] public void BasicSoundExTest102() { Assert.IsTrue(BasicSoundExTest("foyer", "F600")); }
        [TestMethod] public void BasicSoundExTest103() { Assert.IsTrue(BasicSoundExTest("ductions", "D235")); }
        [TestMethod] public void BasicSoundExTest104() { Assert.IsTrue(BasicSoundExTest("Rambo", "R510")); }
        [TestMethod] public void BasicSoundExTest105() { Assert.IsTrue(BasicSoundExTest("Curnutte", "C653")); }
        [TestMethod] public void BasicSoundExTest106() { Assert.IsTrue(BasicSoundExTest("Feltus", "F432")); }
        [TestMethod] public void BasicSoundExTest107() { Assert.IsTrue(BasicSoundExTest("forbairt", "F616")); }
        [TestMethod] public void BasicSoundExTest108() { Assert.IsTrue(BasicSoundExTest("southerners", "S365")); }
        [TestMethod] public void BasicSoundExTest109() { Assert.IsTrue(BasicSoundExTest("hypnotists", "H153")); }
        [TestMethod] public void BasicSoundExTest110() { Assert.IsTrue(BasicSoundExTest("euphony", "E150")); }
        [TestMethod] public void BasicSoundExTest111() { Assert.IsTrue(BasicSoundExTest("mhpa", "M100")); }
        [TestMethod] public void BasicSoundExTest112() { Assert.IsTrue(BasicSoundExTest("matteotti", "M330")); }
        [TestMethod] public void BasicSoundExTest113() { Assert.IsTrue(BasicSoundExTest("Klande", "K453")); }
        [TestMethod] public void BasicSoundExTest114() { Assert.IsTrue(BasicSoundExTest("Trudgeon", "T632")); }
        [TestMethod] public void BasicSoundExTest115() { Assert.IsTrue(BasicSoundExTest("schoolhill", "S440")); }
        [TestMethod] public void BasicSoundExTest116() { Assert.IsTrue(BasicSoundExTest("equalizer", "E242")); }
        [TestMethod] public void BasicSoundExTest117() { Assert.IsTrue(BasicSoundExTest("xnet", "X530")); }
        [TestMethod] public void BasicSoundExTest118() { Assert.IsTrue(BasicSoundExTest("Thell", "T400")); }
        [TestMethod] public void BasicSoundExTest119() { Assert.IsTrue(BasicSoundExTest("Canel", "C540")); }
        [TestMethod] public void BasicSoundExTest120() { Assert.IsTrue(BasicSoundExTest("vmetro", "V536")); }
        [TestMethod] public void BasicSoundExTest121() { Assert.IsTrue(BasicSoundExTest("burgtheater", "B623")); }
        [TestMethod] public void BasicSoundExTest122() { Assert.IsTrue(BasicSoundExTest("Berlinger", "B645")); }
        [TestMethod] public void BasicSoundExTest123() { Assert.IsTrue(BasicSoundExTest("crehan", "C650")); }
        [TestMethod] public void BasicSoundExTest124() { Assert.IsTrue(BasicSoundExTest("abysses", "A122")); }
        [TestMethod] public void BasicSoundExTest125() { Assert.IsTrue(BasicSoundExTest("Hipolito", "H143")); }
        [TestMethod] public void BasicSoundExTest126() { Assert.IsTrue(BasicSoundExTest("splintered", "S145")); }
        [TestMethod] public void BasicSoundExTest127() { Assert.IsTrue(BasicSoundExTest("maintenace", "M535")); }
        [TestMethod] public void BasicSoundExTest128() { Assert.IsTrue(BasicSoundExTest("decency", "D252")); }
        [TestMethod] public void BasicSoundExTest129() { Assert.IsTrue(BasicSoundExTest("quantz", "Q532")); }
        [TestMethod] public void BasicSoundExTest130() { Assert.IsTrue(BasicSoundExTest("wette", "W300")); }
        [TestMethod] public void BasicSoundExTest131() { Assert.IsTrue(BasicSoundExTest("Feary", "F600")); }
        [TestMethod] public void BasicSoundExTest132() { Assert.IsTrue(BasicSoundExTest("Cuchiara", "C260")); }
        [TestMethod] public void BasicSoundExTest133() { Assert.IsTrue(BasicSoundExTest("Arbon", "A615")); }
        [TestMethod] public void BasicSoundExTest134() { Assert.IsTrue(BasicSoundExTest("shyness", "S520")); }
        [TestMethod] public void BasicSoundExTest135() { Assert.IsTrue(BasicSoundExTest("Salin", "S450")); }
        [TestMethod] public void BasicSoundExTest136() { Assert.IsTrue(BasicSoundExTest("Zicafoose", "Z212")); }
        [TestMethod] public void BasicSoundExTest137() { Assert.IsTrue(BasicSoundExTest("Menn", "M500")); }
        [TestMethod] public void BasicSoundExTest138() { Assert.IsTrue(BasicSoundExTest("funker", "F526")); }
        [TestMethod] public void BasicSoundExTest139() { Assert.IsTrue(BasicSoundExTest("santillan", "S534")); }
        [TestMethod] public void BasicSoundExTest140() { Assert.IsTrue(BasicSoundExTest("punani", "P550")); }
        [TestMethod] public void BasicSoundExTest141() { Assert.IsTrue(BasicSoundExTest("basa", "B200")); }
        [TestMethod] public void BasicSoundExTest142() { Assert.IsTrue(BasicSoundExTest("bluefin", "B415")); }
        [TestMethod] public void BasicSoundExTest143() { Assert.IsTrue(BasicSoundExTest("cc", "C000")); }
        [TestMethod] public void BasicSoundExTest144() { Assert.IsTrue(BasicSoundExTest("zipgenius", "Z125")); }
        [TestMethod] public void BasicSoundExTest145() { Assert.IsTrue(BasicSoundExTest("Kirchen", "K625")); }
        [TestMethod] public void BasicSoundExTest146() { Assert.IsTrue(BasicSoundExTest("commentaar", "C553")); }
        [TestMethod] public void BasicSoundExTest147() { Assert.IsTrue(BasicSoundExTest("expansive", "E215")); }
        [TestMethod] public void BasicSoundExTest148() { Assert.IsTrue(BasicSoundExTest("castlebar", "C234")); }
        [TestMethod] public void BasicSoundExTest149() { Assert.IsTrue(BasicSoundExTest("lft", "L130")); }
        [TestMethod] public void BasicSoundExTest150() { Assert.IsTrue(BasicSoundExTest("robla", "R140")); }
        [TestMethod] public void BasicSoundExTest151() { Assert.IsTrue(BasicSoundExTest("zarontin", "Z653")); }
        [TestMethod] public void BasicSoundExTest152() { Assert.IsTrue(BasicSoundExTest("nawc", "N200")); }
        [TestMethod] public void BasicSoundExTest153() { Assert.IsTrue(BasicSoundExTest("resolvconf", "R241")); }
        [TestMethod] public void BasicSoundExTest154() { Assert.IsTrue(BasicSoundExTest("networker", "N362")); }
        [TestMethod] public void BasicSoundExTest155() { Assert.IsTrue(BasicSoundExTest("airlins", "A645")); }
        [TestMethod] public void BasicSoundExTest156() { Assert.IsTrue(BasicSoundExTest("Piskel", "P240")); }
        [TestMethod] public void BasicSoundExTest157() { Assert.IsTrue(BasicSoundExTest("hilson", "H425")); }
        [TestMethod] public void BasicSoundExTest158() { Assert.IsTrue(BasicSoundExTest("deco", "D200")); }
        [TestMethod] public void BasicSoundExTest159() { Assert.IsTrue(BasicSoundExTest("cents", "C532")); }
        [TestMethod] public void BasicSoundExTest160() { Assert.IsTrue(BasicSoundExTest("award", "A630")); }
        [TestMethod] public void BasicSoundExTest161() { Assert.IsTrue(BasicSoundExTest("reykjanes", "R252")); }
        [TestMethod] public void BasicSoundExTest162() { Assert.IsTrue(BasicSoundExTest("perona", "P650")); }
        [TestMethod] public void BasicSoundExTest163() { Assert.IsTrue(BasicSoundExTest("epistle", "E123")); }
        [TestMethod] public void BasicSoundExTest164() { Assert.IsTrue(BasicSoundExTest("insound", "I525")); }
        [TestMethod] public void BasicSoundExTest165() { Assert.IsTrue(BasicSoundExTest("qantas", "Q532")); }
        [TestMethod] public void BasicSoundExTest166() { Assert.IsTrue(BasicSoundExTest("wholey", "W400")); }
        [TestMethod] public void BasicSoundExTest167() { Assert.IsTrue(BasicSoundExTest("aragona", "A625")); }
        [TestMethod] public void BasicSoundExTest168() { Assert.IsTrue(BasicSoundExTest("Vancheri", "V526")); }
        [TestMethod] public void BasicSoundExTest169() { Assert.IsTrue(BasicSoundExTest("allocution", "A423")); }
        [TestMethod] public void BasicSoundExTest170() { Assert.IsTrue(BasicSoundExTest("volodya", "V430")); }
        [TestMethod] public void BasicSoundExTest171() { Assert.IsTrue(BasicSoundExTest("enunciate", "E552")); }
        [TestMethod] public void BasicSoundExTest172() { Assert.IsTrue(BasicSoundExTest("uuuu", "U000")); }
        [TestMethod] public void BasicSoundExTest173() { Assert.IsTrue(BasicSoundExTest("Louato", "L300")); }
        [TestMethod] public void BasicSoundExTest174() { Assert.IsTrue(BasicSoundExTest("Marquitta", "M623")); }
        [TestMethod] public void BasicSoundExTest175() { Assert.IsTrue(BasicSoundExTest("surmountable", "S655")); }
        [TestMethod] public void BasicSoundExTest176() { Assert.IsTrue(BasicSoundExTest("gaultier", "G436")); }
        [TestMethod] public void BasicSoundExTest177() { Assert.IsTrue(BasicSoundExTest("dafoe", "D100")); }
        [TestMethod] public void BasicSoundExTest178() { Assert.IsTrue(BasicSoundExTest("Claudio", "C430")); }
        [TestMethod] public void BasicSoundExTest179() { Assert.IsTrue(BasicSoundExTest("ritva", "R310")); }
        [TestMethod] public void BasicSoundExTest180() { Assert.IsTrue(BasicSoundExTest("spunky", "S152")); }
        [TestMethod] public void BasicSoundExTest181() { Assert.IsTrue(BasicSoundExTest("npov", "N110")); }
        [TestMethod] public void BasicSoundExTest182() { Assert.IsTrue(BasicSoundExTest("eurythmics", "E635")); }
        [TestMethod] public void BasicSoundExTest183() { Assert.IsTrue(BasicSoundExTest("skittish", "S320")); }
        [TestMethod] public void BasicSoundExTest184() { Assert.IsTrue(BasicSoundExTest("scooter", "S360")); }
        [TestMethod] public void BasicSoundExTest185() { Assert.IsTrue(BasicSoundExTest("unfermented", "U516")); }
        [TestMethod] public void BasicSoundExTest186() { Assert.IsTrue(BasicSoundExTest("kerridge", "K632")); }
        [TestMethod] public void BasicSoundExTest187() { Assert.IsTrue(BasicSoundExTest("scenography", "S526")); }
        [TestMethod] public void BasicSoundExTest188() { Assert.IsTrue(BasicSoundExTest("sahalee", "S400")); }
        [TestMethod] public void BasicSoundExTest189() { Assert.IsTrue(BasicSoundExTest("spooktacular", "S123")); }
        [TestMethod] public void BasicSoundExTest190() { Assert.IsTrue(BasicSoundExTest("boissons", "B252")); }
        [TestMethod] public void BasicSoundExTest191() { Assert.IsTrue(BasicSoundExTest("arbete", "A613")); }
        [TestMethod] public void BasicSoundExTest192() { Assert.IsTrue(BasicSoundExTest("Norrick", "N620")); }
        [TestMethod] public void BasicSoundExTest193() { Assert.IsTrue(BasicSoundExTest("Sonnier", "S560")); }
        [TestMethod] public void BasicSoundExTest194() { Assert.IsTrue(BasicSoundExTest("gnomeui", "G550")); }
        [TestMethod] public void BasicSoundExTest195() { Assert.IsTrue(BasicSoundExTest("milian", "M450")); }
        [TestMethod] public void BasicSoundExTest196() { Assert.IsTrue(BasicSoundExTest("blackplanetcom", "B421")); }
        [TestMethod] public void BasicSoundExTest197() { Assert.IsTrue(BasicSoundExTest("tuned", "T530")); }
        [TestMethod] public void BasicSoundExTest198() { Assert.IsTrue(BasicSoundExTest("Salone", "S450")); }
        [TestMethod] public void BasicSoundExTest199() { Assert.IsTrue(BasicSoundExTest("marathon", "M635")); }
        [TestMethod] public void BasicSoundExTest200() { Assert.IsTrue(BasicSoundExTest("layoffs", "L120")); }
        [TestMethod] public void BasicSoundExTest201() { Assert.IsTrue(BasicSoundExTest("hotek", "H320")); }
        [TestMethod] public void BasicSoundExTest202() { Assert.IsTrue(BasicSoundExTest("emme", "E500")); }
        [TestMethod] public void BasicSoundExTest203() { Assert.IsTrue(BasicSoundExTest("amarasinghe", "A562")); }
        [TestMethod] public void BasicSoundExTest204() { Assert.IsTrue(BasicSoundExTest("midas", "M320")); }
        [TestMethod] public void BasicSoundExTest205() { Assert.IsTrue(BasicSoundExTest("inhaltsangabe", "I543")); }
        [TestMethod] public void BasicSoundExTest206() { Assert.IsTrue(BasicSoundExTest("smow", "S500")); }
        [TestMethod] public void BasicSoundExTest207() { Assert.IsTrue(BasicSoundExTest("policing", "P425")); }
        [TestMethod] public void BasicSoundExTest208() { Assert.IsTrue(BasicSoundExTest("usmf", "U251")); }
        [TestMethod] public void BasicSoundExTest209() { Assert.IsTrue(BasicSoundExTest("inferred", "I516")); }
        [TestMethod] public void BasicSoundExTest210() { Assert.IsTrue(BasicSoundExTest("Eaglen", "E245")); }
        [TestMethod] public void BasicSoundExTest211() { Assert.IsTrue(BasicSoundExTest("dralle", "D640")); }
        [TestMethod] public void BasicSoundExTest212() { Assert.IsTrue(BasicSoundExTest("kalmus", "K452")); }
        [TestMethod] public void BasicSoundExTest213() { Assert.IsTrue(BasicSoundExTest("nork", "N620")); }
        [TestMethod] public void BasicSoundExTest214() { Assert.IsTrue(BasicSoundExTest("Waterston", "W362")); }
        [TestMethod] public void BasicSoundExTest215() { Assert.IsTrue(BasicSoundExTest("penalised", "P542")); }
        [TestMethod] public void BasicSoundExTest216() { Assert.IsTrue(BasicSoundExTest("Lupacchino", "L125")); }
        [TestMethod] public void BasicSoundExTest217() { Assert.IsTrue(BasicSoundExTest("getgid", "G323")); }
        [TestMethod] public void BasicSoundExTest218() { Assert.IsTrue(BasicSoundExTest("kever", "K160")); }
        [TestMethod] public void BasicSoundExTest219() { Assert.IsTrue(BasicSoundExTest("pallavicini", "P412")); }
        [TestMethod] public void BasicSoundExTest220() { Assert.IsTrue(BasicSoundExTest("Pais", "P200")); }
        [TestMethod] public void BasicSoundExTest221() { Assert.IsTrue(BasicSoundExTest("youghiogheny", "Y225")); }
        [TestMethod] public void BasicSoundExTest222() { Assert.IsTrue(BasicSoundExTest("Catherina", "C365")); }
        [TestMethod] public void BasicSoundExTest223() { Assert.IsTrue(BasicSoundExTest("Givant", "G153")); }
        [TestMethod] public void BasicSoundExTest224() { Assert.IsTrue(BasicSoundExTest("koffi", "K100")); }
        [TestMethod] public void BasicSoundExTest225() { Assert.IsTrue(BasicSoundExTest("troutbeck", "T631")); }
        [TestMethod] public void BasicSoundExTest226() { Assert.IsTrue(BasicSoundExTest("moreelse", "M642")); }
        [TestMethod] public void BasicSoundExTest227() { Assert.IsTrue(BasicSoundExTest("seacrest", "S262")); }
        [TestMethod] public void BasicSoundExTest228() { Assert.IsTrue(BasicSoundExTest("ufj", "U120")); }
        [TestMethod] public void BasicSoundExTest229() { Assert.IsTrue(BasicSoundExTest("dereferences", "D616")); }
        [TestMethod] public void BasicSoundExTest230() { Assert.IsTrue(BasicSoundExTest("sarena", "S650")); }
        [TestMethod] public void BasicSoundExTest231() { Assert.IsTrue(BasicSoundExTest("Kurt", "K630")); }
        [TestMethod] public void BasicSoundExTest232() { Assert.IsTrue(BasicSoundExTest("comanche", "C552")); }
        [TestMethod] public void BasicSoundExTest233() { Assert.IsTrue(BasicSoundExTest("chersoness", "C625")); }
        [TestMethod] public void BasicSoundExTest234() { Assert.IsTrue(BasicSoundExTest("cd", "C300")); }
        [TestMethod] public void BasicSoundExTest235() { Assert.IsTrue(BasicSoundExTest("merzky", "M620")); }
        [TestMethod] public void BasicSoundExTest236() { Assert.IsTrue(BasicSoundExTest("Nordsiek", "N632")); }
        [TestMethod] public void BasicSoundExTest237() { Assert.IsTrue(BasicSoundExTest("samus", "S520")); }
        [TestMethod] public void BasicSoundExTest238() { Assert.IsTrue(BasicSoundExTest("tougher", "T260")); }
        [TestMethod] public void BasicSoundExTest239() { Assert.IsTrue(BasicSoundExTest("monodoc", "M532")); }
        [TestMethod] public void BasicSoundExTest240() { Assert.IsTrue(BasicSoundExTest("deepings", "D152")); }
        [TestMethod] public void BasicSoundExTest241() { Assert.IsTrue(BasicSoundExTest("datel", "D340")); }
        [TestMethod] public void BasicSoundExTest242() { Assert.IsTrue(BasicSoundExTest("Stockett", "S323")); }
        [TestMethod] public void BasicSoundExTest243() { Assert.IsTrue(BasicSoundExTest("bryum", "B650")); }
        [TestMethod] public void BasicSoundExTest244() { Assert.IsTrue(BasicSoundExTest("surveyed", "S613")); }
        [TestMethod] public void BasicSoundExTest245() { Assert.IsTrue(BasicSoundExTest("microcephaly", "M262")); }
        [TestMethod] public void BasicSoundExTest246() { Assert.IsTrue(BasicSoundExTest("trimoxazole", "T652")); }
        [TestMethod] public void BasicSoundExTest247() { Assert.IsTrue(BasicSoundExTest("bastide", "B233")); }
        [TestMethod] public void BasicSoundExTest248() { Assert.IsTrue(BasicSoundExTest("lipo", "L100")); }
        [TestMethod] public void BasicSoundExTest249() { Assert.IsTrue(BasicSoundExTest("Bosket", "B230")); }
        [TestMethod] public void BasicSoundExTest250() { Assert.IsTrue(BasicSoundExTest("oroms", "O652")); }
        [TestMethod] public void BasicSoundExTest251() { Assert.IsTrue(BasicSoundExTest("vandenburg", "V535")); }
        [TestMethod] public void BasicSoundExTest252() { Assert.IsTrue(BasicSoundExTest("wirtschaftsforschung", "W632")); }
        [TestMethod] public void BasicSoundExTest253() { Assert.IsTrue(BasicSoundExTest("lilypond", "L415")); }
        [TestMethod] public void BasicSoundExTest254() { Assert.IsTrue(BasicSoundExTest("mouthfeel", "M314")); }
        [TestMethod] public void BasicSoundExTest255() { Assert.IsTrue(BasicSoundExTest("wwwunibancocombr", "W515")); }
        [TestMethod] public void BasicSoundExTest256() { Assert.IsTrue(BasicSoundExTest("Worster", "W623")); }
        [TestMethod] public void BasicSoundExTest257() { Assert.IsTrue(BasicSoundExTest("Ahmad", "A530")); }
        [TestMethod] public void BasicSoundExTest258() { Assert.IsTrue(BasicSoundExTest("sweetser", "S326")); }
        [TestMethod] public void BasicSoundExTest259() { Assert.IsTrue(BasicSoundExTest("vsepr", "V216")); }
        [TestMethod] public void BasicSoundExTest260() { Assert.IsTrue(BasicSoundExTest("dput", "D130")); }
        [TestMethod] public void BasicSoundExTest261() { Assert.IsTrue(BasicSoundExTest("austlit", "A234")); }
        [TestMethod] public void BasicSoundExTest262() { Assert.IsTrue(BasicSoundExTest("Clemen", "C455")); }
        [TestMethod] public void BasicSoundExTest263() { Assert.IsTrue(BasicSoundExTest("phrva", "P610")); }
        [TestMethod] public void BasicSoundExTest264() { Assert.IsTrue(BasicSoundExTest("weipa", "W100")); }
        [TestMethod] public void BasicSoundExTest265() { Assert.IsTrue(BasicSoundExTest("Schrantz", "S653")); }
        [TestMethod] public void BasicSoundExTest266() { Assert.IsTrue(BasicSoundExTest("meany", "M500")); }
        [TestMethod] public void BasicSoundExTest267() { Assert.IsTrue(BasicSoundExTest("hodgepodge", "H321")); }
        [TestMethod] public void BasicSoundExTest268() { Assert.IsTrue(BasicSoundExTest("knuble", "K514")); }
        [TestMethod] public void BasicSoundExTest269() { Assert.IsTrue(BasicSoundExTest("caniglia", "C524")); }
        [TestMethod] public void BasicSoundExTest270() { Assert.IsTrue(BasicSoundExTest("blowjobsasics", "B421")); }
        [TestMethod] public void BasicSoundExTest271() { Assert.IsTrue(BasicSoundExTest("flyjacket", "F422")); }
        [TestMethod] public void BasicSoundExTest272() { Assert.IsTrue(BasicSoundExTest("galatian", "G435")); }
        [TestMethod] public void BasicSoundExTest273() { Assert.IsTrue(BasicSoundExTest("hotsel", "H324")); }
        [TestMethod] public void BasicSoundExTest274() { Assert.IsTrue(BasicSoundExTest("autorun", "A365")); }
        [TestMethod] public void BasicSoundExTest275() { Assert.IsTrue(BasicSoundExTest("cocoon", "C250")); }
        [TestMethod] public void BasicSoundExTest276() { Assert.IsTrue(BasicSoundExTest("kooks", "K200")); }
        [TestMethod] public void BasicSoundExTest277() { Assert.IsTrue(BasicSoundExTest("endocrinol", "E532")); }
        [TestMethod] public void BasicSoundExTest278() { Assert.IsTrue(BasicSoundExTest("mesages", "M222")); }
        [TestMethod] public void BasicSoundExTest279() { Assert.IsTrue(BasicSoundExTest("Disney", "D250")); }
        [TestMethod] public void BasicSoundExTest280() { Assert.IsTrue(BasicSoundExTest("speedline", "S134")); }
        [TestMethod] public void BasicSoundExTest281() { Assert.IsTrue(BasicSoundExTest("gabaldon", "G143")); }
        [TestMethod] public void BasicSoundExTest282() { Assert.IsTrue(BasicSoundExTest("margaux", "M622")); }
        [TestMethod] public void BasicSoundExTest283() { Assert.IsTrue(BasicSoundExTest("housecalls", "H224")); }
        [TestMethod] public void BasicSoundExTest284() { Assert.IsTrue(BasicSoundExTest("siltation", "S433")); }
        [TestMethod] public void BasicSoundExTest285() { Assert.IsTrue(BasicSoundExTest("automatic", "A353")); }
        [TestMethod] public void BasicSoundExTest286() { Assert.IsTrue(BasicSoundExTest("freakshow", "F620")); }
        [TestMethod] public void BasicSoundExTest287() { Assert.IsTrue(BasicSoundExTest("gorojovsky", "G621")); }
        [TestMethod] public void BasicSoundExTest288() { Assert.IsTrue(BasicSoundExTest("milwaukie", "M420")); }
        [TestMethod] public void BasicSoundExTest289() { Assert.IsTrue(BasicSoundExTest("wwwgap", "W210")); }
        [TestMethod] public void BasicSoundExTest290() { Assert.IsTrue(BasicSoundExTest("autm", "A350")); }
        [TestMethod] public void BasicSoundExTest291() { Assert.IsTrue(BasicSoundExTest("borromini", "B655")); }
        [TestMethod] public void BasicSoundExTest292() { Assert.IsTrue(BasicSoundExTest("zpp", "Z100")); }
        [TestMethod] public void BasicSoundExTest293() { Assert.IsTrue(BasicSoundExTest("Penovich", "P512")); }
        [TestMethod] public void BasicSoundExTest294() { Assert.IsTrue(BasicSoundExTest("domine", "D550")); }
        [TestMethod] public void BasicSoundExTest295() { Assert.IsTrue(BasicSoundExTest("caves", "C120")); }
        [TestMethod] public void BasicSoundExTest296() { Assert.IsTrue(BasicSoundExTest("uato", "U300")); }
        [TestMethod] public void BasicSoundExTest297() { Assert.IsTrue(BasicSoundExTest("tiltonsville", "T435")); }
        [TestMethod] public void BasicSoundExTest298() { Assert.IsTrue(BasicSoundExTest("Ken", "K500")); }
        [TestMethod] public void BasicSoundExTest299() { Assert.IsTrue(BasicSoundExTest("Delonais", "D452")); }
        [TestMethod] public void BasicSoundExTest300() { Assert.IsTrue(BasicSoundExTest("conniption", "C513")); }
        [TestMethod] public void BasicSoundExTest301() { Assert.IsTrue(BasicSoundExTest("Wenske", "W520")); }
        [TestMethod] public void BasicSoundExTest302() { Assert.IsTrue(BasicSoundExTest("cautery", "C360")); }
        [TestMethod] public void BasicSoundExTest303() { Assert.IsTrue(BasicSoundExTest("barbourville", "B616")); }
        [TestMethod] public void BasicSoundExTest304() { Assert.IsTrue(BasicSoundExTest("departamentos", "D163")); }
        [TestMethod] public void BasicSoundExTest305() { Assert.IsTrue(BasicSoundExTest("weaponry", "W156")); }
        [TestMethod] public void BasicSoundExTest306() { Assert.IsTrue(BasicSoundExTest("Haggett", "H230")); }
        [TestMethod] public void BasicSoundExTest307() { Assert.IsTrue(BasicSoundExTest("martinville", "M635")); }
        [TestMethod] public void BasicSoundExTest308() { Assert.IsTrue(BasicSoundExTest("stina", "S350")); }
        [TestMethod] public void BasicSoundExTest309() { Assert.IsTrue(BasicSoundExTest("Rubottom", "R135")); }
        [TestMethod] public void BasicSoundExTest310() { Assert.IsTrue(BasicSoundExTest("Soyke", "S200")); }
        [TestMethod] public void BasicSoundExTest311() { Assert.IsTrue(BasicSoundExTest("corse", "C620")); }
        [TestMethod] public void BasicSoundExTest312() { Assert.IsTrue(BasicSoundExTest("totalling", "T345")); }
        [TestMethod] public void BasicSoundExTest313() { Assert.IsTrue(BasicSoundExTest("kuppam", "K150")); }
        [TestMethod] public void BasicSoundExTest314() { Assert.IsTrue(BasicSoundExTest("ftpadmin", "F313")); }
        [TestMethod] public void BasicSoundExTest315() { Assert.IsTrue(BasicSoundExTest("Forst", "F623")); }
        [TestMethod] public void BasicSoundExTest316() { Assert.IsTrue(BasicSoundExTest("Ashauer", "A260")); }
        [TestMethod] public void BasicSoundExTest317() { Assert.IsTrue(BasicSoundExTest("ashtanga", "A235")); }
        [TestMethod] public void BasicSoundExTest318() { Assert.IsTrue(BasicSoundExTest("alonissos", "A452")); }
        [TestMethod] public void BasicSoundExTest319() { Assert.IsTrue(BasicSoundExTest("Chimilio", "C540")); }
        [TestMethod] public void BasicSoundExTest320() { Assert.IsTrue(BasicSoundExTest("deafbazon", "D125")); }
        [TestMethod] public void BasicSoundExTest321() { Assert.IsTrue(BasicSoundExTest("psmb", "P251")); }
        [TestMethod] public void BasicSoundExTest322() { Assert.IsTrue(BasicSoundExTest("Ferraraccio", "F662")); }
        [TestMethod] public void BasicSoundExTest323() { Assert.IsTrue(BasicSoundExTest("fractionated", "F623")); }
        [TestMethod] public void BasicSoundExTest324() { Assert.IsTrue(BasicSoundExTest("rrd", "R300")); }
        [TestMethod] public void BasicSoundExTest325() { Assert.IsTrue(BasicSoundExTest("luminosities", "L552")); }
        [TestMethod] public void BasicSoundExTest326() { Assert.IsTrue(BasicSoundExTest("Platzer", "P432")); }
        [TestMethod] public void BasicSoundExTest327() { Assert.IsTrue(BasicSoundExTest("modulator", "M343")); }
        [TestMethod] public void BasicSoundExTest328() { Assert.IsTrue(BasicSoundExTest("tyneside", "T523")); }
        [TestMethod] public void BasicSoundExTest329() { Assert.IsTrue(BasicSoundExTest("nonuser", "N526")); }
        [TestMethod] public void BasicSoundExTest330() { Assert.IsTrue(BasicSoundExTest("haspel", "H214")); }
        [TestMethod] public void BasicSoundExTest331() { Assert.IsTrue(BasicSoundExTest("cortex", "C632")); }
        [TestMethod] public void BasicSoundExTest332() { Assert.IsTrue(BasicSoundExTest("vechicle", "V224")); }
        [TestMethod] public void BasicSoundExTest333() { Assert.IsTrue(BasicSoundExTest("epinions", "E155")); }
        [TestMethod] public void BasicSoundExTest334() { Assert.IsTrue(BasicSoundExTest("wwwusmintgov", "W255")); }
        [TestMethod] public void BasicSoundExTest335() { Assert.IsTrue(BasicSoundExTest("katies", "K320")); }
        [TestMethod] public void BasicSoundExTest336() { Assert.IsTrue(BasicSoundExTest("aminosalicylic", "A552")); }
        [TestMethod] public void BasicSoundExTest337() { Assert.IsTrue(BasicSoundExTest("mmegi", "M200")); }
        [TestMethod] public void BasicSoundExTest338() { Assert.IsTrue(BasicSoundExTest("sbir", "S160")); }
        [TestMethod] public void BasicSoundExTest339() { Assert.IsTrue(BasicSoundExTest("learned", "L653")); }
        [TestMethod] public void BasicSoundExTest340() { Assert.IsTrue(BasicSoundExTest("supris", "S162")); }
        [TestMethod] public void BasicSoundExTest341() { Assert.IsTrue(BasicSoundExTest("mozarteum", "M263")); }
        [TestMethod] public void BasicSoundExTest342() { Assert.IsTrue(BasicSoundExTest("selzer", "S426")); }
        [TestMethod] public void BasicSoundExTest343() { Assert.IsTrue(BasicSoundExTest("tmug", "T520")); }
        [TestMethod] public void BasicSoundExTest344() { Assert.IsTrue(BasicSoundExTest("Kisto", "K230")); }
        [TestMethod] public void BasicSoundExTest345() { Assert.IsTrue(BasicSoundExTest("iib", "I100")); }
        [TestMethod] public void BasicSoundExTest346() { Assert.IsTrue(BasicSoundExTest("wwwincredimail", "W526")); }
        [TestMethod] public void BasicSoundExTest347() { Assert.IsTrue(BasicSoundExTest("izpack", "I212")); }
        [TestMethod] public void BasicSoundExTest348() { Assert.IsTrue(BasicSoundExTest("gaymovie", "G510")); }
        [TestMethod] public void BasicSoundExTest349() { Assert.IsTrue(BasicSoundExTest("Buchholz", "B242")); }
        [TestMethod] public void BasicSoundExTest350() { Assert.IsTrue(BasicSoundExTest("culcairn", "C426")); }
        [TestMethod] public void BasicSoundExTest351() { Assert.IsTrue(BasicSoundExTest("barys", "B620")); }
        [TestMethod] public void BasicSoundExTest352() { Assert.IsTrue(BasicSoundExTest("burets", "B632")); }
        [TestMethod] public void BasicSoundExTest353() { Assert.IsTrue(BasicSoundExTest("Sorce", "S620")); }
        [TestMethod] public void BasicSoundExTest354() { Assert.IsTrue(BasicSoundExTest("chimique", "C520")); }
        [TestMethod] public void BasicSoundExTest355() { Assert.IsTrue(BasicSoundExTest("kitada", "K330")); }
        [TestMethod] public void BasicSoundExTest356() { Assert.IsTrue(BasicSoundExTest("Engeman", "E525")); }
        [TestMethod] public void BasicSoundExTest357() { Assert.IsTrue(BasicSoundExTest("raveendran", "R153")); }
        [TestMethod] public void BasicSoundExTest358() { Assert.IsTrue(BasicSoundExTest("Bendele", "B534")); }
        [TestMethod] public void BasicSoundExTest359() { Assert.IsTrue(BasicSoundExTest("Pawlitschek", "P432")); }
        [TestMethod] public void BasicSoundExTest360() { Assert.IsTrue(BasicSoundExTest("hogfather", "H213")); }
        [TestMethod] public void BasicSoundExTest361() { Assert.IsTrue(BasicSoundExTest("eyedrum", "E365")); }
        [TestMethod] public void BasicSoundExTest362() { Assert.IsTrue(BasicSoundExTest("Ferrara", "F660")); }
        [TestMethod] public void BasicSoundExTest363() { Assert.IsTrue(BasicSoundExTest("zhuh", "Z000")); }
        [TestMethod] public void BasicSoundExTest364() { Assert.IsTrue(BasicSoundExTest("zodiak", "Z320")); }
        [TestMethod] public void BasicSoundExTest365() { Assert.IsTrue(BasicSoundExTest("pchcom", "P225")); }
        [TestMethod] public void BasicSoundExTest366() { Assert.IsTrue(BasicSoundExTest("conferees", "C516")); }
        [TestMethod] public void BasicSoundExTest367() { Assert.IsTrue(BasicSoundExTest("Decillis", "D242")); }
        [TestMethod] public void BasicSoundExTest368() { Assert.IsTrue(BasicSoundExTest("downloar", "D546")); }
        [TestMethod] public void BasicSoundExTest369() { Assert.IsTrue(BasicSoundExTest("shard", "S630")); }
        [TestMethod] public void BasicSoundExTest370() { Assert.IsTrue(BasicSoundExTest("fajr", "F260")); }
        [TestMethod] public void BasicSoundExTest371() { Assert.IsTrue(BasicSoundExTest("quisque", "Q200")); }
        [TestMethod] public void BasicSoundExTest372() { Assert.IsTrue(BasicSoundExTest("winterizing", "W536")); }
        [TestMethod] public void BasicSoundExTest373() { Assert.IsTrue(BasicSoundExTest("referate", "R163")); }
        [TestMethod] public void BasicSoundExTest374() { Assert.IsTrue(BasicSoundExTest("nuxone", "N250")); }
        [TestMethod] public void BasicSoundExTest375() { Assert.IsTrue(BasicSoundExTest("Racheal", "R240")); }
        [TestMethod] public void BasicSoundExTest376() { Assert.IsTrue(BasicSoundExTest("bizben", "B215")); }
        [TestMethod] public void BasicSoundExTest377() { Assert.IsTrue(BasicSoundExTest("musictalk", "M223")); }
        [TestMethod] public void BasicSoundExTest378() { Assert.IsTrue(BasicSoundExTest("ogoal", "O240")); }
        [TestMethod] public void BasicSoundExTest379() { Assert.IsTrue(BasicSoundExTest("Skoff", "S100")); }
        [TestMethod] public void BasicSoundExTest380() { Assert.IsTrue(BasicSoundExTest("Seehusen", "S250")); }
        [TestMethod] public void BasicSoundExTest381() { Assert.IsTrue(BasicSoundExTest("Reim", "R500")); }
        [TestMethod] public void BasicSoundExTest382() { Assert.IsTrue(BasicSoundExTest("Yoh", "Y000")); }
        [TestMethod] public void BasicSoundExTest383() { Assert.IsTrue(BasicSoundExTest("gapi", "G100")); }
        [TestMethod] public void BasicSoundExTest384() { Assert.IsTrue(BasicSoundExTest("Brightbill", "B623")); }
        [TestMethod] public void BasicSoundExTest385() { Assert.IsTrue(BasicSoundExTest("shuey", "S000")); }
        [TestMethod] public void BasicSoundExTest386() { Assert.IsTrue(BasicSoundExTest("posium", "P250")); }
        [TestMethod] public void BasicSoundExTest387() { Assert.IsTrue(BasicSoundExTest("Falknor", "F425")); }
        [TestMethod] public void BasicSoundExTest388() { Assert.IsTrue(BasicSoundExTest("ucat", "U230")); }
        [TestMethod] public void BasicSoundExTest389() { Assert.IsTrue(BasicSoundExTest("properspace", "P616")); }
        [TestMethod] public void BasicSoundExTest390() { Assert.IsTrue(BasicSoundExTest("showimg", "S520")); }
        [TestMethod] public void BasicSoundExTest391() { Assert.IsTrue(BasicSoundExTest("Montecillo", "M532")); }
        [TestMethod] public void BasicSoundExTest392() { Assert.IsTrue(BasicSoundExTest("sajak", "S220")); }
        [TestMethod] public void BasicSoundExTest393() { Assert.IsTrue(BasicSoundExTest("maturbation", "M361")); }
        [TestMethod] public void BasicSoundExTest394() { Assert.IsTrue(BasicSoundExTest("Lettie", "L300")); }
        [TestMethod] public void BasicSoundExTest395() { Assert.IsTrue(BasicSoundExTest("clauss", "C420")); }
        [TestMethod] public void BasicSoundExTest396() { Assert.IsTrue(BasicSoundExTest("scheiber", "S160")); }
        [TestMethod] public void BasicSoundExTest397() { Assert.IsTrue(BasicSoundExTest("matp", "M310")); }
        [TestMethod] public void BasicSoundExTest398() { Assert.IsTrue(BasicSoundExTest("mervtormel", "M613")); }
        [TestMethod] public void BasicSoundExTest399() { Assert.IsTrue(BasicSoundExTest("guanahani", "G550")); }
        [TestMethod] public void BasicSoundExTest400() { Assert.IsTrue(BasicSoundExTest("citement", "C355")); }
        [TestMethod] public void BasicSoundExTest401() { Assert.IsTrue(BasicSoundExTest("immu", "I500")); }
        [TestMethod] public void BasicSoundExTest402() { Assert.IsTrue(BasicSoundExTest("virulence", "V645")); }
        [TestMethod] public void BasicSoundExTest403() { Assert.IsTrue(BasicSoundExTest("kussa", "K200")); }
        [TestMethod] public void BasicSoundExTest404() { Assert.IsTrue(BasicSoundExTest("gso", "G000")); }
        [TestMethod] public void BasicSoundExTest405() { Assert.IsTrue(BasicSoundExTest("webviajes", "W122")); }
        [TestMethod] public void BasicSoundExTest406() { Assert.IsTrue(BasicSoundExTest("ldwork", "L362")); }
        [TestMethod] public void BasicSoundExTest407() { Assert.IsTrue(BasicSoundExTest("verses", "V622")); }
        [TestMethod] public void BasicSoundExTest408() { Assert.IsTrue(BasicSoundExTest("sondes", "S532")); }
        [TestMethod] public void BasicSoundExTest409() { Assert.IsTrue(BasicSoundExTest("freshpair", "F621")); }
        [TestMethod] public void BasicSoundExTest410() { Assert.IsTrue(BasicSoundExTest("licorne", "L265")); }
        [TestMethod] public void BasicSoundExTest411() { Assert.IsTrue(BasicSoundExTest("Vanis", "V520")); }
        [TestMethod] public void BasicSoundExTest412() { Assert.IsTrue(BasicSoundExTest("Buena", "B500")); }
        [TestMethod] public void BasicSoundExTest413() { Assert.IsTrue(BasicSoundExTest("Tauares", "T620")); }
        [TestMethod] public void BasicSoundExTest414() { Assert.IsTrue(BasicSoundExTest("ikus", "I220")); }
        [TestMethod] public void BasicSoundExTest415() { Assert.IsTrue(BasicSoundExTest("genrebox", "G561")); }
        [TestMethod] public void BasicSoundExTest416() { Assert.IsTrue(BasicSoundExTest("rth", "R300")); }
        [TestMethod] public void BasicSoundExTest417() { Assert.IsTrue(BasicSoundExTest("Spaun", "S150")); }
        [TestMethod] public void BasicSoundExTest418() { Assert.IsTrue(BasicSoundExTest("wiersbe", "W621")); }
        [TestMethod] public void BasicSoundExTest419() { Assert.IsTrue(BasicSoundExTest("dad", "D300")); }
        [TestMethod] public void BasicSoundExTest420() { Assert.IsTrue(BasicSoundExTest("tus", "T200")); }
        [TestMethod] public void BasicSoundExTest421() { Assert.IsTrue(BasicSoundExTest("Weidert", "W363")); }
        [TestMethod] public void BasicSoundExTest422() { Assert.IsTrue(BasicSoundExTest("rijke", "R200")); }
        [TestMethod] public void BasicSoundExTest423() { Assert.IsTrue(BasicSoundExTest("fischbein", "F215")); }
        [TestMethod] public void BasicSoundExTest424() { Assert.IsTrue(BasicSoundExTest("fbeye", "F000")); }
        [TestMethod] public void BasicSoundExTest425() { Assert.IsTrue(BasicSoundExTest("hagerty", "H263")); }
        [TestMethod] public void BasicSoundExTest426() { Assert.IsTrue(BasicSoundExTest("Hollendonner", "H453")); }
        [TestMethod] public void BasicSoundExTest427() { Assert.IsTrue(BasicSoundExTest("Huitzacua", "H322")); }
        [TestMethod] public void BasicSoundExTest428() { Assert.IsTrue(BasicSoundExTest("subjunctive", "S125")); }
        [TestMethod] public void BasicSoundExTest429() { Assert.IsTrue(BasicSoundExTest("implored", "I514")); }
        [TestMethod] public void BasicSoundExTest430() { Assert.IsTrue(BasicSoundExTest("pompeius", "P512")); }
        [TestMethod] public void BasicSoundExTest431() { Assert.IsTrue(BasicSoundExTest("afleet", "A143")); }
        [TestMethod] public void BasicSoundExTest432() { Assert.IsTrue(BasicSoundExTest("iacc", "I200")); }
        [TestMethod] public void BasicSoundExTest433() { Assert.IsTrue(BasicSoundExTest("sabalos", "S142")); }
        [TestMethod] public void BasicSoundExTest434() { Assert.IsTrue(BasicSoundExTest("Abdi", "A130")); }
        [TestMethod] public void BasicSoundExTest435() { Assert.IsTrue(BasicSoundExTest("microinsurance", "M265")); }
        [TestMethod] public void BasicSoundExTest436() { Assert.IsTrue(BasicSoundExTest("audiobook", "A312")); }
        [TestMethod] public void BasicSoundExTest437() { Assert.IsTrue(BasicSoundExTest("fulpmes", "F415")); }
        [TestMethod] public void BasicSoundExTest438() { Assert.IsTrue(BasicSoundExTest("registreren", "R223")); }
        [TestMethod] public void BasicSoundExTest439() { Assert.IsTrue(BasicSoundExTest("megapath", "M213")); }
        [TestMethod] public void BasicSoundExTest440() { Assert.IsTrue(BasicSoundExTest("prestidigitation", "P623")); }
        [TestMethod] public void BasicSoundExTest441() { Assert.IsTrue(BasicSoundExTest("wby", "W100")); }
        [TestMethod] public void BasicSoundExTest442() { Assert.IsTrue(BasicSoundExTest("vorschau", "V620")); }
        [TestMethod] public void BasicSoundExTest443() { Assert.IsTrue(BasicSoundExTest("Albertha", "A416")); }
        [TestMethod] public void BasicSoundExTest444() { Assert.IsTrue(BasicSoundExTest("aspalpha", "A214")); }
        [TestMethod] public void BasicSoundExTest445() { Assert.IsTrue(BasicSoundExTest("Belden", "B435")); }
        [TestMethod] public void BasicSoundExTest446() { Assert.IsTrue(BasicSoundExTest("deterministic", "D365")); }
        [TestMethod] public void BasicSoundExTest447() { Assert.IsTrue(BasicSoundExTest("philosophique", "P421")); }
        [TestMethod] public void BasicSoundExTest448() { Assert.IsTrue(BasicSoundExTest("kleinen", "K455")); }
        [TestMethod] public void BasicSoundExTest449() { Assert.IsTrue(BasicSoundExTest("logouri", "L260")); }
        [TestMethod] public void BasicSoundExTest450() { Assert.IsTrue(BasicSoundExTest("xbl", "X140")); }
        [TestMethod] public void BasicSoundExTest451() { Assert.IsTrue(BasicSoundExTest("iz", "I200")); }
        [TestMethod] public void BasicSoundExTest452() { Assert.IsTrue(BasicSoundExTest("throckmorton", "T625")); }
        [TestMethod] public void BasicSoundExTest453() { Assert.IsTrue(BasicSoundExTest("condesa", "C532")); }
        [TestMethod] public void BasicSoundExTest454() { Assert.IsTrue(BasicSoundExTest("Mook", "M200")); }
        [TestMethod] public void BasicSoundExTest455() { Assert.IsTrue(BasicSoundExTest("medseek", "M322")); }
        [TestMethod] public void BasicSoundExTest456() { Assert.IsTrue(BasicSoundExTest("chugalug", "C242")); }
        [TestMethod] public void BasicSoundExTest457() { Assert.IsTrue(BasicSoundExTest("olms", "O452")); }
        [TestMethod] public void BasicSoundExTest458() { Assert.IsTrue(BasicSoundExTest("bogo", "B200")); }
        [TestMethod] public void BasicSoundExTest459() { Assert.IsTrue(BasicSoundExTest("essing", "E252")); }
        [TestMethod] public void BasicSoundExTest460() { Assert.IsTrue(BasicSoundExTest("rarden", "R635")); }
        [TestMethod] public void BasicSoundExTest461() { Assert.IsTrue(BasicSoundExTest("mittlere", "M346")); }
        [TestMethod] public void BasicSoundExTest462() { Assert.IsTrue(BasicSoundExTest("Borsa", "B620")); }
        [TestMethod] public void BasicSoundExTest463() { Assert.IsTrue(BasicSoundExTest("Ainslie", "A524")); }
        [TestMethod] public void BasicSoundExTest464() { Assert.IsTrue(BasicSoundExTest("Ganska", "G520")); }
        [TestMethod] public void BasicSoundExTest465() { Assert.IsTrue(BasicSoundExTest("miv", "M100")); }
        [TestMethod] public void BasicSoundExTest466() { Assert.IsTrue(BasicSoundExTest("concessions", "C522")); }
        [TestMethod] public void BasicSoundExTest467() { Assert.IsTrue(BasicSoundExTest("distinguished", "D235")); }
        [TestMethod] public void BasicSoundExTest468() { Assert.IsTrue(BasicSoundExTest("cano", "C500")); }
        [TestMethod] public void BasicSoundExTest469() { Assert.IsTrue(BasicSoundExTest("plumper", "P451")); }
        [TestMethod] public void BasicSoundExTest470() { Assert.IsTrue(BasicSoundExTest("mindoro", "M536")); }
        [TestMethod] public void BasicSoundExTest471() { Assert.IsTrue(BasicSoundExTest("cephalopod", "C141")); }
        [TestMethod] public void BasicSoundExTest472() { Assert.IsTrue(BasicSoundExTest("Klunk", "K452")); }
        [TestMethod] public void BasicSoundExTest473() { Assert.IsTrue(BasicSoundExTest("Bumbrey", "B516")); }
        [TestMethod] public void BasicSoundExTest474() { Assert.IsTrue(BasicSoundExTest("causeless", "C242")); }
        [TestMethod] public void BasicSoundExTest475() { Assert.IsTrue(BasicSoundExTest("Lothrop", "L361")); }
        [TestMethod] public void BasicSoundExTest476() { Assert.IsTrue(BasicSoundExTest("bodystyles", "B323")); }
        [TestMethod] public void BasicSoundExTest477() { Assert.IsTrue(BasicSoundExTest("beaatiality", "B343")); }
        [TestMethod] public void BasicSoundExTest478() { Assert.IsTrue(BasicSoundExTest("Bobrowski", "B162")); }
        [TestMethod] public void BasicSoundExTest479() { Assert.IsTrue(BasicSoundExTest("erudition", "E633")); }
        [TestMethod] public void BasicSoundExTest480() { Assert.IsTrue(BasicSoundExTest("huttner", "H356")); }
        [TestMethod] public void BasicSoundExTest481() { Assert.IsTrue(BasicSoundExTest("wwwaskjeevescom", "W212")); }
        [TestMethod] public void BasicSoundExTest482() { Assert.IsTrue(BasicSoundExTest("Duross", "D620")); }
        [TestMethod] public void BasicSoundExTest483() { Assert.IsTrue(BasicSoundExTest("Colemen", "C455")); }
        [TestMethod] public void BasicSoundExTest484() { Assert.IsTrue(BasicSoundExTest("Duncomb", "D525")); }
        [TestMethod] public void BasicSoundExTest485() { Assert.IsTrue(BasicSoundExTest("tripe", "T610")); }
        [TestMethod] public void BasicSoundExTest486() { Assert.IsTrue(BasicSoundExTest("dorrigo", "D620")); }
        [TestMethod] public void BasicSoundExTest487() { Assert.IsTrue(BasicSoundExTest("Mascall", "M240")); }
        [TestMethod] public void BasicSoundExTest488() { Assert.IsTrue(BasicSoundExTest("jetplane", "J314")); }
        [TestMethod] public void BasicSoundExTest489() { Assert.IsTrue(BasicSoundExTest("nswrl", "N264")); }
        [TestMethod] public void BasicSoundExTest490() { Assert.IsTrue(BasicSoundExTest("didates", "D332")); }
        [TestMethod] public void BasicSoundExTest491() { Assert.IsTrue(BasicSoundExTest("Jena", "J500")); }
        [TestMethod] public void BasicSoundExTest492() { Assert.IsTrue(BasicSoundExTest("kctu", "K300")); }
        [TestMethod] public void BasicSoundExTest493() { Assert.IsTrue(BasicSoundExTest("cualquiera", "C426")); }
        [TestMethod] public void BasicSoundExTest494() { Assert.IsTrue(BasicSoundExTest("plutella", "P434")); }
        [TestMethod] public void BasicSoundExTest495() { Assert.IsTrue(BasicSoundExTest("Liebig", "L120")); }
        [TestMethod] public void BasicSoundExTest496() { Assert.IsTrue(BasicSoundExTest("Llorens", "L652")); }
        [TestMethod] public void BasicSoundExTest497() { Assert.IsTrue(BasicSoundExTest("mraz", "M620")); }
        [TestMethod] public void BasicSoundExTest498() { Assert.IsTrue(BasicSoundExTest("shadyac", "S320")); }
        [TestMethod] public void BasicSoundExTest499() { Assert.IsTrue(BasicSoundExTest("lossphentermine", "L215")); }
        [TestMethod] public void BasicSoundExTest500() { Assert.IsTrue(BasicSoundExTest("Dreith", "D630")); }

    }
}