using Element34.StringMetrics;

namespace Element34Tests.Phonetic
{
    [TestClass]
    public class Caverphone2Tests
    {
        private bool Caverphone2Test(string sInput, string sExpected)
        {
            Caverphone2 cav2 = new Caverphone2();
            return cav2.Encode(sInput) == sExpected;
        }

        [TestMethod] public void Caverphone2Test001() { Assert.IsTrue(Caverphone2Test("communication", "KMNKSN1111")); }
        [TestMethod] public void Caverphone2Test002() { Assert.IsTrue(Caverphone2Test("worships", "WSPS111111")); }
        [TestMethod] public void Caverphone2Test003() { Assert.IsTrue(Caverphone2Test("televisionhome", "TLFSNM1111")); }
        [TestMethod] public void Caverphone2Test004() { Assert.IsTrue(Caverphone2Test("bumi", "PMA1111111")); }
        [TestMethod] public void Caverphone2Test005() { Assert.IsTrue(Caverphone2Test("shortbread", "STPRT11111")); }
        [TestMethod] public void Caverphone2Test006() { Assert.IsTrue(Caverphone2Test("slice", "SLK1111111")); }
        [TestMethod] public void Caverphone2Test007() { Assert.IsTrue(Caverphone2Test("reint", "RNT1111111")); }
        [TestMethod] public void Caverphone2Test008() { Assert.IsTrue(Caverphone2Test("Florence", "FLRNK11111")); }
        [TestMethod] public void Caverphone2Test009() { Assert.IsTrue(Caverphone2Test("fawzi", "FSA1111111")); }
        [TestMethod] public void Caverphone2Test010() { Assert.IsTrue(Caverphone2Test("sname", "SNM1111111")); }
        [TestMethod] public void Caverphone2Test011() { Assert.IsTrue(Caverphone2Test("modano", "MTNA111111")); }
        [TestMethod] public void Caverphone2Test012() { Assert.IsTrue(Caverphone2Test("stumpage", "STMPK11111")); }
        [TestMethod] public void Caverphone2Test013() { Assert.IsTrue(Caverphone2Test("clears", "KLS1111111")); }
        [TestMethod] public void Caverphone2Test014() { Assert.IsTrue(Caverphone2Test("ciods", "STS1111111")); }
        [TestMethod] public void Caverphone2Test015() { Assert.IsTrue(Caverphone2Test("deseos", "TSS1111111")); }
        [TestMethod] public void Caverphone2Test016() { Assert.IsTrue(Caverphone2Test("dippin", "TPN1111111")); }
        [TestMethod] public void Caverphone2Test017() { Assert.IsTrue(Caverphone2Test("aranna", "ARNA111111")); }
        [TestMethod] public void Caverphone2Test018() { Assert.IsTrue(Caverphone2Test("borse", "PS11111111")); }
        [TestMethod] public void Caverphone2Test019() { Assert.IsTrue(Caverphone2Test("subic", "SPK1111111")); }
        [TestMethod] public void Caverphone2Test020() { Assert.IsTrue(Caverphone2Test("Vidrio", "FTRA111111")); }
        [TestMethod] public void Caverphone2Test021() { Assert.IsTrue(Caverphone2Test("inserters", "ANSTS11111")); }
        [TestMethod] public void Caverphone2Test022() { Assert.IsTrue(Caverphone2Test("perature", "PRTA111111")); }
        [TestMethod] public void Caverphone2Test023() { Assert.IsTrue(Caverphone2Test("msacideas", "MSSTS11111")); }
        [TestMethod] public void Caverphone2Test024() { Assert.IsTrue(Caverphone2Test("cougs", "KKS1111111")); }
        [TestMethod] public void Caverphone2Test025() { Assert.IsTrue(Caverphone2Test("kittens", "KTNS111111")); }
        [TestMethod] public void Caverphone2Test026() { Assert.IsTrue(Caverphone2Test("imperiously", "AMPRSLA111")); }
        [TestMethod] public void Caverphone2Test027() { Assert.IsTrue(Caverphone2Test("boccanegra", "PKNKRA1111")); }
        [TestMethod] public void Caverphone2Test028() { Assert.IsTrue(Caverphone2Test("sextet", "SKTT111111")); }
        [TestMethod] public void Caverphone2Test029() { Assert.IsTrue(Caverphone2Test("setattributes", "STTRPTS111")); }
        [TestMethod] public void Caverphone2Test030() { Assert.IsTrue(Caverphone2Test("dsnt", "TSNT111111")); }
        [TestMethod] public void Caverphone2Test031() { Assert.IsTrue(Caverphone2Test("chubby", "KPA1111111")); }
        [TestMethod] public void Caverphone2Test032() { Assert.IsTrue(Caverphone2Test("ooda", "ATA1111111")); }
        [TestMethod] public void Caverphone2Test033() { Assert.IsTrue(Caverphone2Test("Bressman", "PRSMN11111")); }
        [TestMethod] public void Caverphone2Test034() { Assert.IsTrue(Caverphone2Test("calendarnew", "KLNTNA1111")); }
        [TestMethod] public void Caverphone2Test035() { Assert.IsTrue(Caverphone2Test("duhon", "TN11111111")); }
        [TestMethod] public void Caverphone2Test036() { Assert.IsTrue(Caverphone2Test("nchen", "NKN1111111")); }
        [TestMethod] public void Caverphone2Test037() { Assert.IsTrue(Caverphone2Test("betjemans", "PTMNS11111")); }
        [TestMethod] public void Caverphone2Test038() { Assert.IsTrue(Caverphone2Test("Mangum", "MNKM111111")); }
        [TestMethod] public void Caverphone2Test039() { Assert.IsTrue(Caverphone2Test("cabac", "KPK1111111")); }
        [TestMethod] public void Caverphone2Test040() { Assert.IsTrue(Caverphone2Test("pantys", "PNTS111111")); }
        [TestMethod] public void Caverphone2Test041() { Assert.IsTrue(Caverphone2Test("cofactors", "KFKTS11111")); }
        [TestMethod] public void Caverphone2Test042() { Assert.IsTrue(Caverphone2Test("clickz", "KLKS111111")); }
        [TestMethod] public void Caverphone2Test043() { Assert.IsTrue(Caverphone2Test("chiap", "KP11111111")); }
        [TestMethod] public void Caverphone2Test044() { Assert.IsTrue(Caverphone2Test("Dalpiaz", "TPS1111111")); }
        [TestMethod] public void Caverphone2Test045() { Assert.IsTrue(Caverphone2Test("philosophically", "FLSFKLA111")); }
        [TestMethod] public void Caverphone2Test046() { Assert.IsTrue(Caverphone2Test("backfill", "PKFA111111")); }
        [TestMethod] public void Caverphone2Test047() { Assert.IsTrue(Caverphone2Test("Murders", "MTS1111111")); }
        [TestMethod] public void Caverphone2Test048() { Assert.IsTrue(Caverphone2Test("ecartis", "AKTS111111")); }
        [TestMethod] public void Caverphone2Test049() { Assert.IsTrue(Caverphone2Test("vede", "FT11111111")); }
        [TestMethod] public void Caverphone2Test050() { Assert.IsTrue(Caverphone2Test("usoe", "ASA1111111")); }
        [TestMethod] public void Caverphone2Test051() { Assert.IsTrue(Caverphone2Test("ostara", "ASTRA11111")); }
        [TestMethod] public void Caverphone2Test052() { Assert.IsTrue(Caverphone2Test("labourer", "LPRA111111")); }
        [TestMethod] public void Caverphone2Test053() { Assert.IsTrue(Caverphone2Test("speir", "SPA1111111")); }
        [TestMethod] public void Caverphone2Test054() { Assert.IsTrue(Caverphone2Test("durchaus", "TKS1111111")); }
        [TestMethod] public void Caverphone2Test055() { Assert.IsTrue(Caverphone2Test("inetformfiller", "ANTFMFLA11")); }
        [TestMethod] public void Caverphone2Test056() { Assert.IsTrue(Caverphone2Test("itrs", "ATS1111111")); }
        [TestMethod] public void Caverphone2Test057() { Assert.IsTrue(Caverphone2Test("Tennant", "TNNT111111")); }
        [TestMethod] public void Caverphone2Test058() { Assert.IsTrue(Caverphone2Test("bashore", "PSA1111111")); }
        [TestMethod] public void Caverphone2Test059() { Assert.IsTrue(Caverphone2Test("lemurian", "LMRN111111")); }
        [TestMethod] public void Caverphone2Test060() { Assert.IsTrue(Caverphone2Test("dungannon", "TNKNN11111")); }
        [TestMethod] public void Caverphone2Test061() { Assert.IsTrue(Caverphone2Test("epl", "APA1111111")); }
        [TestMethod] public void Caverphone2Test062() { Assert.IsTrue(Caverphone2Test("grader", "KRTA111111")); }
        [TestMethod] public void Caverphone2Test063() { Assert.IsTrue(Caverphone2Test("synchronise", "SNKRNS1111")); }
        [TestMethod] public void Caverphone2Test064() { Assert.IsTrue(Caverphone2Test("gondorian", "KNTRN11111")); }
        [TestMethod] public void Caverphone2Test065() { Assert.IsTrue(Caverphone2Test("cvnet", "KFNT111111")); }
        [TestMethod] public void Caverphone2Test066() { Assert.IsTrue(Caverphone2Test("Centers", "SNTS111111")); }
        [TestMethod] public void Caverphone2Test067() { Assert.IsTrue(Caverphone2Test("soaks", "SKS1111111")); }
        [TestMethod] public void Caverphone2Test068() { Assert.IsTrue(Caverphone2Test("gogllle", "KKA1111111")); }
        [TestMethod] public void Caverphone2Test069() { Assert.IsTrue(Caverphone2Test("peotone", "PTN1111111")); }
        [TestMethod] public void Caverphone2Test070() { Assert.IsTrue(Caverphone2Test("Sharp", "SP11111111")); }
        [TestMethod] public void Caverphone2Test071() { Assert.IsTrue(Caverphone2Test("mawer", "MWA1111111")); }
        [TestMethod] public void Caverphone2Test072() { Assert.IsTrue(Caverphone2Test("Morasca", "MRSKA11111")); }
        [TestMethod] public void Caverphone2Test073() { Assert.IsTrue(Caverphone2Test("ticknor", "TKNA111111")); }
        [TestMethod] public void Caverphone2Test074() { Assert.IsTrue(Caverphone2Test("beaverdale", "PFTA111111")); }
        [TestMethod] public void Caverphone2Test075() { Assert.IsTrue(Caverphone2Test("caledonianew", "KLTNNA1111")); }
        [TestMethod] public void Caverphone2Test076() { Assert.IsTrue(Caverphone2Test("wellnessdicke", "WNSTK11111")); }
        [TestMethod] public void Caverphone2Test077() { Assert.IsTrue(Caverphone2Test("Rodin", "RTN1111111")); }
        [TestMethod] public void Caverphone2Test078() { Assert.IsTrue(Caverphone2Test("bluffer", "PLFA111111")); }
        [TestMethod] public void Caverphone2Test079() { Assert.IsTrue(Caverphone2Test("joey", "YA11111111")); }
        [TestMethod] public void Caverphone2Test080() { Assert.IsTrue(Caverphone2Test("unbekannter", "ANPKNTA111")); }
        [TestMethod] public void Caverphone2Test081() { Assert.IsTrue(Caverphone2Test("Baylor", "PLA1111111")); }
        [TestMethod] public void Caverphone2Test082() { Assert.IsTrue(Caverphone2Test("striplib", "STRPLP1111")); }
        [TestMethod] public void Caverphone2Test083() { Assert.IsTrue(Caverphone2Test("boquete", "PKT1111111")); }
        [TestMethod] public void Caverphone2Test084() { Assert.IsTrue(Caverphone2Test("geylang", "KLNK111111")); }
        [TestMethod] public void Caverphone2Test085() { Assert.IsTrue(Caverphone2Test("Lavi", "LFA1111111")); }
        [TestMethod] public void Caverphone2Test086() { Assert.IsTrue(Caverphone2Test("moldovans", "MTFNS11111")); }
        [TestMethod] public void Caverphone2Test087() { Assert.IsTrue(Caverphone2Test("linq", "LNK1111111")); }
        [TestMethod] public void Caverphone2Test088() { Assert.IsTrue(Caverphone2Test("Kenworthy", "KNWTA11111")); }
        [TestMethod] public void Caverphone2Test089() { Assert.IsTrue(Caverphone2Test("Steckman", "STKMN11111")); }
        [TestMethod] public void Caverphone2Test090() { Assert.IsTrue(Caverphone2Test("czechoslovakian", "KSKSLFKN11")); }
        [TestMethod] public void Caverphone2Test091() { Assert.IsTrue(Caverphone2Test("marmora", "MMRA111111")); }
        [TestMethod] public void Caverphone2Test092() { Assert.IsTrue(Caverphone2Test("Carvill", "KFA1111111")); }
        [TestMethod] public void Caverphone2Test093() { Assert.IsTrue(Caverphone2Test("chihiro", "KRA1111111")); }
        [TestMethod] public void Caverphone2Test094() { Assert.IsTrue(Caverphone2Test("hctc", "AKTK111111")); }
        [TestMethod] public void Caverphone2Test095() { Assert.IsTrue(Caverphone2Test("nolde", "NT11111111")); }
        [TestMethod] public void Caverphone2Test096() { Assert.IsTrue(Caverphone2Test("aerosolized", "ARSLST1111")); }
        [TestMethod] public void Caverphone2Test097() { Assert.IsTrue(Caverphone2Test("canterbury", "KNTPRA1111")); }
        [TestMethod] public void Caverphone2Test098() { Assert.IsTrue(Caverphone2Test("jss", "AS11111111")); }
        [TestMethod] public void Caverphone2Test099() { Assert.IsTrue(Caverphone2Test("rmn", "MN11111111")); }
        [TestMethod] public void Caverphone2Test100() { Assert.IsTrue(Caverphone2Test("mazlish", "MSLS111111")); }
        [TestMethod] public void Caverphone2Test101() { Assert.IsTrue(Caverphone2Test("faites", "FTS1111111")); }
        [TestMethod] public void Caverphone2Test102() { Assert.IsTrue(Caverphone2Test("foyer", "FA11111111")); }
        [TestMethod] public void Caverphone2Test103() { Assert.IsTrue(Caverphone2Test("ductions", "TKSNS11111")); }
        [TestMethod] public void Caverphone2Test104() { Assert.IsTrue(Caverphone2Test("Rambo", "RMPA111111")); }
        [TestMethod] public void Caverphone2Test105() { Assert.IsTrue(Caverphone2Test("Curnutte", "KNT1111111")); }
        [TestMethod] public void Caverphone2Test106() { Assert.IsTrue(Caverphone2Test("Feltus", "FTS1111111")); }
        [TestMethod] public void Caverphone2Test107() { Assert.IsTrue(Caverphone2Test("forbairt", "FPT1111111")); }
        [TestMethod] public void Caverphone2Test108() { Assert.IsTrue(Caverphone2Test("southerners", "STNS111111")); }
        [TestMethod] public void Caverphone2Test109() { Assert.IsTrue(Caverphone2Test("hypnotists", "APNTSTS111")); }
        [TestMethod] public void Caverphone2Test110() { Assert.IsTrue(Caverphone2Test("euphony", "AFNA111111")); }
        [TestMethod] public void Caverphone2Test111() { Assert.IsTrue(Caverphone2Test("mhpa", "MPA1111111")); }
        [TestMethod] public void Caverphone2Test112() { Assert.IsTrue(Caverphone2Test("matteotti", "MTTA111111")); }
        [TestMethod] public void Caverphone2Test113() { Assert.IsTrue(Caverphone2Test("Klande", "KLNT111111")); }
        [TestMethod] public void Caverphone2Test114() { Assert.IsTrue(Caverphone2Test("Trudgeon", "TRKN111111")); }
        [TestMethod] public void Caverphone2Test115() { Assert.IsTrue(Caverphone2Test("schoolhill", "SKA1111111")); }
        [TestMethod] public void Caverphone2Test116() { Assert.IsTrue(Caverphone2Test("equalizer", "AKLSA11111")); }
        [TestMethod] public void Caverphone2Test117() { Assert.IsTrue(Caverphone2Test("xnet", "KNT1111111")); }
        [TestMethod] public void Caverphone2Test118() { Assert.IsTrue(Caverphone2Test("Thell", "TA11111111")); }
        [TestMethod] public void Caverphone2Test119() { Assert.IsTrue(Caverphone2Test("Canel", "KNA1111111")); }
        [TestMethod] public void Caverphone2Test120() { Assert.IsTrue(Caverphone2Test("vmetro", "FMTRA11111")); }
        [TestMethod] public void Caverphone2Test121() { Assert.IsTrue(Caverphone2Test("burgtheater", "PKTTA11111")); }
        [TestMethod] public void Caverphone2Test122() { Assert.IsTrue(Caverphone2Test("Berlinger", "PLNKA11111")); }
        [TestMethod] public void Caverphone2Test123() { Assert.IsTrue(Caverphone2Test("crehan", "KRN1111111")); }
        [TestMethod] public void Caverphone2Test124() { Assert.IsTrue(Caverphone2Test("abysses", "APSS111111")); }
        [TestMethod] public void Caverphone2Test125() { Assert.IsTrue(Caverphone2Test("Hipolito", "APLTA11111")); }
        [TestMethod] public void Caverphone2Test126() { Assert.IsTrue(Caverphone2Test("splintered", "SPLNTRT111")); }
        [TestMethod] public void Caverphone2Test127() { Assert.IsTrue(Caverphone2Test("maintenace", "MNTNK11111")); }
        [TestMethod] public void Caverphone2Test128() { Assert.IsTrue(Caverphone2Test("decency", "TSNSA11111")); }
        [TestMethod] public void Caverphone2Test129() { Assert.IsTrue(Caverphone2Test("quantz", "KNTS111111")); }
        [TestMethod] public void Caverphone2Test130() { Assert.IsTrue(Caverphone2Test("wette", "WT11111111")); }
        [TestMethod] public void Caverphone2Test131() { Assert.IsTrue(Caverphone2Test("Feary", "FRA1111111")); }
        [TestMethod] public void Caverphone2Test132() { Assert.IsTrue(Caverphone2Test("Cuchiara", "KKRA111111")); }
        [TestMethod] public void Caverphone2Test133() { Assert.IsTrue(Caverphone2Test("Arbon", "APN1111111")); }
        [TestMethod] public void Caverphone2Test134() { Assert.IsTrue(Caverphone2Test("shyness", "SNS1111111")); }
        [TestMethod] public void Caverphone2Test135() { Assert.IsTrue(Caverphone2Test("Salin", "SLN1111111")); }
        [TestMethod] public void Caverphone2Test136() { Assert.IsTrue(Caverphone2Test("Zicafoose", "SKFS111111")); }
        [TestMethod] public void Caverphone2Test137() { Assert.IsTrue(Caverphone2Test("Menn", "MN11111111")); }
        [TestMethod] public void Caverphone2Test138() { Assert.IsTrue(Caverphone2Test("funker", "FNKA111111")); }
        [TestMethod] public void Caverphone2Test139() { Assert.IsTrue(Caverphone2Test("santillan", "SNTLN11111")); }
        [TestMethod] public void Caverphone2Test140() { Assert.IsTrue(Caverphone2Test("punani", "PNNA111111")); }
        [TestMethod] public void Caverphone2Test141() { Assert.IsTrue(Caverphone2Test("basa", "PSA1111111")); }
        [TestMethod] public void Caverphone2Test142() { Assert.IsTrue(Caverphone2Test("bluefin", "PLFN111111")); }
        [TestMethod] public void Caverphone2Test143() { Assert.IsTrue(Caverphone2Test("cc", "K111111111")); }
        [TestMethod] public void Caverphone2Test144() { Assert.IsTrue(Caverphone2Test("zipgenius", "SPKNS11111")); }
        [TestMethod] public void Caverphone2Test145() { Assert.IsTrue(Caverphone2Test("Kirchen", "KKN1111111")); }
        [TestMethod] public void Caverphone2Test146() { Assert.IsTrue(Caverphone2Test("commentaar", "KMNTA11111")); }
        [TestMethod] public void Caverphone2Test147() { Assert.IsTrue(Caverphone2Test("expansive", "AKPNSF1111")); }
        [TestMethod] public void Caverphone2Test148() { Assert.IsTrue(Caverphone2Test("castlebar", "KSTLPA1111")); }
        [TestMethod] public void Caverphone2Test149() { Assert.IsTrue(Caverphone2Test("lft", "FT11111111")); }
        [TestMethod] public void Caverphone2Test150() { Assert.IsTrue(Caverphone2Test("robla", "RPLA111111")); }
        [TestMethod] public void Caverphone2Test151() { Assert.IsTrue(Caverphone2Test("zarontin", "SRNTN11111")); }
        [TestMethod] public void Caverphone2Test152() { Assert.IsTrue(Caverphone2Test("nawc", "NK11111111")); }
        [TestMethod] public void Caverphone2Test153() { Assert.IsTrue(Caverphone2Test("resolvconf", "RSFKNF1111")); }
        [TestMethod] public void Caverphone2Test154() { Assert.IsTrue(Caverphone2Test("networker", "NTWKA11111")); }
        [TestMethod] public void Caverphone2Test155() { Assert.IsTrue(Caverphone2Test("airlins", "ALNS111111")); }
        [TestMethod] public void Caverphone2Test156() { Assert.IsTrue(Caverphone2Test("Piskel", "PSKA111111")); }
        [TestMethod] public void Caverphone2Test157() { Assert.IsTrue(Caverphone2Test("hilson", "ASN1111111")); }
        [TestMethod] public void Caverphone2Test158() { Assert.IsTrue(Caverphone2Test("deco", "TKA1111111")); }
        [TestMethod] public void Caverphone2Test159() { Assert.IsTrue(Caverphone2Test("cents", "SNTS111111")); }
        [TestMethod] public void Caverphone2Test160() { Assert.IsTrue(Caverphone2Test("award", "AWT1111111")); }
        [TestMethod] public void Caverphone2Test161() { Assert.IsTrue(Caverphone2Test("reykjanes", "RKNS111111")); }
        [TestMethod] public void Caverphone2Test162() { Assert.IsTrue(Caverphone2Test("perona", "PRNA111111")); }
        [TestMethod] public void Caverphone2Test163() { Assert.IsTrue(Caverphone2Test("epistle", "APSTA11111")); }
        [TestMethod] public void Caverphone2Test164() { Assert.IsTrue(Caverphone2Test("insound", "ANSNT11111")); }
        [TestMethod] public void Caverphone2Test165() { Assert.IsTrue(Caverphone2Test("qantas", "KNTS111111")); }
        [TestMethod] public void Caverphone2Test166() { Assert.IsTrue(Caverphone2Test("wholey", "WLA1111111")); }
        [TestMethod] public void Caverphone2Test167() { Assert.IsTrue(Caverphone2Test("aragona", "ARKNA11111")); }
        [TestMethod] public void Caverphone2Test168() { Assert.IsTrue(Caverphone2Test("Vancheri", "FNKRA11111")); }
        [TestMethod] public void Caverphone2Test169() { Assert.IsTrue(Caverphone2Test("allocution", "ALKSN11111")); }
        [TestMethod] public void Caverphone2Test170() { Assert.IsTrue(Caverphone2Test("volodya", "FLTA111111")); }
        [TestMethod] public void Caverphone2Test171() { Assert.IsTrue(Caverphone2Test("enunciate", "ANNST11111")); }
        [TestMethod] public void Caverphone2Test172() { Assert.IsTrue(Caverphone2Test("uuuu", "AA11111111")); }
        [TestMethod] public void Caverphone2Test173() { Assert.IsTrue(Caverphone2Test("Louato", "LTA1111111")); }
        [TestMethod] public void Caverphone2Test174() { Assert.IsTrue(Caverphone2Test("Marquitta", "MKTA111111")); }
        [TestMethod] public void Caverphone2Test175() { Assert.IsTrue(Caverphone2Test("surmountable", "SMNTPA1111")); }
        [TestMethod] public void Caverphone2Test176() { Assert.IsTrue(Caverphone2Test("gaultier", "KTA1111111")); }
        [TestMethod] public void Caverphone2Test177() { Assert.IsTrue(Caverphone2Test("dafoe", "TFA1111111")); }
        [TestMethod] public void Caverphone2Test178() { Assert.IsTrue(Caverphone2Test("Claudio", "KLTA111111")); }
        [TestMethod] public void Caverphone2Test179() { Assert.IsTrue(Caverphone2Test("ritva", "RTFA111111")); }
        [TestMethod] public void Caverphone2Test180() { Assert.IsTrue(Caverphone2Test("spunky", "SPNKA11111")); }
        [TestMethod] public void Caverphone2Test181() { Assert.IsTrue(Caverphone2Test("npov", "NPF1111111")); }
        [TestMethod] public void Caverphone2Test182() { Assert.IsTrue(Caverphone2Test("eurythmics", "ARTMKS1111")); }
        [TestMethod] public void Caverphone2Test183() { Assert.IsTrue(Caverphone2Test("skittish", "SKTS111111")); }
        [TestMethod] public void Caverphone2Test184() { Assert.IsTrue(Caverphone2Test("scooter", "SKTA111111")); }
        [TestMethod] public void Caverphone2Test185() { Assert.IsTrue(Caverphone2Test("unfermented", "ANFMNTT111")); }
        [TestMethod] public void Caverphone2Test186() { Assert.IsTrue(Caverphone2Test("kerridge", "KRK1111111")); }
        [TestMethod] public void Caverphone2Test187() { Assert.IsTrue(Caverphone2Test("scenography", "SNKRFA1111")); }
        [TestMethod] public void Caverphone2Test188() { Assert.IsTrue(Caverphone2Test("sahalee", "SLA1111111")); }
        [TestMethod] public void Caverphone2Test189() { Assert.IsTrue(Caverphone2Test("spooktacular", "SPKTKLA111")); }
        [TestMethod] public void Caverphone2Test190() { Assert.IsTrue(Caverphone2Test("boissons", "PSNS111111")); }
        [TestMethod] public void Caverphone2Test191() { Assert.IsTrue(Caverphone2Test("arbete", "APT1111111")); }
        [TestMethod] public void Caverphone2Test192() { Assert.IsTrue(Caverphone2Test("Norrick", "NRK1111111")); }
        [TestMethod] public void Caverphone2Test193() { Assert.IsTrue(Caverphone2Test("Sonnier", "SNA1111111")); }
        [TestMethod] public void Caverphone2Test194() { Assert.IsTrue(Caverphone2Test("gnomeui", "NMA1111111")); }
        [TestMethod] public void Caverphone2Test195() { Assert.IsTrue(Caverphone2Test("milian", "MLN1111111")); }
        [TestMethod] public void Caverphone2Test196() { Assert.IsTrue(Caverphone2Test("blackplanetcom", "PLKPLNTKM1")); }
        [TestMethod] public void Caverphone2Test197() { Assert.IsTrue(Caverphone2Test("tuned", "TNT1111111")); }
        [TestMethod] public void Caverphone2Test198() { Assert.IsTrue(Caverphone2Test("Salone", "SLN1111111")); }
        [TestMethod] public void Caverphone2Test199() { Assert.IsTrue(Caverphone2Test("marathon", "MRTN111111")); }
        [TestMethod] public void Caverphone2Test200() { Assert.IsTrue(Caverphone2Test("layoffs", "LFS1111111")); }
        [TestMethod] public void Caverphone2Test201() { Assert.IsTrue(Caverphone2Test("hotek", "ATK1111111")); }
        [TestMethod] public void Caverphone2Test202() { Assert.IsTrue(Caverphone2Test("emme", "AM11111111")); }
        [TestMethod] public void Caverphone2Test203() { Assert.IsTrue(Caverphone2Test("amarasinghe", "AMRSN11111")); }
        [TestMethod] public void Caverphone2Test204() { Assert.IsTrue(Caverphone2Test("midas", "MTS1111111")); }
        [TestMethod] public void Caverphone2Test205() { Assert.IsTrue(Caverphone2Test("inhaltsangabe", "ANTSNKP111")); }
        [TestMethod] public void Caverphone2Test206() { Assert.IsTrue(Caverphone2Test("smow", "SMA1111111")); }
        [TestMethod] public void Caverphone2Test207() { Assert.IsTrue(Caverphone2Test("policing", "PLSNK11111")); }
        [TestMethod] public void Caverphone2Test208() { Assert.IsTrue(Caverphone2Test("usmf", "ASMF111111")); }
        [TestMethod] public void Caverphone2Test209() { Assert.IsTrue(Caverphone2Test("inferred", "ANFRT11111")); }
        [TestMethod] public void Caverphone2Test210() { Assert.IsTrue(Caverphone2Test("Eaglen", "AKLN111111")); }
        [TestMethod] public void Caverphone2Test211() { Assert.IsTrue(Caverphone2Test("dralle", "TRA1111111")); }
        [TestMethod] public void Caverphone2Test212() { Assert.IsTrue(Caverphone2Test("kalmus", "KMS1111111")); }
        [TestMethod] public void Caverphone2Test213() { Assert.IsTrue(Caverphone2Test("nork", "NK11111111")); }
        [TestMethod] public void Caverphone2Test214() { Assert.IsTrue(Caverphone2Test("Waterston", "WTSTN11111")); }
        [TestMethod] public void Caverphone2Test215() { Assert.IsTrue(Caverphone2Test("penalised", "PNLST11111")); }
        [TestMethod] public void Caverphone2Test216() { Assert.IsTrue(Caverphone2Test("Lupacchino", "LPKNA11111")); }
        [TestMethod] public void Caverphone2Test217() { Assert.IsTrue(Caverphone2Test("getgid", "KTKT111111")); }
        [TestMethod] public void Caverphone2Test218() { Assert.IsTrue(Caverphone2Test("kever", "KFA1111111")); }
        [TestMethod] public void Caverphone2Test219() { Assert.IsTrue(Caverphone2Test("pallavicini", "PLFSNA1111")); }
        [TestMethod] public void Caverphone2Test220() { Assert.IsTrue(Caverphone2Test("Pais", "PS11111111")); }
        [TestMethod] public void Caverphone2Test221() { Assert.IsTrue(Caverphone2Test("youghiogheny", "YKKNA11111")); }
        [TestMethod] public void Caverphone2Test222() { Assert.IsTrue(Caverphone2Test("Catherina", "KTRNA11111")); }
        [TestMethod] public void Caverphone2Test223() { Assert.IsTrue(Caverphone2Test("Givant", "KFNT111111")); }
        [TestMethod] public void Caverphone2Test224() { Assert.IsTrue(Caverphone2Test("koffi", "KFA1111111")); }
        [TestMethod] public void Caverphone2Test225() { Assert.IsTrue(Caverphone2Test("troutbeck", "TRTPK11111")); }
        [TestMethod] public void Caverphone2Test226() { Assert.IsTrue(Caverphone2Test("moreelse", "MRS1111111")); }
        [TestMethod] public void Caverphone2Test227() { Assert.IsTrue(Caverphone2Test("seacrest", "SKRST11111")); }
        [TestMethod] public void Caverphone2Test228() { Assert.IsTrue(Caverphone2Test("ufj", "AFA1111111")); }
        [TestMethod] public void Caverphone2Test229() { Assert.IsTrue(Caverphone2Test("dereferences", "TRFRNSS111")); }
        [TestMethod] public void Caverphone2Test230() { Assert.IsTrue(Caverphone2Test("sarena", "SRNA111111")); }
        [TestMethod] public void Caverphone2Test231() { Assert.IsTrue(Caverphone2Test("Kurt", "KT11111111")); }
        [TestMethod] public void Caverphone2Test232() { Assert.IsTrue(Caverphone2Test("comanche", "KMNK111111")); }
        [TestMethod] public void Caverphone2Test233() { Assert.IsTrue(Caverphone2Test("chersoness", "KSNS111111")); }
        [TestMethod] public void Caverphone2Test234() { Assert.IsTrue(Caverphone2Test("cd", "KT11111111")); }
        [TestMethod] public void Caverphone2Test235() { Assert.IsTrue(Caverphone2Test("merzky", "MSKA111111")); }
        [TestMethod] public void Caverphone2Test236() { Assert.IsTrue(Caverphone2Test("Nordsiek", "NTSK111111")); }
        [TestMethod] public void Caverphone2Test237() { Assert.IsTrue(Caverphone2Test("samus", "SMS1111111")); }
        [TestMethod] public void Caverphone2Test238() { Assert.IsTrue(Caverphone2Test("tougher", "TFA1111111")); }
        [TestMethod] public void Caverphone2Test239() { Assert.IsTrue(Caverphone2Test("monodoc", "MNTK111111")); }
        [TestMethod] public void Caverphone2Test240() { Assert.IsTrue(Caverphone2Test("deepings", "TPNKS11111")); }
        [TestMethod] public void Caverphone2Test241() { Assert.IsTrue(Caverphone2Test("datel", "TTA1111111")); }
        [TestMethod] public void Caverphone2Test242() { Assert.IsTrue(Caverphone2Test("Stockett", "STKT111111")); }
        [TestMethod] public void Caverphone2Test243() { Assert.IsTrue(Caverphone2Test("bryum", "PRM1111111")); }
        [TestMethod] public void Caverphone2Test244() { Assert.IsTrue(Caverphone2Test("surveyed", "SFT1111111")); }
        [TestMethod] public void Caverphone2Test245() { Assert.IsTrue(Caverphone2Test("microcephaly", "MKRSFLA111")); }
        [TestMethod] public void Caverphone2Test246() { Assert.IsTrue(Caverphone2Test("trimoxazole", "TRMKSA1111")); }
        [TestMethod] public void Caverphone2Test247() { Assert.IsTrue(Caverphone2Test("bastide", "PSTT111111")); }
        [TestMethod] public void Caverphone2Test248() { Assert.IsTrue(Caverphone2Test("lipo", "LPA1111111")); }
        [TestMethod] public void Caverphone2Test249() { Assert.IsTrue(Caverphone2Test("Bosket", "PSKT111111")); }
        [TestMethod] public void Caverphone2Test250() { Assert.IsTrue(Caverphone2Test("oroms", "ARMS111111")); }
        [TestMethod] public void Caverphone2Test251() { Assert.IsTrue(Caverphone2Test("vandenburg", "FNTNPK1111")); }
        [TestMethod] public void Caverphone2Test252() { Assert.IsTrue(Caverphone2Test("wirtschaftsforschung", "WTSKFTSFSK")); }
        [TestMethod] public void Caverphone2Test253() { Assert.IsTrue(Caverphone2Test("lilypond", "LLPNT11111")); }
        [TestMethod] public void Caverphone2Test254() { Assert.IsTrue(Caverphone2Test("mouthfeel", "MTFA111111")); }
        [TestMethod] public void Caverphone2Test255() { Assert.IsTrue(Caverphone2Test("wwwunibancocombr", "WNPNKKMPA1")); }
        [TestMethod] public void Caverphone2Test256() { Assert.IsTrue(Caverphone2Test("Worster", "WSTA111111")); }
        [TestMethod] public void Caverphone2Test257() { Assert.IsTrue(Caverphone2Test("Ahmad", "AMT1111111")); }
        [TestMethod] public void Caverphone2Test258() { Assert.IsTrue(Caverphone2Test("sweetser", "SWTSA11111")); }
        [TestMethod] public void Caverphone2Test259() { Assert.IsTrue(Caverphone2Test("vsepr", "FSPA111111")); }
        [TestMethod] public void Caverphone2Test260() { Assert.IsTrue(Caverphone2Test("dput", "TPT1111111")); }
        [TestMethod] public void Caverphone2Test261() { Assert.IsTrue(Caverphone2Test("austlit", "ASTLT11111")); }
        [TestMethod] public void Caverphone2Test262() { Assert.IsTrue(Caverphone2Test("Clemen", "KLMN111111")); }
        [TestMethod] public void Caverphone2Test263() { Assert.IsTrue(Caverphone2Test("phrva", "FFA1111111")); }
        [TestMethod] public void Caverphone2Test264() { Assert.IsTrue(Caverphone2Test("weipa", "WPA1111111")); }
        [TestMethod] public void Caverphone2Test265() { Assert.IsTrue(Caverphone2Test("Schrantz", "SKRNTS1111")); }
        [TestMethod] public void Caverphone2Test266() { Assert.IsTrue(Caverphone2Test("meany", "MNA1111111")); }
        [TestMethod] public void Caverphone2Test267() { Assert.IsTrue(Caverphone2Test("hodgepodge", "AKPK111111")); }
        [TestMethod] public void Caverphone2Test268() { Assert.IsTrue(Caverphone2Test("knuble", "KNPA111111")); }
        [TestMethod] public void Caverphone2Test269() { Assert.IsTrue(Caverphone2Test("caniglia", "KNKLA11111")); }
        [TestMethod] public void Caverphone2Test270() { Assert.IsTrue(Caverphone2Test("blowjobsasics", "PLWPSSKS11")); }
        [TestMethod] public void Caverphone2Test271() { Assert.IsTrue(Caverphone2Test("flyjacket", "FLKT111111")); }
        [TestMethod] public void Caverphone2Test272() { Assert.IsTrue(Caverphone2Test("galatian", "KLSN111111")); }
        [TestMethod] public void Caverphone2Test273() { Assert.IsTrue(Caverphone2Test("hotsel", "ATSA111111")); }
        [TestMethod] public void Caverphone2Test274() { Assert.IsTrue(Caverphone2Test("autorun", "ATRN111111")); }
        [TestMethod] public void Caverphone2Test275() { Assert.IsTrue(Caverphone2Test("cocoon", "KKN1111111")); }
        [TestMethod] public void Caverphone2Test276() { Assert.IsTrue(Caverphone2Test("kooks", "KKS1111111")); }
        [TestMethod] public void Caverphone2Test277() { Assert.IsTrue(Caverphone2Test("endocrinol", "ANTKRNA111")); }
        [TestMethod] public void Caverphone2Test278() { Assert.IsTrue(Caverphone2Test("mesages", "MSKS111111")); }
        [TestMethod] public void Caverphone2Test279() { Assert.IsTrue(Caverphone2Test("Disney", "TSNA111111")); }
        [TestMethod] public void Caverphone2Test280() { Assert.IsTrue(Caverphone2Test("speedline", "SPTLN11111")); }
        [TestMethod] public void Caverphone2Test281() { Assert.IsTrue(Caverphone2Test("gabaldon", "KPTN111111")); }
        [TestMethod] public void Caverphone2Test282() { Assert.IsTrue(Caverphone2Test("margaux", "MKK1111111")); }
        [TestMethod] public void Caverphone2Test283() { Assert.IsTrue(Caverphone2Test("housecalls", "ASKS111111")); }
        [TestMethod] public void Caverphone2Test284() { Assert.IsTrue(Caverphone2Test("siltation", "STSN111111")); }
        [TestMethod] public void Caverphone2Test285() { Assert.IsTrue(Caverphone2Test("automatic", "ATMTK11111")); }
        [TestMethod] public void Caverphone2Test286() { Assert.IsTrue(Caverphone2Test("freakshow", "FRKSA11111")); }
        [TestMethod] public void Caverphone2Test287() { Assert.IsTrue(Caverphone2Test("gorojovsky", "KRFSKA1111")); }
        [TestMethod] public void Caverphone2Test288() { Assert.IsTrue(Caverphone2Test("milwaukie", "MWKA111111")); }
        [TestMethod] public void Caverphone2Test289() { Assert.IsTrue(Caverphone2Test("wwwgap", "KP11111111")); }
        [TestMethod] public void Caverphone2Test290() { Assert.IsTrue(Caverphone2Test("autm", "ATM1111111")); }
        [TestMethod] public void Caverphone2Test291() { Assert.IsTrue(Caverphone2Test("borromini", "PRMNA11111")); }
        [TestMethod] public void Caverphone2Test292() { Assert.IsTrue(Caverphone2Test("zpp", "SP11111111")); }
        [TestMethod] public void Caverphone2Test293() { Assert.IsTrue(Caverphone2Test("Penovich", "PNFK111111")); }
        [TestMethod] public void Caverphone2Test294() { Assert.IsTrue(Caverphone2Test("domine", "TMN1111111")); }
        [TestMethod] public void Caverphone2Test295() { Assert.IsTrue(Caverphone2Test("caves", "KFS1111111")); }
        [TestMethod] public void Caverphone2Test296() { Assert.IsTrue(Caverphone2Test("uato", "ATA1111111")); }
        [TestMethod] public void Caverphone2Test297() { Assert.IsTrue(Caverphone2Test("tiltonsville", "TTNSFA1111")); }
        [TestMethod] public void Caverphone2Test298() { Assert.IsTrue(Caverphone2Test("Ken", "KN11111111")); }
        [TestMethod] public void Caverphone2Test299() { Assert.IsTrue(Caverphone2Test("Delonais", "TLNS111111")); }
        [TestMethod] public void Caverphone2Test300() { Assert.IsTrue(Caverphone2Test("conniption", "KNPSN11111")); }
        [TestMethod] public void Caverphone2Test301() { Assert.IsTrue(Caverphone2Test("Wenske", "WNSK111111")); }
        [TestMethod] public void Caverphone2Test302() { Assert.IsTrue(Caverphone2Test("cautery", "KTRA111111")); }
        [TestMethod] public void Caverphone2Test303() { Assert.IsTrue(Caverphone2Test("barbourville", "PPFA111111")); }
        [TestMethod] public void Caverphone2Test304() { Assert.IsTrue(Caverphone2Test("departamentos", "TPTMNTS111")); }
        [TestMethod] public void Caverphone2Test305() { Assert.IsTrue(Caverphone2Test("weaponry", "WPNRA11111")); }
        [TestMethod] public void Caverphone2Test306() { Assert.IsTrue(Caverphone2Test("Haggett", "AKT1111111")); }
        [TestMethod] public void Caverphone2Test307() { Assert.IsTrue(Caverphone2Test("martinville", "MTNFA11111")); }
        [TestMethod] public void Caverphone2Test308() { Assert.IsTrue(Caverphone2Test("stina", "STNA111111")); }
        [TestMethod] public void Caverphone2Test309() { Assert.IsTrue(Caverphone2Test("Rubottom", "RPTM111111")); }
        [TestMethod] public void Caverphone2Test310() { Assert.IsTrue(Caverphone2Test("Soyke", "SK11111111")); }
        [TestMethod] public void Caverphone2Test311() { Assert.IsTrue(Caverphone2Test("corse", "KS11111111")); }
        [TestMethod] public void Caverphone2Test312() { Assert.IsTrue(Caverphone2Test("totalling", "TTLNK11111")); }
        [TestMethod] public void Caverphone2Test313() { Assert.IsTrue(Caverphone2Test("kuppam", "KPM1111111")); }
        [TestMethod] public void Caverphone2Test314() { Assert.IsTrue(Caverphone2Test("ftpadmin", "FTPTMN1111")); }
        [TestMethod] public void Caverphone2Test315() { Assert.IsTrue(Caverphone2Test("Forst", "FST1111111")); }
        [TestMethod] public void Caverphone2Test316() { Assert.IsTrue(Caverphone2Test("Ashauer", "ASA1111111")); }
        [TestMethod] public void Caverphone2Test317() { Assert.IsTrue(Caverphone2Test("ashtanga", "ASTNKA1111")); }
        [TestMethod] public void Caverphone2Test318() { Assert.IsTrue(Caverphone2Test("alonissos", "ALNSS11111")); }
        [TestMethod] public void Caverphone2Test319() { Assert.IsTrue(Caverphone2Test("Chimilio", "KMLA111111")); }
        [TestMethod] public void Caverphone2Test320() { Assert.IsTrue(Caverphone2Test("deafbazon", "TFPSN11111")); }
        [TestMethod] public void Caverphone2Test321() { Assert.IsTrue(Caverphone2Test("psmb", "PSM1111111")); }
        [TestMethod] public void Caverphone2Test322() { Assert.IsTrue(Caverphone2Test("Ferraraccio", "FRRKSA1111")); }
        [TestMethod] public void Caverphone2Test323() { Assert.IsTrue(Caverphone2Test("fractionated", "FRKSNTT111")); }
        [TestMethod] public void Caverphone2Test324() { Assert.IsTrue(Caverphone2Test("rrd", "T111111111")); }
        [TestMethod] public void Caverphone2Test325() { Assert.IsTrue(Caverphone2Test("luminosities", "LMNSTS1111")); }
        [TestMethod] public void Caverphone2Test326() { Assert.IsTrue(Caverphone2Test("Platzer", "PLTSA11111")); }
        [TestMethod] public void Caverphone2Test327() { Assert.IsTrue(Caverphone2Test("modulator", "MTLTA11111")); }
        [TestMethod] public void Caverphone2Test328() { Assert.IsTrue(Caverphone2Test("tyneside", "TNST111111")); }
        [TestMethod] public void Caverphone2Test329() { Assert.IsTrue(Caverphone2Test("nonuser", "NNSA111111")); }
        [TestMethod] public void Caverphone2Test330() { Assert.IsTrue(Caverphone2Test("haspel", "ASPA111111")); }
        [TestMethod] public void Caverphone2Test331() { Assert.IsTrue(Caverphone2Test("cortex", "KTK1111111")); }
        [TestMethod] public void Caverphone2Test332() { Assert.IsTrue(Caverphone2Test("vechicle", "FKKA111111")); }
        [TestMethod] public void Caverphone2Test333() { Assert.IsTrue(Caverphone2Test("epinions", "APNNS11111")); }
        [TestMethod] public void Caverphone2Test334() { Assert.IsTrue(Caverphone2Test("wwwusmintgov", "WSMNTKF111")); }
        [TestMethod] public void Caverphone2Test335() { Assert.IsTrue(Caverphone2Test("katies", "KTS1111111")); }
        [TestMethod] public void Caverphone2Test336() { Assert.IsTrue(Caverphone2Test("aminosalicylic", "AMNSLSLK11")); }
        [TestMethod] public void Caverphone2Test337() { Assert.IsTrue(Caverphone2Test("mmegi", "MKA1111111")); }
        [TestMethod] public void Caverphone2Test338() { Assert.IsTrue(Caverphone2Test("sbir", "SPA1111111")); }
        [TestMethod] public void Caverphone2Test339() { Assert.IsTrue(Caverphone2Test("learned", "LNT1111111")); }
        [TestMethod] public void Caverphone2Test340() { Assert.IsTrue(Caverphone2Test("supris", "SPRS111111")); }
        [TestMethod] public void Caverphone2Test341() { Assert.IsTrue(Caverphone2Test("mozarteum", "MSTM111111")); }
        [TestMethod] public void Caverphone2Test342() { Assert.IsTrue(Caverphone2Test("selzer", "SSA1111111")); }
        [TestMethod] public void Caverphone2Test343() { Assert.IsTrue(Caverphone2Test("tmug", "TMK1111111")); }
        [TestMethod] public void Caverphone2Test344() { Assert.IsTrue(Caverphone2Test("Kisto", "KSTA111111")); }
        [TestMethod] public void Caverphone2Test345() { Assert.IsTrue(Caverphone2Test("iib", "AP11111111")); }
        [TestMethod] public void Caverphone2Test346() { Assert.IsTrue(Caverphone2Test("wwwincredimail", "WNKRTMA111")); }
        [TestMethod] public void Caverphone2Test347() { Assert.IsTrue(Caverphone2Test("izpack", "ASPK111111")); }
        [TestMethod] public void Caverphone2Test348() { Assert.IsTrue(Caverphone2Test("gaymovie", "KMFA111111")); }
        [TestMethod] public void Caverphone2Test349() { Assert.IsTrue(Caverphone2Test("Buchholz", "PKS1111111")); }
        [TestMethod] public void Caverphone2Test350() { Assert.IsTrue(Caverphone2Test("culcairn", "KKN1111111")); }
        [TestMethod] public void Caverphone2Test351() { Assert.IsTrue(Caverphone2Test("barys", "PRS1111111")); }
        [TestMethod] public void Caverphone2Test352() { Assert.IsTrue(Caverphone2Test("burets", "PRTS111111")); }
        [TestMethod] public void Caverphone2Test353() { Assert.IsTrue(Caverphone2Test("Sorce", "SK11111111")); }
        [TestMethod] public void Caverphone2Test354() { Assert.IsTrue(Caverphone2Test("chimique", "KMKA111111")); }
        [TestMethod] public void Caverphone2Test355() { Assert.IsTrue(Caverphone2Test("kitada", "KTTA111111")); }
        [TestMethod] public void Caverphone2Test356() { Assert.IsTrue(Caverphone2Test("Engeman", "ANKMN11111")); }
        [TestMethod] public void Caverphone2Test357() { Assert.IsTrue(Caverphone2Test("raveendran", "RFNTRN1111")); }
        [TestMethod] public void Caverphone2Test358() { Assert.IsTrue(Caverphone2Test("Bendele", "PNTA111111")); }
        [TestMethod] public void Caverphone2Test359() { Assert.IsTrue(Caverphone2Test("Pawlitschek", "PLTSKK1111")); }
        [TestMethod] public void Caverphone2Test360() { Assert.IsTrue(Caverphone2Test("hogfather", "AKFTA11111")); }
        [TestMethod] public void Caverphone2Test361() { Assert.IsTrue(Caverphone2Test("eyedrum", "ATRM111111")); }
        [TestMethod] public void Caverphone2Test362() { Assert.IsTrue(Caverphone2Test("Ferrara", "FRRA111111")); }
        [TestMethod] public void Caverphone2Test363() { Assert.IsTrue(Caverphone2Test("zhuh", "SA11111111")); }
        [TestMethod] public void Caverphone2Test364() { Assert.IsTrue(Caverphone2Test("zodiak", "STK1111111")); }
        [TestMethod] public void Caverphone2Test365() { Assert.IsTrue(Caverphone2Test("pchcom", "PKKM111111")); }
        [TestMethod] public void Caverphone2Test366() { Assert.IsTrue(Caverphone2Test("conferees", "KNFRS11111")); }
        [TestMethod] public void Caverphone2Test367() { Assert.IsTrue(Caverphone2Test("Decillis", "TSLS111111")); }
        [TestMethod] public void Caverphone2Test368() { Assert.IsTrue(Caverphone2Test("downloar", "TNLA111111")); }
        [TestMethod] public void Caverphone2Test369() { Assert.IsTrue(Caverphone2Test("shard", "ST11111111")); }
        [TestMethod] public void Caverphone2Test370() { Assert.IsTrue(Caverphone2Test("fajr", "FA11111111")); }
        [TestMethod] public void Caverphone2Test371() { Assert.IsTrue(Caverphone2Test("quisque", "KSKA111111")); }
        [TestMethod] public void Caverphone2Test372() { Assert.IsTrue(Caverphone2Test("winterizing", "WNTRSNK111")); }
        [TestMethod] public void Caverphone2Test373() { Assert.IsTrue(Caverphone2Test("referate", "RFRT111111")); }
        [TestMethod] public void Caverphone2Test374() { Assert.IsTrue(Caverphone2Test("nuxone", "NKN1111111")); }
        [TestMethod] public void Caverphone2Test375() { Assert.IsTrue(Caverphone2Test("Racheal", "RKA1111111")); }
        [TestMethod] public void Caverphone2Test376() { Assert.IsTrue(Caverphone2Test("bizben", "PSPN111111")); }
        [TestMethod] public void Caverphone2Test377() { Assert.IsTrue(Caverphone2Test("musictalk", "MSKTK11111")); }
        [TestMethod] public void Caverphone2Test378() { Assert.IsTrue(Caverphone2Test("ogoal", "AKA1111111")); }
        [TestMethod] public void Caverphone2Test379() { Assert.IsTrue(Caverphone2Test("Skoff", "SKF1111111")); }
        [TestMethod] public void Caverphone2Test380() { Assert.IsTrue(Caverphone2Test("Seehusen", "SSN1111111")); }
        [TestMethod] public void Caverphone2Test381() { Assert.IsTrue(Caverphone2Test("Reim", "RM11111111")); }
        [TestMethod] public void Caverphone2Test382() { Assert.IsTrue(Caverphone2Test("Yoh", "YA11111111")); }
        [TestMethod] public void Caverphone2Test383() { Assert.IsTrue(Caverphone2Test("gapi", "KPA1111111")); }
        [TestMethod] public void Caverphone2Test384() { Assert.IsTrue(Caverphone2Test("Brightbill", "PRTPA11111")); }
        [TestMethod] public void Caverphone2Test385() { Assert.IsTrue(Caverphone2Test("shuey", "SA11111111")); }
        [TestMethod] public void Caverphone2Test386() { Assert.IsTrue(Caverphone2Test("posium", "PSM1111111")); }
        [TestMethod] public void Caverphone2Test387() { Assert.IsTrue(Caverphone2Test("Falknor", "FKNA111111")); }
        [TestMethod] public void Caverphone2Test388() { Assert.IsTrue(Caverphone2Test("ucat", "AKT1111111")); }
        [TestMethod] public void Caverphone2Test389() { Assert.IsTrue(Caverphone2Test("properspace", "PRPSPK1111")); }
        [TestMethod] public void Caverphone2Test390() { Assert.IsTrue(Caverphone2Test("showimg", "SWMK111111")); }
        [TestMethod] public void Caverphone2Test391() { Assert.IsTrue(Caverphone2Test("Montecillo", "MNTSLA1111")); }
        [TestMethod] public void Caverphone2Test392() { Assert.IsTrue(Caverphone2Test("sajak", "SK11111111")); }
        [TestMethod] public void Caverphone2Test393() { Assert.IsTrue(Caverphone2Test("maturbation", "MTPSN11111")); }
        [TestMethod] public void Caverphone2Test394() { Assert.IsTrue(Caverphone2Test("Lettie", "LTA1111111")); }
        [TestMethod] public void Caverphone2Test395() { Assert.IsTrue(Caverphone2Test("clauss", "KLS1111111")); }
        [TestMethod] public void Caverphone2Test396() { Assert.IsTrue(Caverphone2Test("scheiber", "SKPA111111")); }
        [TestMethod] public void Caverphone2Test397() { Assert.IsTrue(Caverphone2Test("matp", "MTP1111111")); }
        [TestMethod] public void Caverphone2Test398() { Assert.IsTrue(Caverphone2Test("mervtormel", "MFTMA11111")); }
        [TestMethod] public void Caverphone2Test399() { Assert.IsTrue(Caverphone2Test("guanahani", "KNNA111111")); }
        [TestMethod] public void Caverphone2Test400() { Assert.IsTrue(Caverphone2Test("citement", "STMNT11111")); }
        [TestMethod] public void Caverphone2Test401() { Assert.IsTrue(Caverphone2Test("immu", "AMA1111111")); }
        [TestMethod] public void Caverphone2Test402() { Assert.IsTrue(Caverphone2Test("virulence", "FRLNK11111")); }
        [TestMethod] public void Caverphone2Test403() { Assert.IsTrue(Caverphone2Test("kussa", "KSA1111111")); }
        [TestMethod] public void Caverphone2Test404() { Assert.IsTrue(Caverphone2Test("gso", "KSA1111111")); }
        [TestMethod] public void Caverphone2Test405() { Assert.IsTrue(Caverphone2Test("webviajes", "WPFS111111")); }
        [TestMethod] public void Caverphone2Test406() { Assert.IsTrue(Caverphone2Test("ldwork", "TWK1111111")); }
        [TestMethod] public void Caverphone2Test407() { Assert.IsTrue(Caverphone2Test("verses", "FSS1111111")); }
        [TestMethod] public void Caverphone2Test408() { Assert.IsTrue(Caverphone2Test("sondes", "SNTS111111")); }
        [TestMethod] public void Caverphone2Test409() { Assert.IsTrue(Caverphone2Test("freshpair", "FRSPA11111")); }
        [TestMethod] public void Caverphone2Test410() { Assert.IsTrue(Caverphone2Test("licorne", "LKN1111111")); }
        [TestMethod] public void Caverphone2Test411() { Assert.IsTrue(Caverphone2Test("Vanis", "FNS1111111")); }
        [TestMethod] public void Caverphone2Test412() { Assert.IsTrue(Caverphone2Test("Buena", "PNA1111111")); }
        [TestMethod] public void Caverphone2Test413() { Assert.IsTrue(Caverphone2Test("Tauares", "TRS1111111")); }
        [TestMethod] public void Caverphone2Test414() { Assert.IsTrue(Caverphone2Test("ikus", "AKS1111111")); }
        [TestMethod] public void Caverphone2Test415() { Assert.IsTrue(Caverphone2Test("genrebox", "KNRPK11111")); }
        [TestMethod] public void Caverphone2Test416() { Assert.IsTrue(Caverphone2Test("rth", "T111111111")); }
        [TestMethod] public void Caverphone2Test417() { Assert.IsTrue(Caverphone2Test("Spaun", "SPN1111111")); }
        [TestMethod] public void Caverphone2Test418() { Assert.IsTrue(Caverphone2Test("wiersbe", "WSP1111111")); }
        [TestMethod] public void Caverphone2Test419() { Assert.IsTrue(Caverphone2Test("dad", "TT11111111")); }
        [TestMethod] public void Caverphone2Test420() { Assert.IsTrue(Caverphone2Test("tus", "TS11111111")); }
        [TestMethod] public void Caverphone2Test421() { Assert.IsTrue(Caverphone2Test("Weidert", "WTT1111111")); }
        [TestMethod] public void Caverphone2Test422() { Assert.IsTrue(Caverphone2Test("rijke", "RK11111111")); }
        [TestMethod] public void Caverphone2Test423() { Assert.IsTrue(Caverphone2Test("fischbein", "FSKPN11111")); }
        [TestMethod] public void Caverphone2Test424() { Assert.IsTrue(Caverphone2Test("fbeye", "FPA1111111")); }
        [TestMethod] public void Caverphone2Test425() { Assert.IsTrue(Caverphone2Test("hagerty", "AKTA111111")); }
        [TestMethod] public void Caverphone2Test426() { Assert.IsTrue(Caverphone2Test("Hollendonner", "ALNTNA1111")); }
        [TestMethod] public void Caverphone2Test427() { Assert.IsTrue(Caverphone2Test("Huitzacua", "ATSKA11111")); }
        [TestMethod] public void Caverphone2Test428() { Assert.IsTrue(Caverphone2Test("subjunctive", "SPNKTF1111")); }
        [TestMethod] public void Caverphone2Test429() { Assert.IsTrue(Caverphone2Test("implored", "AMPLRT1111")); }
        [TestMethod] public void Caverphone2Test430() { Assert.IsTrue(Caverphone2Test("pompeius", "PMPS111111")); }
        [TestMethod] public void Caverphone2Test431() { Assert.IsTrue(Caverphone2Test("afleet", "AFLT111111")); }
        [TestMethod] public void Caverphone2Test432() { Assert.IsTrue(Caverphone2Test("iacc", "AK11111111")); }
        [TestMethod] public void Caverphone2Test433() { Assert.IsTrue(Caverphone2Test("sabalos", "SPLS111111")); }
        [TestMethod] public void Caverphone2Test434() { Assert.IsTrue(Caverphone2Test("Abdi", "APTA111111")); }
        [TestMethod] public void Caverphone2Test435() { Assert.IsTrue(Caverphone2Test("microinsurance", "MKRNSRNK11")); }
        [TestMethod] public void Caverphone2Test436() { Assert.IsTrue(Caverphone2Test("audiobook", "ATPK111111")); }
        [TestMethod] public void Caverphone2Test437() { Assert.IsTrue(Caverphone2Test("fulpmes", "FPMS111111")); }
        [TestMethod] public void Caverphone2Test438() { Assert.IsTrue(Caverphone2Test("registreren", "RKSTRRN111")); }
        [TestMethod] public void Caverphone2Test439() { Assert.IsTrue(Caverphone2Test("megapath", "MKPT111111")); }
        [TestMethod] public void Caverphone2Test440() { Assert.IsTrue(Caverphone2Test("prestidigitation", "PRSTTKTSN1")); }
        [TestMethod] public void Caverphone2Test441() { Assert.IsTrue(Caverphone2Test("wby", "PA11111111")); }
        [TestMethod] public void Caverphone2Test442() { Assert.IsTrue(Caverphone2Test("vorschau", "FSKA111111")); }
        [TestMethod] public void Caverphone2Test443() { Assert.IsTrue(Caverphone2Test("Albertha", "APTA111111")); }
        [TestMethod] public void Caverphone2Test444() { Assert.IsTrue(Caverphone2Test("aspalpha", "ASPFA11111")); }
        [TestMethod] public void Caverphone2Test445() { Assert.IsTrue(Caverphone2Test("Belden", "PTN1111111")); }
        [TestMethod] public void Caverphone2Test446() { Assert.IsTrue(Caverphone2Test("deterministic", "TTMNSTK111")); }
        [TestMethod] public void Caverphone2Test447() { Assert.IsTrue(Caverphone2Test("philosophique", "FLSFKA1111")); }
        [TestMethod] public void Caverphone2Test448() { Assert.IsTrue(Caverphone2Test("kleinen", "KLNN111111")); }
        [TestMethod] public void Caverphone2Test449() { Assert.IsTrue(Caverphone2Test("logouri", "LKRA111111")); }
        [TestMethod] public void Caverphone2Test450() { Assert.IsTrue(Caverphone2Test("xbl", "KPA1111111")); }
        [TestMethod] public void Caverphone2Test451() { Assert.IsTrue(Caverphone2Test("iz", "AS11111111")); }
        [TestMethod] public void Caverphone2Test452() { Assert.IsTrue(Caverphone2Test("throckmorton", "TRKMTN1111")); }
        [TestMethod] public void Caverphone2Test453() { Assert.IsTrue(Caverphone2Test("condesa", "KNTSA11111")); }
        [TestMethod] public void Caverphone2Test454() { Assert.IsTrue(Caverphone2Test("Mook", "MK11111111")); }
        [TestMethod] public void Caverphone2Test455() { Assert.IsTrue(Caverphone2Test("medseek", "MTSK111111")); }
        [TestMethod] public void Caverphone2Test456() { Assert.IsTrue(Caverphone2Test("chugalug", "KKLK111111")); }
        [TestMethod] public void Caverphone2Test457() { Assert.IsTrue(Caverphone2Test("olms", "AMS1111111")); }
        [TestMethod] public void Caverphone2Test458() { Assert.IsTrue(Caverphone2Test("bogo", "PKA1111111")); }
        [TestMethod] public void Caverphone2Test459() { Assert.IsTrue(Caverphone2Test("essing", "ASNK111111")); }
        [TestMethod] public void Caverphone2Test460() { Assert.IsTrue(Caverphone2Test("rarden", "RTN1111111")); }
        [TestMethod] public void Caverphone2Test461() { Assert.IsTrue(Caverphone2Test("mittlere", "MTLA111111")); }
        [TestMethod] public void Caverphone2Test462() { Assert.IsTrue(Caverphone2Test("Borsa", "PSA1111111")); }
        [TestMethod] public void Caverphone2Test463() { Assert.IsTrue(Caverphone2Test("Ainslie", "ANSLA11111")); }
        [TestMethod] public void Caverphone2Test464() { Assert.IsTrue(Caverphone2Test("Ganska", "KNSKA11111")); }
        [TestMethod] public void Caverphone2Test465() { Assert.IsTrue(Caverphone2Test("miv", "MF11111111")); }
        [TestMethod] public void Caverphone2Test466() { Assert.IsTrue(Caverphone2Test("concessions", "KNSSNS1111")); }
        [TestMethod] public void Caverphone2Test467() { Assert.IsTrue(Caverphone2Test("distinguished", "TSTNKST111")); }
        [TestMethod] public void Caverphone2Test468() { Assert.IsTrue(Caverphone2Test("cano", "KNA1111111")); }
        [TestMethod] public void Caverphone2Test469() { Assert.IsTrue(Caverphone2Test("plumper", "PLMPA11111")); }
        [TestMethod] public void Caverphone2Test470() { Assert.IsTrue(Caverphone2Test("mindoro", "MNTRA11111")); }
        [TestMethod] public void Caverphone2Test471() { Assert.IsTrue(Caverphone2Test("cephalopod", "SFLPT11111")); }
        [TestMethod] public void Caverphone2Test472() { Assert.IsTrue(Caverphone2Test("Klunk", "KLNK111111")); }
        [TestMethod] public void Caverphone2Test473() { Assert.IsTrue(Caverphone2Test("Bumbrey", "PMPRA11111")); }
        [TestMethod] public void Caverphone2Test474() { Assert.IsTrue(Caverphone2Test("causeless", "KSLS111111")); }
        [TestMethod] public void Caverphone2Test475() { Assert.IsTrue(Caverphone2Test("Lothrop", "LTRP111111")); }
        [TestMethod] public void Caverphone2Test476() { Assert.IsTrue(Caverphone2Test("bodystyles", "PTSTLS1111")); }
        [TestMethod] public void Caverphone2Test477() { Assert.IsTrue(Caverphone2Test("beaatiality", "PSLTA11111")); }
        [TestMethod] public void Caverphone2Test478() { Assert.IsTrue(Caverphone2Test("Bobrowski", "PPRSKA1111")); }
        [TestMethod] public void Caverphone2Test479() { Assert.IsTrue(Caverphone2Test("erudition", "ARTSN11111")); }
        [TestMethod] public void Caverphone2Test480() { Assert.IsTrue(Caverphone2Test("huttner", "ATNA111111")); }
        [TestMethod] public void Caverphone2Test481() { Assert.IsTrue(Caverphone2Test("wwwaskjeevescom", "WSKFSKM111")); }
        [TestMethod] public void Caverphone2Test482() { Assert.IsTrue(Caverphone2Test("Duross", "TRS1111111")); }
        [TestMethod] public void Caverphone2Test483() { Assert.IsTrue(Caverphone2Test("Colemen", "KLMN111111")); }
        [TestMethod] public void Caverphone2Test484() { Assert.IsTrue(Caverphone2Test("Duncomb", "TNKM111111")); }
        [TestMethod] public void Caverphone2Test485() { Assert.IsTrue(Caverphone2Test("tripe", "TRP1111111")); }
        [TestMethod] public void Caverphone2Test486() { Assert.IsTrue(Caverphone2Test("dorrigo", "TRKA111111")); }
        [TestMethod] public void Caverphone2Test487() { Assert.IsTrue(Caverphone2Test("Mascall", "MSKA111111")); }
        [TestMethod] public void Caverphone2Test488() { Assert.IsTrue(Caverphone2Test("jetplane", "YTPLN11111")); }
        [TestMethod] public void Caverphone2Test489() { Assert.IsTrue(Caverphone2Test("nswrl", "NSA1111111")); }
        [TestMethod] public void Caverphone2Test490() { Assert.IsTrue(Caverphone2Test("didates", "TTTS111111")); }
        [TestMethod] public void Caverphone2Test491() { Assert.IsTrue(Caverphone2Test("Jena", "YNA1111111")); }
        [TestMethod] public void Caverphone2Test492() { Assert.IsTrue(Caverphone2Test("kctu", "KTA1111111")); }
        [TestMethod] public void Caverphone2Test493() { Assert.IsTrue(Caverphone2Test("cualquiera", "KKRA111111")); }
        [TestMethod] public void Caverphone2Test494() { Assert.IsTrue(Caverphone2Test("plutella", "PLTLA11111")); }
        [TestMethod] public void Caverphone2Test495() { Assert.IsTrue(Caverphone2Test("Liebig", "LPK1111111")); }
        [TestMethod] public void Caverphone2Test496() { Assert.IsTrue(Caverphone2Test("Llorens", "LRNS111111")); }
        [TestMethod] public void Caverphone2Test497() { Assert.IsTrue(Caverphone2Test("mraz", "MRS1111111")); }
        [TestMethod] public void Caverphone2Test498() { Assert.IsTrue(Caverphone2Test("shadyac", "STK1111111")); }
        [TestMethod] public void Caverphone2Test499() { Assert.IsTrue(Caverphone2Test("lossphentermine", "LSFNTMN111")); }
        [TestMethod] public void Caverphone2Test500() { Assert.IsTrue(Caverphone2Test("Dreith", "TRT1111111")); }

    }
}
