using Element34.StringMetrics.Phonetic;

namespace Element34Tests.Phonetic
{
    [TestClass]
    public class Metaphone1Tests
    {
        private bool MetaphoneTest(string sInput, string sExpected)
        {
            Metaphone metaphone = new Metaphone();
            return metaphone.Encode(sInput) == sExpected;
        }

        [TestMethod] public void MetaphoneTest001() { Assert.IsTrue(MetaphoneTest("communication", "KMNK")); }
        [TestMethod] public void MetaphoneTest002() { Assert.IsTrue(MetaphoneTest("worships", "WRXP")); }
        [TestMethod] public void MetaphoneTest003() { Assert.IsTrue(MetaphoneTest("televisionhome", "TLFX")); }
        [TestMethod] public void MetaphoneTest004() { Assert.IsTrue(MetaphoneTest("bumi", "BM")); }
        [TestMethod] public void MetaphoneTest005() { Assert.IsTrue(MetaphoneTest("shortbread", "XRTB")); }
        [TestMethod] public void MetaphoneTest006() { Assert.IsTrue(MetaphoneTest("slice", "SLS")); }
        [TestMethod] public void MetaphoneTest007() { Assert.IsTrue(MetaphoneTest("reint", "RNT")); }
        [TestMethod] public void MetaphoneTest008() { Assert.IsTrue(MetaphoneTest("Florence", "FLRN")); }
        [TestMethod] public void MetaphoneTest009() { Assert.IsTrue(MetaphoneTest("fawzi", "FS")); }
        [TestMethod] public void MetaphoneTest010() { Assert.IsTrue(MetaphoneTest("sname", "SNM")); }
        [TestMethod] public void MetaphoneTest011() { Assert.IsTrue(MetaphoneTest("modano", "MTN")); }
        [TestMethod] public void MetaphoneTest012() { Assert.IsTrue(MetaphoneTest("stumpage", "STMP")); }
        [TestMethod] public void MetaphoneTest013() { Assert.IsTrue(MetaphoneTest("clears", "KLRS")); }
        [TestMethod] public void MetaphoneTest014() { Assert.IsTrue(MetaphoneTest("ciods", "STS")); }
        [TestMethod] public void MetaphoneTest015() { Assert.IsTrue(MetaphoneTest("deseos", "TSS")); }
        [TestMethod] public void MetaphoneTest016() { Assert.IsTrue(MetaphoneTest("dippin", "TPN")); }
        [TestMethod] public void MetaphoneTest017() { Assert.IsTrue(MetaphoneTest("aranna", "ARN")); }
        [TestMethod] public void MetaphoneTest018() { Assert.IsTrue(MetaphoneTest("borse", "BRS")); }
        [TestMethod] public void MetaphoneTest019() { Assert.IsTrue(MetaphoneTest("subic", "SBK")); }
        [TestMethod] public void MetaphoneTest020() { Assert.IsTrue(MetaphoneTest("Vidrio", "FTR")); }
        [TestMethod] public void MetaphoneTest021() { Assert.IsTrue(MetaphoneTest("inserters", "INSR")); }
        [TestMethod] public void MetaphoneTest022() { Assert.IsTrue(MetaphoneTest("perature", "PRTR")); }
        [TestMethod] public void MetaphoneTest023() { Assert.IsTrue(MetaphoneTest("msacideas", "MSST")); }
        [TestMethod] public void MetaphoneTest024() { Assert.IsTrue(MetaphoneTest("cougs", "KKS")); }
        [TestMethod] public void MetaphoneTest025() { Assert.IsTrue(MetaphoneTest("kittens", "KTNS")); }
        [TestMethod] public void MetaphoneTest026() { Assert.IsTrue(MetaphoneTest("imperiously", "IMPR")); }
        [TestMethod] public void MetaphoneTest027() { Assert.IsTrue(MetaphoneTest("boccanegra", "BKKN")); }
        [TestMethod] public void MetaphoneTest028() { Assert.IsTrue(MetaphoneTest("sextet", "SKST")); }
        [TestMethod] public void MetaphoneTest029() { Assert.IsTrue(MetaphoneTest("setattributes", "STTR")); }
        [TestMethod] public void MetaphoneTest030() { Assert.IsTrue(MetaphoneTest("dsnt", "TSNT")); }
        [TestMethod] public void MetaphoneTest031() { Assert.IsTrue(MetaphoneTest("chubby", "XB")); }
        [TestMethod] public void MetaphoneTest032() { Assert.IsTrue(MetaphoneTest("ooda", "OT")); }
        [TestMethod] public void MetaphoneTest033() { Assert.IsTrue(MetaphoneTest("Bressman", "BRSM")); }
        [TestMethod] public void MetaphoneTest034() { Assert.IsTrue(MetaphoneTest("calendarnew", "KLNT")); }
        [TestMethod] public void MetaphoneTest035() { Assert.IsTrue(MetaphoneTest("duhon", "THN")); }
        [TestMethod] public void MetaphoneTest036() { Assert.IsTrue(MetaphoneTest("nchen", "NXN")); }
        [TestMethod] public void MetaphoneTest037() { Assert.IsTrue(MetaphoneTest("betjemans", "BTJM")); }
        [TestMethod] public void MetaphoneTest038() { Assert.IsTrue(MetaphoneTest("Mangum", "MNKM")); }
        [TestMethod] public void MetaphoneTest039() { Assert.IsTrue(MetaphoneTest("cabac", "KBK")); }
        [TestMethod] public void MetaphoneTest040() { Assert.IsTrue(MetaphoneTest("pantys", "PNTS")); }
        [TestMethod] public void MetaphoneTest041() { Assert.IsTrue(MetaphoneTest("cofactors", "KFKT")); }
        [TestMethod] public void MetaphoneTest042() { Assert.IsTrue(MetaphoneTest("clickz", "KLKS")); }
        [TestMethod] public void MetaphoneTest043() { Assert.IsTrue(MetaphoneTest("chiap", "XP")); }
        [TestMethod] public void MetaphoneTest044() { Assert.IsTrue(MetaphoneTest("Dalpiaz", "TLPS")); }
        [TestMethod] public void MetaphoneTest045() { Assert.IsTrue(MetaphoneTest("philosophically", "FLSF")); }
        [TestMethod] public void MetaphoneTest046() { Assert.IsTrue(MetaphoneTest("backfill", "BKFL")); }
        [TestMethod] public void MetaphoneTest047() { Assert.IsTrue(MetaphoneTest("Murders", "MRTR")); }
        [TestMethod] public void MetaphoneTest048() { Assert.IsTrue(MetaphoneTest("ecartis", "EKRT")); }
        [TestMethod] public void MetaphoneTest049() { Assert.IsTrue(MetaphoneTest("vede", "FT")); }
        [TestMethod] public void MetaphoneTest050() { Assert.IsTrue(MetaphoneTest("usoe", "US")); }
        [TestMethod] public void MetaphoneTest051() { Assert.IsTrue(MetaphoneTest("ostara", "OSTR")); }
        [TestMethod] public void MetaphoneTest052() { Assert.IsTrue(MetaphoneTest("labourer", "LBRR")); }
        [TestMethod] public void MetaphoneTest053() { Assert.IsTrue(MetaphoneTest("speir", "SPR")); }
        [TestMethod] public void MetaphoneTest054() { Assert.IsTrue(MetaphoneTest("durchaus", "TRXS")); }
        [TestMethod] public void MetaphoneTest055() { Assert.IsTrue(MetaphoneTest("inetformfiller", "INTF")); }
        [TestMethod] public void MetaphoneTest056() { Assert.IsTrue(MetaphoneTest("itrs", "ITRS")); }
        [TestMethod] public void MetaphoneTest057() { Assert.IsTrue(MetaphoneTest("Tennant", "TNNT")); }
        [TestMethod] public void MetaphoneTest058() { Assert.IsTrue(MetaphoneTest("bashore", "BXR")); }
        [TestMethod] public void MetaphoneTest059() { Assert.IsTrue(MetaphoneTest("lemurian", "LMRN")); }
        [TestMethod] public void MetaphoneTest060() { Assert.IsTrue(MetaphoneTest("dungannon", "TNKN")); }
        [TestMethod] public void MetaphoneTest061() { Assert.IsTrue(MetaphoneTest("epl", "EPL")); }
        [TestMethod] public void MetaphoneTest062() { Assert.IsTrue(MetaphoneTest("grader", "KRTR")); }
        [TestMethod] public void MetaphoneTest063() { Assert.IsTrue(MetaphoneTest("synchronise", "SNXR")); }
        [TestMethod] public void MetaphoneTest064() { Assert.IsTrue(MetaphoneTest("gondorian", "KNTR")); }
        [TestMethod] public void MetaphoneTest065() { Assert.IsTrue(MetaphoneTest("cvnet", "KFNT")); }
        [TestMethod] public void MetaphoneTest066() { Assert.IsTrue(MetaphoneTest("Centers", "SNTR")); }
        [TestMethod] public void MetaphoneTest067() { Assert.IsTrue(MetaphoneTest("soaks", "SKS")); }
        [TestMethod] public void MetaphoneTest068() { Assert.IsTrue(MetaphoneTest("gogllle", "KKL")); }
        [TestMethod] public void MetaphoneTest069() { Assert.IsTrue(MetaphoneTest("peotone", "PTN")); }
        [TestMethod] public void MetaphoneTest070() { Assert.IsTrue(MetaphoneTest("Sharp", "XRP")); }
        [TestMethod] public void MetaphoneTest071() { Assert.IsTrue(MetaphoneTest("mawer", "MWR")); }
        [TestMethod] public void MetaphoneTest072() { Assert.IsTrue(MetaphoneTest("Morasca", "MRSK")); }
        [TestMethod] public void MetaphoneTest073() { Assert.IsTrue(MetaphoneTest("ticknor", "TKNR")); }
        [TestMethod] public void MetaphoneTest074() { Assert.IsTrue(MetaphoneTest("beaverdale", "BFRT")); }
        [TestMethod] public void MetaphoneTest075() { Assert.IsTrue(MetaphoneTest("caledonianew", "KLTN")); }
        [TestMethod] public void MetaphoneTest076() { Assert.IsTrue(MetaphoneTest("wellnessdicke", "WLNS")); }
        [TestMethod] public void MetaphoneTest077() { Assert.IsTrue(MetaphoneTest("Rodin", "RTN")); }
        [TestMethod] public void MetaphoneTest078() { Assert.IsTrue(MetaphoneTest("bluffer", "BLFR")); }
        [TestMethod] public void MetaphoneTest079() { Assert.IsTrue(MetaphoneTest("joey", "J")); }
        [TestMethod] public void MetaphoneTest080() { Assert.IsTrue(MetaphoneTest("unbekannter", "UNBK")); }
        [TestMethod] public void MetaphoneTest081() { Assert.IsTrue(MetaphoneTest("Baylor", "BLR")); }
        [TestMethod] public void MetaphoneTest082() { Assert.IsTrue(MetaphoneTest("striplib", "STRP")); }
        [TestMethod] public void MetaphoneTest083() { Assert.IsTrue(MetaphoneTest("boquete", "BKT")); }
        [TestMethod] public void MetaphoneTest084() { Assert.IsTrue(MetaphoneTest("geylang", "JLNK")); }
        [TestMethod] public void MetaphoneTest085() { Assert.IsTrue(MetaphoneTest("Lavi", "LF")); }
        [TestMethod] public void MetaphoneTest086() { Assert.IsTrue(MetaphoneTest("moldovans", "MLTF")); }
        [TestMethod] public void MetaphoneTest087() { Assert.IsTrue(MetaphoneTest("linq", "LNK")); }
        [TestMethod] public void MetaphoneTest088() { Assert.IsTrue(MetaphoneTest("Kenworthy", "KNWR")); }
        [TestMethod] public void MetaphoneTest089() { Assert.IsTrue(MetaphoneTest("Steckman", "STKM")); }
        [TestMethod] public void MetaphoneTest090() { Assert.IsTrue(MetaphoneTest("czechoslovakian", "KSXS")); }
        [TestMethod] public void MetaphoneTest091() { Assert.IsTrue(MetaphoneTest("marmora", "MRMR")); }
        [TestMethod] public void MetaphoneTest092() { Assert.IsTrue(MetaphoneTest("Carvill", "KRFL")); }
        [TestMethod] public void MetaphoneTest093() { Assert.IsTrue(MetaphoneTest("chihiro", "XHR")); }
        [TestMethod] public void MetaphoneTest094() { Assert.IsTrue(MetaphoneTest("hctc", "KTK")); }
        [TestMethod] public void MetaphoneTest095() { Assert.IsTrue(MetaphoneTest("nolde", "NLT")); }
        [TestMethod] public void MetaphoneTest096() { Assert.IsTrue(MetaphoneTest("aerosolized", "ERSL")); }
        [TestMethod] public void MetaphoneTest097() { Assert.IsTrue(MetaphoneTest("canterbury", "KNTR")); }
        [TestMethod] public void MetaphoneTest098() { Assert.IsTrue(MetaphoneTest("jss", "JS")); }
        [TestMethod] public void MetaphoneTest099() { Assert.IsTrue(MetaphoneTest("rmn", "RMN")); }
        [TestMethod] public void MetaphoneTest100() { Assert.IsTrue(MetaphoneTest("mazlish", "MSLX")); }
        [TestMethod] public void MetaphoneTest101() { Assert.IsTrue(MetaphoneTest("faites", "FTS")); }
        [TestMethod] public void MetaphoneTest102() { Assert.IsTrue(MetaphoneTest("foyer", "FYR")); }
        [TestMethod] public void MetaphoneTest103() { Assert.IsTrue(MetaphoneTest("ductions", "TKXN")); }
        [TestMethod] public void MetaphoneTest104() { Assert.IsTrue(MetaphoneTest("Rambo", "RM")); }
        [TestMethod] public void MetaphoneTest105() { Assert.IsTrue(MetaphoneTest("Curnutte", "KRNT")); }
        [TestMethod] public void MetaphoneTest106() { Assert.IsTrue(MetaphoneTest("Feltus", "FLTS")); }
        [TestMethod] public void MetaphoneTest107() { Assert.IsTrue(MetaphoneTest("forbairt", "FRBR")); }
        [TestMethod] public void MetaphoneTest108() { Assert.IsTrue(MetaphoneTest("southerners", "S0RN")); }
        [TestMethod] public void MetaphoneTest109() { Assert.IsTrue(MetaphoneTest("hypnotists", "PNTS")); }
        [TestMethod] public void MetaphoneTest110() { Assert.IsTrue(MetaphoneTest("euphony", "EFN")); }
        [TestMethod] public void MetaphoneTest111() { Assert.IsTrue(MetaphoneTest("mhpa", "MP")); }
        [TestMethod] public void MetaphoneTest112() { Assert.IsTrue(MetaphoneTest("matteotti", "MTT")); }
        [TestMethod] public void MetaphoneTest113() { Assert.IsTrue(MetaphoneTest("Klande", "KLNT")); }
        [TestMethod] public void MetaphoneTest114() { Assert.IsTrue(MetaphoneTest("Trudgeon", "TRJN")); }
        [TestMethod] public void MetaphoneTest115() { Assert.IsTrue(MetaphoneTest("schoolhill", "SXLH")); }
        [TestMethod] public void MetaphoneTest116() { Assert.IsTrue(MetaphoneTest("equalizer", "EKLS")); }
        [TestMethod] public void MetaphoneTest117() { Assert.IsTrue(MetaphoneTest("xnet", "SNT")); }
        [TestMethod] public void MetaphoneTest118() { Assert.IsTrue(MetaphoneTest("Thell", "0L")); }
        [TestMethod] public void MetaphoneTest119() { Assert.IsTrue(MetaphoneTest("Canel", "KNL")); }
        [TestMethod] public void MetaphoneTest120() { Assert.IsTrue(MetaphoneTest("vmetro", "FMTR")); }
        [TestMethod] public void MetaphoneTest121() { Assert.IsTrue(MetaphoneTest("burgtheater", "BRK0")); }
        [TestMethod] public void MetaphoneTest122() { Assert.IsTrue(MetaphoneTest("Berlinger", "BRLN")); }
        [TestMethod] public void MetaphoneTest123() { Assert.IsTrue(MetaphoneTest("crehan", "KRHN")); }
        [TestMethod] public void MetaphoneTest124() { Assert.IsTrue(MetaphoneTest("abysses", "ABSS")); }
        [TestMethod] public void MetaphoneTest125() { Assert.IsTrue(MetaphoneTest("Hipolito", "HPLT")); }
        [TestMethod] public void MetaphoneTest126() { Assert.IsTrue(MetaphoneTest("splintered", "SPLN")); }
        [TestMethod] public void MetaphoneTest127() { Assert.IsTrue(MetaphoneTest("maintenace", "MNTN")); }
        [TestMethod] public void MetaphoneTest128() { Assert.IsTrue(MetaphoneTest("decency", "TSNS")); }
        [TestMethod] public void MetaphoneTest129() { Assert.IsTrue(MetaphoneTest("quantz", "KNTS")); }
        [TestMethod] public void MetaphoneTest130() { Assert.IsTrue(MetaphoneTest("wette", "WT")); }
        [TestMethod] public void MetaphoneTest131() { Assert.IsTrue(MetaphoneTest("Feary", "FR")); }
        [TestMethod] public void MetaphoneTest132() { Assert.IsTrue(MetaphoneTest("Cuchiara", "KXR")); }
        [TestMethod] public void MetaphoneTest133() { Assert.IsTrue(MetaphoneTest("Arbon", "ARBN")); }
        [TestMethod] public void MetaphoneTest134() { Assert.IsTrue(MetaphoneTest("shyness", "XNS")); }
        [TestMethod] public void MetaphoneTest135() { Assert.IsTrue(MetaphoneTest("Salin", "SLN")); }
        [TestMethod] public void MetaphoneTest136() { Assert.IsTrue(MetaphoneTest("Zicafoose", "SKFS")); }
        [TestMethod] public void MetaphoneTest137() { Assert.IsTrue(MetaphoneTest("Menn", "MN")); }
        [TestMethod] public void MetaphoneTest138() { Assert.IsTrue(MetaphoneTest("funker", "FNKR")); }
        [TestMethod] public void MetaphoneTest139() { Assert.IsTrue(MetaphoneTest("santillan", "SNTL")); }
        [TestMethod] public void MetaphoneTest140() { Assert.IsTrue(MetaphoneTest("punani", "PNN")); }
        [TestMethod] public void MetaphoneTest141() { Assert.IsTrue(MetaphoneTest("basa", "BS")); }
        [TestMethod] public void MetaphoneTest142() { Assert.IsTrue(MetaphoneTest("bluefin", "BLFN")); }
        [TestMethod] public void MetaphoneTest143() { Assert.IsTrue(MetaphoneTest("cc", "KK")); }
        [TestMethod] public void MetaphoneTest144() { Assert.IsTrue(MetaphoneTest("zipgenius", "SPJN")); }
        [TestMethod] public void MetaphoneTest145() { Assert.IsTrue(MetaphoneTest("Kirchen", "KRXN")); }
        [TestMethod] public void MetaphoneTest146() { Assert.IsTrue(MetaphoneTest("commentaar", "KMNT")); }
        [TestMethod] public void MetaphoneTest147() { Assert.IsTrue(MetaphoneTest("expansive", "EKSP")); }
        [TestMethod] public void MetaphoneTest148() { Assert.IsTrue(MetaphoneTest("castlebar", "KSTL")); }
        [TestMethod] public void MetaphoneTest149() { Assert.IsTrue(MetaphoneTest("lft", "LFT")); }
        [TestMethod] public void MetaphoneTest150() { Assert.IsTrue(MetaphoneTest("robla", "RBL")); }
        [TestMethod] public void MetaphoneTest151() { Assert.IsTrue(MetaphoneTest("zarontin", "SRNT")); }
        [TestMethod] public void MetaphoneTest152() { Assert.IsTrue(MetaphoneTest("nawc", "NK")); }
        [TestMethod] public void MetaphoneTest153() { Assert.IsTrue(MetaphoneTest("resolvconf", "RSLF")); }
        [TestMethod] public void MetaphoneTest154() { Assert.IsTrue(MetaphoneTest("networker", "NTWR")); }
        [TestMethod] public void MetaphoneTest155() { Assert.IsTrue(MetaphoneTest("airlins", "ARLN")); }
        [TestMethod] public void MetaphoneTest156() { Assert.IsTrue(MetaphoneTest("Piskel", "PSKL")); }
        [TestMethod] public void MetaphoneTest157() { Assert.IsTrue(MetaphoneTest("hilson", "HLSN")); }
        [TestMethod] public void MetaphoneTest158() { Assert.IsTrue(MetaphoneTest("deco", "TK")); }
        [TestMethod] public void MetaphoneTest159() { Assert.IsTrue(MetaphoneTest("cents", "SNTS")); }
        [TestMethod] public void MetaphoneTest160() { Assert.IsTrue(MetaphoneTest("award", "AWRT")); }
        [TestMethod] public void MetaphoneTest161() { Assert.IsTrue(MetaphoneTest("reykjanes", "RKJN")); }
        [TestMethod] public void MetaphoneTest162() { Assert.IsTrue(MetaphoneTest("perona", "PRN")); }
        [TestMethod] public void MetaphoneTest163() { Assert.IsTrue(MetaphoneTest("epistle", "EPST")); }
        [TestMethod] public void MetaphoneTest164() { Assert.IsTrue(MetaphoneTest("insound", "INSN")); }
        [TestMethod] public void MetaphoneTest165() { Assert.IsTrue(MetaphoneTest("qantas", "KNTS")); }
        [TestMethod] public void MetaphoneTest166() { Assert.IsTrue(MetaphoneTest("wholey", "WL")); }
        [TestMethod] public void MetaphoneTest167() { Assert.IsTrue(MetaphoneTest("aragona", "ARKN")); }
        [TestMethod] public void MetaphoneTest168() { Assert.IsTrue(MetaphoneTest("Vancheri", "FNXR")); }
        [TestMethod] public void MetaphoneTest169() { Assert.IsTrue(MetaphoneTest("allocution", "ALKX")); }
        [TestMethod] public void MetaphoneTest170() { Assert.IsTrue(MetaphoneTest("volodya", "FLTY")); }
        [TestMethod] public void MetaphoneTest171() { Assert.IsTrue(MetaphoneTest("enunciate", "ENNX")); }
        [TestMethod] public void MetaphoneTest172() { Assert.IsTrue(MetaphoneTest("uuuu", "U")); }
        [TestMethod] public void MetaphoneTest173() { Assert.IsTrue(MetaphoneTest("Louato", "LT")); }
        [TestMethod] public void MetaphoneTest174() { Assert.IsTrue(MetaphoneTest("Marquitta", "MRKT")); }
        [TestMethod] public void MetaphoneTest175() { Assert.IsTrue(MetaphoneTest("surmountable", "SRMN")); }
        [TestMethod] public void MetaphoneTest176() { Assert.IsTrue(MetaphoneTest("gaultier", "KLTR")); }
        [TestMethod] public void MetaphoneTest177() { Assert.IsTrue(MetaphoneTest("dafoe", "TF")); }
        [TestMethod] public void MetaphoneTest178() { Assert.IsTrue(MetaphoneTest("Claudio", "KLT")); }
        [TestMethod] public void MetaphoneTest179() { Assert.IsTrue(MetaphoneTest("ritva", "RTF")); }
        [TestMethod] public void MetaphoneTest180() { Assert.IsTrue(MetaphoneTest("spunky", "SPNK")); }
        [TestMethod] public void MetaphoneTest181() { Assert.IsTrue(MetaphoneTest("npov", "NPF")); }
        [TestMethod] public void MetaphoneTest182() { Assert.IsTrue(MetaphoneTest("eurythmics", "ER0M")); }
        [TestMethod] public void MetaphoneTest183() { Assert.IsTrue(MetaphoneTest("skittish", "SKTX")); }
        [TestMethod] public void MetaphoneTest184() { Assert.IsTrue(MetaphoneTest("scooter", "SKTR")); }
        [TestMethod] public void MetaphoneTest185() { Assert.IsTrue(MetaphoneTest("unfermented", "UNFR")); }
        [TestMethod] public void MetaphoneTest186() { Assert.IsTrue(MetaphoneTest("kerridge", "KRJ")); }
        [TestMethod] public void MetaphoneTest187() { Assert.IsTrue(MetaphoneTest("scenography", "SNKR")); }
        [TestMethod] public void MetaphoneTest188() { Assert.IsTrue(MetaphoneTest("sahalee", "SHL")); }
        [TestMethod] public void MetaphoneTest189() { Assert.IsTrue(MetaphoneTest("spooktacular", "SPKT")); }
        [TestMethod] public void MetaphoneTest190() { Assert.IsTrue(MetaphoneTest("boissons", "BSNS")); }
        [TestMethod] public void MetaphoneTest191() { Assert.IsTrue(MetaphoneTest("arbete", "ARBT")); }
        [TestMethod] public void MetaphoneTest192() { Assert.IsTrue(MetaphoneTest("Norrick", "NRK")); }
        [TestMethod] public void MetaphoneTest193() { Assert.IsTrue(MetaphoneTest("Sonnier", "SNR")); }
        [TestMethod] public void MetaphoneTest194() { Assert.IsTrue(MetaphoneTest("gnomeui", "NM")); }
        [TestMethod] public void MetaphoneTest195() { Assert.IsTrue(MetaphoneTest("milian", "MLN")); }
        [TestMethod] public void MetaphoneTest196() { Assert.IsTrue(MetaphoneTest("blackplanetcom", "BLKP")); }
        [TestMethod] public void MetaphoneTest197() { Assert.IsTrue(MetaphoneTest("tuned", "TNT")); }
        [TestMethod] public void MetaphoneTest198() { Assert.IsTrue(MetaphoneTest("Salone", "SLN")); }
        [TestMethod] public void MetaphoneTest199() { Assert.IsTrue(MetaphoneTest("marathon", "MR0N")); }
        [TestMethod] public void MetaphoneTest200() { Assert.IsTrue(MetaphoneTest("layoffs", "LYFS")); }
        [TestMethod] public void MetaphoneTest201() { Assert.IsTrue(MetaphoneTest("hotek", "HTK")); }
        [TestMethod] public void MetaphoneTest202() { Assert.IsTrue(MetaphoneTest("emme", "EM")); }
        [TestMethod] public void MetaphoneTest203() { Assert.IsTrue(MetaphoneTest("amarasinghe", "AMRS")); }
        [TestMethod] public void MetaphoneTest204() { Assert.IsTrue(MetaphoneTest("midas", "MTS")); }
        [TestMethod] public void MetaphoneTest205() { Assert.IsTrue(MetaphoneTest("inhaltsangabe", "INHL")); }
        [TestMethod] public void MetaphoneTest206() { Assert.IsTrue(MetaphoneTest("smow", "SM")); }
        [TestMethod] public void MetaphoneTest207() { Assert.IsTrue(MetaphoneTest("policing", "PLSN")); }
        [TestMethod] public void MetaphoneTest208() { Assert.IsTrue(MetaphoneTest("usmf", "USMF")); }
        [TestMethod] public void MetaphoneTest209() { Assert.IsTrue(MetaphoneTest("inferred", "INFR")); }
        [TestMethod] public void MetaphoneTest210() { Assert.IsTrue(MetaphoneTest("Eaglen", "EKLN")); }
        [TestMethod] public void MetaphoneTest211() { Assert.IsTrue(MetaphoneTest("dralle", "TRL")); }
        [TestMethod] public void MetaphoneTest212() { Assert.IsTrue(MetaphoneTest("kalmus", "KLMS")); }
        [TestMethod] public void MetaphoneTest213() { Assert.IsTrue(MetaphoneTest("nork", "NRK")); }
        [TestMethod] public void MetaphoneTest214() { Assert.IsTrue(MetaphoneTest("Waterston", "WTRS")); }
        [TestMethod] public void MetaphoneTest215() { Assert.IsTrue(MetaphoneTest("penalised", "PNLS")); }
        [TestMethod] public void MetaphoneTest216() { Assert.IsTrue(MetaphoneTest("Lupacchino", "LPKX")); }
        [TestMethod] public void MetaphoneTest217() { Assert.IsTrue(MetaphoneTest("getgid", "JTJT")); }
        [TestMethod] public void MetaphoneTest218() { Assert.IsTrue(MetaphoneTest("kever", "KFR")); }
        [TestMethod] public void MetaphoneTest219() { Assert.IsTrue(MetaphoneTest("pallavicini", "PLFS")); }
        [TestMethod] public void MetaphoneTest220() { Assert.IsTrue(MetaphoneTest("Pais", "PS")); }
        [TestMethod] public void MetaphoneTest221() { Assert.IsTrue(MetaphoneTest("youghiogheny", "YFN")); }
        [TestMethod] public void MetaphoneTest222() { Assert.IsTrue(MetaphoneTest("Catherina", "K0RN")); }
        [TestMethod] public void MetaphoneTest223() { Assert.IsTrue(MetaphoneTest("Givant", "JFNT")); }
        [TestMethod] public void MetaphoneTest224() { Assert.IsTrue(MetaphoneTest("koffi", "KF")); }
        [TestMethod] public void MetaphoneTest225() { Assert.IsTrue(MetaphoneTest("troutbeck", "TRTB")); }
        [TestMethod] public void MetaphoneTest226() { Assert.IsTrue(MetaphoneTest("moreelse", "MRLS")); }
        [TestMethod] public void MetaphoneTest227() { Assert.IsTrue(MetaphoneTest("seacrest", "SKRS")); }
        [TestMethod] public void MetaphoneTest228() { Assert.IsTrue(MetaphoneTest("ufj", "UFJ")); }
        [TestMethod] public void MetaphoneTest229() { Assert.IsTrue(MetaphoneTest("dereferences", "TRFR")); }
        [TestMethod] public void MetaphoneTest230() { Assert.IsTrue(MetaphoneTest("sarena", "SRN")); }
        [TestMethod] public void MetaphoneTest231() { Assert.IsTrue(MetaphoneTest("Kurt", "KRT")); }
        [TestMethod] public void MetaphoneTest232() { Assert.IsTrue(MetaphoneTest("comanche", "KMNX")); }
        [TestMethod] public void MetaphoneTest233() { Assert.IsTrue(MetaphoneTest("chersoness", "XRSN")); }
        [TestMethod] public void MetaphoneTest234() { Assert.IsTrue(MetaphoneTest("cd", "KT")); }
        [TestMethod] public void MetaphoneTest235() { Assert.IsTrue(MetaphoneTest("merzky", "MRSK")); }
        [TestMethod] public void MetaphoneTest236() { Assert.IsTrue(MetaphoneTest("Nordsiek", "NRTS")); }
        [TestMethod] public void MetaphoneTest237() { Assert.IsTrue(MetaphoneTest("samus", "SMS")); }
        [TestMethod] public void MetaphoneTest238() { Assert.IsTrue(MetaphoneTest("tougher", "TFR")); }
        [TestMethod] public void MetaphoneTest239() { Assert.IsTrue(MetaphoneTest("monodoc", "MNTK")); }
        [TestMethod] public void MetaphoneTest240() { Assert.IsTrue(MetaphoneTest("deepings", "TPNK")); }
        [TestMethod] public void MetaphoneTest241() { Assert.IsTrue(MetaphoneTest("datel", "TTL")); }
        [TestMethod] public void MetaphoneTest242() { Assert.IsTrue(MetaphoneTest("Stockett", "STKT")); }
        [TestMethod] public void MetaphoneTest243() { Assert.IsTrue(MetaphoneTest("bryum", "BRYM")); }
        [TestMethod] public void MetaphoneTest244() { Assert.IsTrue(MetaphoneTest("surveyed", "SRFY")); }
        [TestMethod] public void MetaphoneTest245() { Assert.IsTrue(MetaphoneTest("microcephaly", "MKRS")); }
        [TestMethod] public void MetaphoneTest246() { Assert.IsTrue(MetaphoneTest("trimoxazole", "TRMKS")); }
        [TestMethod] public void MetaphoneTest247() { Assert.IsTrue(MetaphoneTest("bastide", "BSTT")); }
        [TestMethod] public void MetaphoneTest248() { Assert.IsTrue(MetaphoneTest("lipo", "LP")); }
        [TestMethod] public void MetaphoneTest249() { Assert.IsTrue(MetaphoneTest("Bosket", "BSKT")); }
        [TestMethod] public void MetaphoneTest250() { Assert.IsTrue(MetaphoneTest("oroms", "ORMS")); }
        [TestMethod] public void MetaphoneTest251() { Assert.IsTrue(MetaphoneTest("vandenburg", "FNTN")); }
        [TestMethod] public void MetaphoneTest252() { Assert.IsTrue(MetaphoneTest("wirtschaftsforschung", "WRTS")); }
        [TestMethod] public void MetaphoneTest253() { Assert.IsTrue(MetaphoneTest("lilypond", "LLPN")); }
        [TestMethod] public void MetaphoneTest254() { Assert.IsTrue(MetaphoneTest("mouthfeel", "M0FL")); }
        [TestMethod] public void MetaphoneTest255() { Assert.IsTrue(MetaphoneTest("wwwunibancocombr", "NBNK")); }
        [TestMethod] public void MetaphoneTest256() { Assert.IsTrue(MetaphoneTest("Worster", "WRST")); }
        [TestMethod] public void MetaphoneTest257() { Assert.IsTrue(MetaphoneTest("Ahmad", "AMT")); }
        [TestMethod] public void MetaphoneTest258() { Assert.IsTrue(MetaphoneTest("sweetser", "SWTS")); }
        [TestMethod] public void MetaphoneTest259() { Assert.IsTrue(MetaphoneTest("vsepr", "FSPR")); }
        [TestMethod] public void MetaphoneTest260() { Assert.IsTrue(MetaphoneTest("dput", "TPT")); }
        [TestMethod] public void MetaphoneTest261() { Assert.IsTrue(MetaphoneTest("austlit", "ASTL")); }
        [TestMethod] public void MetaphoneTest262() { Assert.IsTrue(MetaphoneTest("Clemen", "KLMN")); }
        [TestMethod] public void MetaphoneTest263() { Assert.IsTrue(MetaphoneTest("phrva", "FRF")); }
        [TestMethod] public void MetaphoneTest264() { Assert.IsTrue(MetaphoneTest("weipa", "WP")); }
        [TestMethod] public void MetaphoneTest265() { Assert.IsTrue(MetaphoneTest("Schrantz", "SXRN")); }
        [TestMethod] public void MetaphoneTest266() { Assert.IsTrue(MetaphoneTest("meany", "MN")); }
        [TestMethod] public void MetaphoneTest267() { Assert.IsTrue(MetaphoneTest("hodgepodge", "HJPJ")); }
        [TestMethod] public void MetaphoneTest268() { Assert.IsTrue(MetaphoneTest("knuble", "NBL")); }
        [TestMethod] public void MetaphoneTest269() { Assert.IsTrue(MetaphoneTest("caniglia", "KNKL")); }
        [TestMethod] public void MetaphoneTest270() { Assert.IsTrue(MetaphoneTest("blowjobsasics", "BLJB")); }
        [TestMethod] public void MetaphoneTest271() { Assert.IsTrue(MetaphoneTest("flyjacket", "FLJK")); }
        [TestMethod] public void MetaphoneTest272() { Assert.IsTrue(MetaphoneTest("galatian", "KLXN")); }
        [TestMethod] public void MetaphoneTest273() { Assert.IsTrue(MetaphoneTest("hotsel", "HTSL")); }
        [TestMethod] public void MetaphoneTest274() { Assert.IsTrue(MetaphoneTest("autorun", "ATRN")); }
        [TestMethod] public void MetaphoneTest275() { Assert.IsTrue(MetaphoneTest("cocoon", "KKN")); }
        [TestMethod] public void MetaphoneTest276() { Assert.IsTrue(MetaphoneTest("kooks", "KKS")); }
        [TestMethod] public void MetaphoneTest277() { Assert.IsTrue(MetaphoneTest("endocrinol", "ENTK")); }
        [TestMethod] public void MetaphoneTest278() { Assert.IsTrue(MetaphoneTest("mesages", "MSJS")); }
        [TestMethod] public void MetaphoneTest279() { Assert.IsTrue(MetaphoneTest("Disney", "TSN")); }
        [TestMethod] public void MetaphoneTest280() { Assert.IsTrue(MetaphoneTest("speedline", "SPTL")); }
        [TestMethod] public void MetaphoneTest281() { Assert.IsTrue(MetaphoneTest("gabaldon", "KBLT")); }
        [TestMethod] public void MetaphoneTest282() { Assert.IsTrue(MetaphoneTest("margaux", "MRKKS")); }
        [TestMethod] public void MetaphoneTest283() { Assert.IsTrue(MetaphoneTest("housecalls", "HSKL")); }
        [TestMethod] public void MetaphoneTest284() { Assert.IsTrue(MetaphoneTest("siltation", "SLTX")); }
        [TestMethod] public void MetaphoneTest285() { Assert.IsTrue(MetaphoneTest("automatic", "ATMT")); }
        [TestMethod] public void MetaphoneTest286() { Assert.IsTrue(MetaphoneTest("freakshow", "FRKX")); }
        [TestMethod] public void MetaphoneTest287() { Assert.IsTrue(MetaphoneTest("gorojovsky", "KRJF")); }
        [TestMethod] public void MetaphoneTest288() { Assert.IsTrue(MetaphoneTest("milwaukie", "MLWK")); }
        [TestMethod] public void MetaphoneTest289() { Assert.IsTrue(MetaphoneTest("wwwgap", "KP")); }
        [TestMethod] public void MetaphoneTest290() { Assert.IsTrue(MetaphoneTest("autm", "ATM")); }
        [TestMethod] public void MetaphoneTest291() { Assert.IsTrue(MetaphoneTest("borromini", "BRMN")); }
        [TestMethod] public void MetaphoneTest292() { Assert.IsTrue(MetaphoneTest("zpp", "SP")); }
        [TestMethod] public void MetaphoneTest293() { Assert.IsTrue(MetaphoneTest("Penovich", "PNFX")); }
        [TestMethod] public void MetaphoneTest294() { Assert.IsTrue(MetaphoneTest("domine", "TMN")); }
        [TestMethod] public void MetaphoneTest295() { Assert.IsTrue(MetaphoneTest("caves", "KFS")); }
        [TestMethod] public void MetaphoneTest296() { Assert.IsTrue(MetaphoneTest("uato", "UT")); }
        [TestMethod] public void MetaphoneTest297() { Assert.IsTrue(MetaphoneTest("tiltonsville", "TLTN")); }
        [TestMethod] public void MetaphoneTest298() { Assert.IsTrue(MetaphoneTest("Ken", "KN")); }
        [TestMethod] public void MetaphoneTest299() { Assert.IsTrue(MetaphoneTest("Delonais", "TLNS")); }
        [TestMethod] public void MetaphoneTest300() { Assert.IsTrue(MetaphoneTest("conniption", "KNPX")); }
        [TestMethod] public void MetaphoneTest301() { Assert.IsTrue(MetaphoneTest("Wenske", "WNSK")); }
        [TestMethod] public void MetaphoneTest302() { Assert.IsTrue(MetaphoneTest("cautery", "KTR")); }
        [TestMethod] public void MetaphoneTest303() { Assert.IsTrue(MetaphoneTest("barbourville", "BRBR")); }
        [TestMethod] public void MetaphoneTest304() { Assert.IsTrue(MetaphoneTest("departamentos", "TPRT")); }
        [TestMethod] public void MetaphoneTest305() { Assert.IsTrue(MetaphoneTest("weaponry", "WPNR")); }
        [TestMethod] public void MetaphoneTest306() { Assert.IsTrue(MetaphoneTest("Haggett", "HKT")); }
        [TestMethod] public void MetaphoneTest307() { Assert.IsTrue(MetaphoneTest("martinville", "MRTN")); }
        [TestMethod] public void MetaphoneTest308() { Assert.IsTrue(MetaphoneTest("stina", "STN")); }
        [TestMethod] public void MetaphoneTest309() { Assert.IsTrue(MetaphoneTest("Rubottom", "RBTM")); }
        [TestMethod] public void MetaphoneTest310() { Assert.IsTrue(MetaphoneTest("Soyke", "SK")); }
        [TestMethod] public void MetaphoneTest311() { Assert.IsTrue(MetaphoneTest("corse", "KRS")); }
        [TestMethod] public void MetaphoneTest312() { Assert.IsTrue(MetaphoneTest("totalling", "TTLN")); }
        [TestMethod] public void MetaphoneTest313() { Assert.IsTrue(MetaphoneTest("kuppam", "KPM")); }
        [TestMethod] public void MetaphoneTest314() { Assert.IsTrue(MetaphoneTest("ftpadmin", "FTPT")); }
        [TestMethod] public void MetaphoneTest315() { Assert.IsTrue(MetaphoneTest("Forst", "FRST")); }
        [TestMethod] public void MetaphoneTest316() { Assert.IsTrue(MetaphoneTest("Ashauer", "AXR")); }
        [TestMethod] public void MetaphoneTest317() { Assert.IsTrue(MetaphoneTest("ashtanga", "AXTN")); }
        [TestMethod] public void MetaphoneTest318() { Assert.IsTrue(MetaphoneTest("alonissos", "ALNS")); }
        [TestMethod] public void MetaphoneTest319() { Assert.IsTrue(MetaphoneTest("Chimilio", "XML")); }
        [TestMethod] public void MetaphoneTest320() { Assert.IsTrue(MetaphoneTest("deafbazon", "TFBS")); }
        [TestMethod] public void MetaphoneTest321() { Assert.IsTrue(MetaphoneTest("psmb", "PSM")); }
        [TestMethod] public void MetaphoneTest322() { Assert.IsTrue(MetaphoneTest("Ferraraccio", "FRRK")); }
        [TestMethod] public void MetaphoneTest323() { Assert.IsTrue(MetaphoneTest("fractionated", "FRKX")); }
        [TestMethod] public void MetaphoneTest324() { Assert.IsTrue(MetaphoneTest("rrd", "RT")); }
        [TestMethod] public void MetaphoneTest325() { Assert.IsTrue(MetaphoneTest("luminosities", "LMNS")); }
        [TestMethod] public void MetaphoneTest326() { Assert.IsTrue(MetaphoneTest("Platzer", "PLTS")); }
        [TestMethod] public void MetaphoneTest327() { Assert.IsTrue(MetaphoneTest("modulator", "MTLT")); }
        [TestMethod] public void MetaphoneTest328() { Assert.IsTrue(MetaphoneTest("tyneside", "TNST")); }
        [TestMethod] public void MetaphoneTest329() { Assert.IsTrue(MetaphoneTest("nonuser", "NNSR")); }
        [TestMethod] public void MetaphoneTest330() { Assert.IsTrue(MetaphoneTest("haspel", "HSPL")); }
        [TestMethod] public void MetaphoneTest331() { Assert.IsTrue(MetaphoneTest("cortex", "KRTKS")); }
        [TestMethod] public void MetaphoneTest332() { Assert.IsTrue(MetaphoneTest("vechicle", "FXKL")); }
        [TestMethod] public void MetaphoneTest333() { Assert.IsTrue(MetaphoneTest("epinions", "EPNN")); }
        [TestMethod] public void MetaphoneTest334() { Assert.IsTrue(MetaphoneTest("wwwusmintgov", "SMNT")); }
        [TestMethod] public void MetaphoneTest335() { Assert.IsTrue(MetaphoneTest("katies", "KTS")); }
        [TestMethod] public void MetaphoneTest336() { Assert.IsTrue(MetaphoneTest("aminosalicylic", "AMNS")); }
        [TestMethod] public void MetaphoneTest337() { Assert.IsTrue(MetaphoneTest("mmegi", "MJ")); }
        [TestMethod] public void MetaphoneTest338() { Assert.IsTrue(MetaphoneTest("sbir", "SBR")); }
        [TestMethod] public void MetaphoneTest339() { Assert.IsTrue(MetaphoneTest("learned", "LRNT")); }
        [TestMethod] public void MetaphoneTest340() { Assert.IsTrue(MetaphoneTest("supris", "SPRS")); }
        [TestMethod] public void MetaphoneTest341() { Assert.IsTrue(MetaphoneTest("mozarteum", "MSRT")); }
        [TestMethod] public void MetaphoneTest342() { Assert.IsTrue(MetaphoneTest("selzer", "SLSR")); }
        [TestMethod] public void MetaphoneTest343() { Assert.IsTrue(MetaphoneTest("tmug", "TMK")); }
        [TestMethod] public void MetaphoneTest344() { Assert.IsTrue(MetaphoneTest("Kisto", "KST")); }
        [TestMethod] public void MetaphoneTest345() { Assert.IsTrue(MetaphoneTest("iib", "IB")); }
        [TestMethod] public void MetaphoneTest346() { Assert.IsTrue(MetaphoneTest("wwwincredimail", "NKRT")); }
        [TestMethod] public void MetaphoneTest347() { Assert.IsTrue(MetaphoneTest("izpack", "ISPK")); }
        [TestMethod] public void MetaphoneTest348() { Assert.IsTrue(MetaphoneTest("gaymovie", "KMF")); }
        [TestMethod] public void MetaphoneTest349() { Assert.IsTrue(MetaphoneTest("Buchholz", "BXLS")); }
        [TestMethod] public void MetaphoneTest350() { Assert.IsTrue(MetaphoneTest("culcairn", "KLKR")); }
        [TestMethod] public void MetaphoneTest351() { Assert.IsTrue(MetaphoneTest("barys", "BRS")); }
        [TestMethod] public void MetaphoneTest352() { Assert.IsTrue(MetaphoneTest("burets", "BRTS")); }
        [TestMethod] public void MetaphoneTest353() { Assert.IsTrue(MetaphoneTest("Sorce", "SRS")); }
        [TestMethod] public void MetaphoneTest354() { Assert.IsTrue(MetaphoneTest("chimique", "XMK")); }
        [TestMethod] public void MetaphoneTest355() { Assert.IsTrue(MetaphoneTest("kitada", "KTT")); }
        [TestMethod] public void MetaphoneTest356() { Assert.IsTrue(MetaphoneTest("Engeman", "ENJM")); }
        [TestMethod] public void MetaphoneTest357() { Assert.IsTrue(MetaphoneTest("raveendran", "RFNT")); }
        [TestMethod] public void MetaphoneTest358() { Assert.IsTrue(MetaphoneTest("Bendele", "BNTL")); }
        [TestMethod] public void MetaphoneTest359() { Assert.IsTrue(MetaphoneTest("Pawlitschek", "PLTS")); }
        [TestMethod] public void MetaphoneTest360() { Assert.IsTrue(MetaphoneTest("hogfather", "HKF0")); }
        [TestMethod] public void MetaphoneTest361() { Assert.IsTrue(MetaphoneTest("eyedrum", "EYTR")); }
        [TestMethod] public void MetaphoneTest362() { Assert.IsTrue(MetaphoneTest("Ferrara", "FRR")); }
        [TestMethod] public void MetaphoneTest363() { Assert.IsTrue(MetaphoneTest("zhuh", "SH")); }
        [TestMethod] public void MetaphoneTest364() { Assert.IsTrue(MetaphoneTest("zodiak", "STK")); }
        [TestMethod] public void MetaphoneTest365() { Assert.IsTrue(MetaphoneTest("pchcom", "PXKM")); }
        [TestMethod] public void MetaphoneTest366() { Assert.IsTrue(MetaphoneTest("conferees", "KNFR")); }
        [TestMethod] public void MetaphoneTest367() { Assert.IsTrue(MetaphoneTest("Decillis", "TSLS")); }
        [TestMethod] public void MetaphoneTest368() { Assert.IsTrue(MetaphoneTest("downloar", "TNLR")); }
        [TestMethod] public void MetaphoneTest369() { Assert.IsTrue(MetaphoneTest("shard", "XRT")); }
        [TestMethod] public void MetaphoneTest370() { Assert.IsTrue(MetaphoneTest("fajr", "FJR")); }
        [TestMethod] public void MetaphoneTest371() { Assert.IsTrue(MetaphoneTest("quisque", "KSK")); }
        [TestMethod] public void MetaphoneTest372() { Assert.IsTrue(MetaphoneTest("winterizing", "WNTR")); }
        [TestMethod] public void MetaphoneTest373() { Assert.IsTrue(MetaphoneTest("referate", "RFRT")); }
        [TestMethod] public void MetaphoneTest374() { Assert.IsTrue(MetaphoneTest("nuxone", "NKSN")); }
        [TestMethod] public void MetaphoneTest375() { Assert.IsTrue(MetaphoneTest("Racheal", "RXL")); }
        [TestMethod] public void MetaphoneTest376() { Assert.IsTrue(MetaphoneTest("bizben", "BSBN")); }
        [TestMethod] public void MetaphoneTest377() { Assert.IsTrue(MetaphoneTest("musictalk", "MSKT")); }
        [TestMethod] public void MetaphoneTest378() { Assert.IsTrue(MetaphoneTest("ogoal", "OKL")); }
        [TestMethod] public void MetaphoneTest379() { Assert.IsTrue(MetaphoneTest("Skoff", "SKF")); }
        [TestMethod] public void MetaphoneTest380() { Assert.IsTrue(MetaphoneTest("Seehusen", "SHSN")); }
        [TestMethod] public void MetaphoneTest381() { Assert.IsTrue(MetaphoneTest("Reim", "RM")); }
        [TestMethod] public void MetaphoneTest382() { Assert.IsTrue(MetaphoneTest("Yoh", "Y")); }
        [TestMethod] public void MetaphoneTest383() { Assert.IsTrue(MetaphoneTest("gapi", "KP")); }
        [TestMethod] public void MetaphoneTest384() { Assert.IsTrue(MetaphoneTest("Brightbill", "BRTB")); }
        [TestMethod] public void MetaphoneTest385() { Assert.IsTrue(MetaphoneTest("shuey", "X")); }
        [TestMethod] public void MetaphoneTest386() { Assert.IsTrue(MetaphoneTest("posium", "PSM")); }
        [TestMethod] public void MetaphoneTest387() { Assert.IsTrue(MetaphoneTest("Falknor", "FLKN")); }
        [TestMethod] public void MetaphoneTest388() { Assert.IsTrue(MetaphoneTest("ucat", "UKT")); }
        [TestMethod] public void MetaphoneTest389() { Assert.IsTrue(MetaphoneTest("properspace", "PRPR")); }
        [TestMethod] public void MetaphoneTest390() { Assert.IsTrue(MetaphoneTest("showimg", "XWMK")); }
        [TestMethod] public void MetaphoneTest391() { Assert.IsTrue(MetaphoneTest("Montecillo", "MNTS")); }
        [TestMethod] public void MetaphoneTest392() { Assert.IsTrue(MetaphoneTest("sajak", "SJK")); }
        [TestMethod] public void MetaphoneTest393() { Assert.IsTrue(MetaphoneTest("maturbation", "MTRB")); }
        [TestMethod] public void MetaphoneTest394() { Assert.IsTrue(MetaphoneTest("Lettie", "LT")); }
        [TestMethod] public void MetaphoneTest395() { Assert.IsTrue(MetaphoneTest("clauss", "KLS")); }
        [TestMethod] public void MetaphoneTest396() { Assert.IsTrue(MetaphoneTest("scheiber", "SXBR")); }
        [TestMethod] public void MetaphoneTest397() { Assert.IsTrue(MetaphoneTest("matp", "MTP")); }
        [TestMethod] public void MetaphoneTest398() { Assert.IsTrue(MetaphoneTest("mervtormel", "MRFT")); }
        [TestMethod] public void MetaphoneTest399() { Assert.IsTrue(MetaphoneTest("guanahani", "KNHN")); }
        [TestMethod] public void MetaphoneTest400() { Assert.IsTrue(MetaphoneTest("citement", "STMN")); }
        [TestMethod] public void MetaphoneTest401() { Assert.IsTrue(MetaphoneTest("immu", "IM")); }
        [TestMethod] public void MetaphoneTest402() { Assert.IsTrue(MetaphoneTest("virulence", "FRLN")); }
        [TestMethod] public void MetaphoneTest403() { Assert.IsTrue(MetaphoneTest("kussa", "KS")); }
        [TestMethod] public void MetaphoneTest404() { Assert.IsTrue(MetaphoneTest("gso", "KS")); }
        [TestMethod] public void MetaphoneTest405() { Assert.IsTrue(MetaphoneTest("webviajes", "WBFJ")); }
        [TestMethod] public void MetaphoneTest406() { Assert.IsTrue(MetaphoneTest("ldwork", "LTWR")); }
        [TestMethod] public void MetaphoneTest407() { Assert.IsTrue(MetaphoneTest("verses", "FRSS")); }
        [TestMethod] public void MetaphoneTest408() { Assert.IsTrue(MetaphoneTest("sondes", "SNTS")); }
        [TestMethod] public void MetaphoneTest409() { Assert.IsTrue(MetaphoneTest("freshpair", "FRXP")); }
        [TestMethod] public void MetaphoneTest410() { Assert.IsTrue(MetaphoneTest("licorne", "LKRN")); }
        [TestMethod] public void MetaphoneTest411() { Assert.IsTrue(MetaphoneTest("Vanis", "FNS")); }
        [TestMethod] public void MetaphoneTest412() { Assert.IsTrue(MetaphoneTest("Buena", "BN")); }
        [TestMethod] public void MetaphoneTest413() { Assert.IsTrue(MetaphoneTest("Tauares", "TRS")); }
        [TestMethod] public void MetaphoneTest414() { Assert.IsTrue(MetaphoneTest("ikus", "IKS")); }
        [TestMethod] public void MetaphoneTest415() { Assert.IsTrue(MetaphoneTest("genrebox", "JNRB")); }
        [TestMethod] public void MetaphoneTest416() { Assert.IsTrue(MetaphoneTest("rth", "R0")); }
        [TestMethod] public void MetaphoneTest417() { Assert.IsTrue(MetaphoneTest("Spaun", "SPN")); }
        [TestMethod] public void MetaphoneTest418() { Assert.IsTrue(MetaphoneTest("wiersbe", "WRSB")); }
        [TestMethod] public void MetaphoneTest419() { Assert.IsTrue(MetaphoneTest("dad", "TT")); }
        [TestMethod] public void MetaphoneTest420() { Assert.IsTrue(MetaphoneTest("tus", "TS")); }
        [TestMethod] public void MetaphoneTest421() { Assert.IsTrue(MetaphoneTest("Weidert", "WTRT")); }
        [TestMethod] public void MetaphoneTest422() { Assert.IsTrue(MetaphoneTest("rijke", "RJK")); }
        [TestMethod] public void MetaphoneTest423() { Assert.IsTrue(MetaphoneTest("fischbein", "FSXB")); }
        [TestMethod] public void MetaphoneTest424() { Assert.IsTrue(MetaphoneTest("fbeye", "FBY")); }
        [TestMethod] public void MetaphoneTest425() { Assert.IsTrue(MetaphoneTest("hagerty", "HJRT")); }
        [TestMethod] public void MetaphoneTest426() { Assert.IsTrue(MetaphoneTest("Hollendonner", "HLNT")); }
        [TestMethod] public void MetaphoneTest427() { Assert.IsTrue(MetaphoneTest("Huitzacua", "HTSK")); }
        [TestMethod] public void MetaphoneTest428() { Assert.IsTrue(MetaphoneTest("subjunctive", "SBJN")); }
        [TestMethod] public void MetaphoneTest429() { Assert.IsTrue(MetaphoneTest("implored", "IMPL")); }
        [TestMethod] public void MetaphoneTest430() { Assert.IsTrue(MetaphoneTest("pompeius", "PMPS")); }
        [TestMethod] public void MetaphoneTest431() { Assert.IsTrue(MetaphoneTest("afleet", "AFLT")); }
        [TestMethod] public void MetaphoneTest432() { Assert.IsTrue(MetaphoneTest("iacc", "IKK")); }
        [TestMethod] public void MetaphoneTest433() { Assert.IsTrue(MetaphoneTest("sabalos", "SBLS")); }
        [TestMethod] public void MetaphoneTest434() { Assert.IsTrue(MetaphoneTest("Abdi", "ABT")); }
        [TestMethod] public void MetaphoneTest435() { Assert.IsTrue(MetaphoneTest("microinsurance", "MKRN")); }
        [TestMethod] public void MetaphoneTest436() { Assert.IsTrue(MetaphoneTest("audiobook", "ATBK")); }
        [TestMethod] public void MetaphoneTest437() { Assert.IsTrue(MetaphoneTest("fulpmes", "FLPM")); }
        [TestMethod] public void MetaphoneTest438() { Assert.IsTrue(MetaphoneTest("registreren", "RJST")); }
        [TestMethod] public void MetaphoneTest439() { Assert.IsTrue(MetaphoneTest("megapath", "MKP0")); }
        [TestMethod] public void MetaphoneTest440() { Assert.IsTrue(MetaphoneTest("prestidigitation", "PRST")); }
        [TestMethod] public void MetaphoneTest441() { Assert.IsTrue(MetaphoneTest("wby", "B")); }
        [TestMethod] public void MetaphoneTest442() { Assert.IsTrue(MetaphoneTest("vorschau", "FRSX")); }
        [TestMethod] public void MetaphoneTest443() { Assert.IsTrue(MetaphoneTest("Albertha", "ALBR")); }
        [TestMethod] public void MetaphoneTest444() { Assert.IsTrue(MetaphoneTest("aspalpha", "ASPL")); }
        [TestMethod] public void MetaphoneTest445() { Assert.IsTrue(MetaphoneTest("Belden", "BLTN")); }
        [TestMethod] public void MetaphoneTest446() { Assert.IsTrue(MetaphoneTest("deterministic", "TTRM")); }
        [TestMethod] public void MetaphoneTest447() { Assert.IsTrue(MetaphoneTest("philosophique", "FLSF")); }
        [TestMethod] public void MetaphoneTest448() { Assert.IsTrue(MetaphoneTest("kleinen", "KLNN")); }
        [TestMethod] public void MetaphoneTest449() { Assert.IsTrue(MetaphoneTest("logouri", "LKR")); }
        [TestMethod] public void MetaphoneTest450() { Assert.IsTrue(MetaphoneTest("xbl", "SBL")); }
        [TestMethod] public void MetaphoneTest451() { Assert.IsTrue(MetaphoneTest("iz", "IS")); }
        [TestMethod] public void MetaphoneTest452() { Assert.IsTrue(MetaphoneTest("throckmorton", "0RKM")); }
        [TestMethod] public void MetaphoneTest453() { Assert.IsTrue(MetaphoneTest("condesa", "KNTS")); }
        [TestMethod] public void MetaphoneTest454() { Assert.IsTrue(MetaphoneTest("Mook", "MK")); }
        [TestMethod] public void MetaphoneTest455() { Assert.IsTrue(MetaphoneTest("medseek", "MTSK")); }
        [TestMethod] public void MetaphoneTest456() { Assert.IsTrue(MetaphoneTest("chugalug", "XKLK")); }
        [TestMethod] public void MetaphoneTest457() { Assert.IsTrue(MetaphoneTest("olms", "OLMS")); }
        [TestMethod] public void MetaphoneTest458() { Assert.IsTrue(MetaphoneTest("bogo", "BK")); }
        [TestMethod] public void MetaphoneTest459() { Assert.IsTrue(MetaphoneTest("essing", "ESNK")); }
        [TestMethod] public void MetaphoneTest460() { Assert.IsTrue(MetaphoneTest("rarden", "RRTN")); }
        [TestMethod] public void MetaphoneTest461() { Assert.IsTrue(MetaphoneTest("mittlere", "MTLR")); }
        [TestMethod] public void MetaphoneTest462() { Assert.IsTrue(MetaphoneTest("Borsa", "BRS")); }
        [TestMethod] public void MetaphoneTest463() { Assert.IsTrue(MetaphoneTest("Ainslie", "ANSL")); }
        [TestMethod] public void MetaphoneTest464() { Assert.IsTrue(MetaphoneTest("Ganska", "KNSK")); }
        [TestMethod] public void MetaphoneTest465() { Assert.IsTrue(MetaphoneTest("miv", "MF")); }
        [TestMethod] public void MetaphoneTest466() { Assert.IsTrue(MetaphoneTest("concessions", "KNSS")); }
        [TestMethod] public void MetaphoneTest467() { Assert.IsTrue(MetaphoneTest("distinguished", "TSTN")); }
        [TestMethod] public void MetaphoneTest468() { Assert.IsTrue(MetaphoneTest("cano", "KN")); }
        [TestMethod] public void MetaphoneTest469() { Assert.IsTrue(MetaphoneTest("plumper", "PLMP")); }
        [TestMethod] public void MetaphoneTest470() { Assert.IsTrue(MetaphoneTest("mindoro", "MNTR")); }
        [TestMethod] public void MetaphoneTest471() { Assert.IsTrue(MetaphoneTest("cephalopod", "SFLP")); }
        [TestMethod] public void MetaphoneTest472() { Assert.IsTrue(MetaphoneTest("Klunk", "KLNK")); }
        [TestMethod] public void MetaphoneTest473() { Assert.IsTrue(MetaphoneTest("Bumbrey", "BMR")); }
        [TestMethod] public void MetaphoneTest474() { Assert.IsTrue(MetaphoneTest("causeless", "KSLS")); }
        [TestMethod] public void MetaphoneTest475() { Assert.IsTrue(MetaphoneTest("Lothrop", "L0RP")); }
        [TestMethod] public void MetaphoneTest476() { Assert.IsTrue(MetaphoneTest("bodystyles", "BTST")); }
        [TestMethod] public void MetaphoneTest477() { Assert.IsTrue(MetaphoneTest("beaatiality", "BXLT")); }
        [TestMethod] public void MetaphoneTest478() { Assert.IsTrue(MetaphoneTest("Bobrowski", "BBRS")); }
        [TestMethod] public void MetaphoneTest479() { Assert.IsTrue(MetaphoneTest("erudition", "ERTX")); }
        [TestMethod] public void MetaphoneTest480() { Assert.IsTrue(MetaphoneTest("huttner", "HTNR")); }
        [TestMethod] public void MetaphoneTest481() { Assert.IsTrue(MetaphoneTest("wwwaskjeevescom", "SKJF")); }
        [TestMethod] public void MetaphoneTest482() { Assert.IsTrue(MetaphoneTest("Duross", "TRS")); }
        [TestMethod] public void MetaphoneTest483() { Assert.IsTrue(MetaphoneTest("Colemen", "KLMN")); }
        [TestMethod] public void MetaphoneTest484() { Assert.IsTrue(MetaphoneTest("Duncomb", "TNKM")); }
        [TestMethod] public void MetaphoneTest485() { Assert.IsTrue(MetaphoneTest("tripe", "TRP")); }
        [TestMethod] public void MetaphoneTest486() { Assert.IsTrue(MetaphoneTest("dorrigo", "TRK")); }
        [TestMethod] public void MetaphoneTest487() { Assert.IsTrue(MetaphoneTest("Mascall", "MSKL")); }
        [TestMethod] public void MetaphoneTest488() { Assert.IsTrue(MetaphoneTest("jetplane", "JTPL")); }
        [TestMethod] public void MetaphoneTest489() { Assert.IsTrue(MetaphoneTest("nswrl", "NSRL")); }
        [TestMethod] public void MetaphoneTest490() { Assert.IsTrue(MetaphoneTest("didates", "TTTS")); }
        [TestMethod] public void MetaphoneTest491() { Assert.IsTrue(MetaphoneTest("Jena", "JN")); }
        [TestMethod] public void MetaphoneTest492() { Assert.IsTrue(MetaphoneTest("kctu", "KKT")); }
        [TestMethod] public void MetaphoneTest493() { Assert.IsTrue(MetaphoneTest("cualquiera", "KLKR")); }
        [TestMethod] public void MetaphoneTest494() { Assert.IsTrue(MetaphoneTest("plutella", "PLTL")); }
        [TestMethod] public void MetaphoneTest495() { Assert.IsTrue(MetaphoneTest("Liebig", "LBK")); }
        [TestMethod] public void MetaphoneTest496() { Assert.IsTrue(MetaphoneTest("Llorens", "LRNS")); }
        [TestMethod] public void MetaphoneTest497() { Assert.IsTrue(MetaphoneTest("mraz", "MRS")); }
        [TestMethod] public void MetaphoneTest498() { Assert.IsTrue(MetaphoneTest("shadyac", "XTYK")); }
        [TestMethod] public void MetaphoneTest499() { Assert.IsTrue(MetaphoneTest("lossphentermine", "LSFN")); }
        [TestMethod] public void MetaphoneTest500() { Assert.IsTrue(MetaphoneTest("Dreith", "TR0")); }
        [TestMethod] public void MetaphoneTest501() { Assert.IsTrue(MetaphoneTest("Windsor", "WNTS")); }


    }
}