using Element34.StringMetrics.Phonetic;

namespace Element34Tests.Phonetic
{
    [TestClass]
    public class Metaphone2Tests
    {
        private bool DoubleMetaphoneTest(string sInput, string sExpected1, string sExpected2)
        {
            DoubleMetaphone mp = new DoubleMetaphone();
            return mp.Compare(sInput, sExpected1, sExpected2);
        }

        [TestMethod] public void Metaphone2Test001() { Assert.IsTrue(DoubleMetaphoneTest("communication", "KMNK", "")); }
        [TestMethod] public void Metaphone2Test002() { Assert.IsTrue(DoubleMetaphoneTest("worships", "ARXP", "FRXP")); }
        [TestMethod] public void Metaphone2Test003() { Assert.IsTrue(DoubleMetaphoneTest("televisionhome", "TLFS", "TLFX")); }
        [TestMethod] public void Metaphone2Test004() { Assert.IsTrue(DoubleMetaphoneTest("bumi", "PM", "")); }
        [TestMethod] public void Metaphone2Test005() { Assert.IsTrue(DoubleMetaphoneTest("shortbread", "XRTP", "")); }
        [TestMethod] public void Metaphone2Test006() { Assert.IsTrue(DoubleMetaphoneTest("slice", "SLS", "XLS")); }
        [TestMethod] public void Metaphone2Test007() { Assert.IsTrue(DoubleMetaphoneTest("reint", "RNT", "")); }
        [TestMethod] public void Metaphone2Test008() { Assert.IsTrue(DoubleMetaphoneTest("Florence", "FLRN", "")); }
        [TestMethod] public void Metaphone2Test009() { Assert.IsTrue(DoubleMetaphoneTest("fawzi", "FS", "FTS")); }
        [TestMethod] public void Metaphone2Test010() { Assert.IsTrue(DoubleMetaphoneTest("sname", "SNM", "XNM")); }
        [TestMethod] public void Metaphone2Test011() { Assert.IsTrue(DoubleMetaphoneTest("modano", "MTN", "")); }
        [TestMethod] public void Metaphone2Test012() { Assert.IsTrue(DoubleMetaphoneTest("stumpage", "STMP", "")); }
        [TestMethod] public void Metaphone2Test013() { Assert.IsTrue(DoubleMetaphoneTest("clears", "KLRS", "")); }
        [TestMethod] public void Metaphone2Test014() { Assert.IsTrue(DoubleMetaphoneTest("ciods", "STS", "XTS")); }
        [TestMethod] public void Metaphone2Test015() { Assert.IsTrue(DoubleMetaphoneTest("deseos", "TSS", "")); }
        [TestMethod] public void Metaphone2Test016() { Assert.IsTrue(DoubleMetaphoneTest("dippin", "TPN", "")); }
        [TestMethod] public void Metaphone2Test017() { Assert.IsTrue(DoubleMetaphoneTest("aranna", "ARN", "")); }
        [TestMethod] public void Metaphone2Test018() { Assert.IsTrue(DoubleMetaphoneTest("borse", "PRS", "")); }
        [TestMethod] public void Metaphone2Test019() { Assert.IsTrue(DoubleMetaphoneTest("subic", "SPK", "")); }
        [TestMethod] public void Metaphone2Test020() { Assert.IsTrue(DoubleMetaphoneTest("Vidrio", "FTR", "")); }
        [TestMethod] public void Metaphone2Test021() { Assert.IsTrue(DoubleMetaphoneTest("inserters", "ANSR", "")); }
        [TestMethod] public void Metaphone2Test022() { Assert.IsTrue(DoubleMetaphoneTest("perature", "PRTR", "")); }
        [TestMethod] public void Metaphone2Test023() { Assert.IsTrue(DoubleMetaphoneTest("msacideas", "MSST", "")); }
        [TestMethod] public void Metaphone2Test024() { Assert.IsTrue(DoubleMetaphoneTest("cougs", "KKS", "")); }
        [TestMethod] public void Metaphone2Test025() { Assert.IsTrue(DoubleMetaphoneTest("kittens", "KTNS", "")); }
        [TestMethod] public void Metaphone2Test026() { Assert.IsTrue(DoubleMetaphoneTest("imperiously", "AMPR", "")); }
        [TestMethod] public void Metaphone2Test027() { Assert.IsTrue(DoubleMetaphoneTest("boccanegra", "PKNK", "")); }
        [TestMethod] public void Metaphone2Test028() { Assert.IsTrue(DoubleMetaphoneTest("sextet", "SKST", "")); }
        [TestMethod] public void Metaphone2Test029() { Assert.IsTrue(DoubleMetaphoneTest("setattributes", "STTR", "")); }
        [TestMethod] public void Metaphone2Test030() { Assert.IsTrue(DoubleMetaphoneTest("dsnt", "TSNT", "")); }
        [TestMethod] public void Metaphone2Test031() { Assert.IsTrue(DoubleMetaphoneTest("chubby", "XP", "")); }
        [TestMethod] public void Metaphone2Test032() { Assert.IsTrue(DoubleMetaphoneTest("ooda", "AT", "")); }
        [TestMethod] public void Metaphone2Test033() { Assert.IsTrue(DoubleMetaphoneTest("Bressman", "PRSM", "")); }
        [TestMethod] public void Metaphone2Test034() { Assert.IsTrue(DoubleMetaphoneTest("calendarnew", "KLNT", "")); }
        [TestMethod] public void Metaphone2Test035() { Assert.IsTrue(DoubleMetaphoneTest("duhon", "THN", "")); }
        [TestMethod] public void Metaphone2Test036() { Assert.IsTrue(DoubleMetaphoneTest("nchen", "NXN", "NKN")); }
        [TestMethod] public void Metaphone2Test037() { Assert.IsTrue(DoubleMetaphoneTest("betjemans", "PTJM", "")); }
        [TestMethod] public void Metaphone2Test038() { Assert.IsTrue(DoubleMetaphoneTest("Mangum", "MNKM", "")); }
        [TestMethod] public void Metaphone2Test039() { Assert.IsTrue(DoubleMetaphoneTest("cabac", "KPK", "")); }
        [TestMethod] public void Metaphone2Test040() { Assert.IsTrue(DoubleMetaphoneTest("pantys", "PNTS", "")); }
        [TestMethod] public void Metaphone2Test041() { Assert.IsTrue(DoubleMetaphoneTest("cofactors", "KFKT", "")); }
        [TestMethod] public void Metaphone2Test042() { Assert.IsTrue(DoubleMetaphoneTest("clickz", "KLKS", "KLKT")); }
        [TestMethod] public void Metaphone2Test043() { Assert.IsTrue(DoubleMetaphoneTest("chiap", "KP", "")); }
        [TestMethod] public void Metaphone2Test044() { Assert.IsTrue(DoubleMetaphoneTest("Dalpiaz", "TLPS", "")); }
        [TestMethod] public void Metaphone2Test045() { Assert.IsTrue(DoubleMetaphoneTest("philosophically", "FLSF", "")); }
        [TestMethod] public void Metaphone2Test046() { Assert.IsTrue(DoubleMetaphoneTest("backfill", "PKFL", "")); }
        [TestMethod] public void Metaphone2Test047() { Assert.IsTrue(DoubleMetaphoneTest("Murders", "MRTR", "")); }
        [TestMethod] public void Metaphone2Test048() { Assert.IsTrue(DoubleMetaphoneTest("ecartis", "AKRT", "")); }
        [TestMethod] public void Metaphone2Test049() { Assert.IsTrue(DoubleMetaphoneTest("vede", "FT", "")); }
        [TestMethod] public void Metaphone2Test050() { Assert.IsTrue(DoubleMetaphoneTest("usoe", "AS", "")); }
        [TestMethod] public void Metaphone2Test051() { Assert.IsTrue(DoubleMetaphoneTest("ostara", "ASTR", "")); }
        [TestMethod] public void Metaphone2Test052() { Assert.IsTrue(DoubleMetaphoneTest("labourer", "LPRR", "")); }
        [TestMethod] public void Metaphone2Test053() { Assert.IsTrue(DoubleMetaphoneTest("speir", "SPR", "")); }
        [TestMethod] public void Metaphone2Test054() { Assert.IsTrue(DoubleMetaphoneTest("durchaus", "TRXS", "TRKS")); }
        [TestMethod] public void Metaphone2Test055() { Assert.IsTrue(DoubleMetaphoneTest("inetformfiller", "ANTF", "")); }
        [TestMethod] public void Metaphone2Test056() { Assert.IsTrue(DoubleMetaphoneTest("itrs", "ATRS", "")); }
        [TestMethod] public void Metaphone2Test057() { Assert.IsTrue(DoubleMetaphoneTest("Tennant", "TNNT", "")); }
        [TestMethod] public void Metaphone2Test058() { Assert.IsTrue(DoubleMetaphoneTest("bashore", "PXR", "")); }
        [TestMethod] public void Metaphone2Test059() { Assert.IsTrue(DoubleMetaphoneTest("lemurian", "LMRN", "")); }
        [TestMethod] public void Metaphone2Test060() { Assert.IsTrue(DoubleMetaphoneTest("dungannon", "TNKN", "")); }
        [TestMethod] public void Metaphone2Test061() { Assert.IsTrue(DoubleMetaphoneTest("epl", "APL", "")); }
        [TestMethod] public void Metaphone2Test062() { Assert.IsTrue(DoubleMetaphoneTest("grader", "KRTR", "")); }
        [TestMethod] public void Metaphone2Test063() { Assert.IsTrue(DoubleMetaphoneTest("synchronise", "SNXR", "SNKR")); }
        [TestMethod] public void Metaphone2Test064() { Assert.IsTrue(DoubleMetaphoneTest("gondorian", "KNTR", "")); }
        [TestMethod] public void Metaphone2Test065() { Assert.IsTrue(DoubleMetaphoneTest("cvnet", "KFNT", "")); }
        [TestMethod] public void Metaphone2Test066() { Assert.IsTrue(DoubleMetaphoneTest("Centers", "SNTR", "")); }
        [TestMethod] public void Metaphone2Test067() { Assert.IsTrue(DoubleMetaphoneTest("soaks", "SKS", "")); }
        [TestMethod] public void Metaphone2Test068() { Assert.IsTrue(DoubleMetaphoneTest("gogllle", "KKLL", "")); }
        [TestMethod] public void Metaphone2Test069() { Assert.IsTrue(DoubleMetaphoneTest("peotone", "PTN", "")); }
        [TestMethod] public void Metaphone2Test070() { Assert.IsTrue(DoubleMetaphoneTest("Sharp", "XRP", "")); }
        [TestMethod] public void Metaphone2Test071() { Assert.IsTrue(DoubleMetaphoneTest("mawer", "MR", "")); }
        [TestMethod] public void Metaphone2Test072() { Assert.IsTrue(DoubleMetaphoneTest("Morasca", "MRSK", "")); }
        [TestMethod] public void Metaphone2Test073() { Assert.IsTrue(DoubleMetaphoneTest("ticknor", "TKNR", "")); }
        [TestMethod] public void Metaphone2Test074() { Assert.IsTrue(DoubleMetaphoneTest("beaverdale", "PFRT", "")); }
        [TestMethod] public void Metaphone2Test075() { Assert.IsTrue(DoubleMetaphoneTest("caledonianew", "KLTN", "")); }
        [TestMethod] public void Metaphone2Test076() { Assert.IsTrue(DoubleMetaphoneTest("wellnessdicke", "ALNS", "FLNS")); }
        [TestMethod] public void Metaphone2Test077() { Assert.IsTrue(DoubleMetaphoneTest("Rodin", "RTN", "")); }
        [TestMethod] public void Metaphone2Test078() { Assert.IsTrue(DoubleMetaphoneTest("bluffer", "PLFR", "")); }
        [TestMethod] public void Metaphone2Test079() { Assert.IsTrue(DoubleMetaphoneTest("joey", "J", "A")); }
        [TestMethod] public void Metaphone2Test080() { Assert.IsTrue(DoubleMetaphoneTest("unbekannter", "ANPK", "")); }
        [TestMethod] public void Metaphone2Test081() { Assert.IsTrue(DoubleMetaphoneTest("Baylor", "PLR", "")); }
        [TestMethod] public void Metaphone2Test082() { Assert.IsTrue(DoubleMetaphoneTest("striplib", "STRP", "")); }
        [TestMethod] public void Metaphone2Test083() { Assert.IsTrue(DoubleMetaphoneTest("boquete", "PKT", "")); }
        [TestMethod] public void Metaphone2Test084() { Assert.IsTrue(DoubleMetaphoneTest("geylang", "KLNK", "JLNK")); }
        [TestMethod] public void Metaphone2Test085() { Assert.IsTrue(DoubleMetaphoneTest("Lavi", "LF", "")); }
        [TestMethod] public void Metaphone2Test086() { Assert.IsTrue(DoubleMetaphoneTest("moldovans", "MLTF", "")); }
        [TestMethod] public void Metaphone2Test087() { Assert.IsTrue(DoubleMetaphoneTest("linq", "LNK", "")); }
        [TestMethod] public void Metaphone2Test088() { Assert.IsTrue(DoubleMetaphoneTest("Kenworthy", "KNR0", "KNRT")); }
        [TestMethod] public void Metaphone2Test089() { Assert.IsTrue(DoubleMetaphoneTest("Steckman", "STKM", "")); }
        [TestMethod] public void Metaphone2Test090() { Assert.IsTrue(DoubleMetaphoneTest("czechoslovakian", "SXSL", "XKSL")); }
        [TestMethod] public void Metaphone2Test091() { Assert.IsTrue(DoubleMetaphoneTest("marmora", "MRMR", "")); }
        [TestMethod] public void Metaphone2Test092() { Assert.IsTrue(DoubleMetaphoneTest("Carvill", "KRFL", "")); }
        [TestMethod] public void Metaphone2Test093() { Assert.IsTrue(DoubleMetaphoneTest("chihiro", "XHR", "")); }
        [TestMethod] public void Metaphone2Test094() { Assert.IsTrue(DoubleMetaphoneTest("hctc", "KTK", "")); }
        [TestMethod] public void Metaphone2Test095() { Assert.IsTrue(DoubleMetaphoneTest("nolde", "NLT", "")); }
        [TestMethod] public void Metaphone2Test096() { Assert.IsTrue(DoubleMetaphoneTest("aerosolized", "ARSL", "")); }
        [TestMethod] public void Metaphone2Test097() { Assert.IsTrue(DoubleMetaphoneTest("canterbury", "KNTR", "")); }
        [TestMethod] public void Metaphone2Test098() { Assert.IsTrue(DoubleMetaphoneTest("jss", "JS", "AS")); }
        [TestMethod] public void Metaphone2Test099() { Assert.IsTrue(DoubleMetaphoneTest("rmn", "RMN", "")); }
        [TestMethod] public void Metaphone2Test100() { Assert.IsTrue(DoubleMetaphoneTest("mazlish", "MSLX", "")); }
        [TestMethod] public void Metaphone2Test101() { Assert.IsTrue(DoubleMetaphoneTest("faites", "FTS", "")); }
        [TestMethod] public void Metaphone2Test102() { Assert.IsTrue(DoubleMetaphoneTest("foyer", "FR", "")); }
        [TestMethod] public void Metaphone2Test103() { Assert.IsTrue(DoubleMetaphoneTest("ductions", "TKXN", "")); }
        [TestMethod] public void Metaphone2Test104() { Assert.IsTrue(DoubleMetaphoneTest("Rambo", "RMP", "")); }
        [TestMethod] public void Metaphone2Test105() { Assert.IsTrue(DoubleMetaphoneTest("Curnutte", "KRNT", "")); }
        [TestMethod] public void Metaphone2Test106() { Assert.IsTrue(DoubleMetaphoneTest("Feltus", "FLTS", "")); }
        [TestMethod] public void Metaphone2Test107() { Assert.IsTrue(DoubleMetaphoneTest("forbairt", "FRPR", "")); }
        [TestMethod] public void Metaphone2Test108() { Assert.IsTrue(DoubleMetaphoneTest("southerners", "S0RN", "STRN")); }
        [TestMethod] public void Metaphone2Test109() { Assert.IsTrue(DoubleMetaphoneTest("hypnotists", "HPNT", "")); }
        [TestMethod] public void Metaphone2Test110() { Assert.IsTrue(DoubleMetaphoneTest("euphony", "AFN", "")); }
        [TestMethod] public void Metaphone2Test111() { Assert.IsTrue(DoubleMetaphoneTest("mhpa", "MP", "")); }
        [TestMethod] public void Metaphone2Test112() { Assert.IsTrue(DoubleMetaphoneTest("matteotti", "MTT", "")); }
        [TestMethod] public void Metaphone2Test113() { Assert.IsTrue(DoubleMetaphoneTest("Klande", "KLNT", "")); }
        [TestMethod] public void Metaphone2Test114() { Assert.IsTrue(DoubleMetaphoneTest("Trudgeon", "TRJN", "")); }
        [TestMethod] public void Metaphone2Test115() { Assert.IsTrue(DoubleMetaphoneTest("schoolhill", "SKLL", "")); }
        [TestMethod] public void Metaphone2Test116() { Assert.IsTrue(DoubleMetaphoneTest("equalizer", "AKLS", "")); }
        [TestMethod] public void Metaphone2Test117() { Assert.IsTrue(DoubleMetaphoneTest("xnet", "SNT", "")); }
        [TestMethod] public void Metaphone2Test118() { Assert.IsTrue(DoubleMetaphoneTest("Thell", "0L", "TL")); }
        [TestMethod] public void Metaphone2Test119() { Assert.IsTrue(DoubleMetaphoneTest("Canel", "KNL", "")); }
        [TestMethod] public void Metaphone2Test120() { Assert.IsTrue(DoubleMetaphoneTest("vmetro", "FMTR", "")); }
        [TestMethod] public void Metaphone2Test121() { Assert.IsTrue(DoubleMetaphoneTest("burgtheater", "PRK0", "PRKT")); }
        [TestMethod] public void Metaphone2Test122() { Assert.IsTrue(DoubleMetaphoneTest("Berlinger", "PRLN", "")); }
        [TestMethod] public void Metaphone2Test123() { Assert.IsTrue(DoubleMetaphoneTest("crehan", "KRHN", "")); }
        [TestMethod] public void Metaphone2Test124() { Assert.IsTrue(DoubleMetaphoneTest("abysses", "APSS", "")); }
        [TestMethod] public void Metaphone2Test125() { Assert.IsTrue(DoubleMetaphoneTest("Hipolito", "HPLT", "")); }
        [TestMethod] public void Metaphone2Test126() { Assert.IsTrue(DoubleMetaphoneTest("splintered", "SPLN", "")); }
        [TestMethod] public void Metaphone2Test127() { Assert.IsTrue(DoubleMetaphoneTest("maintenace", "MNTN", "")); }
        [TestMethod] public void Metaphone2Test128() { Assert.IsTrue(DoubleMetaphoneTest("decency", "TSNS", "")); }
        [TestMethod] public void Metaphone2Test129() { Assert.IsTrue(DoubleMetaphoneTest("quantz", "KNTS", "")); }
        [TestMethod] public void Metaphone2Test130() { Assert.IsTrue(DoubleMetaphoneTest("wette", "AT", "FT")); }
        [TestMethod] public void Metaphone2Test131() { Assert.IsTrue(DoubleMetaphoneTest("Feary", "FR", "")); }
        [TestMethod] public void Metaphone2Test132() { Assert.IsTrue(DoubleMetaphoneTest("Cuchiara", "KKR", "")); }
        [TestMethod] public void Metaphone2Test133() { Assert.IsTrue(DoubleMetaphoneTest("Arbon", "ARPN", "")); }
        [TestMethod] public void Metaphone2Test134() { Assert.IsTrue(DoubleMetaphoneTest("shyness", "XNS", "")); }
        [TestMethod] public void Metaphone2Test135() { Assert.IsTrue(DoubleMetaphoneTest("Salin", "SLN", "")); }
        [TestMethod] public void Metaphone2Test136() { Assert.IsTrue(DoubleMetaphoneTest("Zicafoose", "SKFS", "")); }
        [TestMethod] public void Metaphone2Test137() { Assert.IsTrue(DoubleMetaphoneTest("Menn", "MN", "")); }
        [TestMethod] public void Metaphone2Test138() { Assert.IsTrue(DoubleMetaphoneTest("funker", "FNKR", "")); }
        [TestMethod] public void Metaphone2Test139() { Assert.IsTrue(DoubleMetaphoneTest("santillan", "SNTL", "")); }
        [TestMethod] public void Metaphone2Test140() { Assert.IsTrue(DoubleMetaphoneTest("punani", "PNN", "")); }
        [TestMethod] public void Metaphone2Test141() { Assert.IsTrue(DoubleMetaphoneTest("basa", "PS", "")); }
        [TestMethod] public void Metaphone2Test142() { Assert.IsTrue(DoubleMetaphoneTest("bluefin", "PLFN", "")); }
        [TestMethod] public void Metaphone2Test143() { Assert.IsTrue(DoubleMetaphoneTest("cc", "K", "")); }
        [TestMethod] public void Metaphone2Test144() { Assert.IsTrue(DoubleMetaphoneTest("zipgenius", "SPJN", "SPKN")); }
        [TestMethod] public void Metaphone2Test145() { Assert.IsTrue(DoubleMetaphoneTest("Kirchen", "KRXN", "KRKN")); }
        [TestMethod] public void Metaphone2Test146() { Assert.IsTrue(DoubleMetaphoneTest("commentaar", "KMNT", "")); }
        [TestMethod] public void Metaphone2Test147() { Assert.IsTrue(DoubleMetaphoneTest("expansive", "AKSP", "")); }
        [TestMethod] public void Metaphone2Test148() { Assert.IsTrue(DoubleMetaphoneTest("castlebar", "KSTL", "")); }
        [TestMethod] public void Metaphone2Test149() { Assert.IsTrue(DoubleMetaphoneTest("lft", "LFT", "")); }
        [TestMethod] public void Metaphone2Test150() { Assert.IsTrue(DoubleMetaphoneTest("robla", "RPL", "")); }
        [TestMethod] public void Metaphone2Test151() { Assert.IsTrue(DoubleMetaphoneTest("zarontin", "SRNT", "")); }
        [TestMethod] public void Metaphone2Test152() { Assert.IsTrue(DoubleMetaphoneTest("nawc", "NK", "")); }
        [TestMethod] public void Metaphone2Test153() { Assert.IsTrue(DoubleMetaphoneTest("resolvconf", "RSLF", "")); }
        [TestMethod] public void Metaphone2Test154() { Assert.IsTrue(DoubleMetaphoneTest("networker", "NTRK", "")); }
        [TestMethod] public void Metaphone2Test155() { Assert.IsTrue(DoubleMetaphoneTest("airlins", "ARLN", "")); }
        [TestMethod] public void Metaphone2Test156() { Assert.IsTrue(DoubleMetaphoneTest("Piskel", "PSKL", "")); }
        [TestMethod] public void Metaphone2Test157() { Assert.IsTrue(DoubleMetaphoneTest("hilson", "HLSN", "")); }
        [TestMethod] public void Metaphone2Test158() { Assert.IsTrue(DoubleMetaphoneTest("deco", "TK", "")); }
        [TestMethod] public void Metaphone2Test159() { Assert.IsTrue(DoubleMetaphoneTest("cents", "SNTS", "")); }
        [TestMethod] public void Metaphone2Test160() { Assert.IsTrue(DoubleMetaphoneTest("award", "ART", "")); }
        [TestMethod] public void Metaphone2Test161() { Assert.IsTrue(DoubleMetaphoneTest("reykjanes", "RKNS", "")); }
        [TestMethod] public void Metaphone2Test162() { Assert.IsTrue(DoubleMetaphoneTest("perona", "PRN", "")); }
        [TestMethod] public void Metaphone2Test163() { Assert.IsTrue(DoubleMetaphoneTest("epistle", "APST", "")); }
        [TestMethod] public void Metaphone2Test164() { Assert.IsTrue(DoubleMetaphoneTest("insound", "ANSN", "")); }
        [TestMethod] public void Metaphone2Test165() { Assert.IsTrue(DoubleMetaphoneTest("qantas", "KNTS", "")); }
        [TestMethod] public void Metaphone2Test166() { Assert.IsTrue(DoubleMetaphoneTest("wholey", "AL", "")); }
        [TestMethod] public void Metaphone2Test167() { Assert.IsTrue(DoubleMetaphoneTest("aragona", "ARKN", "")); }
        [TestMethod] public void Metaphone2Test168() { Assert.IsTrue(DoubleMetaphoneTest("Vancheri", "FNXR", "FNKR")); }
        [TestMethod] public void Metaphone2Test169() { Assert.IsTrue(DoubleMetaphoneTest("allocution", "ALKX", "")); }
        [TestMethod] public void Metaphone2Test170() { Assert.IsTrue(DoubleMetaphoneTest("volodya", "FLT", "")); }
        [TestMethod] public void Metaphone2Test171() { Assert.IsTrue(DoubleMetaphoneTest("enunciate", "ANNS", "ANNX")); }
        [TestMethod] public void Metaphone2Test172() { Assert.IsTrue(DoubleMetaphoneTest("uuuu", "A", "")); }
        [TestMethod] public void Metaphone2Test173() { Assert.IsTrue(DoubleMetaphoneTest("Louato", "LT", "")); }
        [TestMethod] public void Metaphone2Test174() { Assert.IsTrue(DoubleMetaphoneTest("Marquitta", "MRKT", "")); }
        [TestMethod] public void Metaphone2Test175() { Assert.IsTrue(DoubleMetaphoneTest("surmountable", "SRMN", "")); }
        [TestMethod] public void Metaphone2Test176() { Assert.IsTrue(DoubleMetaphoneTest("gaultier", "KLT", "KLTR")); }
        [TestMethod] public void Metaphone2Test177() { Assert.IsTrue(DoubleMetaphoneTest("dafoe", "TF", "")); }
        [TestMethod] public void Metaphone2Test178() { Assert.IsTrue(DoubleMetaphoneTest("Claudio", "KLT", "")); }
        [TestMethod] public void Metaphone2Test179() { Assert.IsTrue(DoubleMetaphoneTest("ritva", "RTF", "")); }
        [TestMethod] public void Metaphone2Test180() { Assert.IsTrue(DoubleMetaphoneTest("spunky", "SPNK", "")); }
        [TestMethod] public void Metaphone2Test181() { Assert.IsTrue(DoubleMetaphoneTest("npov", "NPF", "")); }
        [TestMethod] public void Metaphone2Test182() { Assert.IsTrue(DoubleMetaphoneTest("eurythmics", "AR0M", "ARTM")); }
        [TestMethod] public void Metaphone2Test183() { Assert.IsTrue(DoubleMetaphoneTest("skittish", "SKTX", "")); }
        [TestMethod] public void Metaphone2Test184() { Assert.IsTrue(DoubleMetaphoneTest("scooter", "SKTR", "")); }
        [TestMethod] public void Metaphone2Test185() { Assert.IsTrue(DoubleMetaphoneTest("unfermented", "ANFR", "")); }
        [TestMethod] public void Metaphone2Test186() { Assert.IsTrue(DoubleMetaphoneTest("kerridge", "KRJ", "")); }
        [TestMethod] public void Metaphone2Test187() { Assert.IsTrue(DoubleMetaphoneTest("scenography", "SNKR", "")); }
        [TestMethod] public void Metaphone2Test188() { Assert.IsTrue(DoubleMetaphoneTest("sahalee", "SHL", "")); }
        [TestMethod] public void Metaphone2Test189() { Assert.IsTrue(DoubleMetaphoneTest("spooktacular", "SPKT", "")); }
        [TestMethod] public void Metaphone2Test190() { Assert.IsTrue(DoubleMetaphoneTest("boissons", "PSNS", "")); }
        [TestMethod] public void Metaphone2Test191() { Assert.IsTrue(DoubleMetaphoneTest("arbete", "ARPT", "")); }
        [TestMethod] public void Metaphone2Test192() { Assert.IsTrue(DoubleMetaphoneTest("Norrick", "NRK", "")); }
        [TestMethod] public void Metaphone2Test193() { Assert.IsTrue(DoubleMetaphoneTest("Sonnier", "SN", "SNR")); }
        [TestMethod] public void Metaphone2Test194() { Assert.IsTrue(DoubleMetaphoneTest("gnomeui", "NM", "")); }
        [TestMethod] public void Metaphone2Test195() { Assert.IsTrue(DoubleMetaphoneTest("milian", "MLN", "")); }
        [TestMethod] public void Metaphone2Test196() { Assert.IsTrue(DoubleMetaphoneTest("blackplanetcom", "PLKP", "")); }
        [TestMethod] public void Metaphone2Test197() { Assert.IsTrue(DoubleMetaphoneTest("tuned", "TNT", "")); }
        [TestMethod] public void Metaphone2Test198() { Assert.IsTrue(DoubleMetaphoneTest("Salone", "SLN", "")); }
        [TestMethod] public void Metaphone2Test199() { Assert.IsTrue(DoubleMetaphoneTest("marathon", "MR0N", "MRTN")); }
        [TestMethod] public void Metaphone2Test200() { Assert.IsTrue(DoubleMetaphoneTest("layoffs", "LFS", "")); }
        [TestMethod] public void Metaphone2Test201() { Assert.IsTrue(DoubleMetaphoneTest("hotek", "HTK", "")); }
        [TestMethod] public void Metaphone2Test202() { Assert.IsTrue(DoubleMetaphoneTest("emme", "AM", "")); }
        [TestMethod] public void Metaphone2Test203() { Assert.IsTrue(DoubleMetaphoneTest("amarasinghe", "AMRS", "")); }
        [TestMethod] public void Metaphone2Test204() { Assert.IsTrue(DoubleMetaphoneTest("midas", "MTS", "")); }
        [TestMethod] public void Metaphone2Test205() { Assert.IsTrue(DoubleMetaphoneTest("inhaltsangabe", "ANLT", "")); }
        [TestMethod] public void Metaphone2Test206() { Assert.IsTrue(DoubleMetaphoneTest("smow", "SM", "XMF")); }
        [TestMethod] public void Metaphone2Test207() { Assert.IsTrue(DoubleMetaphoneTest("policing", "PLSN", "")); }
        [TestMethod] public void Metaphone2Test208() { Assert.IsTrue(DoubleMetaphoneTest("usmf", "ASMF", "")); }
        [TestMethod] public void Metaphone2Test209() { Assert.IsTrue(DoubleMetaphoneTest("inferred", "ANFR", "")); }
        [TestMethod] public void Metaphone2Test210() { Assert.IsTrue(DoubleMetaphoneTest("Eaglen", "AKLN", "")); }
        [TestMethod] public void Metaphone2Test211() { Assert.IsTrue(DoubleMetaphoneTest("dralle", "TRL", "TR")); }
        [TestMethod] public void Metaphone2Test212() { Assert.IsTrue(DoubleMetaphoneTest("kalmus", "KLMS", "")); }
        [TestMethod] public void Metaphone2Test213() { Assert.IsTrue(DoubleMetaphoneTest("nork", "NRK", "")); }
        [TestMethod] public void Metaphone2Test214() { Assert.IsTrue(DoubleMetaphoneTest("Waterston", "ATRS", "FTRS")); }
        [TestMethod] public void Metaphone2Test215() { Assert.IsTrue(DoubleMetaphoneTest("penalised", "PNLS", "")); }
        [TestMethod] public void Metaphone2Test216() { Assert.IsTrue(DoubleMetaphoneTest("Lupacchino", "LPXN", "")); }
        [TestMethod] public void Metaphone2Test217() { Assert.IsTrue(DoubleMetaphoneTest("getgid", "KTJT", "KTKT")); }
        [TestMethod] public void Metaphone2Test218() { Assert.IsTrue(DoubleMetaphoneTest("kever", "KFR", "")); }
        [TestMethod] public void Metaphone2Test219() { Assert.IsTrue(DoubleMetaphoneTest("pallavicini", "PLFS", "")); }
        [TestMethod] public void Metaphone2Test220() { Assert.IsTrue(DoubleMetaphoneTest("Pais", "P", "PS")); }
        [TestMethod] public void Metaphone2Test221() { Assert.IsTrue(DoubleMetaphoneTest("youghiogheny", "AKN", "")); }
        [TestMethod] public void Metaphone2Test222() { Assert.IsTrue(DoubleMetaphoneTest("Catherina", "K0RN", "KTRN")); }
        [TestMethod] public void Metaphone2Test223() { Assert.IsTrue(DoubleMetaphoneTest("Givant", "JFNT", "KFNT")); }
        [TestMethod] public void Metaphone2Test224() { Assert.IsTrue(DoubleMetaphoneTest("koffi", "KF", "")); }
        [TestMethod] public void Metaphone2Test225() { Assert.IsTrue(DoubleMetaphoneTest("troutbeck", "TRTP", "")); }
        [TestMethod] public void Metaphone2Test226() { Assert.IsTrue(DoubleMetaphoneTest("moreelse", "MRLS", "")); }
        [TestMethod] public void Metaphone2Test227() { Assert.IsTrue(DoubleMetaphoneTest("seacrest", "SKRS", "")); }
        [TestMethod] public void Metaphone2Test228() { Assert.IsTrue(DoubleMetaphoneTest("ufj", "AFJ", "AF")); }
        [TestMethod] public void Metaphone2Test229() { Assert.IsTrue(DoubleMetaphoneTest("dereferences", "TRFR", "")); }
        [TestMethod] public void Metaphone2Test230() { Assert.IsTrue(DoubleMetaphoneTest("sarena", "SRN", "")); }
        [TestMethod] public void Metaphone2Test231() { Assert.IsTrue(DoubleMetaphoneTest("Kurt", "KRT", "")); }
        [TestMethod] public void Metaphone2Test232() { Assert.IsTrue(DoubleMetaphoneTest("comanche", "KMNX", "KMNK")); }
        [TestMethod] public void Metaphone2Test233() { Assert.IsTrue(DoubleMetaphoneTest("chersoness", "XRSN", "")); }
        [TestMethod] public void Metaphone2Test234() { Assert.IsTrue(DoubleMetaphoneTest("cd", "KT", "")); }
        [TestMethod] public void Metaphone2Test235() { Assert.IsTrue(DoubleMetaphoneTest("merzky", "MRSK", "MRTS")); }
        [TestMethod] public void Metaphone2Test236() { Assert.IsTrue(DoubleMetaphoneTest("Nordsiek", "NRTS", "")); }
        [TestMethod] public void Metaphone2Test237() { Assert.IsTrue(DoubleMetaphoneTest("samus", "SMS", "")); }
        [TestMethod] public void Metaphone2Test238() { Assert.IsTrue(DoubleMetaphoneTest("tougher", "TFR", "")); }
        [TestMethod] public void Metaphone2Test239() { Assert.IsTrue(DoubleMetaphoneTest("monodoc", "MNTK", "")); }
        [TestMethod] public void Metaphone2Test240() { Assert.IsTrue(DoubleMetaphoneTest("deepings", "TPNK", "")); }
        [TestMethod] public void Metaphone2Test241() { Assert.IsTrue(DoubleMetaphoneTest("datel", "TTL", "")); }
        [TestMethod] public void Metaphone2Test242() { Assert.IsTrue(DoubleMetaphoneTest("Stockett", "STKT", "")); }
        [TestMethod] public void Metaphone2Test243() { Assert.IsTrue(DoubleMetaphoneTest("bryum", "PRM", "")); }
        [TestMethod] public void Metaphone2Test244() { Assert.IsTrue(DoubleMetaphoneTest("surveyed", "SRFT", "")); }
        [TestMethod] public void Metaphone2Test245() { Assert.IsTrue(DoubleMetaphoneTest("microcephaly", "MKRS", "")); }
        [TestMethod] public void Metaphone2Test246() { Assert.IsTrue(DoubleMetaphoneTest("trimoxazole", "TRMK", "")); }
        [TestMethod] public void Metaphone2Test247() { Assert.IsTrue(DoubleMetaphoneTest("bastide", "PSTT", "")); }
        [TestMethod] public void Metaphone2Test248() { Assert.IsTrue(DoubleMetaphoneTest("lipo", "LP", "")); }
        [TestMethod] public void Metaphone2Test249() { Assert.IsTrue(DoubleMetaphoneTest("Bosket", "PSKT", "")); }
        [TestMethod] public void Metaphone2Test250() { Assert.IsTrue(DoubleMetaphoneTest("oroms", "ARMS", "")); }
        [TestMethod] public void Metaphone2Test251() { Assert.IsTrue(DoubleMetaphoneTest("vandenburg", "FNTN", "")); }
        [TestMethod] public void Metaphone2Test252() { Assert.IsTrue(DoubleMetaphoneTest("wirtschaftsforschung", "ARTX", "FRTX")); }
        [TestMethod] public void Metaphone2Test253() { Assert.IsTrue(DoubleMetaphoneTest("lilypond", "LLPN", "")); }
        [TestMethod] public void Metaphone2Test254() { Assert.IsTrue(DoubleMetaphoneTest("mouthfeel", "M0FL", "MTFL")); }
        [TestMethod] public void Metaphone2Test255() { Assert.IsTrue(DoubleMetaphoneTest("wwwunibancocombr", "NPNK", "")); }
        [TestMethod] public void Metaphone2Test256() { Assert.IsTrue(DoubleMetaphoneTest("Worster", "ARST", "FRST")); }
        [TestMethod] public void Metaphone2Test257() { Assert.IsTrue(DoubleMetaphoneTest("Ahmad", "AMT", "")); }
        [TestMethod] public void Metaphone2Test258() { Assert.IsTrue(DoubleMetaphoneTest("sweetser", "STSR", "XTSR")); }
        [TestMethod] public void Metaphone2Test259() { Assert.IsTrue(DoubleMetaphoneTest("vsepr", "FSPR", "")); }
        [TestMethod] public void Metaphone2Test260() { Assert.IsTrue(DoubleMetaphoneTest("dput", "TPT", "")); }
        [TestMethod] public void Metaphone2Test261() { Assert.IsTrue(DoubleMetaphoneTest("austlit", "ASTL", "")); }
        [TestMethod] public void Metaphone2Test262() { Assert.IsTrue(DoubleMetaphoneTest("Clemen", "KLMN", "")); }
        [TestMethod] public void Metaphone2Test263() { Assert.IsTrue(DoubleMetaphoneTest("phrva", "FRF", "")); }
        [TestMethod] public void Metaphone2Test264() { Assert.IsTrue(DoubleMetaphoneTest("weipa", "AP", "FP")); }
        [TestMethod] public void Metaphone2Test265() { Assert.IsTrue(DoubleMetaphoneTest("Schrantz", "XRNT", "SRNT")); }
        [TestMethod] public void Metaphone2Test266() { Assert.IsTrue(DoubleMetaphoneTest("meany", "MN", "")); }
        [TestMethod] public void Metaphone2Test267() { Assert.IsTrue(DoubleMetaphoneTest("hodgepodge", "HJPJ", "")); }
        [TestMethod] public void Metaphone2Test268() { Assert.IsTrue(DoubleMetaphoneTest("knuble", "NPL", "")); }
        [TestMethod] public void Metaphone2Test269() { Assert.IsTrue(DoubleMetaphoneTest("caniglia", "KNKL", "KNL")); }
        [TestMethod] public void Metaphone2Test270() { Assert.IsTrue(DoubleMetaphoneTest("blowjobsasics", "PLJP", "")); }
        [TestMethod] public void Metaphone2Test271() { Assert.IsTrue(DoubleMetaphoneTest("flyjacket", "FLJK", "")); }
        [TestMethod] public void Metaphone2Test272() { Assert.IsTrue(DoubleMetaphoneTest("galatian", "KLXN", "")); }
        [TestMethod] public void Metaphone2Test273() { Assert.IsTrue(DoubleMetaphoneTest("hotsel", "HTSL", "")); }
        [TestMethod] public void Metaphone2Test274() { Assert.IsTrue(DoubleMetaphoneTest("autorun", "ATRN", "")); }
        [TestMethod] public void Metaphone2Test275() { Assert.IsTrue(DoubleMetaphoneTest("cocoon", "KKN", "")); }
        [TestMethod] public void Metaphone2Test276() { Assert.IsTrue(DoubleMetaphoneTest("kooks", "KKS", "")); }
        [TestMethod] public void Metaphone2Test277() { Assert.IsTrue(DoubleMetaphoneTest("endocrinol", "ANTK", "")); }
        [TestMethod] public void Metaphone2Test278() { Assert.IsTrue(DoubleMetaphoneTest("mesages", "MSJS", "MSKS")); }
        [TestMethod] public void Metaphone2Test279() { Assert.IsTrue(DoubleMetaphoneTest("Disney", "TSN", "")); }
        [TestMethod] public void Metaphone2Test280() { Assert.IsTrue(DoubleMetaphoneTest("speedline", "SPTL", "")); }
        [TestMethod] public void Metaphone2Test281() { Assert.IsTrue(DoubleMetaphoneTest("gabaldon", "KPLT", "")); }
        [TestMethod] public void Metaphone2Test282() { Assert.IsTrue(DoubleMetaphoneTest("margaux", "MRK", "")); }
        [TestMethod] public void Metaphone2Test283() { Assert.IsTrue(DoubleMetaphoneTest("housecalls", "HSKL", "")); }
        [TestMethod] public void Metaphone2Test284() { Assert.IsTrue(DoubleMetaphoneTest("siltation", "SLTX", "")); }
        [TestMethod] public void Metaphone2Test285() { Assert.IsTrue(DoubleMetaphoneTest("automatic", "ATMT", "")); }
        [TestMethod] public void Metaphone2Test286() { Assert.IsTrue(DoubleMetaphoneTest("freakshow", "FRKX", "")); }
        [TestMethod] public void Metaphone2Test287() { Assert.IsTrue(DoubleMetaphoneTest("gorojovsky", "KRJF", "")); }
        [TestMethod] public void Metaphone2Test288() { Assert.IsTrue(DoubleMetaphoneTest("milwaukie", "MLK", "")); }
        [TestMethod] public void Metaphone2Test289() { Assert.IsTrue(DoubleMetaphoneTest("wwwgap", "KP", "")); }
        [TestMethod] public void Metaphone2Test290() { Assert.IsTrue(DoubleMetaphoneTest("autm", "ATM", "")); }
        [TestMethod] public void Metaphone2Test291() { Assert.IsTrue(DoubleMetaphoneTest("borromini", "PRMN", "")); }
        [TestMethod] public void Metaphone2Test292() { Assert.IsTrue(DoubleMetaphoneTest("zpp", "SP", "")); }
        [TestMethod] public void Metaphone2Test293() { Assert.IsTrue(DoubleMetaphoneTest("Penovich", "PNFX", "PNFK")); }
        [TestMethod] public void Metaphone2Test294() { Assert.IsTrue(DoubleMetaphoneTest("domine", "TMN", "")); }
        [TestMethod] public void Metaphone2Test295() { Assert.IsTrue(DoubleMetaphoneTest("caves", "KFS", "")); }
        [TestMethod] public void Metaphone2Test296() { Assert.IsTrue(DoubleMetaphoneTest("uato", "AT", "")); }
        [TestMethod] public void Metaphone2Test297() { Assert.IsTrue(DoubleMetaphoneTest("tiltonsville", "TLTN", "")); }
        [TestMethod] public void Metaphone2Test298() { Assert.IsTrue(DoubleMetaphoneTest("Ken", "KN", "")); }
        [TestMethod] public void Metaphone2Test299() { Assert.IsTrue(DoubleMetaphoneTest("Delonais", "TLN", "TLNS")); }
        [TestMethod] public void Metaphone2Test300() { Assert.IsTrue(DoubleMetaphoneTest("conniption", "KNPX", "")); }
        [TestMethod] public void Metaphone2Test301() { Assert.IsTrue(DoubleMetaphoneTest("Wenske", "ANSK", "FNSK")); }
        [TestMethod] public void Metaphone2Test302() { Assert.IsTrue(DoubleMetaphoneTest("cautery", "KTR", "")); }
        [TestMethod] public void Metaphone2Test303() { Assert.IsTrue(DoubleMetaphoneTest("barbourville", "PRPR", "")); }
        [TestMethod] public void Metaphone2Test304() { Assert.IsTrue(DoubleMetaphoneTest("departamentos", "TPRT", "")); }
        [TestMethod] public void Metaphone2Test305() { Assert.IsTrue(DoubleMetaphoneTest("weaponry", "APNR", "FPNR")); }
        [TestMethod] public void Metaphone2Test306() { Assert.IsTrue(DoubleMetaphoneTest("Haggett", "HKT", "")); }
        [TestMethod] public void Metaphone2Test307() { Assert.IsTrue(DoubleMetaphoneTest("martinville", "MRTN", "")); }
        [TestMethod] public void Metaphone2Test308() { Assert.IsTrue(DoubleMetaphoneTest("stina", "STN", "")); }
        [TestMethod] public void Metaphone2Test309() { Assert.IsTrue(DoubleMetaphoneTest("Rubottom", "RPTM", "")); }
        [TestMethod] public void Metaphone2Test310() { Assert.IsTrue(DoubleMetaphoneTest("Soyke", "SK", "")); }
        [TestMethod] public void Metaphone2Test311() { Assert.IsTrue(DoubleMetaphoneTest("corse", "KRS", "")); }
        [TestMethod] public void Metaphone2Test312() { Assert.IsTrue(DoubleMetaphoneTest("totalling", "TTLN", "")); }
        [TestMethod] public void Metaphone2Test313() { Assert.IsTrue(DoubleMetaphoneTest("kuppam", "KPM", "")); }
        [TestMethod] public void Metaphone2Test314() { Assert.IsTrue(DoubleMetaphoneTest("ftpadmin", "FTPT", "")); }
        [TestMethod] public void Metaphone2Test315() { Assert.IsTrue(DoubleMetaphoneTest("Forst", "FRST", "")); }
        [TestMethod] public void Metaphone2Test316() { Assert.IsTrue(DoubleMetaphoneTest("Ashauer", "AXR", "")); }
        [TestMethod] public void Metaphone2Test317() { Assert.IsTrue(DoubleMetaphoneTest("ashtanga", "AXTN", "")); }
        [TestMethod] public void Metaphone2Test318() { Assert.IsTrue(DoubleMetaphoneTest("alonissos", "ALNS", "")); }
        [TestMethod] public void Metaphone2Test319() { Assert.IsTrue(DoubleMetaphoneTest("Chimilio", "XML", "")); }
        [TestMethod] public void Metaphone2Test320() { Assert.IsTrue(DoubleMetaphoneTest("deafbazon", "TFPS", "")); }
        [TestMethod] public void Metaphone2Test321() { Assert.IsTrue(DoubleMetaphoneTest("psmb", "SMP", "")); }
        [TestMethod] public void Metaphone2Test322() { Assert.IsTrue(DoubleMetaphoneTest("Ferraraccio", "FRRX", "")); }
        [TestMethod] public void Metaphone2Test323() { Assert.IsTrue(DoubleMetaphoneTest("fractionated", "FRKX", "")); }
        [TestMethod] public void Metaphone2Test324() { Assert.IsTrue(DoubleMetaphoneTest("rrd", "RT", "")); }
        [TestMethod] public void Metaphone2Test325() { Assert.IsTrue(DoubleMetaphoneTest("luminosities", "LMNS", "")); }
        [TestMethod] public void Metaphone2Test326() { Assert.IsTrue(DoubleMetaphoneTest("Platzer", "PLTS", "")); }
        [TestMethod] public void Metaphone2Test327() { Assert.IsTrue(DoubleMetaphoneTest("modulator", "MTLT", "")); }
        [TestMethod] public void Metaphone2Test328() { Assert.IsTrue(DoubleMetaphoneTest("tyneside", "TNST", "")); }
        [TestMethod] public void Metaphone2Test329() { Assert.IsTrue(DoubleMetaphoneTest("nonuser", "NNSR", "")); }
        [TestMethod] public void Metaphone2Test330() { Assert.IsTrue(DoubleMetaphoneTest("haspel", "HSPL", "")); }
        [TestMethod] public void Metaphone2Test331() { Assert.IsTrue(DoubleMetaphoneTest("cortex", "KRTK", "")); }
        [TestMethod] public void Metaphone2Test332() { Assert.IsTrue(DoubleMetaphoneTest("vechicle", "FXKL", "FKKL")); }
        [TestMethod] public void Metaphone2Test333() { Assert.IsTrue(DoubleMetaphoneTest("epinions", "APNN", "")); }
        [TestMethod] public void Metaphone2Test334() { Assert.IsTrue(DoubleMetaphoneTest("wwwusmintgov", "SMNT", "")); }
        [TestMethod] public void Metaphone2Test335() { Assert.IsTrue(DoubleMetaphoneTest("katies", "KTS", "")); }
        [TestMethod] public void Metaphone2Test336() { Assert.IsTrue(DoubleMetaphoneTest("aminosalicylic", "AMNS", "")); }
        [TestMethod] public void Metaphone2Test337() { Assert.IsTrue(DoubleMetaphoneTest("mmegi", "MJ", "MK")); }
        [TestMethod] public void Metaphone2Test338() { Assert.IsTrue(DoubleMetaphoneTest("sbir", "SPR", "")); }
        [TestMethod] public void Metaphone2Test339() { Assert.IsTrue(DoubleMetaphoneTest("learned", "LRNT", "")); }
        [TestMethod] public void Metaphone2Test340() { Assert.IsTrue(DoubleMetaphoneTest("supris", "SPRS", "")); }
        [TestMethod] public void Metaphone2Test341() { Assert.IsTrue(DoubleMetaphoneTest("mozarteum", "MSRT", "")); }
        [TestMethod] public void Metaphone2Test342() { Assert.IsTrue(DoubleMetaphoneTest("selzer", "SLSR", "")); }
        [TestMethod] public void Metaphone2Test343() { Assert.IsTrue(DoubleMetaphoneTest("tmug", "TMK", "")); }
        [TestMethod] public void Metaphone2Test344() { Assert.IsTrue(DoubleMetaphoneTest("Kisto", "KST", "")); }
        [TestMethod] public void Metaphone2Test345() { Assert.IsTrue(DoubleMetaphoneTest("iib", "AP", "")); }
        [TestMethod] public void Metaphone2Test346() { Assert.IsTrue(DoubleMetaphoneTest("wwwincredimail", "NKRT", "")); }
        [TestMethod] public void Metaphone2Test347() { Assert.IsTrue(DoubleMetaphoneTest("izpack", "ASPK", "ATSP")); }
        [TestMethod] public void Metaphone2Test348() { Assert.IsTrue(DoubleMetaphoneTest("gaymovie", "KMF", "")); }
        [TestMethod] public void Metaphone2Test349() { Assert.IsTrue(DoubleMetaphoneTest("Buchholz", "PKLS", "")); }
        [TestMethod] public void Metaphone2Test350() { Assert.IsTrue(DoubleMetaphoneTest("culcairn", "KLKR", "")); }
        [TestMethod] public void Metaphone2Test351() { Assert.IsTrue(DoubleMetaphoneTest("barys", "PRS", "")); }
        [TestMethod] public void Metaphone2Test352() { Assert.IsTrue(DoubleMetaphoneTest("burets", "PRTS", "")); }
        [TestMethod] public void Metaphone2Test353() { Assert.IsTrue(DoubleMetaphoneTest("Sorce", "SRS", "")); }
        [TestMethod] public void Metaphone2Test354() { Assert.IsTrue(DoubleMetaphoneTest("chimique", "XMK", "")); }
        [TestMethod] public void Metaphone2Test355() { Assert.IsTrue(DoubleMetaphoneTest("kitada", "KTT", "")); }
        [TestMethod] public void Metaphone2Test356() { Assert.IsTrue(DoubleMetaphoneTest("Engeman", "ANJM", "ANKM")); }
        [TestMethod] public void Metaphone2Test357() { Assert.IsTrue(DoubleMetaphoneTest("raveendran", "RFNT", "")); }
        [TestMethod] public void Metaphone2Test358() { Assert.IsTrue(DoubleMetaphoneTest("Bendele", "PNTL", "")); }
        [TestMethod] public void Metaphone2Test359() { Assert.IsTrue(DoubleMetaphoneTest("Pawlitschek", "PLTX", "")); }
        [TestMethod] public void Metaphone2Test360() { Assert.IsTrue(DoubleMetaphoneTest("hogfather", "HKF0", "HKFT")); }
        [TestMethod] public void Metaphone2Test361() { Assert.IsTrue(DoubleMetaphoneTest("eyedrum", "ATRM", "")); }
        [TestMethod] public void Metaphone2Test362() { Assert.IsTrue(DoubleMetaphoneTest("Ferrara", "FRR", "")); }
        [TestMethod] public void Metaphone2Test363() { Assert.IsTrue(DoubleMetaphoneTest("zhuh", "J", "")); }
        [TestMethod] public void Metaphone2Test364() { Assert.IsTrue(DoubleMetaphoneTest("zodiak", "STK", "")); }
        [TestMethod] public void Metaphone2Test365() { Assert.IsTrue(DoubleMetaphoneTest("pchcom", "PXKM", "PKKM")); }
        [TestMethod] public void Metaphone2Test366() { Assert.IsTrue(DoubleMetaphoneTest("conferees", "KNFR", "")); }
        [TestMethod] public void Metaphone2Test367() { Assert.IsTrue(DoubleMetaphoneTest("Decillis", "TSLS", "")); }
        [TestMethod] public void Metaphone2Test368() { Assert.IsTrue(DoubleMetaphoneTest("downloar", "TNLR", "")); }
        [TestMethod] public void Metaphone2Test369() { Assert.IsTrue(DoubleMetaphoneTest("shard", "XRT", "")); }
        [TestMethod] public void Metaphone2Test370() { Assert.IsTrue(DoubleMetaphoneTest("fajr", "FJR", "")); }
        [TestMethod] public void Metaphone2Test371() { Assert.IsTrue(DoubleMetaphoneTest("quisque", "KSK", "")); }
        [TestMethod] public void Metaphone2Test372() { Assert.IsTrue(DoubleMetaphoneTest("winterizing", "ANTR", "FNTR")); }
        [TestMethod] public void Metaphone2Test373() { Assert.IsTrue(DoubleMetaphoneTest("referate", "RFRT", "")); }
        [TestMethod] public void Metaphone2Test374() { Assert.IsTrue(DoubleMetaphoneTest("nuxone", "NKSN", "")); }
        [TestMethod] public void Metaphone2Test375() { Assert.IsTrue(DoubleMetaphoneTest("Racheal", "RXL", "RKL")); }
        [TestMethod] public void Metaphone2Test376() { Assert.IsTrue(DoubleMetaphoneTest("bizben", "PSPN", "")); }
        [TestMethod] public void Metaphone2Test377() { Assert.IsTrue(DoubleMetaphoneTest("musictalk", "MSKT", "")); }
        [TestMethod] public void Metaphone2Test378() { Assert.IsTrue(DoubleMetaphoneTest("ogoal", "AKL", "")); }
        [TestMethod] public void Metaphone2Test379() { Assert.IsTrue(DoubleMetaphoneTest("Skoff", "SKF", "")); }
        [TestMethod] public void Metaphone2Test380() { Assert.IsTrue(DoubleMetaphoneTest("Seehusen", "SHSN", "")); }
        [TestMethod] public void Metaphone2Test381() { Assert.IsTrue(DoubleMetaphoneTest("Reim", "RM", "")); }
        [TestMethod] public void Metaphone2Test382() { Assert.IsTrue(DoubleMetaphoneTest("Yoh", "A", "")); }
        [TestMethod] public void Metaphone2Test383() { Assert.IsTrue(DoubleMetaphoneTest("gapi", "KP", "")); }
        [TestMethod] public void Metaphone2Test384() { Assert.IsTrue(DoubleMetaphoneTest("Brightbill", "PRTP", "")); }
        [TestMethod] public void Metaphone2Test385() { Assert.IsTrue(DoubleMetaphoneTest("shuey", "X", "")); }
        [TestMethod] public void Metaphone2Test386() { Assert.IsTrue(DoubleMetaphoneTest("posium", "PSM", "")); }
        [TestMethod] public void Metaphone2Test387() { Assert.IsTrue(DoubleMetaphoneTest("Falknor", "FLKN", "")); }
        [TestMethod] public void Metaphone2Test388() { Assert.IsTrue(DoubleMetaphoneTest("ucat", "AKT", "")); }
        [TestMethod] public void Metaphone2Test389() { Assert.IsTrue(DoubleMetaphoneTest("properspace", "PRPR", "")); }
        [TestMethod] public void Metaphone2Test390() { Assert.IsTrue(DoubleMetaphoneTest("showimg", "XMK", "")); }
        [TestMethod] public void Metaphone2Test391() { Assert.IsTrue(DoubleMetaphoneTest("Montecillo", "MNTS", "")); }
        [TestMethod] public void Metaphone2Test392() { Assert.IsTrue(DoubleMetaphoneTest("sajak", "SJK", "")); }
        [TestMethod] public void Metaphone2Test393() { Assert.IsTrue(DoubleMetaphoneTest("maturbation", "MTRP", "")); }
        [TestMethod] public void Metaphone2Test394() { Assert.IsTrue(DoubleMetaphoneTest("Lettie", "LT", "")); }
        [TestMethod] public void Metaphone2Test395() { Assert.IsTrue(DoubleMetaphoneTest("clauss", "KLS", "")); }
        [TestMethod] public void Metaphone2Test396() { Assert.IsTrue(DoubleMetaphoneTest("scheiber", "XPR", "")); }
        [TestMethod] public void Metaphone2Test397() { Assert.IsTrue(DoubleMetaphoneTest("matp", "MTP", "")); }
        [TestMethod] public void Metaphone2Test398() { Assert.IsTrue(DoubleMetaphoneTest("mervtormel", "MRFT", "")); }
        [TestMethod] public void Metaphone2Test399() { Assert.IsTrue(DoubleMetaphoneTest("guanahani", "KNHN", "")); }
        [TestMethod] public void Metaphone2Test400() { Assert.IsTrue(DoubleMetaphoneTest("citement", "STMN", "")); }
        [TestMethod] public void Metaphone2Test401() { Assert.IsTrue(DoubleMetaphoneTest("immu", "AM", "")); }
        [TestMethod] public void Metaphone2Test402() { Assert.IsTrue(DoubleMetaphoneTest("virulence", "FRLN", "")); }
        [TestMethod] public void Metaphone2Test403() { Assert.IsTrue(DoubleMetaphoneTest("kussa", "KS", "")); }
        [TestMethod] public void Metaphone2Test404() { Assert.IsTrue(DoubleMetaphoneTest("gso", "KS", "")); }
        [TestMethod] public void Metaphone2Test405() { Assert.IsTrue(DoubleMetaphoneTest("webviajes", "APFJ", "FPFJ")); }
        [TestMethod] public void Metaphone2Test406() { Assert.IsTrue(DoubleMetaphoneTest("ldwork", "LTRK", "")); }
        [TestMethod] public void Metaphone2Test407() { Assert.IsTrue(DoubleMetaphoneTest("verses", "FRSS", "")); }
        [TestMethod] public void Metaphone2Test408() { Assert.IsTrue(DoubleMetaphoneTest("sondes", "SNTS", "")); }
        [TestMethod] public void Metaphone2Test409() { Assert.IsTrue(DoubleMetaphoneTest("freshpair", "FRXP", "")); }
        [TestMethod] public void Metaphone2Test410() { Assert.IsTrue(DoubleMetaphoneTest("licorne", "LKRN", "")); }
        [TestMethod] public void Metaphone2Test411() { Assert.IsTrue(DoubleMetaphoneTest("Vanis", "FNS", "")); }
        [TestMethod] public void Metaphone2Test412() { Assert.IsTrue(DoubleMetaphoneTest("Buena", "PN", "")); }
        [TestMethod] public void Metaphone2Test413() { Assert.IsTrue(DoubleMetaphoneTest("Tauares", "TRS", "")); }
        [TestMethod] public void Metaphone2Test414() { Assert.IsTrue(DoubleMetaphoneTest("ikus", "AKS", "")); }
        [TestMethod] public void Metaphone2Test415() { Assert.IsTrue(DoubleMetaphoneTest("genrebox", "JNRP", "KNRP")); }
        [TestMethod] public void Metaphone2Test416() { Assert.IsTrue(DoubleMetaphoneTest("rth", "R0", "RT")); }
        [TestMethod] public void Metaphone2Test417() { Assert.IsTrue(DoubleMetaphoneTest("Spaun", "SPN", "")); }
        [TestMethod] public void Metaphone2Test418() { Assert.IsTrue(DoubleMetaphoneTest("wiersbe", "ARSP", "FRSP")); }
        [TestMethod] public void Metaphone2Test419() { Assert.IsTrue(DoubleMetaphoneTest("dad", "TT", "")); }
        [TestMethod] public void Metaphone2Test420() { Assert.IsTrue(DoubleMetaphoneTest("tus", "TS", "")); }
        [TestMethod] public void Metaphone2Test421() { Assert.IsTrue(DoubleMetaphoneTest("Weidert", "ATRT", "FTRT")); }
        [TestMethod] public void Metaphone2Test422() { Assert.IsTrue(DoubleMetaphoneTest("rijke", "RK", "")); }
        [TestMethod] public void Metaphone2Test423() { Assert.IsTrue(DoubleMetaphoneTest("fischbein", "FXPN", "")); }
        [TestMethod] public void Metaphone2Test424() { Assert.IsTrue(DoubleMetaphoneTest("fbeye", "FP", "")); }
        [TestMethod] public void Metaphone2Test425() { Assert.IsTrue(DoubleMetaphoneTest("hagerty", "HKRT", "HJRT")); }
        [TestMethod] public void Metaphone2Test426() { Assert.IsTrue(DoubleMetaphoneTest("Hollendonner", "HLNT", "")); }
        [TestMethod] public void Metaphone2Test427() { Assert.IsTrue(DoubleMetaphoneTest("Huitzacua", "HTSK", "")); }
        [TestMethod] public void Metaphone2Test428() { Assert.IsTrue(DoubleMetaphoneTest("subjunctive", "SPJN", "")); }
        [TestMethod] public void Metaphone2Test429() { Assert.IsTrue(DoubleMetaphoneTest("implored", "AMPL", "")); }
        [TestMethod] public void Metaphone2Test430() { Assert.IsTrue(DoubleMetaphoneTest("pompeius", "PMPS", "")); }
        [TestMethod] public void Metaphone2Test431() { Assert.IsTrue(DoubleMetaphoneTest("afleet", "AFLT", "")); }
        [TestMethod] public void Metaphone2Test432() { Assert.IsTrue(DoubleMetaphoneTest("iacc", "AK", "")); }
        [TestMethod] public void Metaphone2Test433() { Assert.IsTrue(DoubleMetaphoneTest("sabalos", "SPLS", "")); }
        [TestMethod] public void Metaphone2Test434() { Assert.IsTrue(DoubleMetaphoneTest("Abdi", "APT", "")); }
        [TestMethod] public void Metaphone2Test435() { Assert.IsTrue(DoubleMetaphoneTest("microinsurance", "MKRN", "")); }
        [TestMethod] public void Metaphone2Test436() { Assert.IsTrue(DoubleMetaphoneTest("audiobook", "ATPK", "")); }
        [TestMethod] public void Metaphone2Test437() { Assert.IsTrue(DoubleMetaphoneTest("fulpmes", "FLPM", "")); }
        [TestMethod] public void Metaphone2Test438() { Assert.IsTrue(DoubleMetaphoneTest("registreren", "RJST", "RKST")); }
        [TestMethod] public void Metaphone2Test439() { Assert.IsTrue(DoubleMetaphoneTest("megapath", "MKP0", "MKPT")); }
        [TestMethod] public void Metaphone2Test440() { Assert.IsTrue(DoubleMetaphoneTest("prestidigitation", "PRST", "")); }
        [TestMethod] public void Metaphone2Test441() { Assert.IsTrue(DoubleMetaphoneTest("wby", "P", "")); }
        [TestMethod] public void Metaphone2Test442() { Assert.IsTrue(DoubleMetaphoneTest("vorschau", "FRX", "")); }
        [TestMethod] public void Metaphone2Test443() { Assert.IsTrue(DoubleMetaphoneTest("Albertha", "ALPR", "")); }
        [TestMethod] public void Metaphone2Test444() { Assert.IsTrue(DoubleMetaphoneTest("aspalpha", "ASPL", "")); }
        [TestMethod] public void Metaphone2Test445() { Assert.IsTrue(DoubleMetaphoneTest("Belden", "PLTN", "")); }
        [TestMethod] public void Metaphone2Test446() { Assert.IsTrue(DoubleMetaphoneTest("deterministic", "TTRM", "")); }
        [TestMethod] public void Metaphone2Test447() { Assert.IsTrue(DoubleMetaphoneTest("philosophique", "FLSF", "")); }
        [TestMethod] public void Metaphone2Test448() { Assert.IsTrue(DoubleMetaphoneTest("kleinen", "KLNN", "")); }
        [TestMethod] public void Metaphone2Test449() { Assert.IsTrue(DoubleMetaphoneTest("logouri", "LKR", "")); }
        [TestMethod] public void Metaphone2Test450() { Assert.IsTrue(DoubleMetaphoneTest("xbl", "SPL", "")); }
        [TestMethod] public void Metaphone2Test451() { Assert.IsTrue(DoubleMetaphoneTest("iz", "AS", "")); }
        [TestMethod] public void Metaphone2Test452() { Assert.IsTrue(DoubleMetaphoneTest("throckmorton", "0RKM", "TRKM")); }
        [TestMethod] public void Metaphone2Test453() { Assert.IsTrue(DoubleMetaphoneTest("condesa", "KNTS", "")); }
        [TestMethod] public void Metaphone2Test454() { Assert.IsTrue(DoubleMetaphoneTest("Mook", "MK", "")); }
        [TestMethod] public void Metaphone2Test455() { Assert.IsTrue(DoubleMetaphoneTest("medseek", "MTSK", "")); }
        [TestMethod] public void Metaphone2Test456() { Assert.IsTrue(DoubleMetaphoneTest("chugalug", "XKLK", "")); }
        [TestMethod] public void Metaphone2Test457() { Assert.IsTrue(DoubleMetaphoneTest("olms", "ALMS", "")); }
        [TestMethod] public void Metaphone2Test458() { Assert.IsTrue(DoubleMetaphoneTest("bogo", "PK", "")); }
        [TestMethod] public void Metaphone2Test459() { Assert.IsTrue(DoubleMetaphoneTest("essing", "ASNK", "")); }
        [TestMethod] public void Metaphone2Test460() { Assert.IsTrue(DoubleMetaphoneTest("rarden", "RRTN", "")); }
        [TestMethod] public void Metaphone2Test461() { Assert.IsTrue(DoubleMetaphoneTest("mittlere", "MTLR", "")); }
        [TestMethod] public void Metaphone2Test462() { Assert.IsTrue(DoubleMetaphoneTest("Borsa", "PRS", "")); }
        [TestMethod] public void Metaphone2Test463() { Assert.IsTrue(DoubleMetaphoneTest("Ainslie", "ANSL", "")); }
        [TestMethod] public void Metaphone2Test464() { Assert.IsTrue(DoubleMetaphoneTest("Ganska", "KNSK", "")); }
        [TestMethod] public void Metaphone2Test465() { Assert.IsTrue(DoubleMetaphoneTest("miv", "MF", "")); }
        [TestMethod] public void Metaphone2Test466() { Assert.IsTrue(DoubleMetaphoneTest("concessions", "KNSS", "")); }
        [TestMethod] public void Metaphone2Test467() { Assert.IsTrue(DoubleMetaphoneTest("distinguished", "TSTN", "")); }
        [TestMethod] public void Metaphone2Test468() { Assert.IsTrue(DoubleMetaphoneTest("cano", "KN", "")); }
        [TestMethod] public void Metaphone2Test469() { Assert.IsTrue(DoubleMetaphoneTest("plumper", "PLMP", "")); }
        [TestMethod] public void Metaphone2Test470() { Assert.IsTrue(DoubleMetaphoneTest("mindoro", "MNTR", "")); }
        [TestMethod] public void Metaphone2Test471() { Assert.IsTrue(DoubleMetaphoneTest("cephalopod", "SFLP", "")); }
        [TestMethod] public void Metaphone2Test472() { Assert.IsTrue(DoubleMetaphoneTest("Klunk", "KLNK", "")); }
        [TestMethod] public void Metaphone2Test473() { Assert.IsTrue(DoubleMetaphoneTest("Bumbrey", "PMPR", "")); }
        [TestMethod] public void Metaphone2Test474() { Assert.IsTrue(DoubleMetaphoneTest("causeless", "KSLS", "")); }
        [TestMethod] public void Metaphone2Test475() { Assert.IsTrue(DoubleMetaphoneTest("Lothrop", "L0RP", "LTRP")); }
        [TestMethod] public void Metaphone2Test476() { Assert.IsTrue(DoubleMetaphoneTest("bodystyles", "PTST", "")); }
        [TestMethod] public void Metaphone2Test477() { Assert.IsTrue(DoubleMetaphoneTest("beaatiality", "PXLT", "")); }
        [TestMethod] public void Metaphone2Test478() { Assert.IsTrue(DoubleMetaphoneTest("Bobrowski", "PPRS", "PPRF")); }
        [TestMethod] public void Metaphone2Test479() { Assert.IsTrue(DoubleMetaphoneTest("erudition", "ARTX", "")); }
        [TestMethod] public void Metaphone2Test480() { Assert.IsTrue(DoubleMetaphoneTest("huttner", "HTNR", "")); }
        [TestMethod] public void Metaphone2Test481() { Assert.IsTrue(DoubleMetaphoneTest("wwwaskjeevescom", "SKFS", "")); }
        [TestMethod] public void Metaphone2Test482() { Assert.IsTrue(DoubleMetaphoneTest("Duross", "TRS", "")); }
        [TestMethod] public void Metaphone2Test483() { Assert.IsTrue(DoubleMetaphoneTest("Colemen", "KLMN", "")); }
        [TestMethod] public void Metaphone2Test484() { Assert.IsTrue(DoubleMetaphoneTest("Duncomb", "TNKM", "")); }
        [TestMethod] public void Metaphone2Test485() { Assert.IsTrue(DoubleMetaphoneTest("tripe", "TRP", "")); }
        [TestMethod] public void Metaphone2Test486() { Assert.IsTrue(DoubleMetaphoneTest("dorrigo", "TRK", "")); }
        [TestMethod] public void Metaphone2Test487() { Assert.IsTrue(DoubleMetaphoneTest("Mascall", "MSKL", "")); }
        [TestMethod] public void Metaphone2Test488() { Assert.IsTrue(DoubleMetaphoneTest("jetplane", "JTPL", "ATPL")); }
        [TestMethod] public void Metaphone2Test489() { Assert.IsTrue(DoubleMetaphoneTest("nswrl", "NSRL", "")); }
        [TestMethod] public void Metaphone2Test490() { Assert.IsTrue(DoubleMetaphoneTest("didates", "TTTS", "")); }
        [TestMethod] public void Metaphone2Test491() { Assert.IsTrue(DoubleMetaphoneTest("Jena", "JN", "AN")); }
        [TestMethod] public void Metaphone2Test492() { Assert.IsTrue(DoubleMetaphoneTest("kctu", "KKT", "")); }
        [TestMethod] public void Metaphone2Test493() { Assert.IsTrue(DoubleMetaphoneTest("cualquiera", "KLKR", "")); }
        [TestMethod] public void Metaphone2Test494() { Assert.IsTrue(DoubleMetaphoneTest("plutella", "PLTL", "")); }
        [TestMethod] public void Metaphone2Test495() { Assert.IsTrue(DoubleMetaphoneTest("Liebig", "LPK", "")); }
        [TestMethod] public void Metaphone2Test496() { Assert.IsTrue(DoubleMetaphoneTest("Llorens", "LRNS", "")); }
        [TestMethod] public void Metaphone2Test497() { Assert.IsTrue(DoubleMetaphoneTest("mraz", "MRS", "")); }
        [TestMethod] public void Metaphone2Test498() { Assert.IsTrue(DoubleMetaphoneTest("shadyac", "XTK", "")); }
        [TestMethod] public void Metaphone2Test499() { Assert.IsTrue(DoubleMetaphoneTest("lossphentermine", "LSFN", "")); }
        [TestMethod] public void Metaphone2Test500() { Assert.IsTrue(DoubleMetaphoneTest("Dreith", "TR0", "TRT")); }
        [TestMethod] public void Metaphone2Test501() { Assert.IsTrue(DoubleMetaphoneTest("Windsor", "ANTS", "FNTS")); }

    }
}