using Element34.StringMetrics;

namespace Element34Tests.Phonetic
{
    [TestClass]
    public class Metaphone1Tests
    {
        private bool MetaphoneTest(string sInput, string sExpected)
        {
            Metaphone metaphone = new Metaphone();
            return metaphone.Encode(sInput) == sExpected;
        }

        [TestMethod] public void MetaphoneTest001() { Assert.IsTrue(MetaphoneTest("communication", "C38368")); }
        [TestMethod] public void MetaphoneTest002() { Assert.IsTrue(MetaphoneTest("worships", "W9313")); }
        [TestMethod] public void MetaphoneTest003() { Assert.IsTrue(MetaphoneTest("televisionhome", "T67238")); }
        [TestMethod] public void MetaphoneTest004() { Assert.IsTrue(MetaphoneTest("bumi", "B18")); }
        [TestMethod] public void MetaphoneTest005() { Assert.IsTrue(MetaphoneTest("shortbread", "S396196")); }
        [TestMethod] public void MetaphoneTest006() { Assert.IsTrue(MetaphoneTest("slice", "S373")); }
        [TestMethod] public void MetaphoneTest007() { Assert.IsTrue(MetaphoneTest("reint", "R986")); }
        [TestMethod] public void MetaphoneTest008() { Assert.IsTrue(MetaphoneTest("Florence", "F27983")); }
        [TestMethod] public void MetaphoneTest009() { Assert.IsTrue(MetaphoneTest("fawzi", "F25")); }
        [TestMethod] public void MetaphoneTest010() { Assert.IsTrue(MetaphoneTest("sname", "S38")); }
        [TestMethod] public void MetaphoneTest011() { Assert.IsTrue(MetaphoneTest("modano", "M868")); }
        [TestMethod] public void MetaphoneTest012() { Assert.IsTrue(MetaphoneTest("stumpage", "S36814")); }
        [TestMethod] public void MetaphoneTest013() { Assert.IsTrue(MetaphoneTest("clears", "C3793")); }
        [TestMethod] public void MetaphoneTest014() { Assert.IsTrue(MetaphoneTest("ciods", "C363")); }
        [TestMethod] public void MetaphoneTest015() { Assert.IsTrue(MetaphoneTest("deseos", "D63")); }
        [TestMethod] public void MetaphoneTest016() { Assert.IsTrue(MetaphoneTest("dippin", "D618")); }
        [TestMethod] public void MetaphoneTest017() { Assert.IsTrue(MetaphoneTest("aranna", "A98")); }
        [TestMethod] public void MetaphoneTest018() { Assert.IsTrue(MetaphoneTest("borse", "B193")); }
        [TestMethod] public void MetaphoneTest019() { Assert.IsTrue(MetaphoneTest("subic", "S313")); }
        [TestMethod] public void MetaphoneTest020() { Assert.IsTrue(MetaphoneTest("Vidrio", "V269")); }
        [TestMethod] public void MetaphoneTest021() { Assert.IsTrue(MetaphoneTest("inserters", "I839693")); }
        [TestMethod] public void MetaphoneTest022() { Assert.IsTrue(MetaphoneTest("perature", "P1969")); }
        [TestMethod] public void MetaphoneTest023() { Assert.IsTrue(MetaphoneTest("msacideas", "M8363")); }
        [TestMethod] public void MetaphoneTest024() { Assert.IsTrue(MetaphoneTest("cougs", "C343")); }
        [TestMethod] public void MetaphoneTest025() { Assert.IsTrue(MetaphoneTest("kittens", "K3683")); }
        [TestMethod] public void MetaphoneTest026() { Assert.IsTrue(MetaphoneTest("imperiously", "I81937")); }
        [TestMethod] public void MetaphoneTest027() { Assert.IsTrue(MetaphoneTest("boccanegra", "B13849")); }
        [TestMethod] public void MetaphoneTest028() { Assert.IsTrue(MetaphoneTest("sextet", "S356")); }
        [TestMethod] public void MetaphoneTest029() { Assert.IsTrue(MetaphoneTest("setattributes", "S369163")); }
        [TestMethod] public void MetaphoneTest030() { Assert.IsTrue(MetaphoneTest("dsnt", "D6386")); }
        [TestMethod] public void MetaphoneTest031() { Assert.IsTrue(MetaphoneTest("chubby", "C31")); }
        [TestMethod] public void MetaphoneTest032() { Assert.IsTrue(MetaphoneTest("ooda", "O6")); }
        [TestMethod] public void MetaphoneTest033() { Assert.IsTrue(MetaphoneTest("Bressman", "B1938")); }
        [TestMethod] public void MetaphoneTest034() { Assert.IsTrue(MetaphoneTest("calendarnew", "C378698")); }
        [TestMethod] public void MetaphoneTest035() { Assert.IsTrue(MetaphoneTest("duhon", "D68")); }
        [TestMethod] public void MetaphoneTest036() { Assert.IsTrue(MetaphoneTest("nchen", "N838")); }
        [TestMethod] public void MetaphoneTest037() { Assert.IsTrue(MetaphoneTest("betjemans", "B16483")); }
        [TestMethod] public void MetaphoneTest038() { Assert.IsTrue(MetaphoneTest("Mangum", "M848")); }
        [TestMethod] public void MetaphoneTest039() { Assert.IsTrue(MetaphoneTest("cabac", "C313")); }
        [TestMethod] public void MetaphoneTest040() { Assert.IsTrue(MetaphoneTest("pantys", "P1863")); }
        [TestMethod] public void MetaphoneTest041() { Assert.IsTrue(MetaphoneTest("cofactors", "C323693")); }
        [TestMethod] public void MetaphoneTest042() { Assert.IsTrue(MetaphoneTest("clickz", "C3735")); }
        [TestMethod] public void MetaphoneTest043() { Assert.IsTrue(MetaphoneTest("chiap", "C31")); }
        [TestMethod] public void MetaphoneTest044() { Assert.IsTrue(MetaphoneTest("Dalpiaz", "D6715")); }
        [TestMethod] public void MetaphoneTest045() { Assert.IsTrue(MetaphoneTest("philosophically", "P173137")); }
        [TestMethod] public void MetaphoneTest046() { Assert.IsTrue(MetaphoneTest("backfill", "B1327")); }
        [TestMethod] public void MetaphoneTest047() { Assert.IsTrue(MetaphoneTest("Murders", "M89693")); }
        [TestMethod] public void MetaphoneTest048() { Assert.IsTrue(MetaphoneTest("ecartis", "E3963")); }
        [TestMethod] public void MetaphoneTest049() { Assert.IsTrue(MetaphoneTest("vede", "V26")); }
        [TestMethod] public void MetaphoneTest050() { Assert.IsTrue(MetaphoneTest("usoe", "U3")); }
        [TestMethod] public void MetaphoneTest051() { Assert.IsTrue(MetaphoneTest("ostara", "O369")); }
        [TestMethod] public void MetaphoneTest052() { Assert.IsTrue(MetaphoneTest("labourer", "L719")); }
        [TestMethod] public void MetaphoneTest053() { Assert.IsTrue(MetaphoneTest("speir", "S319")); }
        [TestMethod] public void MetaphoneTest054() { Assert.IsTrue(MetaphoneTest("durchaus", "D693")); }
        [TestMethod] public void MetaphoneTest055() { Assert.IsTrue(MetaphoneTest("inetformfiller", "I86298279")); }
        [TestMethod] public void MetaphoneTest056() { Assert.IsTrue(MetaphoneTest("itrs", "I693")); }
        [TestMethod] public void MetaphoneTest057() { Assert.IsTrue(MetaphoneTest("Tennant", "T686")); }
        [TestMethod] public void MetaphoneTest058() { Assert.IsTrue(MetaphoneTest("bashore", "B139")); }
        [TestMethod] public void MetaphoneTest059() { Assert.IsTrue(MetaphoneTest("lemurian", "L7898")); }
        [TestMethod] public void MetaphoneTest060() { Assert.IsTrue(MetaphoneTest("dungannon", "D6848")); }
        [TestMethod] public void MetaphoneTest061() { Assert.IsTrue(MetaphoneTest("epl", "E17")); }
        [TestMethod] public void MetaphoneTest062() { Assert.IsTrue(MetaphoneTest("grader", "G4969")); }
        [TestMethod] public void MetaphoneTest063() { Assert.IsTrue(MetaphoneTest("synchronise", "S383983")); }
        [TestMethod] public void MetaphoneTest064() { Assert.IsTrue(MetaphoneTest("gondorian", "G48698")); }
        [TestMethod] public void MetaphoneTest065() { Assert.IsTrue(MetaphoneTest("cvnet", "C3286")); }
        [TestMethod] public void MetaphoneTest066() { Assert.IsTrue(MetaphoneTest("Centers", "C38693")); }
        [TestMethod] public void MetaphoneTest067() { Assert.IsTrue(MetaphoneTest("soaks", "S3")); }
        [TestMethod] public void MetaphoneTest068() { Assert.IsTrue(MetaphoneTest("gogllle", "G47")); }
        [TestMethod] public void MetaphoneTest069() { Assert.IsTrue(MetaphoneTest("peotone", "P168")); }
        [TestMethod] public void MetaphoneTest070() { Assert.IsTrue(MetaphoneTest("Sharp", "S391")); }
        [TestMethod] public void MetaphoneTest071() { Assert.IsTrue(MetaphoneTest("mawer", "M89")); }
        [TestMethod] public void MetaphoneTest072() { Assert.IsTrue(MetaphoneTest("Morasca", "M893")); }
        [TestMethod] public void MetaphoneTest073() { Assert.IsTrue(MetaphoneTest("ticknor", "T6389")); }
        [TestMethod] public void MetaphoneTest074() { Assert.IsTrue(MetaphoneTest("beaverdale", "B12967")); }
        [TestMethod] public void MetaphoneTest075() { Assert.IsTrue(MetaphoneTest("caledonianew", "C3768")); }
        [TestMethod] public void MetaphoneTest076() { Assert.IsTrue(MetaphoneTest("wellnessdicke", "W78363")); }
        [TestMethod] public void MetaphoneTest077() { Assert.IsTrue(MetaphoneTest("Rodin", "R968")); }
        [TestMethod] public void MetaphoneTest078() { Assert.IsTrue(MetaphoneTest("bluffer", "B1729")); }
        [TestMethod] public void MetaphoneTest079() { Assert.IsTrue(MetaphoneTest("joey", "J4")); }
        [TestMethod] public void MetaphoneTest080() { Assert.IsTrue(MetaphoneTest("unbekannter", "U813869")); }
        [TestMethod] public void MetaphoneTest081() { Assert.IsTrue(MetaphoneTest("Baylor", "B179")); }
        [TestMethod] public void MetaphoneTest082() { Assert.IsTrue(MetaphoneTest("striplib", "S369171")); }
        [TestMethod] public void MetaphoneTest083() { Assert.IsTrue(MetaphoneTest("boquete", "B156")); }
        [TestMethod] public void MetaphoneTest084() { Assert.IsTrue(MetaphoneTest("geylang", "G4784")); }
        [TestMethod] public void MetaphoneTest085() { Assert.IsTrue(MetaphoneTest("Lavi", "L72")); }
        [TestMethod] public void MetaphoneTest086() { Assert.IsTrue(MetaphoneTest("moldovans", "M876283")); }
        [TestMethod] public void MetaphoneTest087() { Assert.IsTrue(MetaphoneTest("linq", "L785")); }
        [TestMethod] public void MetaphoneTest088() { Assert.IsTrue(MetaphoneTest("Kenworthy", "K3896")); }
        [TestMethod] public void MetaphoneTest089() { Assert.IsTrue(MetaphoneTest("Steckman", "S3638")); }
        [TestMethod] public void MetaphoneTest090() { Assert.IsTrue(MetaphoneTest("czechoslovakian", "C3537238")); }
        [TestMethod] public void MetaphoneTest091() { Assert.IsTrue(MetaphoneTest("marmora", "M8989")); }
        [TestMethod] public void MetaphoneTest092() { Assert.IsTrue(MetaphoneTest("Carvill", "C3927")); }
        [TestMethod] public void MetaphoneTest093() { Assert.IsTrue(MetaphoneTest("chihiro", "C39")); }
        [TestMethod] public void MetaphoneTest094() { Assert.IsTrue(MetaphoneTest("hctc", "H363")); }
        [TestMethod] public void MetaphoneTest095() { Assert.IsTrue(MetaphoneTest("nolde", "N876")); }
        [TestMethod] public void MetaphoneTest096() { Assert.IsTrue(MetaphoneTest("aerosolized", "A93756")); }
        [TestMethod] public void MetaphoneTest097() { Assert.IsTrue(MetaphoneTest("canterbury", "C386919")); }
        [TestMethod] public void MetaphoneTest098() { Assert.IsTrue(MetaphoneTest("jss", "J43")); }
        [TestMethod] public void MetaphoneTest099() { Assert.IsTrue(MetaphoneTest("rmn", "R98")); }
        [TestMethod] public void MetaphoneTest100() { Assert.IsTrue(MetaphoneTest("mazlish", "M8573")); }
        [TestMethod] public void MetaphoneTest101() { Assert.IsTrue(MetaphoneTest("faites", "F263")); }
        [TestMethod] public void MetaphoneTest102() { Assert.IsTrue(MetaphoneTest("foyer", "F29")); }
        [TestMethod] public void MetaphoneTest103() { Assert.IsTrue(MetaphoneTest("ductions", "D63683")); }
        [TestMethod] public void MetaphoneTest104() { Assert.IsTrue(MetaphoneTest("Rambo", "R981")); }
        [TestMethod] public void MetaphoneTest105() { Assert.IsTrue(MetaphoneTest("Curnutte", "C3986")); }
        [TestMethod] public void MetaphoneTest106() { Assert.IsTrue(MetaphoneTest("Feltus", "F2763")); }
        [TestMethod] public void MetaphoneTest107() { Assert.IsTrue(MetaphoneTest("forbairt", "F29196")); }
        [TestMethod] public void MetaphoneTest108() { Assert.IsTrue(MetaphoneTest("southerners", "S369893")); }
        [TestMethod] public void MetaphoneTest109() { Assert.IsTrue(MetaphoneTest("hypnotists", "H186363")); }
        [TestMethod] public void MetaphoneTest110() { Assert.IsTrue(MetaphoneTest("euphony", "E18")); }
        [TestMethod] public void MetaphoneTest111() { Assert.IsTrue(MetaphoneTest("mhpa", "M81")); }
        [TestMethod] public void MetaphoneTest112() { Assert.IsTrue(MetaphoneTest("matteotti", "M86")); }
        [TestMethod] public void MetaphoneTest113() { Assert.IsTrue(MetaphoneTest("Klande", "K3786")); }
        [TestMethod] public void MetaphoneTest114() { Assert.IsTrue(MetaphoneTest("Trudgeon", "T69648")); }
        [TestMethod] public void MetaphoneTest115() { Assert.IsTrue(MetaphoneTest("schoolhill", "S37")); }
        [TestMethod] public void MetaphoneTest116() { Assert.IsTrue(MetaphoneTest("equalizer", "E5759")); }
        [TestMethod] public void MetaphoneTest117() { Assert.IsTrue(MetaphoneTest("xnet", "X586")); }
        [TestMethod] public void MetaphoneTest118() { Assert.IsTrue(MetaphoneTest("Thell", "T67")); }
        [TestMethod] public void MetaphoneTest119() { Assert.IsTrue(MetaphoneTest("Canel", "C387")); }
        [TestMethod] public void MetaphoneTest120() { Assert.IsTrue(MetaphoneTest("vmetro", "V2869")); }
        [TestMethod] public void MetaphoneTest121() { Assert.IsTrue(MetaphoneTest("burgtheater", "B19469")); }
        [TestMethod] public void MetaphoneTest122() { Assert.IsTrue(MetaphoneTest("Berlinger", "B197849")); }
        [TestMethod] public void MetaphoneTest123() { Assert.IsTrue(MetaphoneTest("crehan", "C398")); }
        [TestMethod] public void MetaphoneTest124() { Assert.IsTrue(MetaphoneTest("abysses", "A13")); }
        [TestMethod] public void MetaphoneTest125() { Assert.IsTrue(MetaphoneTest("Hipolito", "H176")); }
        [TestMethod] public void MetaphoneTest126() { Assert.IsTrue(MetaphoneTest("splintered", "S3178696")); }
        [TestMethod] public void MetaphoneTest127() { Assert.IsTrue(MetaphoneTest("maintenace", "M8683")); }
        [TestMethod] public void MetaphoneTest128() { Assert.IsTrue(MetaphoneTest("decency", "D6383")); }
        [TestMethod] public void MetaphoneTest129() { Assert.IsTrue(MetaphoneTest("quantz", "Q5865")); }
        [TestMethod] public void MetaphoneTest130() { Assert.IsTrue(MetaphoneTest("wette", "W6")); }
        [TestMethod] public void MetaphoneTest131() { Assert.IsTrue(MetaphoneTest("Feary", "F29")); }
        [TestMethod] public void MetaphoneTest132() { Assert.IsTrue(MetaphoneTest("Cuchiara", "C39")); }
        [TestMethod] public void MetaphoneTest133() { Assert.IsTrue(MetaphoneTest("Arbon", "A918")); }
        [TestMethod] public void MetaphoneTest134() { Assert.IsTrue(MetaphoneTest("shyness", "S383")); }
        [TestMethod] public void MetaphoneTest135() { Assert.IsTrue(MetaphoneTest("Salin", "S378")); }
        [TestMethod] public void MetaphoneTest136() { Assert.IsTrue(MetaphoneTest("Zicafoose", "Z5323")); }
        [TestMethod] public void MetaphoneTest137() { Assert.IsTrue(MetaphoneTest("Menn", "M8")); }
        [TestMethod] public void MetaphoneTest138() { Assert.IsTrue(MetaphoneTest("funker", "F2839")); }
        [TestMethod] public void MetaphoneTest139() { Assert.IsTrue(MetaphoneTest("santillan", "S38678")); }
        [TestMethod] public void MetaphoneTest140() { Assert.IsTrue(MetaphoneTest("punani", "P18")); }
        [TestMethod] public void MetaphoneTest141() { Assert.IsTrue(MetaphoneTest("basa", "B13")); }
        [TestMethod] public void MetaphoneTest142() { Assert.IsTrue(MetaphoneTest("bluefin", "B1728")); }
        [TestMethod] public void MetaphoneTest143() { Assert.IsTrue(MetaphoneTest("cc", "C3")); }
        [TestMethod] public void MetaphoneTest144() { Assert.IsTrue(MetaphoneTest("zipgenius", "Z51483")); }
        [TestMethod] public void MetaphoneTest145() { Assert.IsTrue(MetaphoneTest("Kirchen", "K3938")); }
        [TestMethod] public void MetaphoneTest146() { Assert.IsTrue(MetaphoneTest("commentaar", "C3869")); }
        [TestMethod] public void MetaphoneTest147() { Assert.IsTrue(MetaphoneTest("expansive", "E51832")); }
        [TestMethod] public void MetaphoneTest148() { Assert.IsTrue(MetaphoneTest("castlebar", "C36719")); }
        [TestMethod] public void MetaphoneTest149() { Assert.IsTrue(MetaphoneTest("lft", "L726")); }
        [TestMethod] public void MetaphoneTest150() { Assert.IsTrue(MetaphoneTest("robla", "R917")); }
        [TestMethod] public void MetaphoneTest151() { Assert.IsTrue(MetaphoneTest("zarontin", "Z59868")); }
        [TestMethod] public void MetaphoneTest152() { Assert.IsTrue(MetaphoneTest("nawc", "N83")); }
        [TestMethod] public void MetaphoneTest153() { Assert.IsTrue(MetaphoneTest("resolvconf", "R9372382")); }
        [TestMethod] public void MetaphoneTest154() { Assert.IsTrue(MetaphoneTest("networker", "N86939")); }
        [TestMethod] public void MetaphoneTest155() { Assert.IsTrue(MetaphoneTest("airlins", "A9783")); }
        [TestMethod] public void MetaphoneTest156() { Assert.IsTrue(MetaphoneTest("Piskel", "P137")); }
        [TestMethod] public void MetaphoneTest157() { Assert.IsTrue(MetaphoneTest("hilson", "H738")); }
        [TestMethod] public void MetaphoneTest158() { Assert.IsTrue(MetaphoneTest("deco", "D63")); }
        [TestMethod] public void MetaphoneTest159() { Assert.IsTrue(MetaphoneTest("cents", "C3863")); }
        [TestMethod] public void MetaphoneTest160() { Assert.IsTrue(MetaphoneTest("award", "A96")); }
        [TestMethod] public void MetaphoneTest161() { Assert.IsTrue(MetaphoneTest("reykjanes", "R93483")); }
        [TestMethod] public void MetaphoneTest162() { Assert.IsTrue(MetaphoneTest("perona", "P198")); }
        [TestMethod] public void MetaphoneTest163() { Assert.IsTrue(MetaphoneTest("epistle", "E1367")); }
        [TestMethod] public void MetaphoneTest164() { Assert.IsTrue(MetaphoneTest("insound", "I8386")); }
        [TestMethod] public void MetaphoneTest165() { Assert.IsTrue(MetaphoneTest("qantas", "Q5863")); }
        [TestMethod] public void MetaphoneTest166() { Assert.IsTrue(MetaphoneTest("wholey", "W7")); }
        [TestMethod] public void MetaphoneTest167() { Assert.IsTrue(MetaphoneTest("aragona", "A948")); }
        [TestMethod] public void MetaphoneTest168() { Assert.IsTrue(MetaphoneTest("Vancheri", "V2839")); }
        [TestMethod] public void MetaphoneTest169() { Assert.IsTrue(MetaphoneTest("allocution", "A7368")); }
        [TestMethod] public void MetaphoneTest170() { Assert.IsTrue(MetaphoneTest("volodya", "V276")); }
        [TestMethod] public void MetaphoneTest171() { Assert.IsTrue(MetaphoneTest("enunciate", "E836")); }
        [TestMethod] public void MetaphoneTest172() { Assert.IsTrue(MetaphoneTest("uuuu", "U")); }
        [TestMethod] public void MetaphoneTest173() { Assert.IsTrue(MetaphoneTest("Louato", "L76")); }
        [TestMethod] public void MetaphoneTest174() { Assert.IsTrue(MetaphoneTest("Marquitta", "M8956")); }
        [TestMethod] public void MetaphoneTest175() { Assert.IsTrue(MetaphoneTest("surmountable", "S398617")); }
        [TestMethod] public void MetaphoneTest176() { Assert.IsTrue(MetaphoneTest("gaultier", "G4769")); }
        [TestMethod] public void MetaphoneTest177() { Assert.IsTrue(MetaphoneTest("dafoe", "D62")); }
        [TestMethod] public void MetaphoneTest178() { Assert.IsTrue(MetaphoneTest("Claudio", "C376")); }
        [TestMethod] public void MetaphoneTest179() { Assert.IsTrue(MetaphoneTest("ritva", "R962")); }
        [TestMethod] public void MetaphoneTest180() { Assert.IsTrue(MetaphoneTest("spunky", "S3183")); }
        [TestMethod] public void MetaphoneTest181() { Assert.IsTrue(MetaphoneTest("npov", "N812")); }
        [TestMethod] public void MetaphoneTest182() { Assert.IsTrue(MetaphoneTest("eurythmics", "E9683")); }
        [TestMethod] public void MetaphoneTest183() { Assert.IsTrue(MetaphoneTest("skittish", "S363")); }
        [TestMethod] public void MetaphoneTest184() { Assert.IsTrue(MetaphoneTest("scooter", "S369")); }
        [TestMethod] public void MetaphoneTest185() { Assert.IsTrue(MetaphoneTest("unfermented", "U82986")); }
        [TestMethod] public void MetaphoneTest186() { Assert.IsTrue(MetaphoneTest("kerridge", "K3964")); }
        [TestMethod] public void MetaphoneTest187() { Assert.IsTrue(MetaphoneTest("scenography", "S38491")); }
        [TestMethod] public void MetaphoneTest188() { Assert.IsTrue(MetaphoneTest("sahalee", "S37")); }
        [TestMethod] public void MetaphoneTest189() { Assert.IsTrue(MetaphoneTest("spooktacular", "S3136379")); }
        [TestMethod] public void MetaphoneTest190() { Assert.IsTrue(MetaphoneTest("boissons", "B1383")); }
        [TestMethod] public void MetaphoneTest191() { Assert.IsTrue(MetaphoneTest("arbete", "A916")); }
        [TestMethod] public void MetaphoneTest192() { Assert.IsTrue(MetaphoneTest("Norrick", "N893")); }
        [TestMethod] public void MetaphoneTest193() { Assert.IsTrue(MetaphoneTest("Sonnier", "S389")); }
        [TestMethod] public void MetaphoneTest194() { Assert.IsTrue(MetaphoneTest("gnomeui", "G48")); }
        [TestMethod] public void MetaphoneTest195() { Assert.IsTrue(MetaphoneTest("milian", "M878")); }
        [TestMethod] public void MetaphoneTest196() { Assert.IsTrue(MetaphoneTest("blackplanetcom", "B173178638")); }
        [TestMethod] public void MetaphoneTest197() { Assert.IsTrue(MetaphoneTest("tuned", "T686")); }
        [TestMethod] public void MetaphoneTest198() { Assert.IsTrue(MetaphoneTest("Salone", "S378")); }
        [TestMethod] public void MetaphoneTest199() { Assert.IsTrue(MetaphoneTest("marathon", "M8968")); }
        [TestMethod] public void MetaphoneTest200() { Assert.IsTrue(MetaphoneTest("layoffs", "L723")); }
        [TestMethod] public void MetaphoneTest201() { Assert.IsTrue(MetaphoneTest("hotek", "H63")); }
        [TestMethod] public void MetaphoneTest202() { Assert.IsTrue(MetaphoneTest("emme", "E8")); }
        [TestMethod] public void MetaphoneTest203() { Assert.IsTrue(MetaphoneTest("amarasinghe", "A89384")); }
        [TestMethod] public void MetaphoneTest204() { Assert.IsTrue(MetaphoneTest("midas", "M863")); }
        [TestMethod] public void MetaphoneTest205() { Assert.IsTrue(MetaphoneTest("inhaltsangabe", "I8763841")); }
        [TestMethod] public void MetaphoneTest206() { Assert.IsTrue(MetaphoneTest("smow", "S38")); }
        [TestMethod] public void MetaphoneTest207() { Assert.IsTrue(MetaphoneTest("policing", "P17384")); }
        [TestMethod] public void MetaphoneTest208() { Assert.IsTrue(MetaphoneTest("usmf", "U382")); }
        [TestMethod] public void MetaphoneTest209() { Assert.IsTrue(MetaphoneTest("inferred", "I8296")); }
        [TestMethod] public void MetaphoneTest210() { Assert.IsTrue(MetaphoneTest("Eaglen", "E478")); }
        [TestMethod] public void MetaphoneTest211() { Assert.IsTrue(MetaphoneTest("dralle", "D697")); }
        [TestMethod] public void MetaphoneTest212() { Assert.IsTrue(MetaphoneTest("kalmus", "K3783")); }
        [TestMethod] public void MetaphoneTest213() { Assert.IsTrue(MetaphoneTest("nork", "N893")); }
        [TestMethod] public void MetaphoneTest214() { Assert.IsTrue(MetaphoneTest("Waterston", "W69368")); }
        [TestMethod] public void MetaphoneTest215() { Assert.IsTrue(MetaphoneTest("penalised", "P18736")); }
        [TestMethod] public void MetaphoneTest216() { Assert.IsTrue(MetaphoneTest("Lupacchino", "L7138")); }
        [TestMethod] public void MetaphoneTest217() { Assert.IsTrue(MetaphoneTest("getgid", "G4646")); }
        [TestMethod] public void MetaphoneTest218() { Assert.IsTrue(MetaphoneTest("kever", "K329")); }
        [TestMethod] public void MetaphoneTest219() { Assert.IsTrue(MetaphoneTest("pallavicini", "P17238")); }
        [TestMethod] public void MetaphoneTest220() { Assert.IsTrue(MetaphoneTest("Pais", "P13")); }
        [TestMethod] public void MetaphoneTest221() { Assert.IsTrue(MetaphoneTest("youghiogheny", "Y48")); }
        [TestMethod] public void MetaphoneTest222() { Assert.IsTrue(MetaphoneTest("Catherina", "C3698")); }
        [TestMethod] public void MetaphoneTest223() { Assert.IsTrue(MetaphoneTest("Givant", "G4286")); }
        [TestMethod] public void MetaphoneTest224() { Assert.IsTrue(MetaphoneTest("koffi", "K32")); }
        [TestMethod] public void MetaphoneTest225() { Assert.IsTrue(MetaphoneTest("troutbeck", "T69613")); }
        [TestMethod] public void MetaphoneTest226() { Assert.IsTrue(MetaphoneTest("moreelse", "M8973")); }
        [TestMethod] public void MetaphoneTest227() { Assert.IsTrue(MetaphoneTest("seacrest", "S3936")); }
        [TestMethod] public void MetaphoneTest228() { Assert.IsTrue(MetaphoneTest("ufj", "U24")); }
        [TestMethod] public void MetaphoneTest229() { Assert.IsTrue(MetaphoneTest("dereferences", "D692983")); }
        [TestMethod] public void MetaphoneTest230() { Assert.IsTrue(MetaphoneTest("sarena", "S398")); }
        [TestMethod] public void MetaphoneTest231() { Assert.IsTrue(MetaphoneTest("Kurt", "K396")); }
        [TestMethod] public void MetaphoneTest232() { Assert.IsTrue(MetaphoneTest("comanche", "C383")); }
        [TestMethod] public void MetaphoneTest233() { Assert.IsTrue(MetaphoneTest("chersoness", "C39383")); }
        [TestMethod] public void MetaphoneTest234() { Assert.IsTrue(MetaphoneTest("cd", "C36")); }
        [TestMethod] public void MetaphoneTest235() { Assert.IsTrue(MetaphoneTest("merzky", "M8953")); }
        [TestMethod] public void MetaphoneTest236() { Assert.IsTrue(MetaphoneTest("Nordsiek", "N8963")); }
        [TestMethod] public void MetaphoneTest237() { Assert.IsTrue(MetaphoneTest("samus", "S383")); }
        [TestMethod] public void MetaphoneTest238() { Assert.IsTrue(MetaphoneTest("tougher", "T649")); }
        [TestMethod] public void MetaphoneTest239() { Assert.IsTrue(MetaphoneTest("monodoc", "M863")); }
        [TestMethod] public void MetaphoneTest240() { Assert.IsTrue(MetaphoneTest("deepings", "D61843")); }
        [TestMethod] public void MetaphoneTest241() { Assert.IsTrue(MetaphoneTest("datel", "D67")); }
        [TestMethod] public void MetaphoneTest242() { Assert.IsTrue(MetaphoneTest("Stockett", "S3636")); }
        [TestMethod] public void MetaphoneTest243() { Assert.IsTrue(MetaphoneTest("bryum", "B198")); }
        [TestMethod] public void MetaphoneTest244() { Assert.IsTrue(MetaphoneTest("surveyed", "S3926")); }
        [TestMethod] public void MetaphoneTest245() { Assert.IsTrue(MetaphoneTest("microcephaly", "M839317")); }
        [TestMethod] public void MetaphoneTest246() { Assert.IsTrue(MetaphoneTest("trimoxazole", "T69857")); }
        [TestMethod] public void MetaphoneTest247() { Assert.IsTrue(MetaphoneTest("bastide", "B136")); }
        [TestMethod] public void MetaphoneTest248() { Assert.IsTrue(MetaphoneTest("lipo", "L71")); }
        [TestMethod] public void MetaphoneTest249() { Assert.IsTrue(MetaphoneTest("Bosket", "B136")); }
        [TestMethod] public void MetaphoneTest250() { Assert.IsTrue(MetaphoneTest("oroms", "O983")); }
        [TestMethod] public void MetaphoneTest251() { Assert.IsTrue(MetaphoneTest("vandenburg", "V2868194")); }
        [TestMethod] public void MetaphoneTest252() { Assert.IsTrue(MetaphoneTest("wirtschaftsforschung", "W96326329384")); }
        [TestMethod] public void MetaphoneTest253() { Assert.IsTrue(MetaphoneTest("lilypond", "L7186")); }
        [TestMethod] public void MetaphoneTest254() { Assert.IsTrue(MetaphoneTest("mouthfeel", "M8627")); }
        [TestMethod] public void MetaphoneTest255() { Assert.IsTrue(MetaphoneTest("wwwunibancocombr", "W8183819")); }
        [TestMethod] public void MetaphoneTest256() { Assert.IsTrue(MetaphoneTest("Worster", "W9369")); }
        [TestMethod] public void MetaphoneTest257() { Assert.IsTrue(MetaphoneTest("Ahmad", "A86")); }
        [TestMethod] public void MetaphoneTest258() { Assert.IsTrue(MetaphoneTest("sweetser", "S3639")); }
        [TestMethod] public void MetaphoneTest259() { Assert.IsTrue(MetaphoneTest("vsepr", "V2319")); }
        [TestMethod] public void MetaphoneTest260() { Assert.IsTrue(MetaphoneTest("dput", "D616")); }
        [TestMethod] public void MetaphoneTest261() { Assert.IsTrue(MetaphoneTest("austlit", "A3676")); }
        [TestMethod] public void MetaphoneTest262() { Assert.IsTrue(MetaphoneTest("Clemen", "C378")); }
        [TestMethod] public void MetaphoneTest263() { Assert.IsTrue(MetaphoneTest("phrva", "P192")); }
        [TestMethod] public void MetaphoneTest264() { Assert.IsTrue(MetaphoneTest("weipa", "W1")); }
        [TestMethod] public void MetaphoneTest265() { Assert.IsTrue(MetaphoneTest("Schrantz", "S39865")); }
        [TestMethod] public void MetaphoneTest266() { Assert.IsTrue(MetaphoneTest("meany", "M8")); }
        [TestMethod] public void MetaphoneTest267() { Assert.IsTrue(MetaphoneTest("hodgepodge", "H64164")); }
        [TestMethod] public void MetaphoneTest268() { Assert.IsTrue(MetaphoneTest("knuble", "K3817")); }
        [TestMethod] public void MetaphoneTest269() { Assert.IsTrue(MetaphoneTest("caniglia", "C3847")); }
        [TestMethod] public void MetaphoneTest270() { Assert.IsTrue(MetaphoneTest("blowjobsasics", "B17413")); }
        [TestMethod] public void MetaphoneTest271() { Assert.IsTrue(MetaphoneTest("flyjacket", "F27436")); }
        [TestMethod] public void MetaphoneTest272() { Assert.IsTrue(MetaphoneTest("galatian", "G4768")); }
        [TestMethod] public void MetaphoneTest273() { Assert.IsTrue(MetaphoneTest("hotsel", "H637")); }
        [TestMethod] public void MetaphoneTest274() { Assert.IsTrue(MetaphoneTest("autorun", "A698")); }
        [TestMethod] public void MetaphoneTest275() { Assert.IsTrue(MetaphoneTest("cocoon", "C38")); }
        [TestMethod] public void MetaphoneTest276() { Assert.IsTrue(MetaphoneTest("kooks", "K3")); }
        [TestMethod] public void MetaphoneTest277() { Assert.IsTrue(MetaphoneTest("endocrinol", "E863987")); }
        [TestMethod] public void MetaphoneTest278() { Assert.IsTrue(MetaphoneTest("mesages", "M8343")); }
        [TestMethod] public void MetaphoneTest279() { Assert.IsTrue(MetaphoneTest("Disney", "D638")); }
        [TestMethod] public void MetaphoneTest280() { Assert.IsTrue(MetaphoneTest("speedline", "S31678")); }
        [TestMethod] public void MetaphoneTest281() { Assert.IsTrue(MetaphoneTest("gabaldon", "G41768")); }
        [TestMethod] public void MetaphoneTest282() { Assert.IsTrue(MetaphoneTest("margaux", "M8945")); }
        [TestMethod] public void MetaphoneTest283() { Assert.IsTrue(MetaphoneTest("housecalls", "H373")); }
        [TestMethod] public void MetaphoneTest284() { Assert.IsTrue(MetaphoneTest("siltation", "S3768")); }
        [TestMethod] public void MetaphoneTest285() { Assert.IsTrue(MetaphoneTest("automatic", "A6863")); }
        [TestMethod] public void MetaphoneTest286() { Assert.IsTrue(MetaphoneTest("freakshow", "F293")); }
        [TestMethod] public void MetaphoneTest287() { Assert.IsTrue(MetaphoneTest("gorojovsky", "G49423")); }
        [TestMethod] public void MetaphoneTest288() { Assert.IsTrue(MetaphoneTest("milwaukie", "M873")); }
        [TestMethod] public void MetaphoneTest289() { Assert.IsTrue(MetaphoneTest("wwwgap", "W41")); }
        [TestMethod] public void MetaphoneTest290() { Assert.IsTrue(MetaphoneTest("autm", "A68")); }
        [TestMethod] public void MetaphoneTest291() { Assert.IsTrue(MetaphoneTest("borromini", "B198")); }
        [TestMethod] public void MetaphoneTest292() { Assert.IsTrue(MetaphoneTest("zpp", "Z51")); }
        [TestMethod] public void MetaphoneTest293() { Assert.IsTrue(MetaphoneTest("Penovich", "P1823")); }
        [TestMethod] public void MetaphoneTest294() { Assert.IsTrue(MetaphoneTest("domine", "D68")); }
        [TestMethod] public void MetaphoneTest295() { Assert.IsTrue(MetaphoneTest("caves", "C323")); }
        [TestMethod] public void MetaphoneTest296() { Assert.IsTrue(MetaphoneTest("uato", "U6")); }
        [TestMethod] public void MetaphoneTest297() { Assert.IsTrue(MetaphoneTest("tiltonsville", "T6768327")); }
        [TestMethod] public void MetaphoneTest298() { Assert.IsTrue(MetaphoneTest("Ken", "K38")); }
        [TestMethod] public void MetaphoneTest299() { Assert.IsTrue(MetaphoneTest("Delonais", "D6783")); }
        [TestMethod] public void MetaphoneTest300() { Assert.IsTrue(MetaphoneTest("conniption", "C38168")); }
        [TestMethod] public void MetaphoneTest301() { Assert.IsTrue(MetaphoneTest("Wenske", "W83")); }
        [TestMethod] public void MetaphoneTest302() { Assert.IsTrue(MetaphoneTest("cautery", "C369")); }
        [TestMethod] public void MetaphoneTest303() { Assert.IsTrue(MetaphoneTest("barbourville", "B191927")); }
        [TestMethod] public void MetaphoneTest304() { Assert.IsTrue(MetaphoneTest("departamentos", "D6196863")); }
        [TestMethod] public void MetaphoneTest305() { Assert.IsTrue(MetaphoneTest("weaponry", "W189")); }
        [TestMethod] public void MetaphoneTest306() { Assert.IsTrue(MetaphoneTest("Haggett", "H46")); }
        [TestMethod] public void MetaphoneTest307() { Assert.IsTrue(MetaphoneTest("martinville", "M896827")); }
        [TestMethod] public void MetaphoneTest308() { Assert.IsTrue(MetaphoneTest("stina", "S368")); }
        [TestMethod] public void MetaphoneTest309() { Assert.IsTrue(MetaphoneTest("Rubottom", "R9168")); }
        [TestMethod] public void MetaphoneTest310() { Assert.IsTrue(MetaphoneTest("Soyke", "S3")); }
        [TestMethod] public void MetaphoneTest311() { Assert.IsTrue(MetaphoneTest("corse", "C393")); }
        [TestMethod] public void MetaphoneTest312() { Assert.IsTrue(MetaphoneTest("totalling", "T6784")); }
        [TestMethod] public void MetaphoneTest313() { Assert.IsTrue(MetaphoneTest("kuppam", "K318")); }
        [TestMethod] public void MetaphoneTest314() { Assert.IsTrue(MetaphoneTest("ftpadmin", "F26168")); }
        [TestMethod] public void MetaphoneTest315() { Assert.IsTrue(MetaphoneTest("Forst", "F2936")); }
        [TestMethod] public void MetaphoneTest316() { Assert.IsTrue(MetaphoneTest("Ashauer", "A39")); }
        [TestMethod] public void MetaphoneTest317() { Assert.IsTrue(MetaphoneTest("ashtanga", "A3684")); }
        [TestMethod] public void MetaphoneTest318() { Assert.IsTrue(MetaphoneTest("alonissos", "A783")); }
        [TestMethod] public void MetaphoneTest319() { Assert.IsTrue(MetaphoneTest("Chimilio", "C387")); }
        [TestMethod] public void MetaphoneTest320() { Assert.IsTrue(MetaphoneTest("deafbazon", "D62158")); }
        [TestMethod] public void MetaphoneTest321() { Assert.IsTrue(MetaphoneTest("psmb", "P1381")); }
        [TestMethod] public void MetaphoneTest322() { Assert.IsTrue(MetaphoneTest("Ferraraccio", "F293")); }
        [TestMethod] public void MetaphoneTest323() { Assert.IsTrue(MetaphoneTest("fractionated", "F293686")); }
        [TestMethod] public void MetaphoneTest324() { Assert.IsTrue(MetaphoneTest("rrd", "R96")); }
        [TestMethod] public void MetaphoneTest325() { Assert.IsTrue(MetaphoneTest("luminosities", "L78363")); }
        [TestMethod] public void MetaphoneTest326() { Assert.IsTrue(MetaphoneTest("Platzer", "P17659")); }
        [TestMethod] public void MetaphoneTest327() { Assert.IsTrue(MetaphoneTest("modulator", "M86769")); }
        [TestMethod] public void MetaphoneTest328() { Assert.IsTrue(MetaphoneTest("tyneside", "T6836")); }
        [TestMethod] public void MetaphoneTest329() { Assert.IsTrue(MetaphoneTest("nonuser", "N839")); }
        [TestMethod] public void MetaphoneTest330() { Assert.IsTrue(MetaphoneTest("haspel", "H317")); }
        [TestMethod] public void MetaphoneTest331() { Assert.IsTrue(MetaphoneTest("cortex", "C3965")); }
        [TestMethod] public void MetaphoneTest332() { Assert.IsTrue(MetaphoneTest("vechicle", "V237")); }
        [TestMethod] public void MetaphoneTest333() { Assert.IsTrue(MetaphoneTest("epinions", "E183")); }
        [TestMethod] public void MetaphoneTest334() { Assert.IsTrue(MetaphoneTest("wwwusmintgov", "W38642")); }
        [TestMethod] public void MetaphoneTest335() { Assert.IsTrue(MetaphoneTest("katies", "K363")); }
        [TestMethod] public void MetaphoneTest336() { Assert.IsTrue(MetaphoneTest("aminosalicylic", "A837373")); }
        [TestMethod] public void MetaphoneTest337() { Assert.IsTrue(MetaphoneTest("mmegi", "M84")); }
        [TestMethod] public void MetaphoneTest338() { Assert.IsTrue(MetaphoneTest("sbir", "S319")); }
        [TestMethod] public void MetaphoneTest339() { Assert.IsTrue(MetaphoneTest("learned", "L7986")); }
        [TestMethod] public void MetaphoneTest340() { Assert.IsTrue(MetaphoneTest("supris", "S3193")); }
        [TestMethod] public void MetaphoneTest341() { Assert.IsTrue(MetaphoneTest("mozarteum", "M85968")); }
        [TestMethod] public void MetaphoneTest342() { Assert.IsTrue(MetaphoneTest("selzer", "S3759")); }
        [TestMethod] public void MetaphoneTest343() { Assert.IsTrue(MetaphoneTest("tmug", "T684")); }
        [TestMethod] public void MetaphoneTest344() { Assert.IsTrue(MetaphoneTest("Kisto", "K36")); }
        [TestMethod] public void MetaphoneTest345() { Assert.IsTrue(MetaphoneTest("iib", "I1")); }
        [TestMethod] public void MetaphoneTest346() { Assert.IsTrue(MetaphoneTest("wwwincredimail", "W839687")); }
        [TestMethod] public void MetaphoneTest347() { Assert.IsTrue(MetaphoneTest("izpack", "I513")); }
        [TestMethod] public void MetaphoneTest348() { Assert.IsTrue(MetaphoneTest("gaymovie", "G482")); }
        [TestMethod] public void MetaphoneTest349() { Assert.IsTrue(MetaphoneTest("Buchholz", "B1375")); }
        [TestMethod] public void MetaphoneTest350() { Assert.IsTrue(MetaphoneTest("culcairn", "C37398")); }
        [TestMethod] public void MetaphoneTest351() { Assert.IsTrue(MetaphoneTest("barys", "B193")); }
        [TestMethod] public void MetaphoneTest352() { Assert.IsTrue(MetaphoneTest("burets", "B1963")); }
        [TestMethod] public void MetaphoneTest353() { Assert.IsTrue(MetaphoneTest("Sorce", "S393")); }
        [TestMethod] public void MetaphoneTest354() { Assert.IsTrue(MetaphoneTest("chimique", "C385")); }
        [TestMethod] public void MetaphoneTest355() { Assert.IsTrue(MetaphoneTest("kitada", "K36")); }
        [TestMethod] public void MetaphoneTest356() { Assert.IsTrue(MetaphoneTest("Engeman", "E848")); }
        [TestMethod] public void MetaphoneTest357() { Assert.IsTrue(MetaphoneTest("raveendran", "R928698")); }
        [TestMethod] public void MetaphoneTest358() { Assert.IsTrue(MetaphoneTest("Bendele", "B1867")); }
        [TestMethod] public void MetaphoneTest359() { Assert.IsTrue(MetaphoneTest("Pawlitschek", "P1763")); }
        [TestMethod] public void MetaphoneTest360() { Assert.IsTrue(MetaphoneTest("hogfather", "H4269")); }
        [TestMethod] public void MetaphoneTest361() { Assert.IsTrue(MetaphoneTest("eyedrum", "E698")); }
        [TestMethod] public void MetaphoneTest362() { Assert.IsTrue(MetaphoneTest("Ferrara", "F29")); }
        [TestMethod] public void MetaphoneTest363() { Assert.IsTrue(MetaphoneTest("zhuh", "Z5")); }
        [TestMethod] public void MetaphoneTest364() { Assert.IsTrue(MetaphoneTest("zodiak", "Z563")); }
        [TestMethod] public void MetaphoneTest365() { Assert.IsTrue(MetaphoneTest("pchcom", "P138")); }
        [TestMethod] public void MetaphoneTest366() { Assert.IsTrue(MetaphoneTest("conferees", "C38293")); }
        [TestMethod] public void MetaphoneTest367() { Assert.IsTrue(MetaphoneTest("Decillis", "D6373")); }
        [TestMethod] public void MetaphoneTest368() { Assert.IsTrue(MetaphoneTest("downloar", "D6879")); }
        [TestMethod] public void MetaphoneTest369() { Assert.IsTrue(MetaphoneTest("shard", "S396")); }
        [TestMethod] public void MetaphoneTest370() { Assert.IsTrue(MetaphoneTest("fajr", "F249")); }
        [TestMethod] public void MetaphoneTest371() { Assert.IsTrue(MetaphoneTest("quisque", "Q535")); }
        [TestMethod] public void MetaphoneTest372() { Assert.IsTrue(MetaphoneTest("winterizing", "W869584")); }
        [TestMethod] public void MetaphoneTest373() { Assert.IsTrue(MetaphoneTest("referate", "R9296")); }
        [TestMethod] public void MetaphoneTest374() { Assert.IsTrue(MetaphoneTest("nuxone", "N858")); }
        [TestMethod] public void MetaphoneTest375() { Assert.IsTrue(MetaphoneTest("Racheal", "R937")); }
        [TestMethod] public void MetaphoneTest376() { Assert.IsTrue(MetaphoneTest("bizben", "B1518")); }
        [TestMethod] public void MetaphoneTest377() { Assert.IsTrue(MetaphoneTest("musictalk", "M83673")); }
        [TestMethod] public void MetaphoneTest378() { Assert.IsTrue(MetaphoneTest("ogoal", "O47")); }
        [TestMethod] public void MetaphoneTest379() { Assert.IsTrue(MetaphoneTest("Skoff", "S32")); }
        [TestMethod] public void MetaphoneTest380() { Assert.IsTrue(MetaphoneTest("Seehusen", "S38")); }
        [TestMethod] public void MetaphoneTest381() { Assert.IsTrue(MetaphoneTest("Reim", "R98")); }
        [TestMethod] public void MetaphoneTest382() { Assert.IsTrue(MetaphoneTest("Yoh", "Y")); }
        [TestMethod] public void MetaphoneTest383() { Assert.IsTrue(MetaphoneTest("gapi", "G41")); }
        [TestMethod] public void MetaphoneTest384() { Assert.IsTrue(MetaphoneTest("Brightbill", "B194617")); }
        [TestMethod] public void MetaphoneTest385() { Assert.IsTrue(MetaphoneTest("shuey", "S3")); }
        [TestMethod] public void MetaphoneTest386() { Assert.IsTrue(MetaphoneTest("posium", "P138")); }
        [TestMethod] public void MetaphoneTest387() { Assert.IsTrue(MetaphoneTest("Falknor", "F27389")); }
        [TestMethod] public void MetaphoneTest388() { Assert.IsTrue(MetaphoneTest("ucat", "U36")); }
        [TestMethod] public void MetaphoneTest389() { Assert.IsTrue(MetaphoneTest("properspace", "P1919313")); }
        [TestMethod] public void MetaphoneTest390() { Assert.IsTrue(MetaphoneTest("showimg", "S384")); }
        [TestMethod] public void MetaphoneTest391() { Assert.IsTrue(MetaphoneTest("Montecillo", "M8637")); }
        [TestMethod] public void MetaphoneTest392() { Assert.IsTrue(MetaphoneTest("sajak", "S343")); }
        [TestMethod] public void MetaphoneTest393() { Assert.IsTrue(MetaphoneTest("maturbation", "M869168")); }
        [TestMethod] public void MetaphoneTest394() { Assert.IsTrue(MetaphoneTest("Lettie", "L76")); }
        [TestMethod] public void MetaphoneTest395() { Assert.IsTrue(MetaphoneTest("clauss", "C373")); }
        [TestMethod] public void MetaphoneTest396() { Assert.IsTrue(MetaphoneTest("scheiber", "S319")); }
        [TestMethod] public void MetaphoneTest397() { Assert.IsTrue(MetaphoneTest("matp", "M861")); }
        [TestMethod] public void MetaphoneTest398() { Assert.IsTrue(MetaphoneTest("mervtormel", "M8926987")); }
        [TestMethod] public void MetaphoneTest399() { Assert.IsTrue(MetaphoneTest("guanahani", "G48")); }
        [TestMethod] public void MetaphoneTest400() { Assert.IsTrue(MetaphoneTest("citement", "C3686")); }
        [TestMethod] public void MetaphoneTest401() { Assert.IsTrue(MetaphoneTest("immu", "I8")); }
        [TestMethod] public void MetaphoneTest402() { Assert.IsTrue(MetaphoneTest("virulence", "V29783")); }
        [TestMethod] public void MetaphoneTest403() { Assert.IsTrue(MetaphoneTest("kussa", "K3")); }
        [TestMethod] public void MetaphoneTest404() { Assert.IsTrue(MetaphoneTest("gso", "G43")); }
        [TestMethod] public void MetaphoneTest405() { Assert.IsTrue(MetaphoneTest("webviajes", "W1243")); }
        [TestMethod] public void MetaphoneTest406() { Assert.IsTrue(MetaphoneTest("ldwork", "L7693")); }
        [TestMethod] public void MetaphoneTest407() { Assert.IsTrue(MetaphoneTest("verses", "V293")); }
        [TestMethod] public void MetaphoneTest408() { Assert.IsTrue(MetaphoneTest("sondes", "S3863")); }
        [TestMethod] public void MetaphoneTest409() { Assert.IsTrue(MetaphoneTest("freshpair", "F29319")); }
        [TestMethod] public void MetaphoneTest410() { Assert.IsTrue(MetaphoneTest("licorne", "L7398")); }
        [TestMethod] public void MetaphoneTest411() { Assert.IsTrue(MetaphoneTest("Vanis", "V283")); }
        [TestMethod] public void MetaphoneTest412() { Assert.IsTrue(MetaphoneTest("Buena", "B18")); }
        [TestMethod] public void MetaphoneTest413() { Assert.IsTrue(MetaphoneTest("Tauares", "T693")); }
        [TestMethod] public void MetaphoneTest414() { Assert.IsTrue(MetaphoneTest("ikus", "I3")); }
        [TestMethod] public void MetaphoneTest415() { Assert.IsTrue(MetaphoneTest("genrebox", "G48915")); }
        [TestMethod] public void MetaphoneTest416() { Assert.IsTrue(MetaphoneTest("rth", "R96")); }
        [TestMethod] public void MetaphoneTest417() { Assert.IsTrue(MetaphoneTest("Spaun", "S318")); }
        [TestMethod] public void MetaphoneTest418() { Assert.IsTrue(MetaphoneTest("wiersbe", "W931")); }
        [TestMethod] public void MetaphoneTest419() { Assert.IsTrue(MetaphoneTest("dad", "D6")); }
        [TestMethod] public void MetaphoneTest420() { Assert.IsTrue(MetaphoneTest("tus", "T63")); }
        [TestMethod] public void MetaphoneTest421() { Assert.IsTrue(MetaphoneTest("Weidert", "W696")); }
        [TestMethod] public void MetaphoneTest422() { Assert.IsTrue(MetaphoneTest("rijke", "R943")); }
        [TestMethod] public void MetaphoneTest423() { Assert.IsTrue(MetaphoneTest("fischbein", "F2318")); }
        [TestMethod] public void MetaphoneTest424() { Assert.IsTrue(MetaphoneTest("fbeye", "F21")); }
        [TestMethod] public void MetaphoneTest425() { Assert.IsTrue(MetaphoneTest("hagerty", "H496")); }
        [TestMethod] public void MetaphoneTest426() { Assert.IsTrue(MetaphoneTest("Hollendonner", "H78689")); }
        [TestMethod] public void MetaphoneTest427() { Assert.IsTrue(MetaphoneTest("Huitzacua", "H653")); }
        [TestMethod] public void MetaphoneTest428() { Assert.IsTrue(MetaphoneTest("subjunctive", "S3148362")); }
        [TestMethod] public void MetaphoneTest429() { Assert.IsTrue(MetaphoneTest("implored", "I81796")); }
        [TestMethod] public void MetaphoneTest430() { Assert.IsTrue(MetaphoneTest("pompeius", "P1813")); }
        [TestMethod] public void MetaphoneTest431() { Assert.IsTrue(MetaphoneTest("afleet", "A276")); }
        [TestMethod] public void MetaphoneTest432() { Assert.IsTrue(MetaphoneTest("iacc", "I3")); }
        [TestMethod] public void MetaphoneTest433() { Assert.IsTrue(MetaphoneTest("sabalos", "S3173")); }
        [TestMethod] public void MetaphoneTest434() { Assert.IsTrue(MetaphoneTest("Abdi", "A16")); }
        [TestMethod] public void MetaphoneTest435() { Assert.IsTrue(MetaphoneTest("microinsurance", "M83983983")); }
        [TestMethod] public void MetaphoneTest436() { Assert.IsTrue(MetaphoneTest("audiobook", "A613")); }
        [TestMethod] public void MetaphoneTest437() { Assert.IsTrue(MetaphoneTest("fulpmes", "F27183")); }
        [TestMethod] public void MetaphoneTest438() { Assert.IsTrue(MetaphoneTest("registreren", "R943698")); }
        [TestMethod] public void MetaphoneTest439() { Assert.IsTrue(MetaphoneTest("megapath", "M8416")); }
        [TestMethod] public void MetaphoneTest440() { Assert.IsTrue(MetaphoneTest("prestidigitation", "P1936468")); }
        [TestMethod] public void MetaphoneTest441() { Assert.IsTrue(MetaphoneTest("wby", "W1")); }
        [TestMethod] public void MetaphoneTest442() { Assert.IsTrue(MetaphoneTest("vorschau", "V293")); }
        [TestMethod] public void MetaphoneTest443() { Assert.IsTrue(MetaphoneTest("Albertha", "A7196")); }
        [TestMethod] public void MetaphoneTest444() { Assert.IsTrue(MetaphoneTest("aspalpha", "A3171")); }
        [TestMethod] public void MetaphoneTest445() { Assert.IsTrue(MetaphoneTest("Belden", "B1768")); }
        [TestMethod] public void MetaphoneTest446() { Assert.IsTrue(MetaphoneTest("deterministic", "D698363")); }
        [TestMethod] public void MetaphoneTest447() { Assert.IsTrue(MetaphoneTest("philosophique", "P17315")); }
        [TestMethod] public void MetaphoneTest448() { Assert.IsTrue(MetaphoneTest("kleinen", "K378")); }
        [TestMethod] public void MetaphoneTest449() { Assert.IsTrue(MetaphoneTest("logouri", "L749")); }
        [TestMethod] public void MetaphoneTest450() { Assert.IsTrue(MetaphoneTest("xbl", "X517")); }
        [TestMethod] public void MetaphoneTest451() { Assert.IsTrue(MetaphoneTest("iz", "I5")); }
        [TestMethod] public void MetaphoneTest452() { Assert.IsTrue(MetaphoneTest("throckmorton", "T6938968")); }
        [TestMethod] public void MetaphoneTest453() { Assert.IsTrue(MetaphoneTest("condesa", "C3863")); }
        [TestMethod] public void MetaphoneTest454() { Assert.IsTrue(MetaphoneTest("Mook", "M83")); }
        [TestMethod] public void MetaphoneTest455() { Assert.IsTrue(MetaphoneTest("medseek", "M863")); }
        [TestMethod] public void MetaphoneTest456() { Assert.IsTrue(MetaphoneTest("chugalug", "C3474")); }
        [TestMethod] public void MetaphoneTest457() { Assert.IsTrue(MetaphoneTest("olms", "O783")); }
        [TestMethod] public void MetaphoneTest458() { Assert.IsTrue(MetaphoneTest("bogo", "B14")); }
        [TestMethod] public void MetaphoneTest459() { Assert.IsTrue(MetaphoneTest("essing", "E384")); }
        [TestMethod] public void MetaphoneTest460() { Assert.IsTrue(MetaphoneTest("rarden", "R968")); }
        [TestMethod] public void MetaphoneTest461() { Assert.IsTrue(MetaphoneTest("mittlere", "M8679")); }
        [TestMethod] public void MetaphoneTest462() { Assert.IsTrue(MetaphoneTest("Borsa", "B193")); }
        [TestMethod] public void MetaphoneTest463() { Assert.IsTrue(MetaphoneTest("Ainslie", "A837")); }
        [TestMethod] public void MetaphoneTest464() { Assert.IsTrue(MetaphoneTest("Ganska", "G483")); }
        [TestMethod] public void MetaphoneTest465() { Assert.IsTrue(MetaphoneTest("miv", "M82")); }
        [TestMethod] public void MetaphoneTest466() { Assert.IsTrue(MetaphoneTest("concessions", "C38383")); }
        [TestMethod] public void MetaphoneTest467() { Assert.IsTrue(MetaphoneTest("distinguished", "D6368436")); }
        [TestMethod] public void MetaphoneTest468() { Assert.IsTrue(MetaphoneTest("cano", "C38")); }
        [TestMethod] public void MetaphoneTest469() { Assert.IsTrue(MetaphoneTest("plumper", "P17819")); }
        [TestMethod] public void MetaphoneTest470() { Assert.IsTrue(MetaphoneTest("mindoro", "M869")); }
        [TestMethod] public void MetaphoneTest471() { Assert.IsTrue(MetaphoneTest("cephalopod", "C31716")); }
        [TestMethod] public void MetaphoneTest472() { Assert.IsTrue(MetaphoneTest("Klunk", "K3783")); }
        [TestMethod] public void MetaphoneTest473() { Assert.IsTrue(MetaphoneTest("Bumbrey", "B1819")); }
        [TestMethod] public void MetaphoneTest474() { Assert.IsTrue(MetaphoneTest("causeless", "C373")); }
        [TestMethod] public void MetaphoneTest475() { Assert.IsTrue(MetaphoneTest("Lothrop", "L7691")); }
        [TestMethod] public void MetaphoneTest476() { Assert.IsTrue(MetaphoneTest("bodystyles", "B163673")); }
        [TestMethod] public void MetaphoneTest477() { Assert.IsTrue(MetaphoneTest("beaatiality", "B1676")); }
        [TestMethod] public void MetaphoneTest478() { Assert.IsTrue(MetaphoneTest("Bobrowski", "B193")); }
        [TestMethod] public void MetaphoneTest479() { Assert.IsTrue(MetaphoneTest("erudition", "E968")); }
        [TestMethod] public void MetaphoneTest480() { Assert.IsTrue(MetaphoneTest("huttner", "H689")); }
        [TestMethod] public void MetaphoneTest481() { Assert.IsTrue(MetaphoneTest("wwwaskjeevescom", "W34238")); }
        [TestMethod] public void MetaphoneTest482() { Assert.IsTrue(MetaphoneTest("Duross", "D693")); }
        [TestMethod] public void MetaphoneTest483() { Assert.IsTrue(MetaphoneTest("Colemen", "C378")); }
        [TestMethod] public void MetaphoneTest484() { Assert.IsTrue(MetaphoneTest("Duncomb", "D68381")); }
        [TestMethod] public void MetaphoneTest485() { Assert.IsTrue(MetaphoneTest("tripe", "T691")); }
        [TestMethod] public void MetaphoneTest486() { Assert.IsTrue(MetaphoneTest("dorrigo", "D694")); }
        [TestMethod] public void MetaphoneTest487() { Assert.IsTrue(MetaphoneTest("Mascall", "M837")); }
        [TestMethod] public void MetaphoneTest488() { Assert.IsTrue(MetaphoneTest("jetplane", "J46178")); }
        [TestMethod] public void MetaphoneTest489() { Assert.IsTrue(MetaphoneTest("nswrl", "N8397")); }
        [TestMethod] public void MetaphoneTest490() { Assert.IsTrue(MetaphoneTest("didates", "D63")); }
        [TestMethod] public void MetaphoneTest491() { Assert.IsTrue(MetaphoneTest("Jena", "J48")); }
        [TestMethod] public void MetaphoneTest492() { Assert.IsTrue(MetaphoneTest("kctu", "K36")); }
        [TestMethod] public void MetaphoneTest493() { Assert.IsTrue(MetaphoneTest("cualquiera", "C3759")); }
        [TestMethod] public void MetaphoneTest494() { Assert.IsTrue(MetaphoneTest("plutella", "P1767")); }
        [TestMethod] public void MetaphoneTest495() { Assert.IsTrue(MetaphoneTest("Liebig", "L714")); }
        [TestMethod] public void MetaphoneTest496() { Assert.IsTrue(MetaphoneTest("Llorens", "L7983")); }
        [TestMethod] public void MetaphoneTest497() { Assert.IsTrue(MetaphoneTest("mraz", "M895")); }
        [TestMethod] public void MetaphoneTest498() { Assert.IsTrue(MetaphoneTest("shadyac", "S363")); }
        [TestMethod] public void MetaphoneTest499() { Assert.IsTrue(MetaphoneTest("lossphentermine", "L7318698")); }
        [TestMethod] public void MetaphoneTest500() { Assert.IsTrue(MetaphoneTest("Dreith", "D696")); }

    }
}