using Element34.StringMetrics;

namespace Element34Tests.Phonetic
{
    [TestClass]
    public class RefinedNYSIISTests
    {
        private bool RefinedNYSIISTest(string sInput, string sExpected)
        {
            NYSIISRefined refinedNYSIIS = new NYSIISRefined();
            return refinedNYSIIS.Encode(sInput) == sExpected;
        }

        [TestMethod] public void RefinedNYSIISTest001() { Assert.IsTrue(RefinedNYSIISTest("communication", "CANANA[CATAN]")); }
        [TestMethod] public void RefinedNYSIISTest002() { Assert.IsTrue(RefinedNYSIISTest("worships", "WARSAP")); }
        [TestMethod] public void RefinedNYSIISTest003() { Assert.IsTrue(RefinedNYSIISTest("televisionhome", "TALAFA[SANAN]")); }
        [TestMethod] public void RefinedNYSIISTest004() { Assert.IsTrue(RefinedNYSIISTest("bumi", "BAN")); }
        [TestMethod] public void RefinedNYSIISTest005() { Assert.IsTrue(RefinedNYSIISTest("shortbread", "SARTBR[AD]")); }
        [TestMethod] public void RefinedNYSIISTest006() { Assert.IsTrue(RefinedNYSIISTest("slice", "SLAC")); }
        [TestMethod] public void RefinedNYSIISTest007() { Assert.IsTrue(RefinedNYSIISTest("reint", "RAD")); }
        [TestMethod] public void RefinedNYSIISTest008() { Assert.IsTrue(RefinedNYSIISTest("Florence", "FLARAN[C]")); }
        [TestMethod] public void RefinedNYSIISTest009() { Assert.IsTrue(RefinedNYSIISTest("fawzi", "FAS")); }
        [TestMethod] public void RefinedNYSIISTest010() { Assert.IsTrue(RefinedNYSIISTest("sname", "SNAN")); }
        [TestMethod] public void RefinedNYSIISTest011() { Assert.IsTrue(RefinedNYSIISTest("modano", "MADAN")); }
        [TestMethod] public void RefinedNYSIISTest012() { Assert.IsTrue(RefinedNYSIISTest("stumpage", "STANPA[G]")); }
        [TestMethod] public void RefinedNYSIISTest013() { Assert.IsTrue(RefinedNYSIISTest("clears", "CLAR")); }
        [TestMethod] public void RefinedNYSIISTest014() { Assert.IsTrue(RefinedNYSIISTest("ciods", "CAD")); }
        [TestMethod] public void RefinedNYSIISTest015() { Assert.IsTrue(RefinedNYSIISTest("deseos", "DAS")); }
        [TestMethod] public void RefinedNYSIISTest016() { Assert.IsTrue(RefinedNYSIISTest("dippin", "DAPAN")); }
        [TestMethod] public void RefinedNYSIISTest017() { Assert.IsTrue(RefinedNYSIISTest("aranna", "A")); }
        [TestMethod] public void RefinedNYSIISTest018() { Assert.IsTrue(RefinedNYSIISTest("borse", "BARS")); }
        [TestMethod] public void RefinedNYSIISTest019() { Assert.IsTrue(RefinedNYSIISTest("subic", "SABAC")); }
        [TestMethod] public void RefinedNYSIISTest020() { Assert.IsTrue(RefinedNYSIISTest("Vidrio", "VADR")); }
        [TestMethod] public void RefinedNYSIISTest021() { Assert.IsTrue(RefinedNYSIISTest("inserters", "I")); }
        [TestMethod] public void RefinedNYSIISTest022() { Assert.IsTrue(RefinedNYSIISTest("perature", "PARATA[R]")); }
        [TestMethod] public void RefinedNYSIISTest023() { Assert.IsTrue(RefinedNYSIISTest("msacideas", "MSACAD")); }
        [TestMethod] public void RefinedNYSIISTest024() { Assert.IsTrue(RefinedNYSIISTest("cougs", "CAG")); }
        [TestMethod] public void RefinedNYSIISTest025() { Assert.IsTrue(RefinedNYSIISTest("kittens", "CATAN")); }
        [TestMethod] public void RefinedNYSIISTest026() { Assert.IsTrue(RefinedNYSIISTest("imperiously", "I")); }
        [TestMethod] public void RefinedNYSIISTest027() { Assert.IsTrue(RefinedNYSIISTest("boccanegra", "BACANA[GR]")); }
        [TestMethod] public void RefinedNYSIISTest028() { Assert.IsTrue(RefinedNYSIISTest("sextet", "SAXTAT")); }
        [TestMethod] public void RefinedNYSIISTest029() { Assert.IsTrue(RefinedNYSIISTest("setattributes", "SATATR[ABAT]")); }
        [TestMethod] public void RefinedNYSIISTest030() { Assert.IsTrue(RefinedNYSIISTest("dsnt", "DSD")); }
        [TestMethod] public void RefinedNYSIISTest031() { Assert.IsTrue(RefinedNYSIISTest("chubby", "CABY")); }
        [TestMethod] public void RefinedNYSIISTest032() { Assert.IsTrue(RefinedNYSIISTest("ooda", "O")); }
        [TestMethod] public void RefinedNYSIISTest033() { Assert.IsTrue(RefinedNYSIISTest("Bressman", "BRASNA[N]")); }
        [TestMethod] public void RefinedNYSIISTest034() { Assert.IsTrue(RefinedNYSIISTest("calendarnew", "CALAND[ARN]")); }
        [TestMethod] public void RefinedNYSIISTest035() { Assert.IsTrue(RefinedNYSIISTest("duhon", "DAN")); }
        [TestMethod] public void RefinedNYSIISTest036() { Assert.IsTrue(RefinedNYSIISTest("nchen", "NCAN")); }
        [TestMethod] public void RefinedNYSIISTest037() { Assert.IsTrue(RefinedNYSIISTest("betjemans", "BATJAN[AN]")); }
        [TestMethod] public void RefinedNYSIISTest038() { Assert.IsTrue(RefinedNYSIISTest("Mangum", "MANGAN")); }
        [TestMethod] public void RefinedNYSIISTest039() { Assert.IsTrue(RefinedNYSIISTest("cabac", "CABAC")); }
        [TestMethod] public void RefinedNYSIISTest040() { Assert.IsTrue(RefinedNYSIISTest("pantys", "PANTY")); }
        [TestMethod] public void RefinedNYSIISTest041() { Assert.IsTrue(RefinedNYSIISTest("cofactors", "CAFACT[AR]")); }
        [TestMethod] public void RefinedNYSIISTest042() { Assert.IsTrue(RefinedNYSIISTest("clickz", "CLAC")); }
        [TestMethod] public void RefinedNYSIISTest043() { Assert.IsTrue(RefinedNYSIISTest("chiap", "CAP")); }
        [TestMethod] public void RefinedNYSIISTest044() { Assert.IsTrue(RefinedNYSIISTest("Dalpiaz", "DALP")); }
        [TestMethod] public void RefinedNYSIISTest045() { Assert.IsTrue(RefinedNYSIISTest("philosophically", "FALASA[FACALY]")); }
        [TestMethod] public void RefinedNYSIISTest046() { Assert.IsTrue(RefinedNYSIISTest("backfill", "BACFAL")); }
        [TestMethod] public void RefinedNYSIISTest047() { Assert.IsTrue(RefinedNYSIISTest("Murders", "MARDAR")); }
        [TestMethod] public void RefinedNYSIISTest048() { Assert.IsTrue(RefinedNYSIISTest("ecartis", "E")); }
        [TestMethod] public void RefinedNYSIISTest049() { Assert.IsTrue(RefinedNYSIISTest("vede", "VAD")); }
        [TestMethod] public void RefinedNYSIISTest050() { Assert.IsTrue(RefinedNYSIISTest("usoe", "U")); }
        [TestMethod] public void RefinedNYSIISTest051() { Assert.IsTrue(RefinedNYSIISTest("ostara", "O")); }
        [TestMethod] public void RefinedNYSIISTest052() { Assert.IsTrue(RefinedNYSIISTest("labourer", "LABARA[R]")); }
        [TestMethod] public void RefinedNYSIISTest053() { Assert.IsTrue(RefinedNYSIISTest("speir", "SPAR")); }
        [TestMethod] public void RefinedNYSIISTest054() { Assert.IsTrue(RefinedNYSIISTest("durchaus", "DARC")); }
        [TestMethod] public void RefinedNYSIISTest055() { Assert.IsTrue(RefinedNYSIISTest("inetformfiller", "I")); }
        [TestMethod] public void RefinedNYSIISTest056() { Assert.IsTrue(RefinedNYSIISTest("itrs", "I")); }
        [TestMethod] public void RefinedNYSIISTest057() { Assert.IsTrue(RefinedNYSIISTest("Tennant", "TANAD")); }
        [TestMethod] public void RefinedNYSIISTest058() { Assert.IsTrue(RefinedNYSIISTest("bashore", "BASAR")); }
        [TestMethod] public void RefinedNYSIISTest059() { Assert.IsTrue(RefinedNYSIISTest("lemurian", "LANARA[N]")); }
        [TestMethod] public void RefinedNYSIISTest060() { Assert.IsTrue(RefinedNYSIISTest("dungannon", "DANGAN[AN]")); }
        [TestMethod] public void RefinedNYSIISTest061() { Assert.IsTrue(RefinedNYSIISTest("epl", "E")); }
        [TestMethod] public void RefinedNYSIISTest062() { Assert.IsTrue(RefinedNYSIISTest("grader", "GRADAR")); }
        [TestMethod] public void RefinedNYSIISTest063() { Assert.IsTrue(RefinedNYSIISTest("synchronise", "SANCHR[ANAS]")); }
        [TestMethod] public void RefinedNYSIISTest064() { Assert.IsTrue(RefinedNYSIISTest("gondorian", "GANDAR[AN]")); }
        [TestMethod] public void RefinedNYSIISTest065() { Assert.IsTrue(RefinedNYSIISTest("cvnet", "CVNAT")); }
        [TestMethod] public void RefinedNYSIISTest066() { Assert.IsTrue(RefinedNYSIISTest("Centers", "CANTAR")); }
        [TestMethod] public void RefinedNYSIISTest067() { Assert.IsTrue(RefinedNYSIISTest("soaks", "SAC")); }
        [TestMethod] public void RefinedNYSIISTest068() { Assert.IsTrue(RefinedNYSIISTest("gogllle", "GAGL")); }
        [TestMethod] public void RefinedNYSIISTest069() { Assert.IsTrue(RefinedNYSIISTest("peotone", "PATAN")); }
        [TestMethod] public void RefinedNYSIISTest070() { Assert.IsTrue(RefinedNYSIISTest("Sharp", "SARP")); }
        [TestMethod] public void RefinedNYSIISTest071() { Assert.IsTrue(RefinedNYSIISTest("mawer", "MAR")); }
        [TestMethod] public void RefinedNYSIISTest072() { Assert.IsTrue(RefinedNYSIISTest("Morasca", "MARASC")); }
        [TestMethod] public void RefinedNYSIISTest073() { Assert.IsTrue(RefinedNYSIISTest("ticknor", "TACNAR")); }
        [TestMethod] public void RefinedNYSIISTest074() { Assert.IsTrue(RefinedNYSIISTest("beaverdale", "BAVARD[AL]")); }
        [TestMethod] public void RefinedNYSIISTest075() { Assert.IsTrue(RefinedNYSIISTest("caledonianew", "CALADA[NAN]")); }
        [TestMethod] public void RefinedNYSIISTest076() { Assert.IsTrue(RefinedNYSIISTest("wellnessdicke", "WALNAS[DAC]")); }
        [TestMethod] public void RefinedNYSIISTest077() { Assert.IsTrue(RefinedNYSIISTest("Rodin", "RADAN")); }
        [TestMethod] public void RefinedNYSIISTest078() { Assert.IsTrue(RefinedNYSIISTest("bluffer", "BLAFAR")); }
        [TestMethod] public void RefinedNYSIISTest079() { Assert.IsTrue(RefinedNYSIISTest("joey", "JY")); }
        [TestMethod] public void RefinedNYSIISTest080() { Assert.IsTrue(RefinedNYSIISTest("unbekannter", "U")); }
        [TestMethod] public void RefinedNYSIISTest081() { Assert.IsTrue(RefinedNYSIISTest("Baylor", "BALAR")); }
        [TestMethod] public void RefinedNYSIISTest082() { Assert.IsTrue(RefinedNYSIISTest("striplib", "STRAPL[AB]")); }
        [TestMethod] public void RefinedNYSIISTest083() { Assert.IsTrue(RefinedNYSIISTest("boquete", "BAGAT")); }
        [TestMethod] public void RefinedNYSIISTest084() { Assert.IsTrue(RefinedNYSIISTest("geylang", "GALANG")); }
        [TestMethod] public void RefinedNYSIISTest085() { Assert.IsTrue(RefinedNYSIISTest("Lavi", "LAV")); }
        [TestMethod] public void RefinedNYSIISTest086() { Assert.IsTrue(RefinedNYSIISTest("moldovans", "MALDAV[AN]")); }
        [TestMethod] public void RefinedNYSIISTest087() { Assert.IsTrue(RefinedNYSIISTest("linq", "LANG")); }
        [TestMethod] public void RefinedNYSIISTest088() { Assert.IsTrue(RefinedNYSIISTest("Kenworthy", "CANWAR[THY]")); }
        [TestMethod] public void RefinedNYSIISTest089() { Assert.IsTrue(RefinedNYSIISTest("Steckman", "STACNA[N]")); }
        [TestMethod] public void RefinedNYSIISTest090() { Assert.IsTrue(RefinedNYSIISTest("czechoslovakian", "CSACAS[LAVACAN]")); }
        [TestMethod] public void RefinedNYSIISTest091() { Assert.IsTrue(RefinedNYSIISTest("marmora", "MARNAR")); }
        [TestMethod] public void RefinedNYSIISTest092() { Assert.IsTrue(RefinedNYSIISTest("Carvill", "CARVAL")); }
        [TestMethod] public void RefinedNYSIISTest093() { Assert.IsTrue(RefinedNYSIISTest("chihiro", "CAR")); }
        [TestMethod] public void RefinedNYSIISTest094() { Assert.IsTrue(RefinedNYSIISTest("hctc", "HCTC")); }
        [TestMethod] public void RefinedNYSIISTest095() { Assert.IsTrue(RefinedNYSIISTest("nolde", "NALD")); }
        [TestMethod] public void RefinedNYSIISTest096() { Assert.IsTrue(RefinedNYSIISTest("aerosolized", "A")); }
        [TestMethod] public void RefinedNYSIISTest097() { Assert.IsTrue(RefinedNYSIISTest("canterbury", "CANTAR[BARY]")); }
        [TestMethod] public void RefinedNYSIISTest098() { Assert.IsTrue(RefinedNYSIISTest("jss", "J")); }
        [TestMethod] public void RefinedNYSIISTest099() { Assert.IsTrue(RefinedNYSIISTest("rmn", "RN")); }
        [TestMethod] public void RefinedNYSIISTest100() { Assert.IsTrue(RefinedNYSIISTest("mazlish", "MASLAS")); }
        [TestMethod] public void RefinedNYSIISTest101() { Assert.IsTrue(RefinedNYSIISTest("faites", "FAT")); }
        [TestMethod] public void RefinedNYSIISTest102() { Assert.IsTrue(RefinedNYSIISTest("foyer", "FAR")); }
        [TestMethod] public void RefinedNYSIISTest103() { Assert.IsTrue(RefinedNYSIISTest("ductions", "DACTAN")); }
        [TestMethod] public void RefinedNYSIISTest104() { Assert.IsTrue(RefinedNYSIISTest("Rambo", "RANB")); }
        [TestMethod] public void RefinedNYSIISTest105() { Assert.IsTrue(RefinedNYSIISTest("Curnutte", "CARNAT")); }
        [TestMethod] public void RefinedNYSIISTest106() { Assert.IsTrue(RefinedNYSIISTest("Feltus", "FALT")); }
        [TestMethod] public void RefinedNYSIISTest107() { Assert.IsTrue(RefinedNYSIISTest("forbairt", "FARBAD")); }
        [TestMethod] public void RefinedNYSIISTest108() { Assert.IsTrue(RefinedNYSIISTest("southerners", "SATARN[AR]")); }
        [TestMethod] public void RefinedNYSIISTest109() { Assert.IsTrue(RefinedNYSIISTest("hypnotists", "HAPNAT[AST]")); }
        [TestMethod] public void RefinedNYSIISTest110() { Assert.IsTrue(RefinedNYSIISTest("euphony", "E")); }
        [TestMethod] public void RefinedNYSIISTest111() { Assert.IsTrue(RefinedNYSIISTest("mhpa", "MHP")); }
        [TestMethod] public void RefinedNYSIISTest112() { Assert.IsTrue(RefinedNYSIISTest("matteotti", "MATAT")); }
        [TestMethod] public void RefinedNYSIISTest113() { Assert.IsTrue(RefinedNYSIISTest("Klande", "CLAND")); }
        [TestMethod] public void RefinedNYSIISTest114() { Assert.IsTrue(RefinedNYSIISTest("Trudgeon", "TRAGAN")); }
        [TestMethod] public void RefinedNYSIISTest115() { Assert.IsTrue(RefinedNYSIISTest("schoolhill", "SCALAL")); }
        [TestMethod] public void RefinedNYSIISTest116() { Assert.IsTrue(RefinedNYSIISTest("equalizer", "E")); }
        [TestMethod] public void RefinedNYSIISTest117() { Assert.IsTrue(RefinedNYSIISTest("xnet", "XNAT")); }
        [TestMethod] public void RefinedNYSIISTest118() { Assert.IsTrue(RefinedNYSIISTest("Thell", "TAL")); }
        [TestMethod] public void RefinedNYSIISTest119() { Assert.IsTrue(RefinedNYSIISTest("Canel", "CANAL")); }
        [TestMethod] public void RefinedNYSIISTest120() { Assert.IsTrue(RefinedNYSIISTest("vmetro", "VNATR")); }
        [TestMethod] public void RefinedNYSIISTest121() { Assert.IsTrue(RefinedNYSIISTest("burgtheater", "BARGTA[TAR]")); }
        [TestMethod] public void RefinedNYSIISTest122() { Assert.IsTrue(RefinedNYSIISTest("Berlinger", "BARLAN[GAR]")); }
        [TestMethod] public void RefinedNYSIISTest123() { Assert.IsTrue(RefinedNYSIISTest("crehan", "CRAN")); }
        [TestMethod] public void RefinedNYSIISTest124() { Assert.IsTrue(RefinedNYSIISTest("abysses", "A")); }
        [TestMethod] public void RefinedNYSIISTest125() { Assert.IsTrue(RefinedNYSIISTest("Hipolito", "HAPALA[T]")); }
        [TestMethod] public void RefinedNYSIISTest126() { Assert.IsTrue(RefinedNYSIISTest("splintered", "SPLANT[ARAD]")); }
        [TestMethod] public void RefinedNYSIISTest127() { Assert.IsTrue(RefinedNYSIISTest("maintenace", "MANTAN[AC]")); }
        [TestMethod] public void RefinedNYSIISTest128() { Assert.IsTrue(RefinedNYSIISTest("decency", "DACANC[Y]")); }
        [TestMethod] public void RefinedNYSIISTest129() { Assert.IsTrue(RefinedNYSIISTest("quantz", "QAD")); }
        [TestMethod] public void RefinedNYSIISTest130() { Assert.IsTrue(RefinedNYSIISTest("wette", "WAT")); }
        [TestMethod] public void RefinedNYSIISTest131() { Assert.IsTrue(RefinedNYSIISTest("Feary", "FARY")); }
        [TestMethod] public void RefinedNYSIISTest132() { Assert.IsTrue(RefinedNYSIISTest("Cuchiara", "CACAR")); }
        [TestMethod] public void RefinedNYSIISTest133() { Assert.IsTrue(RefinedNYSIISTest("Arbon", "A")); }
        [TestMethod] public void RefinedNYSIISTest134() { Assert.IsTrue(RefinedNYSIISTest("shyness", "SAN")); }
        [TestMethod] public void RefinedNYSIISTest135() { Assert.IsTrue(RefinedNYSIISTest("Salin", "SALAN")); }
        [TestMethod] public void RefinedNYSIISTest136() { Assert.IsTrue(RefinedNYSIISTest("Zicafoose", "ZACAFA[S]")); }
        [TestMethod] public void RefinedNYSIISTest137() { Assert.IsTrue(RefinedNYSIISTest("Menn", "MAN")); }
        [TestMethod] public void RefinedNYSIISTest138() { Assert.IsTrue(RefinedNYSIISTest("funker", "FANCAR")); }
        [TestMethod] public void RefinedNYSIISTest139() { Assert.IsTrue(RefinedNYSIISTest("santillan", "SANTAL[AN]")); }
        [TestMethod] public void RefinedNYSIISTest140() { Assert.IsTrue(RefinedNYSIISTest("punani", "PANAN")); }
        [TestMethod] public void RefinedNYSIISTest141() { Assert.IsTrue(RefinedNYSIISTest("basa", "BAS")); }
        [TestMethod] public void RefinedNYSIISTest142() { Assert.IsTrue(RefinedNYSIISTest("bluefin", "BLAFAN")); }
        [TestMethod] public void RefinedNYSIISTest143() { Assert.IsTrue(RefinedNYSIISTest("cc", "C")); }
        [TestMethod] public void RefinedNYSIISTest144() { Assert.IsTrue(RefinedNYSIISTest("zipgenius", "ZAPGAN")); }
        [TestMethod] public void RefinedNYSIISTest145() { Assert.IsTrue(RefinedNYSIISTest("Kirchen", "CARCAN")); }
        [TestMethod] public void RefinedNYSIISTest146() { Assert.IsTrue(RefinedNYSIISTest("commentaar", "CANANT[AR]")); }
        [TestMethod] public void RefinedNYSIISTest147() { Assert.IsTrue(RefinedNYSIISTest("expansive", "E")); }
        [TestMethod] public void RefinedNYSIISTest148() { Assert.IsTrue(RefinedNYSIISTest("castlebar", "CASTLA[BAR]")); }
        [TestMethod] public void RefinedNYSIISTest149() { Assert.IsTrue(RefinedNYSIISTest("lft", "LFT")); }
        [TestMethod] public void RefinedNYSIISTest150() { Assert.IsTrue(RefinedNYSIISTest("robla", "RABL")); }
        [TestMethod] public void RefinedNYSIISTest151() { Assert.IsTrue(RefinedNYSIISTest("zarontin", "ZARANT[AN]")); }
        [TestMethod] public void RefinedNYSIISTest152() { Assert.IsTrue(RefinedNYSIISTest("nawc", "NAC")); }
        [TestMethod] public void RefinedNYSIISTest153() { Assert.IsTrue(RefinedNYSIISTest("resolvconf", "RASALV[CANF]")); }
        [TestMethod] public void RefinedNYSIISTest154() { Assert.IsTrue(RefinedNYSIISTest("networker", "NATWAR[CAR]")); }
        [TestMethod] public void RefinedNYSIISTest155() { Assert.IsTrue(RefinedNYSIISTest("airlins", "A")); }
        [TestMethod] public void RefinedNYSIISTest156() { Assert.IsTrue(RefinedNYSIISTest("Piskel", "PASCAL")); }
        [TestMethod] public void RefinedNYSIISTest157() { Assert.IsTrue(RefinedNYSIISTest("hilson", "HALSAN")); }
        [TestMethod] public void RefinedNYSIISTest158() { Assert.IsTrue(RefinedNYSIISTest("deco", "DAC")); }
        [TestMethod] public void RefinedNYSIISTest159() { Assert.IsTrue(RefinedNYSIISTest("cents", "CAD")); }
        [TestMethod] public void RefinedNYSIISTest160() { Assert.IsTrue(RefinedNYSIISTest("award", "A")); }
        [TestMethod] public void RefinedNYSIISTest161() { Assert.IsTrue(RefinedNYSIISTest("reykjanes", "RACJAN")); }
        [TestMethod] public void RefinedNYSIISTest162() { Assert.IsTrue(RefinedNYSIISTest("perona", "PARAN")); }
        [TestMethod] public void RefinedNYSIISTest163() { Assert.IsTrue(RefinedNYSIISTest("epistle", "E")); }
        [TestMethod] public void RefinedNYSIISTest164() { Assert.IsTrue(RefinedNYSIISTest("insound", "I")); }
        [TestMethod] public void RefinedNYSIISTest165() { Assert.IsTrue(RefinedNYSIISTest("qantas", "QANT")); }
        [TestMethod] public void RefinedNYSIISTest166() { Assert.IsTrue(RefinedNYSIISTest("wholey", "WALY")); }
        [TestMethod] public void RefinedNYSIISTest167() { Assert.IsTrue(RefinedNYSIISTest("aragona", "A")); }
        [TestMethod] public void RefinedNYSIISTest168() { Assert.IsTrue(RefinedNYSIISTest("Vancheri", "VANCAR")); }
        [TestMethod] public void RefinedNYSIISTest169() { Assert.IsTrue(RefinedNYSIISTest("allocution", "A")); }
        [TestMethod] public void RefinedNYSIISTest170() { Assert.IsTrue(RefinedNYSIISTest("volodya", "VALAD")); }
        [TestMethod] public void RefinedNYSIISTest171() { Assert.IsTrue(RefinedNYSIISTest("enunciate", "E")); }
        [TestMethod] public void RefinedNYSIISTest172() { Assert.IsTrue(RefinedNYSIISTest("uuuu", "U")); }
        [TestMethod] public void RefinedNYSIISTest173() { Assert.IsTrue(RefinedNYSIISTest("Louato", "LAT")); }
        [TestMethod] public void RefinedNYSIISTest174() { Assert.IsTrue(RefinedNYSIISTest("Marquitta", "MARGAT")); }
        [TestMethod] public void RefinedNYSIISTest175() { Assert.IsTrue(RefinedNYSIISTest("surmountable", "SARNAN[TABL]")); }
        [TestMethod] public void RefinedNYSIISTest176() { Assert.IsTrue(RefinedNYSIISTest("gaultier", "GALTAR")); }
        [TestMethod] public void RefinedNYSIISTest177() { Assert.IsTrue(RefinedNYSIISTest("dafoe", "DAF")); }
        [TestMethod] public void RefinedNYSIISTest178() { Assert.IsTrue(RefinedNYSIISTest("Claudio", "CLAD")); }
        [TestMethod] public void RefinedNYSIISTest179() { Assert.IsTrue(RefinedNYSIISTest("ritva", "RATV")); }
        [TestMethod] public void RefinedNYSIISTest180() { Assert.IsTrue(RefinedNYSIISTest("spunky", "SPANCY")); }
        [TestMethod] public void RefinedNYSIISTest181() { Assert.IsTrue(RefinedNYSIISTest("npov", "NPAV")); }
        [TestMethod] public void RefinedNYSIISTest182() { Assert.IsTrue(RefinedNYSIISTest("eurythmics", "E")); }
        [TestMethod] public void RefinedNYSIISTest183() { Assert.IsTrue(RefinedNYSIISTest("skittish", "SCATAS")); }
        [TestMethod] public void RefinedNYSIISTest184() { Assert.IsTrue(RefinedNYSIISTest("scooter", "SCATAR")); }
        [TestMethod] public void RefinedNYSIISTest185() { Assert.IsTrue(RefinedNYSIISTest("unfermented", "U")); }
        [TestMethod] public void RefinedNYSIISTest186() { Assert.IsTrue(RefinedNYSIISTest("kerridge", "CARAG")); }
        [TestMethod] public void RefinedNYSIISTest187() { Assert.IsTrue(RefinedNYSIISTest("scenography", "SCANAG[RAFY]")); }
        [TestMethod] public void RefinedNYSIISTest188() { Assert.IsTrue(RefinedNYSIISTest("sahalee", "SALY")); }
        [TestMethod] public void RefinedNYSIISTest189() { Assert.IsTrue(RefinedNYSIISTest("spooktacular", "SPACTA[CALAR]")); }
        [TestMethod] public void RefinedNYSIISTest190() { Assert.IsTrue(RefinedNYSIISTest("boissons", "BASAN")); }
        [TestMethod] public void RefinedNYSIISTest191() { Assert.IsTrue(RefinedNYSIISTest("arbete", "A")); }
        [TestMethod] public void RefinedNYSIISTest192() { Assert.IsTrue(RefinedNYSIISTest("Norrick", "NARAC")); }
        [TestMethod] public void RefinedNYSIISTest193() { Assert.IsTrue(RefinedNYSIISTest("Sonnier", "SANAR")); }
        [TestMethod] public void RefinedNYSIISTest194() { Assert.IsTrue(RefinedNYSIISTest("gnomeui", "GNAN")); }
        [TestMethod] public void RefinedNYSIISTest195() { Assert.IsTrue(RefinedNYSIISTest("milian", "MALAN")); }
        [TestMethod] public void RefinedNYSIISTest196() { Assert.IsTrue(RefinedNYSIISTest("blackplanetcom", "BLACPL[ANATCAN]")); }
        [TestMethod] public void RefinedNYSIISTest197() { Assert.IsTrue(RefinedNYSIISTest("tuned", "TANAD")); }
        [TestMethod] public void RefinedNYSIISTest198() { Assert.IsTrue(RefinedNYSIISTest("Salone", "SALAN")); }
        [TestMethod] public void RefinedNYSIISTest199() { Assert.IsTrue(RefinedNYSIISTest("marathon", "MARATA[N]")); }
        [TestMethod] public void RefinedNYSIISTest200() { Assert.IsTrue(RefinedNYSIISTest("layoffs", "LAF")); }
        [TestMethod] public void RefinedNYSIISTest201() { Assert.IsTrue(RefinedNYSIISTest("hotek", "HATAC")); }
        [TestMethod] public void RefinedNYSIISTest202() { Assert.IsTrue(RefinedNYSIISTest("emme", "E")); }
        [TestMethod] public void RefinedNYSIISTest203() { Assert.IsTrue(RefinedNYSIISTest("amarasinghe", "A")); }
        [TestMethod] public void RefinedNYSIISTest204() { Assert.IsTrue(RefinedNYSIISTest("midas", "MAD")); }
        [TestMethod] public void RefinedNYSIISTest205() { Assert.IsTrue(RefinedNYSIISTest("inhaltsangabe", "I")); }
        [TestMethod] public void RefinedNYSIISTest206() { Assert.IsTrue(RefinedNYSIISTest("smow", "SN")); }
        [TestMethod] public void RefinedNYSIISTest207() { Assert.IsTrue(RefinedNYSIISTest("policing", "PALACA[NG]")); }
        [TestMethod] public void RefinedNYSIISTest208() { Assert.IsTrue(RefinedNYSIISTest("usmf", "U")); }
        [TestMethod] public void RefinedNYSIISTest209() { Assert.IsTrue(RefinedNYSIISTest("inferred", "I")); }
        [TestMethod] public void RefinedNYSIISTest210() { Assert.IsTrue(RefinedNYSIISTest("Eaglen", "E")); }
        [TestMethod] public void RefinedNYSIISTest211() { Assert.IsTrue(RefinedNYSIISTest("dralle", "DRAL")); }
        [TestMethod] public void RefinedNYSIISTest212() { Assert.IsTrue(RefinedNYSIISTest("kalmus", "CALN")); }
        [TestMethod] public void RefinedNYSIISTest213() { Assert.IsTrue(RefinedNYSIISTest("nork", "NARC")); }
        [TestMethod] public void RefinedNYSIISTest214() { Assert.IsTrue(RefinedNYSIISTest("Waterston", "WATARS[TAN]")); }
        [TestMethod] public void RefinedNYSIISTest215() { Assert.IsTrue(RefinedNYSIISTest("penalised", "PANALA[SAD]")); }
        [TestMethod] public void RefinedNYSIISTest216() { Assert.IsTrue(RefinedNYSIISTest("Lupacchino", "LAPACA[N]")); }
        [TestMethod] public void RefinedNYSIISTest217() { Assert.IsTrue(RefinedNYSIISTest("getgid", "GATGAD")); }
        [TestMethod] public void RefinedNYSIISTest218() { Assert.IsTrue(RefinedNYSIISTest("kever", "CAFAR")); }
        [TestMethod] public void RefinedNYSIISTest219() { Assert.IsTrue(RefinedNYSIISTest("pallavicini", "PALAVA[CAN]")); }
        [TestMethod] public void RefinedNYSIISTest220() { Assert.IsTrue(RefinedNYSIISTest("Pais", "P")); }
        [TestMethod] public void RefinedNYSIISTest221() { Assert.IsTrue(RefinedNYSIISTest("youghiogheny", "YAGAGA[NY]")); }
        [TestMethod] public void RefinedNYSIISTest222() { Assert.IsTrue(RefinedNYSIISTest("Catherina", "CATARA[N]")); }
        [TestMethod] public void RefinedNYSIISTest223() { Assert.IsTrue(RefinedNYSIISTest("Givant", "GAVAD")); }
        [TestMethod] public void RefinedNYSIISTest224() { Assert.IsTrue(RefinedNYSIISTest("koffi", "CAF")); }
        [TestMethod] public void RefinedNYSIISTest225() { Assert.IsTrue(RefinedNYSIISTest("troutbeck", "TRATBA[C]")); }
        [TestMethod] public void RefinedNYSIISTest226() { Assert.IsTrue(RefinedNYSIISTest("moreelse", "MARALS")); }
        [TestMethod] public void RefinedNYSIISTest227() { Assert.IsTrue(RefinedNYSIISTest("seacrest", "SACRAS[T]")); }
        [TestMethod] public void RefinedNYSIISTest228() { Assert.IsTrue(RefinedNYSIISTest("ufj", "U")); }
        [TestMethod] public void RefinedNYSIISTest229() { Assert.IsTrue(RefinedNYSIISTest("dereferences", "DARAFA[RANC]")); }
        [TestMethod] public void RefinedNYSIISTest230() { Assert.IsTrue(RefinedNYSIISTest("sarena", "SARAN")); }
        [TestMethod] public void RefinedNYSIISTest231() { Assert.IsTrue(RefinedNYSIISTest("Kurt", "CAD")); }
        [TestMethod] public void RefinedNYSIISTest232() { Assert.IsTrue(RefinedNYSIISTest("comanche", "CANANC")); }
        [TestMethod] public void RefinedNYSIISTest233() { Assert.IsTrue(RefinedNYSIISTest("chersoness", "CARSAN")); }
        [TestMethod] public void RefinedNYSIISTest234() { Assert.IsTrue(RefinedNYSIISTest("cd", "CD")); }
        [TestMethod] public void RefinedNYSIISTest235() { Assert.IsTrue(RefinedNYSIISTest("merzky", "MARSCY")); }
        [TestMethod] public void RefinedNYSIISTest236() { Assert.IsTrue(RefinedNYSIISTest("Nordsiek", "NARDSA[C]")); }
        [TestMethod] public void RefinedNYSIISTest237() { Assert.IsTrue(RefinedNYSIISTest("samus", "SAN")); }
        [TestMethod] public void RefinedNYSIISTest238() { Assert.IsTrue(RefinedNYSIISTest("tougher", "TAGAR")); }
        [TestMethod] public void RefinedNYSIISTest239() { Assert.IsTrue(RefinedNYSIISTest("monodoc", "MANADA[C]")); }
        [TestMethod] public void RefinedNYSIISTest240() { Assert.IsTrue(RefinedNYSIISTest("deepings", "DAPANG")); }
        [TestMethod] public void RefinedNYSIISTest241() { Assert.IsTrue(RefinedNYSIISTest("datel", "DATAL")); }
        [TestMethod] public void RefinedNYSIISTest242() { Assert.IsTrue(RefinedNYSIISTest("Stockett", "STACAT")); }
        [TestMethod] public void RefinedNYSIISTest243() { Assert.IsTrue(RefinedNYSIISTest("bryum", "BRAN")); }
        [TestMethod] public void RefinedNYSIISTest244() { Assert.IsTrue(RefinedNYSIISTest("surveyed", "SARVAD")); }
        [TestMethod] public void RefinedNYSIISTest245() { Assert.IsTrue(RefinedNYSIISTest("microcephaly", "MACRAC[AFALY]")); }
        [TestMethod] public void RefinedNYSIISTest246() { Assert.IsTrue(RefinedNYSIISTest("trimoxazole", "TRANAX[ASAL]")); }
        [TestMethod] public void RefinedNYSIISTest247() { Assert.IsTrue(RefinedNYSIISTest("bastide", "BASTAD")); }
        [TestMethod] public void RefinedNYSIISTest248() { Assert.IsTrue(RefinedNYSIISTest("lipo", "LAP")); }
        [TestMethod] public void RefinedNYSIISTest249() { Assert.IsTrue(RefinedNYSIISTest("Bosket", "BASCAT")); }
        [TestMethod] public void RefinedNYSIISTest250() { Assert.IsTrue(RefinedNYSIISTest("oroms", "O")); }
        [TestMethod] public void RefinedNYSIISTest251() { Assert.IsTrue(RefinedNYSIISTest("vandenburg", "VANDAN[BARG]")); }
        [TestMethod] public void RefinedNYSIISTest252() { Assert.IsTrue(RefinedNYSIISTest("wirtschaftsforschung", "WARTSC[AFTSFARSCANG]")); }
        [TestMethod] public void RefinedNYSIISTest253() { Assert.IsTrue(RefinedNYSIISTest("lilypond", "LALAPA[D]")); }
        [TestMethod] public void RefinedNYSIISTest254() { Assert.IsTrue(RefinedNYSIISTest("mouthfeel", "MATHFA[L]")); }
        [TestMethod] public void RefinedNYSIISTest255() { Assert.IsTrue(RefinedNYSIISTest("wwwunibancocombr", "WANABA[NCACANBR]")); }
        [TestMethod] public void RefinedNYSIISTest256() { Assert.IsTrue(RefinedNYSIISTest("Worster", "WARSTA[R]")); }
        [TestMethod] public void RefinedNYSIISTest257() { Assert.IsTrue(RefinedNYSIISTest("Ahmad", "A")); }
        [TestMethod] public void RefinedNYSIISTest258() { Assert.IsTrue(RefinedNYSIISTest("sweetser", "SWATSA[R]")); }
        [TestMethod] public void RefinedNYSIISTest259() { Assert.IsTrue(RefinedNYSIISTest("vsepr", "VSAPR")); }
        [TestMethod] public void RefinedNYSIISTest260() { Assert.IsTrue(RefinedNYSIISTest("dput", "DPAT")); }
        [TestMethod] public void RefinedNYSIISTest261() { Assert.IsTrue(RefinedNYSIISTest("austlit", "A")); }
        [TestMethod] public void RefinedNYSIISTest262() { Assert.IsTrue(RefinedNYSIISTest("Clemen", "CLANAN")); }
        [TestMethod] public void RefinedNYSIISTest263() { Assert.IsTrue(RefinedNYSIISTest("phrva", "FRV")); }
        [TestMethod] public void RefinedNYSIISTest264() { Assert.IsTrue(RefinedNYSIISTest("weipa", "WAP")); }
        [TestMethod] public void RefinedNYSIISTest265() { Assert.IsTrue(RefinedNYSIISTest("Schrantz", "SRAD")); }
        [TestMethod] public void RefinedNYSIISTest266() { Assert.IsTrue(RefinedNYSIISTest("meany", "MANY")); }
        [TestMethod] public void RefinedNYSIISTest267() { Assert.IsTrue(RefinedNYSIISTest("hodgepodge", "HAGAPA[G]")); }
        [TestMethod] public void RefinedNYSIISTest268() { Assert.IsTrue(RefinedNYSIISTest("knuble", "NABL")); }
        [TestMethod] public void RefinedNYSIISTest269() { Assert.IsTrue(RefinedNYSIISTest("caniglia", "CANAGL")); }
        [TestMethod] public void RefinedNYSIISTest270() { Assert.IsTrue(RefinedNYSIISTest("blowjobsasics", "BLAJAB[SASAC]")); }
        [TestMethod] public void RefinedNYSIISTest271() { Assert.IsTrue(RefinedNYSIISTest("flyjacket", "FLAJAC[AT]")); }
        [TestMethod] public void RefinedNYSIISTest272() { Assert.IsTrue(RefinedNYSIISTest("galatian", "GALATA[N]")); }
        [TestMethod] public void RefinedNYSIISTest273() { Assert.IsTrue(RefinedNYSIISTest("hotsel", "HATSAL")); }
        [TestMethod] public void RefinedNYSIISTest274() { Assert.IsTrue(RefinedNYSIISTest("autorun", "A")); }
        [TestMethod] public void RefinedNYSIISTest275() { Assert.IsTrue(RefinedNYSIISTest("cocoon", "CACAN")); }
        [TestMethod] public void RefinedNYSIISTest276() { Assert.IsTrue(RefinedNYSIISTest("kooks", "CAC")); }
        [TestMethod] public void RefinedNYSIISTest277() { Assert.IsTrue(RefinedNYSIISTest("endocrinol", "E")); }
        [TestMethod] public void RefinedNYSIISTest278() { Assert.IsTrue(RefinedNYSIISTest("mesages", "MASAG")); }
        [TestMethod] public void RefinedNYSIISTest279() { Assert.IsTrue(RefinedNYSIISTest("Disney", "DASNY")); }
        [TestMethod] public void RefinedNYSIISTest280() { Assert.IsTrue(RefinedNYSIISTest("speedline", "SPADLA[N]")); }
        [TestMethod] public void RefinedNYSIISTest281() { Assert.IsTrue(RefinedNYSIISTest("gabaldon", "GABALD[AN]")); }
        [TestMethod] public void RefinedNYSIISTest282() { Assert.IsTrue(RefinedNYSIISTest("margaux", "MARGAX")); }
        [TestMethod] public void RefinedNYSIISTest283() { Assert.IsTrue(RefinedNYSIISTest("housecalls", "HASACA[L]")); }
        [TestMethod] public void RefinedNYSIISTest284() { Assert.IsTrue(RefinedNYSIISTest("siltation", "SALTAT[AN]")); }
        [TestMethod] public void RefinedNYSIISTest285() { Assert.IsTrue(RefinedNYSIISTest("automatic", "A")); }
        [TestMethod] public void RefinedNYSIISTest286() { Assert.IsTrue(RefinedNYSIISTest("freakshow", "FRACS")); }
        [TestMethod] public void RefinedNYSIISTest287() { Assert.IsTrue(RefinedNYSIISTest("gorojovsky", "GARAJA[VSCY]")); }
        [TestMethod] public void RefinedNYSIISTest288() { Assert.IsTrue(RefinedNYSIISTest("milwaukie", "MALWAC[Y]")); }
        [TestMethod] public void RefinedNYSIISTest289() { Assert.IsTrue(RefinedNYSIISTest("wwwgap", "WGAP")); }
        [TestMethod] public void RefinedNYSIISTest290() { Assert.IsTrue(RefinedNYSIISTest("autm", "A")); }
        [TestMethod] public void RefinedNYSIISTest291() { Assert.IsTrue(RefinedNYSIISTest("borromini", "BARANA[N]")); }
        [TestMethod] public void RefinedNYSIISTest292() { Assert.IsTrue(RefinedNYSIISTest("zpp", "ZP")); }
        [TestMethod] public void RefinedNYSIISTest293() { Assert.IsTrue(RefinedNYSIISTest("Penovich", "PANAVA[CH]")); }
        [TestMethod] public void RefinedNYSIISTest294() { Assert.IsTrue(RefinedNYSIISTest("domine", "DANAN")); }
        [TestMethod] public void RefinedNYSIISTest295() { Assert.IsTrue(RefinedNYSIISTest("caves", "CAV")); }
        [TestMethod] public void RefinedNYSIISTest296() { Assert.IsTrue(RefinedNYSIISTest("uato", "U")); }
        [TestMethod] public void RefinedNYSIISTest297() { Assert.IsTrue(RefinedNYSIISTest("tiltonsville", "TALTAN[SVAL]")); }
        [TestMethod] public void RefinedNYSIISTest298() { Assert.IsTrue(RefinedNYSIISTest("Ken", "CAN")); }
        [TestMethod] public void RefinedNYSIISTest299() { Assert.IsTrue(RefinedNYSIISTest("Delonais", "DALAN")); }
        [TestMethod] public void RefinedNYSIISTest300() { Assert.IsTrue(RefinedNYSIISTest("conniption", "CANAPT[AN]")); }
        [TestMethod] public void RefinedNYSIISTest301() { Assert.IsTrue(RefinedNYSIISTest("Wenske", "WANSC")); }
        [TestMethod] public void RefinedNYSIISTest302() { Assert.IsTrue(RefinedNYSIISTest("cautery", "CATARY")); }
        [TestMethod] public void RefinedNYSIISTest303() { Assert.IsTrue(RefinedNYSIISTest("barbourville", "BARBAR[VAL]")); }
        [TestMethod] public void RefinedNYSIISTest304() { Assert.IsTrue(RefinedNYSIISTest("departamentos", "DAPART[ANANT]")); }
        [TestMethod] public void RefinedNYSIISTest305() { Assert.IsTrue(RefinedNYSIISTest("weaponry", "WAPANR[Y]")); }
        [TestMethod] public void RefinedNYSIISTest306() { Assert.IsTrue(RefinedNYSIISTest("Haggett", "HAGAT")); }
        [TestMethod] public void RefinedNYSIISTest307() { Assert.IsTrue(RefinedNYSIISTest("martinville", "MARTAN[VAL]")); }
        [TestMethod] public void RefinedNYSIISTest308() { Assert.IsTrue(RefinedNYSIISTest("stina", "STAN")); }
        [TestMethod] public void RefinedNYSIISTest309() { Assert.IsTrue(RefinedNYSIISTest("Rubottom", "RABATA[N]")); }
        [TestMethod] public void RefinedNYSIISTest310() { Assert.IsTrue(RefinedNYSIISTest("Soyke", "SAC")); }
        [TestMethod] public void RefinedNYSIISTest311() { Assert.IsTrue(RefinedNYSIISTest("corse", "CARS")); }
        [TestMethod] public void RefinedNYSIISTest312() { Assert.IsTrue(RefinedNYSIISTest("totalling", "TATALA[NG]")); }
        [TestMethod] public void RefinedNYSIISTest313() { Assert.IsTrue(RefinedNYSIISTest("kuppam", "CAPAN")); }
        [TestMethod] public void RefinedNYSIISTest314() { Assert.IsTrue(RefinedNYSIISTest("ftpadmin", "FTPADN[AN]")); }
        [TestMethod] public void RefinedNYSIISTest315() { Assert.IsTrue(RefinedNYSIISTest("Forst", "FARST")); }
        [TestMethod] public void RefinedNYSIISTest316() { Assert.IsTrue(RefinedNYSIISTest("Ashauer", "A")); }
        [TestMethod] public void RefinedNYSIISTest317() { Assert.IsTrue(RefinedNYSIISTest("ashtanga", "A")); }
        [TestMethod] public void RefinedNYSIISTest318() { Assert.IsTrue(RefinedNYSIISTest("alonissos", "A")); }
        [TestMethod] public void RefinedNYSIISTest319() { Assert.IsTrue(RefinedNYSIISTest("Chimilio", "CANAL")); }
        [TestMethod] public void RefinedNYSIISTest320() { Assert.IsTrue(RefinedNYSIISTest("deafbazon", "DAFBAS[AN]")); }
        [TestMethod] public void RefinedNYSIISTest321() { Assert.IsTrue(RefinedNYSIISTest("psmb", "PSNB")); }
        [TestMethod] public void RefinedNYSIISTest322() { Assert.IsTrue(RefinedNYSIISTest("Ferraraccio", "FARARA[C]")); }
        [TestMethod] public void RefinedNYSIISTest323() { Assert.IsTrue(RefinedNYSIISTest("fractionated", "FRACTA[NATAD]")); }
        [TestMethod] public void RefinedNYSIISTest324() { Assert.IsTrue(RefinedNYSIISTest("rrd", "D")); }
        [TestMethod] public void RefinedNYSIISTest325() { Assert.IsTrue(RefinedNYSIISTest("luminosities", "LANANA[SATY]")); }
        [TestMethod] public void RefinedNYSIISTest326() { Assert.IsTrue(RefinedNYSIISTest("Platzer", "PLATSA[R]")); }
        [TestMethod] public void RefinedNYSIISTest327() { Assert.IsTrue(RefinedNYSIISTest("modulator", "MADALA[TAR]")); }
        [TestMethod] public void RefinedNYSIISTest328() { Assert.IsTrue(RefinedNYSIISTest("tyneside", "TANASA[D]")); }
        [TestMethod] public void RefinedNYSIISTest329() { Assert.IsTrue(RefinedNYSIISTest("nonuser", "NANASA[R]")); }
        [TestMethod] public void RefinedNYSIISTest330() { Assert.IsTrue(RefinedNYSIISTest("haspel", "HASPAL")); }
        [TestMethod] public void RefinedNYSIISTest331() { Assert.IsTrue(RefinedNYSIISTest("cortex", "CARTAC")); }
        [TestMethod] public void RefinedNYSIISTest332() { Assert.IsTrue(RefinedNYSIISTest("vechicle", "VACACL")); }
        [TestMethod] public void RefinedNYSIISTest333() { Assert.IsTrue(RefinedNYSIISTest("epinions", "E")); }
        [TestMethod] public void RefinedNYSIISTest334() { Assert.IsTrue(RefinedNYSIISTest("wwwusmintgov", "WASNAN[TGAV]")); }
        [TestMethod] public void RefinedNYSIISTest335() { Assert.IsTrue(RefinedNYSIISTest("katies", "CATY")); }
        [TestMethod] public void RefinedNYSIISTest336() { Assert.IsTrue(RefinedNYSIISTest("aminosalicylic", "A")); }
        [TestMethod] public void RefinedNYSIISTest337() { Assert.IsTrue(RefinedNYSIISTest("mmegi", "MNAG")); }
        [TestMethod] public void RefinedNYSIISTest338() { Assert.IsTrue(RefinedNYSIISTest("sbir", "SBAR")); }
        [TestMethod] public void RefinedNYSIISTest339() { Assert.IsTrue(RefinedNYSIISTest("learned", "LARNAD")); }
        [TestMethod] public void RefinedNYSIISTest340() { Assert.IsTrue(RefinedNYSIISTest("supris", "SAPR")); }
        [TestMethod] public void RefinedNYSIISTest341() { Assert.IsTrue(RefinedNYSIISTest("mozarteum", "MASART[AN]")); }
        [TestMethod] public void RefinedNYSIISTest342() { Assert.IsTrue(RefinedNYSIISTest("selzer", "SALSAR")); }
        [TestMethod] public void RefinedNYSIISTest343() { Assert.IsTrue(RefinedNYSIISTest("tmug", "TNAG")); }
        [TestMethod] public void RefinedNYSIISTest344() { Assert.IsTrue(RefinedNYSIISTest("Kisto", "CAST")); }
        [TestMethod] public void RefinedNYSIISTest345() { Assert.IsTrue(RefinedNYSIISTest("iib", "I")); }
        [TestMethod] public void RefinedNYSIISTest346() { Assert.IsTrue(RefinedNYSIISTest("wwwincredimail", "WANCRA[DANAL]")); }
        [TestMethod] public void RefinedNYSIISTest347() { Assert.IsTrue(RefinedNYSIISTest("izpack", "I")); }
        [TestMethod] public void RefinedNYSIISTest348() { Assert.IsTrue(RefinedNYSIISTest("gaymovie", "GANAVY")); }
        [TestMethod] public void RefinedNYSIISTest349() { Assert.IsTrue(RefinedNYSIISTest("Buchholz", "BACHAL")); }
        [TestMethod] public void RefinedNYSIISTest350() { Assert.IsTrue(RefinedNYSIISTest("culcairn", "CALCAR[N]")); }
        [TestMethod] public void RefinedNYSIISTest351() { Assert.IsTrue(RefinedNYSIISTest("barys", "BARY")); }
        [TestMethod] public void RefinedNYSIISTest352() { Assert.IsTrue(RefinedNYSIISTest("burets", "BARAT")); }
        [TestMethod] public void RefinedNYSIISTest353() { Assert.IsTrue(RefinedNYSIISTest("Sorce", "SARC")); }
        [TestMethod] public void RefinedNYSIISTest354() { Assert.IsTrue(RefinedNYSIISTest("chimique", "CANAG")); }
        [TestMethod] public void RefinedNYSIISTest355() { Assert.IsTrue(RefinedNYSIISTest("kitada", "CATAD")); }
        [TestMethod] public void RefinedNYSIISTest356() { Assert.IsTrue(RefinedNYSIISTest("Engeman", "E")); }
        [TestMethod] public void RefinedNYSIISTest357() { Assert.IsTrue(RefinedNYSIISTest("raveendran", "RAVAND[RAN]")); }
        [TestMethod] public void RefinedNYSIISTest358() { Assert.IsTrue(RefinedNYSIISTest("Bendele", "BANDAL")); }
        [TestMethod] public void RefinedNYSIISTest359() { Assert.IsTrue(RefinedNYSIISTest("Pawlitschek", "PALATS[CAC]")); }
        [TestMethod] public void RefinedNYSIISTest360() { Assert.IsTrue(RefinedNYSIISTest("hogfather", "HAGFAT[AR]")); }
        [TestMethod] public void RefinedNYSIISTest361() { Assert.IsTrue(RefinedNYSIISTest("eyedrum", "E")); }
        [TestMethod] public void RefinedNYSIISTest362() { Assert.IsTrue(RefinedNYSIISTest("Ferrara", "FARAR")); }
        [TestMethod] public void RefinedNYSIISTest363() { Assert.IsTrue(RefinedNYSIISTest("zhuh", "ZAH")); }
        [TestMethod] public void RefinedNYSIISTest364() { Assert.IsTrue(RefinedNYSIISTest("zodiak", "ZADAC")); }
        [TestMethod] public void RefinedNYSIISTest365() { Assert.IsTrue(RefinedNYSIISTest("pchcom", "PCHCAN")); }
        [TestMethod] public void RefinedNYSIISTest366() { Assert.IsTrue(RefinedNYSIISTest("conferees", "CANFAR[Y]")); }
        [TestMethod] public void RefinedNYSIISTest367() { Assert.IsTrue(RefinedNYSIISTest("Decillis", "DACAL")); }
        [TestMethod] public void RefinedNYSIISTest368() { Assert.IsTrue(RefinedNYSIISTest("downloar", "DANLAR")); }
        [TestMethod] public void RefinedNYSIISTest369() { Assert.IsTrue(RefinedNYSIISTest("shard", "SAD")); }
        [TestMethod] public void RefinedNYSIISTest370() { Assert.IsTrue(RefinedNYSIISTest("fajr", "FAJR")); }
        [TestMethod] public void RefinedNYSIISTest371() { Assert.IsTrue(RefinedNYSIISTest("quisque", "QASG")); }
        [TestMethod] public void RefinedNYSIISTest372() { Assert.IsTrue(RefinedNYSIISTest("winterizing", "WANTAR[ASANG]")); }
        [TestMethod] public void RefinedNYSIISTest373() { Assert.IsTrue(RefinedNYSIISTest("referate", "RAFARA[T]")); }
        [TestMethod] public void RefinedNYSIISTest374() { Assert.IsTrue(RefinedNYSIISTest("nuxone", "NAXAN")); }
        [TestMethod] public void RefinedNYSIISTest375() { Assert.IsTrue(RefinedNYSIISTest("Racheal", "RACAL")); }
        [TestMethod] public void RefinedNYSIISTest376() { Assert.IsTrue(RefinedNYSIISTest("bizben", "BASBAN")); }
        [TestMethod] public void RefinedNYSIISTest377() { Assert.IsTrue(RefinedNYSIISTest("musictalk", "MASACT[ALC]")); }
        [TestMethod] public void RefinedNYSIISTest378() { Assert.IsTrue(RefinedNYSIISTest("ogoal", "O")); }
        [TestMethod] public void RefinedNYSIISTest379() { Assert.IsTrue(RefinedNYSIISTest("Skoff", "SCAF")); }
        [TestMethod] public void RefinedNYSIISTest380() { Assert.IsTrue(RefinedNYSIISTest("Seehusen", "SASAN")); }
        [TestMethod] public void RefinedNYSIISTest381() { Assert.IsTrue(RefinedNYSIISTest("Reim", "RAN")); }
        [TestMethod] public void RefinedNYSIISTest382() { Assert.IsTrue(RefinedNYSIISTest("Yoh", "Y")); }
        [TestMethod] public void RefinedNYSIISTest383() { Assert.IsTrue(RefinedNYSIISTest("gapi", "GAP")); }
        [TestMethod] public void RefinedNYSIISTest384() { Assert.IsTrue(RefinedNYSIISTest("Brightbill", "BRAGTB[AL]")); }
        [TestMethod] public void RefinedNYSIISTest385() { Assert.IsTrue(RefinedNYSIISTest("shuey", "SY")); }
        [TestMethod] public void RefinedNYSIISTest386() { Assert.IsTrue(RefinedNYSIISTest("posium", "PASAN")); }
        [TestMethod] public void RefinedNYSIISTest387() { Assert.IsTrue(RefinedNYSIISTest("Falknor", "FALNAR")); }
        [TestMethod] public void RefinedNYSIISTest388() { Assert.IsTrue(RefinedNYSIISTest("ucat", "U")); }
        [TestMethod] public void RefinedNYSIISTest389() { Assert.IsTrue(RefinedNYSIISTest("properspace", "PRAPAR[SPAC]")); }
        [TestMethod] public void RefinedNYSIISTest390() { Assert.IsTrue(RefinedNYSIISTest("showimg", "SANG")); }
        [TestMethod] public void RefinedNYSIISTest391() { Assert.IsTrue(RefinedNYSIISTest("Montecillo", "MANTAC[AL]")); }
        [TestMethod] public void RefinedNYSIISTest392() { Assert.IsTrue(RefinedNYSIISTest("sajak", "SAJAC")); }
        [TestMethod] public void RefinedNYSIISTest393() { Assert.IsTrue(RefinedNYSIISTest("maturbation", "MATARB[ATAN]")); }
        [TestMethod] public void RefinedNYSIISTest394() { Assert.IsTrue(RefinedNYSIISTest("Lettie", "LATY")); }
        [TestMethod] public void RefinedNYSIISTest395() { Assert.IsTrue(RefinedNYSIISTest("clauss", "CL")); }
        [TestMethod] public void RefinedNYSIISTest396() { Assert.IsTrue(RefinedNYSIISTest("scheiber", "SCABAR")); }
        [TestMethod] public void RefinedNYSIISTest397() { Assert.IsTrue(RefinedNYSIISTest("matp", "MATP")); }
        [TestMethod] public void RefinedNYSIISTest398() { Assert.IsTrue(RefinedNYSIISTest("mervtormel", "MARVTA[RNAL]")); }
        [TestMethod] public void RefinedNYSIISTest399() { Assert.IsTrue(RefinedNYSIISTest("guanahani", "GANAN")); }
        [TestMethod] public void RefinedNYSIISTest400() { Assert.IsTrue(RefinedNYSIISTest("citement", "CATANA[D]")); }
        [TestMethod] public void RefinedNYSIISTest401() { Assert.IsTrue(RefinedNYSIISTest("immu", "I")); }
        [TestMethod] public void RefinedNYSIISTest402() { Assert.IsTrue(RefinedNYSIISTest("virulence", "VARALA[NC]")); }
        [TestMethod] public void RefinedNYSIISTest403() { Assert.IsTrue(RefinedNYSIISTest("kussa", "CAS")); }
        [TestMethod] public void RefinedNYSIISTest404() { Assert.IsTrue(RefinedNYSIISTest("gso", "GS")); }
        [TestMethod] public void RefinedNYSIISTest405() { Assert.IsTrue(RefinedNYSIISTest("webviajes", "WABVAJ")); }
        [TestMethod] public void RefinedNYSIISTest406() { Assert.IsTrue(RefinedNYSIISTest("ldwork", "LDWARC")); }
        [TestMethod] public void RefinedNYSIISTest407() { Assert.IsTrue(RefinedNYSIISTest("verses", "VARS")); }
        [TestMethod] public void RefinedNYSIISTest408() { Assert.IsTrue(RefinedNYSIISTest("sondes", "SAND")); }
        [TestMethod] public void RefinedNYSIISTest409() { Assert.IsTrue(RefinedNYSIISTest("freshpair", "FRASPA[R]")); }
        [TestMethod] public void RefinedNYSIISTest410() { Assert.IsTrue(RefinedNYSIISTest("licorne", "LACARN")); }
        [TestMethod] public void RefinedNYSIISTest411() { Assert.IsTrue(RefinedNYSIISTest("Vanis", "VAN")); }
        [TestMethod] public void RefinedNYSIISTest412() { Assert.IsTrue(RefinedNYSIISTest("Buena", "BAN")); }
        [TestMethod] public void RefinedNYSIISTest413() { Assert.IsTrue(RefinedNYSIISTest("Tauares", "TAR")); }
        [TestMethod] public void RefinedNYSIISTest414() { Assert.IsTrue(RefinedNYSIISTest("ikus", "I")); }
        [TestMethod] public void RefinedNYSIISTest415() { Assert.IsTrue(RefinedNYSIISTest("genrebox", "GANRAB[AX]")); }
        [TestMethod] public void RefinedNYSIISTest416() { Assert.IsTrue(RefinedNYSIISTest("rth", "RTH")); }
        [TestMethod] public void RefinedNYSIISTest417() { Assert.IsTrue(RefinedNYSIISTest("Spaun", "SPAN")); }
        [TestMethod] public void RefinedNYSIISTest418() { Assert.IsTrue(RefinedNYSIISTest("wiersbe", "WARSB")); }
        [TestMethod] public void RefinedNYSIISTest419() { Assert.IsTrue(RefinedNYSIISTest("dad", "DAD")); }
        [TestMethod] public void RefinedNYSIISTest420() { Assert.IsTrue(RefinedNYSIISTest("tus", "T")); }
        [TestMethod] public void RefinedNYSIISTest421() { Assert.IsTrue(RefinedNYSIISTest("Weidert", "WADAD")); }
        [TestMethod] public void RefinedNYSIISTest422() { Assert.IsTrue(RefinedNYSIISTest("rijke", "RAJC")); }
        [TestMethod] public void RefinedNYSIISTest423() { Assert.IsTrue(RefinedNYSIISTest("fischbein", "FASBAN")); }
        [TestMethod] public void RefinedNYSIISTest424() { Assert.IsTrue(RefinedNYSIISTest("fbeye", "FBY")); }
        [TestMethod] public void RefinedNYSIISTest425() { Assert.IsTrue(RefinedNYSIISTest("hagerty", "HAGART[Y]")); }
        [TestMethod] public void RefinedNYSIISTest426() { Assert.IsTrue(RefinedNYSIISTest("Hollendonner", "HALAND[ANAR]")); }
        [TestMethod] public void RefinedNYSIISTest427() { Assert.IsTrue(RefinedNYSIISTest("Huitzacua", "HATSAC")); }
        [TestMethod] public void RefinedNYSIISTest428() { Assert.IsTrue(RefinedNYSIISTest("subjunctive", "SABJAN[CTAV]")); }
        [TestMethod] public void RefinedNYSIISTest429() { Assert.IsTrue(RefinedNYSIISTest("implored", "I")); }
        [TestMethod] public void RefinedNYSIISTest430() { Assert.IsTrue(RefinedNYSIISTest("pompeius", "PANP")); }
        [TestMethod] public void RefinedNYSIISTest431() { Assert.IsTrue(RefinedNYSIISTest("afleet", "A")); }
        [TestMethod] public void RefinedNYSIISTest432() { Assert.IsTrue(RefinedNYSIISTest("iacc", "I")); }
        [TestMethod] public void RefinedNYSIISTest433() { Assert.IsTrue(RefinedNYSIISTest("sabalos", "SABAL")); }
        [TestMethod] public void RefinedNYSIISTest434() { Assert.IsTrue(RefinedNYSIISTest("Abdi", "A")); }
        [TestMethod] public void RefinedNYSIISTest435() { Assert.IsTrue(RefinedNYSIISTest("microinsurance", "MACRAN[SARANC]")); }
        [TestMethod] public void RefinedNYSIISTest436() { Assert.IsTrue(RefinedNYSIISTest("audiobook", "A")); }
        [TestMethod] public void RefinedNYSIISTest437() { Assert.IsTrue(RefinedNYSIISTest("fulpmes", "FALPN")); }
        [TestMethod] public void RefinedNYSIISTest438() { Assert.IsTrue(RefinedNYSIISTest("registreren", "RAGAST[RARAN]")); }
        [TestMethod] public void RefinedNYSIISTest439() { Assert.IsTrue(RefinedNYSIISTest("megapath", "MAGAPA[TH]")); }
        [TestMethod] public void RefinedNYSIISTest440() { Assert.IsTrue(RefinedNYSIISTest("prestidigitation", "PRASTA[DAGATATAN]")); }
        [TestMethod] public void RefinedNYSIISTest441() { Assert.IsTrue(RefinedNYSIISTest("wby", "WBY")); }
        [TestMethod] public void RefinedNYSIISTest442() { Assert.IsTrue(RefinedNYSIISTest("vorschau", "VARSC")); }
        [TestMethod] public void RefinedNYSIISTest443() { Assert.IsTrue(RefinedNYSIISTest("Albertha", "A")); }
        [TestMethod] public void RefinedNYSIISTest444() { Assert.IsTrue(RefinedNYSIISTest("aspalpha", "A")); }
        [TestMethod] public void RefinedNYSIISTest445() { Assert.IsTrue(RefinedNYSIISTest("Belden", "BALDAN")); }
        [TestMethod] public void RefinedNYSIISTest446() { Assert.IsTrue(RefinedNYSIISTest("deterministic", "DATARN[ANASTAC]")); }
        [TestMethod] public void RefinedNYSIISTest447() { Assert.IsTrue(RefinedNYSIISTest("philosophique", "FALASA[FAG]")); }
        [TestMethod] public void RefinedNYSIISTest448() { Assert.IsTrue(RefinedNYSIISTest("kleinen", "CLANAN")); }
        [TestMethod] public void RefinedNYSIISTest449() { Assert.IsTrue(RefinedNYSIISTest("logouri", "LAGAR")); }
        [TestMethod] public void RefinedNYSIISTest450() { Assert.IsTrue(RefinedNYSIISTest("xbl", "XBL")); }
        [TestMethod] public void RefinedNYSIISTest451() { Assert.IsTrue(RefinedNYSIISTest("iz", "I")); }
        [TestMethod] public void RefinedNYSIISTest452() { Assert.IsTrue(RefinedNYSIISTest("throckmorton", "THRACN[ARTAN]")); }
        [TestMethod] public void RefinedNYSIISTest453() { Assert.IsTrue(RefinedNYSIISTest("condesa", "CANDAS")); }
        [TestMethod] public void RefinedNYSIISTest454() { Assert.IsTrue(RefinedNYSIISTest("Mook", "MAC")); }
        [TestMethod] public void RefinedNYSIISTest455() { Assert.IsTrue(RefinedNYSIISTest("medseek", "MADSAC")); }
        [TestMethod] public void RefinedNYSIISTest456() { Assert.IsTrue(RefinedNYSIISTest("chugalug", "CAGALA[G]")); }
        [TestMethod] public void RefinedNYSIISTest457() { Assert.IsTrue(RefinedNYSIISTest("olms", "O")); }
        [TestMethod] public void RefinedNYSIISTest458() { Assert.IsTrue(RefinedNYSIISTest("bogo", "BAG")); }
        [TestMethod] public void RefinedNYSIISTest459() { Assert.IsTrue(RefinedNYSIISTest("essing", "E")); }
        [TestMethod] public void RefinedNYSIISTest460() { Assert.IsTrue(RefinedNYSIISTest("rarden", "RARDAN")); }
        [TestMethod] public void RefinedNYSIISTest461() { Assert.IsTrue(RefinedNYSIISTest("mittlere", "MATLAR")); }
        [TestMethod] public void RefinedNYSIISTest462() { Assert.IsTrue(RefinedNYSIISTest("Borsa", "BARS")); }
        [TestMethod] public void RefinedNYSIISTest463() { Assert.IsTrue(RefinedNYSIISTest("Ainslie", "A")); }
        [TestMethod] public void RefinedNYSIISTest464() { Assert.IsTrue(RefinedNYSIISTest("Ganska", "GANSC")); }
        [TestMethod] public void RefinedNYSIISTest465() { Assert.IsTrue(RefinedNYSIISTest("miv", "MAV")); }
        [TestMethod] public void RefinedNYSIISTest466() { Assert.IsTrue(RefinedNYSIISTest("concessions", "CANCAS[AN]")); }
        [TestMethod] public void RefinedNYSIISTest467() { Assert.IsTrue(RefinedNYSIISTest("distinguished", "DASTAN[GASAD]")); }
        [TestMethod] public void RefinedNYSIISTest468() { Assert.IsTrue(RefinedNYSIISTest("cano", "CAN")); }
        [TestMethod] public void RefinedNYSIISTest469() { Assert.IsTrue(RefinedNYSIISTest("plumper", "PLANPA[R]")); }
        [TestMethod] public void RefinedNYSIISTest470() { Assert.IsTrue(RefinedNYSIISTest("mindoro", "MANDAR")); }
        [TestMethod] public void RefinedNYSIISTest471() { Assert.IsTrue(RefinedNYSIISTest("cephalopod", "CAFALA[PAD]")); }
        [TestMethod] public void RefinedNYSIISTest472() { Assert.IsTrue(RefinedNYSIISTest("Klunk", "CLANC")); }
        [TestMethod] public void RefinedNYSIISTest473() { Assert.IsTrue(RefinedNYSIISTest("Bumbrey", "BANBRY")); }
        [TestMethod] public void RefinedNYSIISTest474() { Assert.IsTrue(RefinedNYSIISTest("causeless", "CASAL")); }
        [TestMethod] public void RefinedNYSIISTest475() { Assert.IsTrue(RefinedNYSIISTest("Lothrop", "LATHRA[P]")); }
        [TestMethod] public void RefinedNYSIISTest476() { Assert.IsTrue(RefinedNYSIISTest("bodystyles", "BADAST[AL]")); }
        [TestMethod] public void RefinedNYSIISTest477() { Assert.IsTrue(RefinedNYSIISTest("beaatiality", "BATALA[TY]")); }
        [TestMethod] public void RefinedNYSIISTest478() { Assert.IsTrue(RefinedNYSIISTest("Bobrowski", "BABRAS[C]")); }
        [TestMethod] public void RefinedNYSIISTest479() { Assert.IsTrue(RefinedNYSIISTest("erudition", "E")); }
        [TestMethod] public void RefinedNYSIISTest480() { Assert.IsTrue(RefinedNYSIISTest("huttner", "HATNAR")); }
        [TestMethod] public void RefinedNYSIISTest481() { Assert.IsTrue(RefinedNYSIISTest("wwwaskjeevescom", "WASCJA[FASCAN]")); }
        [TestMethod] public void RefinedNYSIISTest482() { Assert.IsTrue(RefinedNYSIISTest("Duross", "DAR")); }
        [TestMethod] public void RefinedNYSIISTest483() { Assert.IsTrue(RefinedNYSIISTest("Colemen", "CALANA[N]")); }
        [TestMethod] public void RefinedNYSIISTest484() { Assert.IsTrue(RefinedNYSIISTest("Duncomb", "DANCAN[B]")); }
        [TestMethod] public void RefinedNYSIISTest485() { Assert.IsTrue(RefinedNYSIISTest("tripe", "TRAP")); }
        [TestMethod] public void RefinedNYSIISTest486() { Assert.IsTrue(RefinedNYSIISTest("dorrigo", "DARAG")); }
        [TestMethod] public void RefinedNYSIISTest487() { Assert.IsTrue(RefinedNYSIISTest("Mascall", "MASCAL")); }
        [TestMethod] public void RefinedNYSIISTest488() { Assert.IsTrue(RefinedNYSIISTest("jetplane", "JATPLA[N]")); }
        [TestMethod] public void RefinedNYSIISTest489() { Assert.IsTrue(RefinedNYSIISTest("nswrl", "NSRL")); }
        [TestMethod] public void RefinedNYSIISTest490() { Assert.IsTrue(RefinedNYSIISTest("didates", "DADAT")); }
        [TestMethod] public void RefinedNYSIISTest491() { Assert.IsTrue(RefinedNYSIISTest("Jena", "JAN")); }
        [TestMethod] public void RefinedNYSIISTest492() { Assert.IsTrue(RefinedNYSIISTest("kctu", "CT")); }
        [TestMethod] public void RefinedNYSIISTest493() { Assert.IsTrue(RefinedNYSIISTest("cualquiera", "CALGAR")); }
        [TestMethod] public void RefinedNYSIISTest494() { Assert.IsTrue(RefinedNYSIISTest("plutella", "PLATAL")); }
        [TestMethod] public void RefinedNYSIISTest495() { Assert.IsTrue(RefinedNYSIISTest("Liebig", "LABAG")); }
        [TestMethod] public void RefinedNYSIISTest496() { Assert.IsTrue(RefinedNYSIISTest("Llorens", "LARAN")); }
        [TestMethod] public void RefinedNYSIISTest497() { Assert.IsTrue(RefinedNYSIISTest("mraz", "MR")); }
        [TestMethod] public void RefinedNYSIISTest498() { Assert.IsTrue(RefinedNYSIISTest("shadyac", "SADAC")); }
        [TestMethod] public void RefinedNYSIISTest499() { Assert.IsTrue(RefinedNYSIISTest("lossphentermine", "LASFAN[TARNAN]")); }
        [TestMethod] public void RefinedNYSIISTest500() { Assert.IsTrue(RefinedNYSIISTest("Dreith", "DRATH")); }

    }
}
