using Element34.StringMetrics;

namespace Element34Tests.Phonetic
{
    [TestClass]
    public class RefinedSoundExTests
    {
        private bool RefinedSoundExTest(string sInput, string sExpected)
        {
            SoundExRefined soundEx = new SoundExRefined();
            return soundEx.Encode(sInput) == sExpected;
        }
        [TestMethod] public void RefinedSoundExTest001() { Assert.IsTrue(RefinedSoundExTest("communication", "C38368")); }
        [TestMethod] public void RefinedSoundExTest002() { Assert.IsTrue(RefinedSoundExTest("worships", "W9313")); }
        [TestMethod] public void RefinedSoundExTest003() { Assert.IsTrue(RefinedSoundExTest("televisionhome", "T67238")); }
        [TestMethod] public void RefinedSoundExTest004() { Assert.IsTrue(RefinedSoundExTest("bumi", "B18")); }
        [TestMethod] public void RefinedSoundExTest005() { Assert.IsTrue(RefinedSoundExTest("shortbread", "S396196")); }
        [TestMethod] public void RefinedSoundExTest006() { Assert.IsTrue(RefinedSoundExTest("slice", "S373")); }
        [TestMethod] public void RefinedSoundExTest007() { Assert.IsTrue(RefinedSoundExTest("reint", "R986")); }
        [TestMethod] public void RefinedSoundExTest008() { Assert.IsTrue(RefinedSoundExTest("Florence", "F27983")); }
        [TestMethod] public void RefinedSoundExTest009() { Assert.IsTrue(RefinedSoundExTest("fawzi", "F25")); }
        [TestMethod] public void RefinedSoundExTest010() { Assert.IsTrue(RefinedSoundExTest("sname", "S38")); }
        [TestMethod] public void RefinedSoundExTest011() { Assert.IsTrue(RefinedSoundExTest("modano", "M868")); }
        [TestMethod] public void RefinedSoundExTest012() { Assert.IsTrue(RefinedSoundExTest("stumpage", "S36814")); }
        [TestMethod] public void RefinedSoundExTest013() { Assert.IsTrue(RefinedSoundExTest("clears", "C3793")); }
        [TestMethod] public void RefinedSoundExTest014() { Assert.IsTrue(RefinedSoundExTest("ciods", "C363")); }
        [TestMethod] public void RefinedSoundExTest015() { Assert.IsTrue(RefinedSoundExTest("deseos", "D63")); }
        [TestMethod] public void RefinedSoundExTest016() { Assert.IsTrue(RefinedSoundExTest("dippin", "D618")); }
        [TestMethod] public void RefinedSoundExTest017() { Assert.IsTrue(RefinedSoundExTest("aranna", "A98")); }
        [TestMethod] public void RefinedSoundExTest018() { Assert.IsTrue(RefinedSoundExTest("borse", "B193")); }
        [TestMethod] public void RefinedSoundExTest019() { Assert.IsTrue(RefinedSoundExTest("subic", "S313")); }
        [TestMethod] public void RefinedSoundExTest020() { Assert.IsTrue(RefinedSoundExTest("Vidrio", "V269")); }
        [TestMethod] public void RefinedSoundExTest021() { Assert.IsTrue(RefinedSoundExTest("inserters", "I839693")); }
        [TestMethod] public void RefinedSoundExTest022() { Assert.IsTrue(RefinedSoundExTest("perature", "P1969")); }
        [TestMethod] public void RefinedSoundExTest023() { Assert.IsTrue(RefinedSoundExTest("msacideas", "M8363")); }
        [TestMethod] public void RefinedSoundExTest024() { Assert.IsTrue(RefinedSoundExTest("cougs", "C343")); }
        [TestMethod] public void RefinedSoundExTest025() { Assert.IsTrue(RefinedSoundExTest("kittens", "K3683")); }
        [TestMethod] public void RefinedSoundExTest026() { Assert.IsTrue(RefinedSoundExTest("imperiously", "I81937")); }
        [TestMethod] public void RefinedSoundExTest027() { Assert.IsTrue(RefinedSoundExTest("boccanegra", "B13849")); }
        [TestMethod] public void RefinedSoundExTest028() { Assert.IsTrue(RefinedSoundExTest("sextet", "S356")); }
        [TestMethod] public void RefinedSoundExTest029() { Assert.IsTrue(RefinedSoundExTest("setattributes", "S369163")); }
        [TestMethod] public void RefinedSoundExTest030() { Assert.IsTrue(RefinedSoundExTest("dsnt", "D6386")); }
        [TestMethod] public void RefinedSoundExTest031() { Assert.IsTrue(RefinedSoundExTest("chubby", "C31")); }
        [TestMethod] public void RefinedSoundExTest032() { Assert.IsTrue(RefinedSoundExTest("ooda", "O6")); }
        [TestMethod] public void RefinedSoundExTest033() { Assert.IsTrue(RefinedSoundExTest("Bressman", "B1938")); }
        [TestMethod] public void RefinedSoundExTest034() { Assert.IsTrue(RefinedSoundExTest("calendarnew", "C378698")); }
        [TestMethod] public void RefinedSoundExTest035() { Assert.IsTrue(RefinedSoundExTest("duhon", "D68")); }
        [TestMethod] public void RefinedSoundExTest036() { Assert.IsTrue(RefinedSoundExTest("nchen", "N838")); }
        [TestMethod] public void RefinedSoundExTest037() { Assert.IsTrue(RefinedSoundExTest("betjemans", "B16483")); }
        [TestMethod] public void RefinedSoundExTest038() { Assert.IsTrue(RefinedSoundExTest("Mangum", "M848")); }
        [TestMethod] public void RefinedSoundExTest039() { Assert.IsTrue(RefinedSoundExTest("cabac", "C313")); }
        [TestMethod] public void RefinedSoundExTest040() { Assert.IsTrue(RefinedSoundExTest("pantys", "P1863")); }
        [TestMethod] public void RefinedSoundExTest041() { Assert.IsTrue(RefinedSoundExTest("cofactors", "C323693")); }
        [TestMethod] public void RefinedSoundExTest042() { Assert.IsTrue(RefinedSoundExTest("clickz", "C3735")); }
        [TestMethod] public void RefinedSoundExTest043() { Assert.IsTrue(RefinedSoundExTest("chiap", "C31")); }
        [TestMethod] public void RefinedSoundExTest044() { Assert.IsTrue(RefinedSoundExTest("Dalpiaz", "D6715")); }
        [TestMethod] public void RefinedSoundExTest045() { Assert.IsTrue(RefinedSoundExTest("philosophically", "P173137")); }
        [TestMethod] public void RefinedSoundExTest046() { Assert.IsTrue(RefinedSoundExTest("backfill", "B1327")); }
        [TestMethod] public void RefinedSoundExTest047() { Assert.IsTrue(RefinedSoundExTest("Murders", "M89693")); }
        [TestMethod] public void RefinedSoundExTest048() { Assert.IsTrue(RefinedSoundExTest("ecartis", "E3963")); }
        [TestMethod] public void RefinedSoundExTest049() { Assert.IsTrue(RefinedSoundExTest("vede", "V26")); }
        [TestMethod] public void RefinedSoundExTest050() { Assert.IsTrue(RefinedSoundExTest("usoe", "U3")); }
        [TestMethod] public void RefinedSoundExTest051() { Assert.IsTrue(RefinedSoundExTest("ostara", "O369")); }
        [TestMethod] public void RefinedSoundExTest052() { Assert.IsTrue(RefinedSoundExTest("labourer", "L719")); }
        [TestMethod] public void RefinedSoundExTest053() { Assert.IsTrue(RefinedSoundExTest("speir", "S319")); }
        [TestMethod] public void RefinedSoundExTest054() { Assert.IsTrue(RefinedSoundExTest("durchaus", "D693")); }
        [TestMethod] public void RefinedSoundExTest055() { Assert.IsTrue(RefinedSoundExTest("inetformfiller", "I86298279")); }
        [TestMethod] public void RefinedSoundExTest056() { Assert.IsTrue(RefinedSoundExTest("itrs", "I693")); }
        [TestMethod] public void RefinedSoundExTest057() { Assert.IsTrue(RefinedSoundExTest("Tennant", "T686")); }
        [TestMethod] public void RefinedSoundExTest058() { Assert.IsTrue(RefinedSoundExTest("bashore", "B139")); }
        [TestMethod] public void RefinedSoundExTest059() { Assert.IsTrue(RefinedSoundExTest("lemurian", "L7898")); }
        [TestMethod] public void RefinedSoundExTest060() { Assert.IsTrue(RefinedSoundExTest("dungannon", "D6848")); }
        [TestMethod] public void RefinedSoundExTest061() { Assert.IsTrue(RefinedSoundExTest("epl", "E17")); }
        [TestMethod] public void RefinedSoundExTest062() { Assert.IsTrue(RefinedSoundExTest("grader", "G4969")); }
        [TestMethod] public void RefinedSoundExTest063() { Assert.IsTrue(RefinedSoundExTest("synchronise", "S383983")); }
        [TestMethod] public void RefinedSoundExTest064() { Assert.IsTrue(RefinedSoundExTest("gondorian", "G48698")); }
        [TestMethod] public void RefinedSoundExTest065() { Assert.IsTrue(RefinedSoundExTest("cvnet", "C3286")); }
        [TestMethod] public void RefinedSoundExTest066() { Assert.IsTrue(RefinedSoundExTest("Centers", "C38693")); }
        [TestMethod] public void RefinedSoundExTest067() { Assert.IsTrue(RefinedSoundExTest("soaks", "S3")); }
        [TestMethod] public void RefinedSoundExTest068() { Assert.IsTrue(RefinedSoundExTest("gogllle", "G47")); }
        [TestMethod] public void RefinedSoundExTest069() { Assert.IsTrue(RefinedSoundExTest("peotone", "P168")); }
        [TestMethod] public void RefinedSoundExTest070() { Assert.IsTrue(RefinedSoundExTest("Sharp", "S391")); }
        [TestMethod] public void RefinedSoundExTest071() { Assert.IsTrue(RefinedSoundExTest("mawer", "M89")); }
        [TestMethod] public void RefinedSoundExTest072() { Assert.IsTrue(RefinedSoundExTest("Morasca", "M893")); }
        [TestMethod] public void RefinedSoundExTest073() { Assert.IsTrue(RefinedSoundExTest("ticknor", "T6389")); }
        [TestMethod] public void RefinedSoundExTest074() { Assert.IsTrue(RefinedSoundExTest("beaverdale", "B12967")); }
        [TestMethod] public void RefinedSoundExTest075() { Assert.IsTrue(RefinedSoundExTest("caledonianew", "C3768")); }
        [TestMethod] public void RefinedSoundExTest076() { Assert.IsTrue(RefinedSoundExTest("wellnessdicke", "W78363")); }
        [TestMethod] public void RefinedSoundExTest077() { Assert.IsTrue(RefinedSoundExTest("Rodin", "R968")); }
        [TestMethod] public void RefinedSoundExTest078() { Assert.IsTrue(RefinedSoundExTest("bluffer", "B1729")); }
        [TestMethod] public void RefinedSoundExTest079() { Assert.IsTrue(RefinedSoundExTest("joey", "J4")); }
        [TestMethod] public void RefinedSoundExTest080() { Assert.IsTrue(RefinedSoundExTest("unbekannter", "U813869")); }
        [TestMethod] public void RefinedSoundExTest081() { Assert.IsTrue(RefinedSoundExTest("Baylor", "B179")); }
        [TestMethod] public void RefinedSoundExTest082() { Assert.IsTrue(RefinedSoundExTest("striplib", "S369171")); }
        [TestMethod] public void RefinedSoundExTest083() { Assert.IsTrue(RefinedSoundExTest("boquete", "B156")); }
        [TestMethod] public void RefinedSoundExTest084() { Assert.IsTrue(RefinedSoundExTest("geylang", "G4784")); }
        [TestMethod] public void RefinedSoundExTest085() { Assert.IsTrue(RefinedSoundExTest("Lavi", "L72")); }
        [TestMethod] public void RefinedSoundExTest086() { Assert.IsTrue(RefinedSoundExTest("moldovans", "M876283")); }
        [TestMethod] public void RefinedSoundExTest087() { Assert.IsTrue(RefinedSoundExTest("linq", "L785")); }
        [TestMethod] public void RefinedSoundExTest088() { Assert.IsTrue(RefinedSoundExTest("Kenworthy", "K3896")); }
        [TestMethod] public void RefinedSoundExTest089() { Assert.IsTrue(RefinedSoundExTest("Steckman", "S3638")); }
        [TestMethod] public void RefinedSoundExTest090() { Assert.IsTrue(RefinedSoundExTest("czechoslovakian", "C3537238")); }
        [TestMethod] public void RefinedSoundExTest091() { Assert.IsTrue(RefinedSoundExTest("marmora", "M8989")); }
        [TestMethod] public void RefinedSoundExTest092() { Assert.IsTrue(RefinedSoundExTest("Carvill", "C3927")); }
        [TestMethod] public void RefinedSoundExTest093() { Assert.IsTrue(RefinedSoundExTest("chihiro", "C39")); }
        [TestMethod] public void RefinedSoundExTest094() { Assert.IsTrue(RefinedSoundExTest("hctc", "H363")); }
        [TestMethod] public void RefinedSoundExTest095() { Assert.IsTrue(RefinedSoundExTest("nolde", "N876")); }
        [TestMethod] public void RefinedSoundExTest096() { Assert.IsTrue(RefinedSoundExTest("aerosolized", "A93756")); }
        [TestMethod] public void RefinedSoundExTest097() { Assert.IsTrue(RefinedSoundExTest("canterbury", "C386919")); }
        [TestMethod] public void RefinedSoundExTest098() { Assert.IsTrue(RefinedSoundExTest("jss", "J43")); }
        [TestMethod] public void RefinedSoundExTest099() { Assert.IsTrue(RefinedSoundExTest("rmn", "R98")); }
        [TestMethod] public void RefinedSoundExTest100() { Assert.IsTrue(RefinedSoundExTest("mazlish", "M8573")); }
        [TestMethod] public void RefinedSoundExTest101() { Assert.IsTrue(RefinedSoundExTest("faites", "F263")); }
        [TestMethod] public void RefinedSoundExTest102() { Assert.IsTrue(RefinedSoundExTest("foyer", "F29")); }
        [TestMethod] public void RefinedSoundExTest103() { Assert.IsTrue(RefinedSoundExTest("ductions", "D63683")); }
        [TestMethod] public void RefinedSoundExTest104() { Assert.IsTrue(RefinedSoundExTest("Rambo", "R981")); }
        [TestMethod] public void RefinedSoundExTest105() { Assert.IsTrue(RefinedSoundExTest("Curnutte", "C3986")); }
        [TestMethod] public void RefinedSoundExTest106() { Assert.IsTrue(RefinedSoundExTest("Feltus", "F2763")); }
        [TestMethod] public void RefinedSoundExTest107() { Assert.IsTrue(RefinedSoundExTest("forbairt", "F29196")); }
        [TestMethod] public void RefinedSoundExTest108() { Assert.IsTrue(RefinedSoundExTest("southerners", "S369893")); }
        [TestMethod] public void RefinedSoundExTest109() { Assert.IsTrue(RefinedSoundExTest("hypnotists", "H186363")); }
        [TestMethod] public void RefinedSoundExTest110() { Assert.IsTrue(RefinedSoundExTest("euphony", "E18")); }
        [TestMethod] public void RefinedSoundExTest111() { Assert.IsTrue(RefinedSoundExTest("mhpa", "M81")); }
        [TestMethod] public void RefinedSoundExTest112() { Assert.IsTrue(RefinedSoundExTest("matteotti", "M86")); }
        [TestMethod] public void RefinedSoundExTest113() { Assert.IsTrue(RefinedSoundExTest("Klande", "K3786")); }
        [TestMethod] public void RefinedSoundExTest114() { Assert.IsTrue(RefinedSoundExTest("Trudgeon", "T69648")); }
        [TestMethod] public void RefinedSoundExTest115() { Assert.IsTrue(RefinedSoundExTest("schoolhill", "S37")); }
        [TestMethod] public void RefinedSoundExTest116() { Assert.IsTrue(RefinedSoundExTest("equalizer", "E5759")); }
        [TestMethod] public void RefinedSoundExTest117() { Assert.IsTrue(RefinedSoundExTest("xnet", "X586")); }
        [TestMethod] public void RefinedSoundExTest118() { Assert.IsTrue(RefinedSoundExTest("Thell", "T67")); }
        [TestMethod] public void RefinedSoundExTest119() { Assert.IsTrue(RefinedSoundExTest("Canel", "C387")); }
        [TestMethod] public void RefinedSoundExTest120() { Assert.IsTrue(RefinedSoundExTest("vmetro", "V2869")); }
        [TestMethod] public void RefinedSoundExTest121() { Assert.IsTrue(RefinedSoundExTest("burgtheater", "B19469")); }
        [TestMethod] public void RefinedSoundExTest122() { Assert.IsTrue(RefinedSoundExTest("Berlinger", "B197849")); }
        [TestMethod] public void RefinedSoundExTest123() { Assert.IsTrue(RefinedSoundExTest("crehan", "C398")); }
        [TestMethod] public void RefinedSoundExTest124() { Assert.IsTrue(RefinedSoundExTest("abysses", "A13")); }
        [TestMethod] public void RefinedSoundExTest125() { Assert.IsTrue(RefinedSoundExTest("Hipolito", "H176")); }
        [TestMethod] public void RefinedSoundExTest126() { Assert.IsTrue(RefinedSoundExTest("splintered", "S3178696")); }
        [TestMethod] public void RefinedSoundExTest127() { Assert.IsTrue(RefinedSoundExTest("maintenace", "M8683")); }
        [TestMethod] public void RefinedSoundExTest128() { Assert.IsTrue(RefinedSoundExTest("decency", "D6383")); }
        [TestMethod] public void RefinedSoundExTest129() { Assert.IsTrue(RefinedSoundExTest("quantz", "Q5865")); }
        [TestMethod] public void RefinedSoundExTest130() { Assert.IsTrue(RefinedSoundExTest("wette", "W6")); }
        [TestMethod] public void RefinedSoundExTest131() { Assert.IsTrue(RefinedSoundExTest("Feary", "F29")); }
        [TestMethod] public void RefinedSoundExTest132() { Assert.IsTrue(RefinedSoundExTest("Cuchiara", "C39")); }
        [TestMethod] public void RefinedSoundExTest133() { Assert.IsTrue(RefinedSoundExTest("Arbon", "A918")); }
        [TestMethod] public void RefinedSoundExTest134() { Assert.IsTrue(RefinedSoundExTest("shyness", "S383")); }
        [TestMethod] public void RefinedSoundExTest135() { Assert.IsTrue(RefinedSoundExTest("Salin", "S378")); }
        [TestMethod] public void RefinedSoundExTest136() { Assert.IsTrue(RefinedSoundExTest("Zicafoose", "Z5323")); }
        [TestMethod] public void RefinedSoundExTest137() { Assert.IsTrue(RefinedSoundExTest("Menn", "M8")); }
        [TestMethod] public void RefinedSoundExTest138() { Assert.IsTrue(RefinedSoundExTest("funker", "F2839")); }
        [TestMethod] public void RefinedSoundExTest139() { Assert.IsTrue(RefinedSoundExTest("santillan", "S38678")); }
        [TestMethod] public void RefinedSoundExTest140() { Assert.IsTrue(RefinedSoundExTest("punani", "P18")); }
        [TestMethod] public void RefinedSoundExTest141() { Assert.IsTrue(RefinedSoundExTest("basa", "B13")); }
        [TestMethod] public void RefinedSoundExTest142() { Assert.IsTrue(RefinedSoundExTest("bluefin", "B1728")); }
        [TestMethod] public void RefinedSoundExTest143() { Assert.IsTrue(RefinedSoundExTest("cc", "C3")); }
        [TestMethod] public void RefinedSoundExTest144() { Assert.IsTrue(RefinedSoundExTest("zipgenius", "Z51483")); }
        [TestMethod] public void RefinedSoundExTest145() { Assert.IsTrue(RefinedSoundExTest("Kirchen", "K3938")); }
        [TestMethod] public void RefinedSoundExTest146() { Assert.IsTrue(RefinedSoundExTest("commentaar", "C3869")); }
        [TestMethod] public void RefinedSoundExTest147() { Assert.IsTrue(RefinedSoundExTest("expansive", "E51832")); }
        [TestMethod] public void RefinedSoundExTest148() { Assert.IsTrue(RefinedSoundExTest("castlebar", "C36719")); }
        [TestMethod] public void RefinedSoundExTest149() { Assert.IsTrue(RefinedSoundExTest("lft", "L726")); }
        [TestMethod] public void RefinedSoundExTest150() { Assert.IsTrue(RefinedSoundExTest("robla", "R917")); }
        [TestMethod] public void RefinedSoundExTest151() { Assert.IsTrue(RefinedSoundExTest("zarontin", "Z59868")); }
        [TestMethod] public void RefinedSoundExTest152() { Assert.IsTrue(RefinedSoundExTest("nawc", "N83")); }
        [TestMethod] public void RefinedSoundExTest153() { Assert.IsTrue(RefinedSoundExTest("resolvconf", "R9372382")); }
        [TestMethod] public void RefinedSoundExTest154() { Assert.IsTrue(RefinedSoundExTest("networker", "N86939")); }
        [TestMethod] public void RefinedSoundExTest155() { Assert.IsTrue(RefinedSoundExTest("airlins", "A9783")); }
        [TestMethod] public void RefinedSoundExTest156() { Assert.IsTrue(RefinedSoundExTest("Piskel", "P137")); }
        [TestMethod] public void RefinedSoundExTest157() { Assert.IsTrue(RefinedSoundExTest("hilson", "H738")); }
        [TestMethod] public void RefinedSoundExTest158() { Assert.IsTrue(RefinedSoundExTest("deco", "D63")); }
        [TestMethod] public void RefinedSoundExTest159() { Assert.IsTrue(RefinedSoundExTest("cents", "C3863")); }
        [TestMethod] public void RefinedSoundExTest160() { Assert.IsTrue(RefinedSoundExTest("award", "A96")); }
        [TestMethod] public void RefinedSoundExTest161() { Assert.IsTrue(RefinedSoundExTest("reykjanes", "R93483")); }
        [TestMethod] public void RefinedSoundExTest162() { Assert.IsTrue(RefinedSoundExTest("perona", "P198")); }
        [TestMethod] public void RefinedSoundExTest163() { Assert.IsTrue(RefinedSoundExTest("epistle", "E1367")); }
        [TestMethod] public void RefinedSoundExTest164() { Assert.IsTrue(RefinedSoundExTest("insound", "I8386")); }
        [TestMethod] public void RefinedSoundExTest165() { Assert.IsTrue(RefinedSoundExTest("qantas", "Q5863")); }
        [TestMethod] public void RefinedSoundExTest166() { Assert.IsTrue(RefinedSoundExTest("wholey", "W7")); }
        [TestMethod] public void RefinedSoundExTest167() { Assert.IsTrue(RefinedSoundExTest("aragona", "A948")); }
        [TestMethod] public void RefinedSoundExTest168() { Assert.IsTrue(RefinedSoundExTest("Vancheri", "V2839")); }
        [TestMethod] public void RefinedSoundExTest169() { Assert.IsTrue(RefinedSoundExTest("allocution", "A7368")); }
        [TestMethod] public void RefinedSoundExTest170() { Assert.IsTrue(RefinedSoundExTest("volodya", "V276")); }
        [TestMethod] public void RefinedSoundExTest171() { Assert.IsTrue(RefinedSoundExTest("enunciate", "E836")); }
        [TestMethod] public void RefinedSoundExTest172() { Assert.IsTrue(RefinedSoundExTest("uuuu", "U")); }
        [TestMethod] public void RefinedSoundExTest173() { Assert.IsTrue(RefinedSoundExTest("Louato", "L76")); }
        [TestMethod] public void RefinedSoundExTest174() { Assert.IsTrue(RefinedSoundExTest("Marquitta", "M8956")); }
        [TestMethod] public void RefinedSoundExTest175() { Assert.IsTrue(RefinedSoundExTest("surmountable", "S398617")); }
        [TestMethod] public void RefinedSoundExTest176() { Assert.IsTrue(RefinedSoundExTest("gaultier", "G4769")); }
        [TestMethod] public void RefinedSoundExTest177() { Assert.IsTrue(RefinedSoundExTest("dafoe", "D62")); }
        [TestMethod] public void RefinedSoundExTest178() { Assert.IsTrue(RefinedSoundExTest("Claudio", "C376")); }
        [TestMethod] public void RefinedSoundExTest179() { Assert.IsTrue(RefinedSoundExTest("ritva", "R962")); }
        [TestMethod] public void RefinedSoundExTest180() { Assert.IsTrue(RefinedSoundExTest("spunky", "S3183")); }
        [TestMethod] public void RefinedSoundExTest181() { Assert.IsTrue(RefinedSoundExTest("npov", "N812")); }
        [TestMethod] public void RefinedSoundExTest182() { Assert.IsTrue(RefinedSoundExTest("eurythmics", "E9683")); }
        [TestMethod] public void RefinedSoundExTest183() { Assert.IsTrue(RefinedSoundExTest("skittish", "S363")); }
        [TestMethod] public void RefinedSoundExTest184() { Assert.IsTrue(RefinedSoundExTest("scooter", "S369")); }
        [TestMethod] public void RefinedSoundExTest185() { Assert.IsTrue(RefinedSoundExTest("unfermented", "U82986")); }
        [TestMethod] public void RefinedSoundExTest186() { Assert.IsTrue(RefinedSoundExTest("kerridge", "K3964")); }
        [TestMethod] public void RefinedSoundExTest187() { Assert.IsTrue(RefinedSoundExTest("scenography", "S38491")); }
        [TestMethod] public void RefinedSoundExTest188() { Assert.IsTrue(RefinedSoundExTest("sahalee", "S37")); }
        [TestMethod] public void RefinedSoundExTest189() { Assert.IsTrue(RefinedSoundExTest("spooktacular", "S3136379")); }
        [TestMethod] public void RefinedSoundExTest190() { Assert.IsTrue(RefinedSoundExTest("boissons", "B1383")); }
        [TestMethod] public void RefinedSoundExTest191() { Assert.IsTrue(RefinedSoundExTest("arbete", "A916")); }
        [TestMethod] public void RefinedSoundExTest192() { Assert.IsTrue(RefinedSoundExTest("Norrick", "N893")); }
        [TestMethod] public void RefinedSoundExTest193() { Assert.IsTrue(RefinedSoundExTest("Sonnier", "S389")); }
        [TestMethod] public void RefinedSoundExTest194() { Assert.IsTrue(RefinedSoundExTest("gnomeui", "G48")); }
        [TestMethod] public void RefinedSoundExTest195() { Assert.IsTrue(RefinedSoundExTest("milian", "M878")); }
        [TestMethod] public void RefinedSoundExTest196() { Assert.IsTrue(RefinedSoundExTest("blackplanetcom", "B173178638")); }
        [TestMethod] public void RefinedSoundExTest197() { Assert.IsTrue(RefinedSoundExTest("tuned", "T686")); }
        [TestMethod] public void RefinedSoundExTest198() { Assert.IsTrue(RefinedSoundExTest("Salone", "S378")); }
        [TestMethod] public void RefinedSoundExTest199() { Assert.IsTrue(RefinedSoundExTest("marathon", "M8968")); }
        [TestMethod] public void RefinedSoundExTest200() { Assert.IsTrue(RefinedSoundExTest("layoffs", "L723")); }
        [TestMethod] public void RefinedSoundExTest201() { Assert.IsTrue(RefinedSoundExTest("hotek", "H63")); }
        [TestMethod] public void RefinedSoundExTest202() { Assert.IsTrue(RefinedSoundExTest("emme", "E8")); }
        [TestMethod] public void RefinedSoundExTest203() { Assert.IsTrue(RefinedSoundExTest("amarasinghe", "A89384")); }
        [TestMethod] public void RefinedSoundExTest204() { Assert.IsTrue(RefinedSoundExTest("midas", "M863")); }
        [TestMethod] public void RefinedSoundExTest205() { Assert.IsTrue(RefinedSoundExTest("inhaltsangabe", "I8763841")); }
        [TestMethod] public void RefinedSoundExTest206() { Assert.IsTrue(RefinedSoundExTest("smow", "S38")); }
        [TestMethod] public void RefinedSoundExTest207() { Assert.IsTrue(RefinedSoundExTest("policing", "P17384")); }
        [TestMethod] public void RefinedSoundExTest208() { Assert.IsTrue(RefinedSoundExTest("usmf", "U382")); }
        [TestMethod] public void RefinedSoundExTest209() { Assert.IsTrue(RefinedSoundExTest("inferred", "I8296")); }
        [TestMethod] public void RefinedSoundExTest210() { Assert.IsTrue(RefinedSoundExTest("Eaglen", "E478")); }
        [TestMethod] public void RefinedSoundExTest211() { Assert.IsTrue(RefinedSoundExTest("dralle", "D697")); }
        [TestMethod] public void RefinedSoundExTest212() { Assert.IsTrue(RefinedSoundExTest("kalmus", "K3783")); }
        [TestMethod] public void RefinedSoundExTest213() { Assert.IsTrue(RefinedSoundExTest("nork", "N893")); }
        [TestMethod] public void RefinedSoundExTest214() { Assert.IsTrue(RefinedSoundExTest("Waterston", "W69368")); }
        [TestMethod] public void RefinedSoundExTest215() { Assert.IsTrue(RefinedSoundExTest("penalised", "P18736")); }
        [TestMethod] public void RefinedSoundExTest216() { Assert.IsTrue(RefinedSoundExTest("Lupacchino", "L7138")); }
        [TestMethod] public void RefinedSoundExTest217() { Assert.IsTrue(RefinedSoundExTest("getgid", "G4646")); }
        [TestMethod] public void RefinedSoundExTest218() { Assert.IsTrue(RefinedSoundExTest("kever", "K329")); }
        [TestMethod] public void RefinedSoundExTest219() { Assert.IsTrue(RefinedSoundExTest("pallavicini", "P17238")); }
        [TestMethod] public void RefinedSoundExTest220() { Assert.IsTrue(RefinedSoundExTest("Pais", "P13")); }
        [TestMethod] public void RefinedSoundExTest221() { Assert.IsTrue(RefinedSoundExTest("youghiogheny", "Y48")); }
        [TestMethod] public void RefinedSoundExTest222() { Assert.IsTrue(RefinedSoundExTest("Catherina", "C3698")); }
        [TestMethod] public void RefinedSoundExTest223() { Assert.IsTrue(RefinedSoundExTest("Givant", "G4286")); }
        [TestMethod] public void RefinedSoundExTest224() { Assert.IsTrue(RefinedSoundExTest("koffi", "K32")); }
        [TestMethod] public void RefinedSoundExTest225() { Assert.IsTrue(RefinedSoundExTest("troutbeck", "T69613")); }
        [TestMethod] public void RefinedSoundExTest226() { Assert.IsTrue(RefinedSoundExTest("moreelse", "M8973")); }
        [TestMethod] public void RefinedSoundExTest227() { Assert.IsTrue(RefinedSoundExTest("seacrest", "S3936")); }
        [TestMethod] public void RefinedSoundExTest228() { Assert.IsTrue(RefinedSoundExTest("ufj", "U24")); }
        [TestMethod] public void RefinedSoundExTest229() { Assert.IsTrue(RefinedSoundExTest("dereferences", "D692983")); }
        [TestMethod] public void RefinedSoundExTest230() { Assert.IsTrue(RefinedSoundExTest("sarena", "S398")); }
        [TestMethod] public void RefinedSoundExTest231() { Assert.IsTrue(RefinedSoundExTest("Kurt", "K396")); }
        [TestMethod] public void RefinedSoundExTest232() { Assert.IsTrue(RefinedSoundExTest("comanche", "C383")); }
        [TestMethod] public void RefinedSoundExTest233() { Assert.IsTrue(RefinedSoundExTest("chersoness", "C39383")); }
        [TestMethod] public void RefinedSoundExTest234() { Assert.IsTrue(RefinedSoundExTest("cd", "C36")); }
        [TestMethod] public void RefinedSoundExTest235() { Assert.IsTrue(RefinedSoundExTest("merzky", "M8953")); }
        [TestMethod] public void RefinedSoundExTest236() { Assert.IsTrue(RefinedSoundExTest("Nordsiek", "N8963")); }
        [TestMethod] public void RefinedSoundExTest237() { Assert.IsTrue(RefinedSoundExTest("samus", "S383")); }
        [TestMethod] public void RefinedSoundExTest238() { Assert.IsTrue(RefinedSoundExTest("tougher", "T649")); }
        [TestMethod] public void RefinedSoundExTest239() { Assert.IsTrue(RefinedSoundExTest("monodoc", "M863")); }
        [TestMethod] public void RefinedSoundExTest240() { Assert.IsTrue(RefinedSoundExTest("deepings", "D61843")); }
        [TestMethod] public void RefinedSoundExTest241() { Assert.IsTrue(RefinedSoundExTest("datel", "D67")); }
        [TestMethod] public void RefinedSoundExTest242() { Assert.IsTrue(RefinedSoundExTest("Stockett", "S3636")); }
        [TestMethod] public void RefinedSoundExTest243() { Assert.IsTrue(RefinedSoundExTest("bryum", "B198")); }
        [TestMethod] public void RefinedSoundExTest244() { Assert.IsTrue(RefinedSoundExTest("surveyed", "S3926")); }
        [TestMethod] public void RefinedSoundExTest245() { Assert.IsTrue(RefinedSoundExTest("microcephaly", "M839317")); }
        [TestMethod] public void RefinedSoundExTest246() { Assert.IsTrue(RefinedSoundExTest("trimoxazole", "T69857")); }
        [TestMethod] public void RefinedSoundExTest247() { Assert.IsTrue(RefinedSoundExTest("bastide", "B136")); }
        [TestMethod] public void RefinedSoundExTest248() { Assert.IsTrue(RefinedSoundExTest("lipo", "L71")); }
        [TestMethod] public void RefinedSoundExTest249() { Assert.IsTrue(RefinedSoundExTest("Bosket", "B136")); }
        [TestMethod] public void RefinedSoundExTest250() { Assert.IsTrue(RefinedSoundExTest("oroms", "O983")); }
        [TestMethod] public void RefinedSoundExTest251() { Assert.IsTrue(RefinedSoundExTest("vandenburg", "V2868194")); }
        [TestMethod] public void RefinedSoundExTest252() { Assert.IsTrue(RefinedSoundExTest("wirtschaftsforschung", "W96326329384")); }
        [TestMethod] public void RefinedSoundExTest253() { Assert.IsTrue(RefinedSoundExTest("lilypond", "L7186")); }
        [TestMethod] public void RefinedSoundExTest254() { Assert.IsTrue(RefinedSoundExTest("mouthfeel", "M8627")); }
        [TestMethod] public void RefinedSoundExTest255() { Assert.IsTrue(RefinedSoundExTest("wwwunibancocombr", "W8183819")); }
        [TestMethod] public void RefinedSoundExTest256() { Assert.IsTrue(RefinedSoundExTest("Worster", "W9369")); }
        [TestMethod] public void RefinedSoundExTest257() { Assert.IsTrue(RefinedSoundExTest("Ahmad", "A86")); }
        [TestMethod] public void RefinedSoundExTest258() { Assert.IsTrue(RefinedSoundExTest("sweetser", "S3639")); }
        [TestMethod] public void RefinedSoundExTest259() { Assert.IsTrue(RefinedSoundExTest("vsepr", "V2319")); }
        [TestMethod] public void RefinedSoundExTest260() { Assert.IsTrue(RefinedSoundExTest("dput", "D616")); }
        [TestMethod] public void RefinedSoundExTest261() { Assert.IsTrue(RefinedSoundExTest("austlit", "A3676")); }
        [TestMethod] public void RefinedSoundExTest262() { Assert.IsTrue(RefinedSoundExTest("Clemen", "C378")); }
        [TestMethod] public void RefinedSoundExTest263() { Assert.IsTrue(RefinedSoundExTest("phrva", "P192")); }
        [TestMethod] public void RefinedSoundExTest264() { Assert.IsTrue(RefinedSoundExTest("weipa", "W1")); }
        [TestMethod] public void RefinedSoundExTest265() { Assert.IsTrue(RefinedSoundExTest("Schrantz", "S39865")); }
        [TestMethod] public void RefinedSoundExTest266() { Assert.IsTrue(RefinedSoundExTest("meany", "M8")); }
        [TestMethod] public void RefinedSoundExTest267() { Assert.IsTrue(RefinedSoundExTest("hodgepodge", "H64164")); }
        [TestMethod] public void RefinedSoundExTest268() { Assert.IsTrue(RefinedSoundExTest("knuble", "K3817")); }
        [TestMethod] public void RefinedSoundExTest269() { Assert.IsTrue(RefinedSoundExTest("caniglia", "C3847")); }
        [TestMethod] public void RefinedSoundExTest270() { Assert.IsTrue(RefinedSoundExTest("blowjobsasics", "B17413")); }
        [TestMethod] public void RefinedSoundExTest271() { Assert.IsTrue(RefinedSoundExTest("flyjacket", "F27436")); }
        [TestMethod] public void RefinedSoundExTest272() { Assert.IsTrue(RefinedSoundExTest("galatian", "G4768")); }
        [TestMethod] public void RefinedSoundExTest273() { Assert.IsTrue(RefinedSoundExTest("hotsel", "H637")); }
        [TestMethod] public void RefinedSoundExTest274() { Assert.IsTrue(RefinedSoundExTest("autorun", "A698")); }
        [TestMethod] public void RefinedSoundExTest275() { Assert.IsTrue(RefinedSoundExTest("cocoon", "C38")); }
        [TestMethod] public void RefinedSoundExTest276() { Assert.IsTrue(RefinedSoundExTest("kooks", "K3")); }
        [TestMethod] public void RefinedSoundExTest277() { Assert.IsTrue(RefinedSoundExTest("endocrinol", "E863987")); }
        [TestMethod] public void RefinedSoundExTest278() { Assert.IsTrue(RefinedSoundExTest("mesages", "M8343")); }
        [TestMethod] public void RefinedSoundExTest279() { Assert.IsTrue(RefinedSoundExTest("Disney", "D638")); }
        [TestMethod] public void RefinedSoundExTest280() { Assert.IsTrue(RefinedSoundExTest("speedline", "S31678")); }
        [TestMethod] public void RefinedSoundExTest281() { Assert.IsTrue(RefinedSoundExTest("gabaldon", "G41768")); }
        [TestMethod] public void RefinedSoundExTest282() { Assert.IsTrue(RefinedSoundExTest("margaux", "M8945")); }
        [TestMethod] public void RefinedSoundExTest283() { Assert.IsTrue(RefinedSoundExTest("housecalls", "H373")); }
        [TestMethod] public void RefinedSoundExTest284() { Assert.IsTrue(RefinedSoundExTest("siltation", "S3768")); }
        [TestMethod] public void RefinedSoundExTest285() { Assert.IsTrue(RefinedSoundExTest("automatic", "A6863")); }
        [TestMethod] public void RefinedSoundExTest286() { Assert.IsTrue(RefinedSoundExTest("freakshow", "F293")); }
        [TestMethod] public void RefinedSoundExTest287() { Assert.IsTrue(RefinedSoundExTest("gorojovsky", "G49423")); }
        [TestMethod] public void RefinedSoundExTest288() { Assert.IsTrue(RefinedSoundExTest("milwaukie", "M873")); }
        [TestMethod] public void RefinedSoundExTest289() { Assert.IsTrue(RefinedSoundExTest("wwwgap", "W41")); }
        [TestMethod] public void RefinedSoundExTest290() { Assert.IsTrue(RefinedSoundExTest("autm", "A68")); }
        [TestMethod] public void RefinedSoundExTest291() { Assert.IsTrue(RefinedSoundExTest("borromini", "B198")); }
        [TestMethod] public void RefinedSoundExTest292() { Assert.IsTrue(RefinedSoundExTest("zpp", "Z51")); }
        [TestMethod] public void RefinedSoundExTest293() { Assert.IsTrue(RefinedSoundExTest("Penovich", "P1823")); }
        [TestMethod] public void RefinedSoundExTest294() { Assert.IsTrue(RefinedSoundExTest("domine", "D68")); }
        [TestMethod] public void RefinedSoundExTest295() { Assert.IsTrue(RefinedSoundExTest("caves", "C323")); }
        [TestMethod] public void RefinedSoundExTest296() { Assert.IsTrue(RefinedSoundExTest("uato", "U6")); }
        [TestMethod] public void RefinedSoundExTest297() { Assert.IsTrue(RefinedSoundExTest("tiltonsville", "T6768327")); }
        [TestMethod] public void RefinedSoundExTest298() { Assert.IsTrue(RefinedSoundExTest("Ken", "K38")); }
        [TestMethod] public void RefinedSoundExTest299() { Assert.IsTrue(RefinedSoundExTest("Delonais", "D6783")); }
        [TestMethod] public void RefinedSoundExTest300() { Assert.IsTrue(RefinedSoundExTest("conniption", "C38168")); }
        [TestMethod] public void RefinedSoundExTest301() { Assert.IsTrue(RefinedSoundExTest("Wenske", "W83")); }
        [TestMethod] public void RefinedSoundExTest302() { Assert.IsTrue(RefinedSoundExTest("cautery", "C369")); }
        [TestMethod] public void RefinedSoundExTest303() { Assert.IsTrue(RefinedSoundExTest("barbourville", "B191927")); }
        [TestMethod] public void RefinedSoundExTest304() { Assert.IsTrue(RefinedSoundExTest("departamentos", "D6196863")); }
        [TestMethod] public void RefinedSoundExTest305() { Assert.IsTrue(RefinedSoundExTest("weaponry", "W189")); }
        [TestMethod] public void RefinedSoundExTest306() { Assert.IsTrue(RefinedSoundExTest("Haggett", "H46")); }
        [TestMethod] public void RefinedSoundExTest307() { Assert.IsTrue(RefinedSoundExTest("martinville", "M896827")); }
        [TestMethod] public void RefinedSoundExTest308() { Assert.IsTrue(RefinedSoundExTest("stina", "S368")); }
        [TestMethod] public void RefinedSoundExTest309() { Assert.IsTrue(RefinedSoundExTest("Rubottom", "R9168")); }
        [TestMethod] public void RefinedSoundExTest310() { Assert.IsTrue(RefinedSoundExTest("Soyke", "S3")); }
        [TestMethod] public void RefinedSoundExTest311() { Assert.IsTrue(RefinedSoundExTest("corse", "C393")); }
        [TestMethod] public void RefinedSoundExTest312() { Assert.IsTrue(RefinedSoundExTest("totalling", "T6784")); }
        [TestMethod] public void RefinedSoundExTest313() { Assert.IsTrue(RefinedSoundExTest("kuppam", "K318")); }
        [TestMethod] public void RefinedSoundExTest314() { Assert.IsTrue(RefinedSoundExTest("ftpadmin", "F26168")); }
        [TestMethod] public void RefinedSoundExTest315() { Assert.IsTrue(RefinedSoundExTest("Forst", "F2936")); }
        [TestMethod] public void RefinedSoundExTest316() { Assert.IsTrue(RefinedSoundExTest("Ashauer", "A39")); }
        [TestMethod] public void RefinedSoundExTest317() { Assert.IsTrue(RefinedSoundExTest("ashtanga", "A3684")); }
        [TestMethod] public void RefinedSoundExTest318() { Assert.IsTrue(RefinedSoundExTest("alonissos", "A783")); }
        [TestMethod] public void RefinedSoundExTest319() { Assert.IsTrue(RefinedSoundExTest("Chimilio", "C387")); }
        [TestMethod] public void RefinedSoundExTest320() { Assert.IsTrue(RefinedSoundExTest("deafbazon", "D62158")); }
        [TestMethod] public void RefinedSoundExTest321() { Assert.IsTrue(RefinedSoundExTest("psmb", "P1381")); }
        [TestMethod] public void RefinedSoundExTest322() { Assert.IsTrue(RefinedSoundExTest("Ferraraccio", "F293")); }
        [TestMethod] public void RefinedSoundExTest323() { Assert.IsTrue(RefinedSoundExTest("fractionated", "F293686")); }
        [TestMethod] public void RefinedSoundExTest324() { Assert.IsTrue(RefinedSoundExTest("rrd", "R96")); }
        [TestMethod] public void RefinedSoundExTest325() { Assert.IsTrue(RefinedSoundExTest("luminosities", "L78363")); }
        [TestMethod] public void RefinedSoundExTest326() { Assert.IsTrue(RefinedSoundExTest("Platzer", "P17659")); }
        [TestMethod] public void RefinedSoundExTest327() { Assert.IsTrue(RefinedSoundExTest("modulator", "M86769")); }
        [TestMethod] public void RefinedSoundExTest328() { Assert.IsTrue(RefinedSoundExTest("tyneside", "T6836")); }
        [TestMethod] public void RefinedSoundExTest329() { Assert.IsTrue(RefinedSoundExTest("nonuser", "N839")); }
        [TestMethod] public void RefinedSoundExTest330() { Assert.IsTrue(RefinedSoundExTest("haspel", "H317")); }
        [TestMethod] public void RefinedSoundExTest331() { Assert.IsTrue(RefinedSoundExTest("cortex", "C3965")); }
        [TestMethod] public void RefinedSoundExTest332() { Assert.IsTrue(RefinedSoundExTest("vechicle", "V237")); }
        [TestMethod] public void RefinedSoundExTest333() { Assert.IsTrue(RefinedSoundExTest("epinions", "E183")); }
        [TestMethod] public void RefinedSoundExTest334() { Assert.IsTrue(RefinedSoundExTest("wwwusmintgov", "W38642")); }
        [TestMethod] public void RefinedSoundExTest335() { Assert.IsTrue(RefinedSoundExTest("katies", "K363")); }
        [TestMethod] public void RefinedSoundExTest336() { Assert.IsTrue(RefinedSoundExTest("aminosalicylic", "A837373")); }
        [TestMethod] public void RefinedSoundExTest337() { Assert.IsTrue(RefinedSoundExTest("mmegi", "M84")); }
        [TestMethod] public void RefinedSoundExTest338() { Assert.IsTrue(RefinedSoundExTest("sbir", "S319")); }
        [TestMethod] public void RefinedSoundExTest339() { Assert.IsTrue(RefinedSoundExTest("learned", "L7986")); }
        [TestMethod] public void RefinedSoundExTest340() { Assert.IsTrue(RefinedSoundExTest("supris", "S3193")); }
        [TestMethod] public void RefinedSoundExTest341() { Assert.IsTrue(RefinedSoundExTest("mozarteum", "M85968")); }
        [TestMethod] public void RefinedSoundExTest342() { Assert.IsTrue(RefinedSoundExTest("selzer", "S3759")); }
        [TestMethod] public void RefinedSoundExTest343() { Assert.IsTrue(RefinedSoundExTest("tmug", "T684")); }
        [TestMethod] public void RefinedSoundExTest344() { Assert.IsTrue(RefinedSoundExTest("Kisto", "K36")); }
        [TestMethod] public void RefinedSoundExTest345() { Assert.IsTrue(RefinedSoundExTest("iib", "I1")); }
        [TestMethod] public void RefinedSoundExTest346() { Assert.IsTrue(RefinedSoundExTest("wwwincredimail", "W839687")); }
        [TestMethod] public void RefinedSoundExTest347() { Assert.IsTrue(RefinedSoundExTest("izpack", "I513")); }
        [TestMethod] public void RefinedSoundExTest348() { Assert.IsTrue(RefinedSoundExTest("gaymovie", "G482")); }
        [TestMethod] public void RefinedSoundExTest349() { Assert.IsTrue(RefinedSoundExTest("Buchholz", "B1375")); }
        [TestMethod] public void RefinedSoundExTest350() { Assert.IsTrue(RefinedSoundExTest("culcairn", "C37398")); }
        [TestMethod] public void RefinedSoundExTest351() { Assert.IsTrue(RefinedSoundExTest("barys", "B193")); }
        [TestMethod] public void RefinedSoundExTest352() { Assert.IsTrue(RefinedSoundExTest("burets", "B1963")); }
        [TestMethod] public void RefinedSoundExTest353() { Assert.IsTrue(RefinedSoundExTest("Sorce", "S393")); }
        [TestMethod] public void RefinedSoundExTest354() { Assert.IsTrue(RefinedSoundExTest("chimique", "C385")); }
        [TestMethod] public void RefinedSoundExTest355() { Assert.IsTrue(RefinedSoundExTest("kitada", "K36")); }
        [TestMethod] public void RefinedSoundExTest356() { Assert.IsTrue(RefinedSoundExTest("Engeman", "E848")); }
        [TestMethod] public void RefinedSoundExTest357() { Assert.IsTrue(RefinedSoundExTest("raveendran", "R928698")); }
        [TestMethod] public void RefinedSoundExTest358() { Assert.IsTrue(RefinedSoundExTest("Bendele", "B1867")); }
        [TestMethod] public void RefinedSoundExTest359() { Assert.IsTrue(RefinedSoundExTest("Pawlitschek", "P1763")); }
        [TestMethod] public void RefinedSoundExTest360() { Assert.IsTrue(RefinedSoundExTest("hogfather", "H4269")); }
        [TestMethod] public void RefinedSoundExTest361() { Assert.IsTrue(RefinedSoundExTest("eyedrum", "E698")); }
        [TestMethod] public void RefinedSoundExTest362() { Assert.IsTrue(RefinedSoundExTest("Ferrara", "F29")); }
        [TestMethod] public void RefinedSoundExTest363() { Assert.IsTrue(RefinedSoundExTest("zhuh", "Z5")); }
        [TestMethod] public void RefinedSoundExTest364() { Assert.IsTrue(RefinedSoundExTest("zodiak", "Z563")); }
        [TestMethod] public void RefinedSoundExTest365() { Assert.IsTrue(RefinedSoundExTest("pchcom", "P138")); }
        [TestMethod] public void RefinedSoundExTest366() { Assert.IsTrue(RefinedSoundExTest("conferees", "C38293")); }
        [TestMethod] public void RefinedSoundExTest367() { Assert.IsTrue(RefinedSoundExTest("Decillis", "D6373")); }
        [TestMethod] public void RefinedSoundExTest368() { Assert.IsTrue(RefinedSoundExTest("downloar", "D6879")); }
        [TestMethod] public void RefinedSoundExTest369() { Assert.IsTrue(RefinedSoundExTest("shard", "S396")); }
        [TestMethod] public void RefinedSoundExTest370() { Assert.IsTrue(RefinedSoundExTest("fajr", "F249")); }
        [TestMethod] public void RefinedSoundExTest371() { Assert.IsTrue(RefinedSoundExTest("quisque", "Q535")); }
        [TestMethod] public void RefinedSoundExTest372() { Assert.IsTrue(RefinedSoundExTest("winterizing", "W869584")); }
        [TestMethod] public void RefinedSoundExTest373() { Assert.IsTrue(RefinedSoundExTest("referate", "R9296")); }
        [TestMethod] public void RefinedSoundExTest374() { Assert.IsTrue(RefinedSoundExTest("nuxone", "N858")); }
        [TestMethod] public void RefinedSoundExTest375() { Assert.IsTrue(RefinedSoundExTest("Racheal", "R937")); }
        [TestMethod] public void RefinedSoundExTest376() { Assert.IsTrue(RefinedSoundExTest("bizben", "B1518")); }
        [TestMethod] public void RefinedSoundExTest377() { Assert.IsTrue(RefinedSoundExTest("musictalk", "M83673")); }
        [TestMethod] public void RefinedSoundExTest378() { Assert.IsTrue(RefinedSoundExTest("ogoal", "O47")); }
        [TestMethod] public void RefinedSoundExTest379() { Assert.IsTrue(RefinedSoundExTest("Skoff", "S32")); }
        [TestMethod] public void RefinedSoundExTest380() { Assert.IsTrue(RefinedSoundExTest("Seehusen", "S38")); }
        [TestMethod] public void RefinedSoundExTest381() { Assert.IsTrue(RefinedSoundExTest("Reim", "R98")); }
        [TestMethod] public void RefinedSoundExTest382() { Assert.IsTrue(RefinedSoundExTest("Yoh", "Y")); }
        [TestMethod] public void RefinedSoundExTest383() { Assert.IsTrue(RefinedSoundExTest("gapi", "G41")); }
        [TestMethod] public void RefinedSoundExTest384() { Assert.IsTrue(RefinedSoundExTest("Brightbill", "B194617")); }
        [TestMethod] public void RefinedSoundExTest385() { Assert.IsTrue(RefinedSoundExTest("shuey", "S3")); }
        [TestMethod] public void RefinedSoundExTest386() { Assert.IsTrue(RefinedSoundExTest("posium", "P138")); }
        [TestMethod] public void RefinedSoundExTest387() { Assert.IsTrue(RefinedSoundExTest("Falknor", "F27389")); }
        [TestMethod] public void RefinedSoundExTest388() { Assert.IsTrue(RefinedSoundExTest("ucat", "U36")); }
        [TestMethod] public void RefinedSoundExTest389() { Assert.IsTrue(RefinedSoundExTest("properspace", "P1919313")); }
        [TestMethod] public void RefinedSoundExTest390() { Assert.IsTrue(RefinedSoundExTest("showimg", "S384")); }
        [TestMethod] public void RefinedSoundExTest391() { Assert.IsTrue(RefinedSoundExTest("Montecillo", "M8637")); }
        [TestMethod] public void RefinedSoundExTest392() { Assert.IsTrue(RefinedSoundExTest("sajak", "S343")); }
        [TestMethod] public void RefinedSoundExTest393() { Assert.IsTrue(RefinedSoundExTest("maturbation", "M869168")); }
        [TestMethod] public void RefinedSoundExTest394() { Assert.IsTrue(RefinedSoundExTest("Lettie", "L76")); }
        [TestMethod] public void RefinedSoundExTest395() { Assert.IsTrue(RefinedSoundExTest("clauss", "C373")); }
        [TestMethod] public void RefinedSoundExTest396() { Assert.IsTrue(RefinedSoundExTest("scheiber", "S319")); }
        [TestMethod] public void RefinedSoundExTest397() { Assert.IsTrue(RefinedSoundExTest("matp", "M861")); }
        [TestMethod] public void RefinedSoundExTest398() { Assert.IsTrue(RefinedSoundExTest("mervtormel", "M8926987")); }
        [TestMethod] public void RefinedSoundExTest399() { Assert.IsTrue(RefinedSoundExTest("guanahani", "G48")); }
        [TestMethod] public void RefinedSoundExTest400() { Assert.IsTrue(RefinedSoundExTest("citement", "C3686")); }
        [TestMethod] public void RefinedSoundExTest401() { Assert.IsTrue(RefinedSoundExTest("immu", "I8")); }
        [TestMethod] public void RefinedSoundExTest402() { Assert.IsTrue(RefinedSoundExTest("virulence", "V29783")); }
        [TestMethod] public void RefinedSoundExTest403() { Assert.IsTrue(RefinedSoundExTest("kussa", "K3")); }
        [TestMethod] public void RefinedSoundExTest404() { Assert.IsTrue(RefinedSoundExTest("gso", "G43")); }
        [TestMethod] public void RefinedSoundExTest405() { Assert.IsTrue(RefinedSoundExTest("webviajes", "W1243")); }
        [TestMethod] public void RefinedSoundExTest406() { Assert.IsTrue(RefinedSoundExTest("ldwork", "L7693")); }
        [TestMethod] public void RefinedSoundExTest407() { Assert.IsTrue(RefinedSoundExTest("verses", "V293")); }
        [TestMethod] public void RefinedSoundExTest408() { Assert.IsTrue(RefinedSoundExTest("sondes", "S3863")); }
        [TestMethod] public void RefinedSoundExTest409() { Assert.IsTrue(RefinedSoundExTest("freshpair", "F29319")); }
        [TestMethod] public void RefinedSoundExTest410() { Assert.IsTrue(RefinedSoundExTest("licorne", "L7398")); }
        [TestMethod] public void RefinedSoundExTest411() { Assert.IsTrue(RefinedSoundExTest("Vanis", "V283")); }
        [TestMethod] public void RefinedSoundExTest412() { Assert.IsTrue(RefinedSoundExTest("Buena", "B18")); }
        [TestMethod] public void RefinedSoundExTest413() { Assert.IsTrue(RefinedSoundExTest("Tauares", "T693")); }
        [TestMethod] public void RefinedSoundExTest414() { Assert.IsTrue(RefinedSoundExTest("ikus", "I3")); }
        [TestMethod] public void RefinedSoundExTest415() { Assert.IsTrue(RefinedSoundExTest("genrebox", "G48915")); }
        [TestMethod] public void RefinedSoundExTest416() { Assert.IsTrue(RefinedSoundExTest("rth", "R96")); }
        [TestMethod] public void RefinedSoundExTest417() { Assert.IsTrue(RefinedSoundExTest("Spaun", "S318")); }
        [TestMethod] public void RefinedSoundExTest418() { Assert.IsTrue(RefinedSoundExTest("wiersbe", "W931")); }
        [TestMethod] public void RefinedSoundExTest419() { Assert.IsTrue(RefinedSoundExTest("dad", "D6")); }
        [TestMethod] public void RefinedSoundExTest420() { Assert.IsTrue(RefinedSoundExTest("tus", "T63")); }
        [TestMethod] public void RefinedSoundExTest421() { Assert.IsTrue(RefinedSoundExTest("Weidert", "W696")); }
        [TestMethod] public void RefinedSoundExTest422() { Assert.IsTrue(RefinedSoundExTest("rijke", "R943")); }
        [TestMethod] public void RefinedSoundExTest423() { Assert.IsTrue(RefinedSoundExTest("fischbein", "F2318")); }
        [TestMethod] public void RefinedSoundExTest424() { Assert.IsTrue(RefinedSoundExTest("fbeye", "F21")); }
        [TestMethod] public void RefinedSoundExTest425() { Assert.IsTrue(RefinedSoundExTest("hagerty", "H496")); }
        [TestMethod] public void RefinedSoundExTest426() { Assert.IsTrue(RefinedSoundExTest("Hollendonner", "H78689")); }
        [TestMethod] public void RefinedSoundExTest427() { Assert.IsTrue(RefinedSoundExTest("Huitzacua", "H653")); }
        [TestMethod] public void RefinedSoundExTest428() { Assert.IsTrue(RefinedSoundExTest("subjunctive", "S3148362")); }
        [TestMethod] public void RefinedSoundExTest429() { Assert.IsTrue(RefinedSoundExTest("implored", "I81796")); }
        [TestMethod] public void RefinedSoundExTest430() { Assert.IsTrue(RefinedSoundExTest("pompeius", "P1813")); }
        [TestMethod] public void RefinedSoundExTest431() { Assert.IsTrue(RefinedSoundExTest("afleet", "A276")); }
        [TestMethod] public void RefinedSoundExTest432() { Assert.IsTrue(RefinedSoundExTest("iacc", "I3")); }
        [TestMethod] public void RefinedSoundExTest433() { Assert.IsTrue(RefinedSoundExTest("sabalos", "S3173")); }
        [TestMethod] public void RefinedSoundExTest434() { Assert.IsTrue(RefinedSoundExTest("Abdi", "A16")); }
        [TestMethod] public void RefinedSoundExTest435() { Assert.IsTrue(RefinedSoundExTest("microinsurance", "M83983983")); }
        [TestMethod] public void RefinedSoundExTest436() { Assert.IsTrue(RefinedSoundExTest("audiobook", "A613")); }
        [TestMethod] public void RefinedSoundExTest437() { Assert.IsTrue(RefinedSoundExTest("fulpmes", "F27183")); }
        [TestMethod] public void RefinedSoundExTest438() { Assert.IsTrue(RefinedSoundExTest("registreren", "R943698")); }
        [TestMethod] public void RefinedSoundExTest439() { Assert.IsTrue(RefinedSoundExTest("megapath", "M8416")); }
        [TestMethod] public void RefinedSoundExTest440() { Assert.IsTrue(RefinedSoundExTest("prestidigitation", "P1936468")); }
        [TestMethod] public void RefinedSoundExTest441() { Assert.IsTrue(RefinedSoundExTest("wby", "W1")); }
        [TestMethod] public void RefinedSoundExTest442() { Assert.IsTrue(RefinedSoundExTest("vorschau", "V293")); }
        [TestMethod] public void RefinedSoundExTest443() { Assert.IsTrue(RefinedSoundExTest("Albertha", "A7196")); }
        [TestMethod] public void RefinedSoundExTest444() { Assert.IsTrue(RefinedSoundExTest("aspalpha", "A3171")); }
        [TestMethod] public void RefinedSoundExTest445() { Assert.IsTrue(RefinedSoundExTest("Belden", "B1768")); }
        [TestMethod] public void RefinedSoundExTest446() { Assert.IsTrue(RefinedSoundExTest("deterministic", "D698363")); }
        [TestMethod] public void RefinedSoundExTest447() { Assert.IsTrue(RefinedSoundExTest("philosophique", "P17315")); }
        [TestMethod] public void RefinedSoundExTest448() { Assert.IsTrue(RefinedSoundExTest("kleinen", "K378")); }
        [TestMethod] public void RefinedSoundExTest449() { Assert.IsTrue(RefinedSoundExTest("logouri", "L749")); }
        [TestMethod] public void RefinedSoundExTest450() { Assert.IsTrue(RefinedSoundExTest("xbl", "X517")); }
        [TestMethod] public void RefinedSoundExTest451() { Assert.IsTrue(RefinedSoundExTest("iz", "I5")); }
        [TestMethod] public void RefinedSoundExTest452() { Assert.IsTrue(RefinedSoundExTest("throckmorton", "T6938968")); }
        [TestMethod] public void RefinedSoundExTest453() { Assert.IsTrue(RefinedSoundExTest("condesa", "C3863")); }
        [TestMethod] public void RefinedSoundExTest454() { Assert.IsTrue(RefinedSoundExTest("Mook", "M83")); }
        [TestMethod] public void RefinedSoundExTest455() { Assert.IsTrue(RefinedSoundExTest("medseek", "M863")); }
        [TestMethod] public void RefinedSoundExTest456() { Assert.IsTrue(RefinedSoundExTest("chugalug", "C3474")); }
        [TestMethod] public void RefinedSoundExTest457() { Assert.IsTrue(RefinedSoundExTest("olms", "O783")); }
        [TestMethod] public void RefinedSoundExTest458() { Assert.IsTrue(RefinedSoundExTest("bogo", "B14")); }
        [TestMethod] public void RefinedSoundExTest459() { Assert.IsTrue(RefinedSoundExTest("essing", "E384")); }
        [TestMethod] public void RefinedSoundExTest460() { Assert.IsTrue(RefinedSoundExTest("rarden", "R968")); }
        [TestMethod] public void RefinedSoundExTest461() { Assert.IsTrue(RefinedSoundExTest("mittlere", "M8679")); }
        [TestMethod] public void RefinedSoundExTest462() { Assert.IsTrue(RefinedSoundExTest("Borsa", "B193")); }
        [TestMethod] public void RefinedSoundExTest463() { Assert.IsTrue(RefinedSoundExTest("Ainslie", "A837")); }
        [TestMethod] public void RefinedSoundExTest464() { Assert.IsTrue(RefinedSoundExTest("Ganska", "G483")); }
        [TestMethod] public void RefinedSoundExTest465() { Assert.IsTrue(RefinedSoundExTest("miv", "M82")); }
        [TestMethod] public void RefinedSoundExTest466() { Assert.IsTrue(RefinedSoundExTest("concessions", "C38383")); }
        [TestMethod] public void RefinedSoundExTest467() { Assert.IsTrue(RefinedSoundExTest("distinguished", "D6368436")); }
        [TestMethod] public void RefinedSoundExTest468() { Assert.IsTrue(RefinedSoundExTest("cano", "C38")); }
        [TestMethod] public void RefinedSoundExTest469() { Assert.IsTrue(RefinedSoundExTest("plumper", "P17819")); }
        [TestMethod] public void RefinedSoundExTest470() { Assert.IsTrue(RefinedSoundExTest("mindoro", "M869")); }
        [TestMethod] public void RefinedSoundExTest471() { Assert.IsTrue(RefinedSoundExTest("cephalopod", "C31716")); }
        [TestMethod] public void RefinedSoundExTest472() { Assert.IsTrue(RefinedSoundExTest("Klunk", "K3783")); }
        [TestMethod] public void RefinedSoundExTest473() { Assert.IsTrue(RefinedSoundExTest("Bumbrey", "B1819")); }
        [TestMethod] public void RefinedSoundExTest474() { Assert.IsTrue(RefinedSoundExTest("causeless", "C373")); }
        [TestMethod] public void RefinedSoundExTest475() { Assert.IsTrue(RefinedSoundExTest("Lothrop", "L7691")); }
        [TestMethod] public void RefinedSoundExTest476() { Assert.IsTrue(RefinedSoundExTest("bodystyles", "B163673")); }
        [TestMethod] public void RefinedSoundExTest477() { Assert.IsTrue(RefinedSoundExTest("beaatiality", "B1676")); }
        [TestMethod] public void RefinedSoundExTest478() { Assert.IsTrue(RefinedSoundExTest("Bobrowski", "B193")); }
        [TestMethod] public void RefinedSoundExTest479() { Assert.IsTrue(RefinedSoundExTest("erudition", "E968")); }
        [TestMethod] public void RefinedSoundExTest480() { Assert.IsTrue(RefinedSoundExTest("huttner", "H689")); }
        [TestMethod] public void RefinedSoundExTest481() { Assert.IsTrue(RefinedSoundExTest("wwwaskjeevescom", "W34238")); }
        [TestMethod] public void RefinedSoundExTest482() { Assert.IsTrue(RefinedSoundExTest("Duross", "D693")); }
        [TestMethod] public void RefinedSoundExTest483() { Assert.IsTrue(RefinedSoundExTest("Colemen", "C378")); }
        [TestMethod] public void RefinedSoundExTest484() { Assert.IsTrue(RefinedSoundExTest("Duncomb", "D68381")); }
        [TestMethod] public void RefinedSoundExTest485() { Assert.IsTrue(RefinedSoundExTest("tripe", "T691")); }
        [TestMethod] public void RefinedSoundExTest486() { Assert.IsTrue(RefinedSoundExTest("dorrigo", "D694")); }
        [TestMethod] public void RefinedSoundExTest487() { Assert.IsTrue(RefinedSoundExTest("Mascall", "M837")); }
        [TestMethod] public void RefinedSoundExTest488() { Assert.IsTrue(RefinedSoundExTest("jetplane", "J46178")); }
        [TestMethod] public void RefinedSoundExTest489() { Assert.IsTrue(RefinedSoundExTest("nswrl", "N8397")); }
        [TestMethod] public void RefinedSoundExTest490() { Assert.IsTrue(RefinedSoundExTest("didates", "D63")); }
        [TestMethod] public void RefinedSoundExTest491() { Assert.IsTrue(RefinedSoundExTest("Jena", "J48")); }
        [TestMethod] public void RefinedSoundExTest492() { Assert.IsTrue(RefinedSoundExTest("kctu", "K36")); }
        [TestMethod] public void RefinedSoundExTest493() { Assert.IsTrue(RefinedSoundExTest("cualquiera", "C3759")); }
        [TestMethod] public void RefinedSoundExTest494() { Assert.IsTrue(RefinedSoundExTest("plutella", "P1767")); }
        [TestMethod] public void RefinedSoundExTest495() { Assert.IsTrue(RefinedSoundExTest("Liebig", "L714")); }
        [TestMethod] public void RefinedSoundExTest496() { Assert.IsTrue(RefinedSoundExTest("Llorens", "L7983")); }
        [TestMethod] public void RefinedSoundExTest497() { Assert.IsTrue(RefinedSoundExTest("mraz", "M895")); }
        [TestMethod] public void RefinedSoundExTest498() { Assert.IsTrue(RefinedSoundExTest("shadyac", "S363")); }
        [TestMethod] public void RefinedSoundExTest499() { Assert.IsTrue(RefinedSoundExTest("lossphentermine", "L7318698")); }
        [TestMethod] public void RefinedSoundExTest500() { Assert.IsTrue(RefinedSoundExTest("Dreith", "D696")); }
        [TestMethod] public void RefinedSoundExTest501() { Assert.IsTrue(RefinedSoundExTest("Windsor", "W8639")); }

    }
}