using Element34.StringMetrics.Phonetic;

namespace Element34Tests.Phonetic
{
    [TestClass]
    public class ReverseSoundExTests
    {
        private bool ReverseSoundExTest(string sInput, string sExpected)
        {
            SoundExReverse soundEx = new SoundExReverse();
            return soundEx.Encode(sInput) == sExpected;
        }

        [TestMethod] public void ReverseSoundExTest001() { Assert.IsTrue(ReverseSoundExTest("communication", "N552")); }
        [TestMethod] public void ReverseSoundExTest002() { Assert.IsTrue(ReverseSoundExTest("worships", "S621")); }
        [TestMethod] public void ReverseSoundExTest003() { Assert.IsTrue(ReverseSoundExTest("televisionhome", "E412")); }
        [TestMethod] public void ReverseSoundExTest004() { Assert.IsTrue(ReverseSoundExTest("bumi", "I500")); }
        [TestMethod] public void ReverseSoundExTest005() { Assert.IsTrue(ReverseSoundExTest("shortbread", "D631")); }
        [TestMethod] public void ReverseSoundExTest006() { Assert.IsTrue(ReverseSoundExTest("slice", "E420")); }
        [TestMethod] public void ReverseSoundExTest007() { Assert.IsTrue(ReverseSoundExTest("reint", "T530")); }
        [TestMethod] public void ReverseSoundExTest008() { Assert.IsTrue(ReverseSoundExTest("Florence", "E465")); }
        [TestMethod] public void ReverseSoundExTest009() { Assert.IsTrue(ReverseSoundExTest("fawzi", "I200")); }
        [TestMethod] public void ReverseSoundExTest010() { Assert.IsTrue(ReverseSoundExTest("sname", "E550")); }
        [TestMethod] public void ReverseSoundExTest011() { Assert.IsTrue(ReverseSoundExTest("modano", "O350")); }
        [TestMethod] public void ReverseSoundExTest012() { Assert.IsTrue(ReverseSoundExTest("stumpage", "E351")); }
        [TestMethod] public void ReverseSoundExTest013() { Assert.IsTrue(ReverseSoundExTest("clears", "S462")); }
        [TestMethod] public void ReverseSoundExTest014() { Assert.IsTrue(ReverseSoundExTest("ciods", "S320")); }
        [TestMethod] public void ReverseSoundExTest015() { Assert.IsTrue(ReverseSoundExTest("deseos", "S220")); }
        [TestMethod] public void ReverseSoundExTest016() { Assert.IsTrue(ReverseSoundExTest("dippin", "N150")); }
        [TestMethod] public void ReverseSoundExTest017() { Assert.IsTrue(ReverseSoundExTest("aranna", "A650")); }
        [TestMethod] public void ReverseSoundExTest018() { Assert.IsTrue(ReverseSoundExTest("borse", "E620")); }
        [TestMethod] public void ReverseSoundExTest019() { Assert.IsTrue(ReverseSoundExTest("subic", "C120")); }
        [TestMethod] public void ReverseSoundExTest020() { Assert.IsTrue(ReverseSoundExTest("Vidrio", "O360")); }
        [TestMethod] public void ReverseSoundExTest021() { Assert.IsTrue(ReverseSoundExTest("inserters", "S526")); }
        [TestMethod] public void ReverseSoundExTest022() { Assert.IsTrue(ReverseSoundExTest("perature", "E636")); }
        [TestMethod] public void ReverseSoundExTest023() { Assert.IsTrue(ReverseSoundExTest("msacideas", "S223")); }
        [TestMethod] public void ReverseSoundExTest024() { Assert.IsTrue(ReverseSoundExTest("cougs", "S200")); }
        [TestMethod] public void ReverseSoundExTest025() { Assert.IsTrue(ReverseSoundExTest("kittens", "S352")); }
        [TestMethod] public void ReverseSoundExTest026() { Assert.IsTrue(ReverseSoundExTest("imperiously", "Y516")); }
        [TestMethod] public void ReverseSoundExTest027() { Assert.IsTrue(ReverseSoundExTest("boccanegra", "A252")); }
        [TestMethod] public void ReverseSoundExTest028() { Assert.IsTrue(ReverseSoundExTest("sextet", "T233")); }
        [TestMethod] public void ReverseSoundExTest029() { Assert.IsTrue(ReverseSoundExTest("setattributes", "S336")); }
        [TestMethod] public void ReverseSoundExTest030() { Assert.IsTrue(ReverseSoundExTest("dsnt", "T253")); }
        [TestMethod] public void ReverseSoundExTest031() { Assert.IsTrue(ReverseSoundExTest("chubby", "Y100")); }
        [TestMethod] public void ReverseSoundExTest032() { Assert.IsTrue(ReverseSoundExTest("ooda", "A300")); }
        [TestMethod] public void ReverseSoundExTest033() { Assert.IsTrue(ReverseSoundExTest("Bressman", "N625")); }
        [TestMethod] public void ReverseSoundExTest034() { Assert.IsTrue(ReverseSoundExTest("calendarnew", "W453")); }
        [TestMethod] public void ReverseSoundExTest035() { Assert.IsTrue(ReverseSoundExTest("duhon", "N500")); }
        [TestMethod] public void ReverseSoundExTest036() { Assert.IsTrue(ReverseSoundExTest("nchen", "N250")); }
        [TestMethod] public void ReverseSoundExTest037() { Assert.IsTrue(ReverseSoundExTest("betjemans", "S325")); }
        [TestMethod] public void ReverseSoundExTest038() { Assert.IsTrue(ReverseSoundExTest("Mangum", "M525")); }
        [TestMethod] public void ReverseSoundExTest039() { Assert.IsTrue(ReverseSoundExTest("cabac", "C120")); }
        [TestMethod] public void ReverseSoundExTest040() { Assert.IsTrue(ReverseSoundExTest("pantys", "S532")); }
        [TestMethod] public void ReverseSoundExTest041() { Assert.IsTrue(ReverseSoundExTest("cofactors", "S123")); }
        [TestMethod] public void ReverseSoundExTest042() { Assert.IsTrue(ReverseSoundExTest("clickz", "Z420")); }
        [TestMethod] public void ReverseSoundExTest043() { Assert.IsTrue(ReverseSoundExTest("chiap", "P100")); }
        [TestMethod] public void ReverseSoundExTest044() { Assert.IsTrue(ReverseSoundExTest("Dalpiaz", "Z412")); }
        [TestMethod] public void ReverseSoundExTest045() { Assert.IsTrue(ReverseSoundExTest("philosophically", "Y421")); }
        [TestMethod] public void ReverseSoundExTest046() { Assert.IsTrue(ReverseSoundExTest("backfill", "L214")); }
        [TestMethod] public void ReverseSoundExTest047() { Assert.IsTrue(ReverseSoundExTest("Murders", "S636")); }
        [TestMethod] public void ReverseSoundExTest048() { Assert.IsTrue(ReverseSoundExTest("ecartis", "S263")); }
        [TestMethod] public void ReverseSoundExTest049() { Assert.IsTrue(ReverseSoundExTest("vede", "E300")); }
        [TestMethod] public void ReverseSoundExTest050() { Assert.IsTrue(ReverseSoundExTest("usoe", "E200")); }
        [TestMethod] public void ReverseSoundExTest051() { Assert.IsTrue(ReverseSoundExTest("ostara", "A236")); }
        [TestMethod] public void ReverseSoundExTest052() { Assert.IsTrue(ReverseSoundExTest("labourer", "R166")); }
        [TestMethod] public void ReverseSoundExTest053() { Assert.IsTrue(ReverseSoundExTest("speir", "R160")); }
        [TestMethod] public void ReverseSoundExTest054() { Assert.IsTrue(ReverseSoundExTest("durchaus", "S622")); }
        [TestMethod] public void ReverseSoundExTest055() { Assert.IsTrue(ReverseSoundExTest("inetformfiller", "R531")); }
        [TestMethod] public void ReverseSoundExTest056() { Assert.IsTrue(ReverseSoundExTest("itrs", "S362")); }
        [TestMethod] public void ReverseSoundExTest057() { Assert.IsTrue(ReverseSoundExTest("Tennant", "T553")); }
        [TestMethod] public void ReverseSoundExTest058() { Assert.IsTrue(ReverseSoundExTest("bashore", "E260")); }
        [TestMethod] public void ReverseSoundExTest059() { Assert.IsTrue(ReverseSoundExTest("lemurian", "N565")); }
        [TestMethod] public void ReverseSoundExTest060() { Assert.IsTrue(ReverseSoundExTest("dungannon", "N525")); }
        [TestMethod] public void ReverseSoundExTest061() { Assert.IsTrue(ReverseSoundExTest("epl", "L140")); }
        [TestMethod] public void ReverseSoundExTest062() { Assert.IsTrue(ReverseSoundExTest("grader", "R636")); }
        [TestMethod] public void ReverseSoundExTest063() { Assert.IsTrue(ReverseSoundExTest("synchronise", "E526")); }
        [TestMethod] public void ReverseSoundExTest064() { Assert.IsTrue(ReverseSoundExTest("gondorian", "N536")); }
        [TestMethod] public void ReverseSoundExTest065() { Assert.IsTrue(ReverseSoundExTest("cvnet", "T153")); }
        [TestMethod] public void ReverseSoundExTest066() { Assert.IsTrue(ReverseSoundExTest("Centers", "S536")); }
        [TestMethod] public void ReverseSoundExTest067() { Assert.IsTrue(ReverseSoundExTest("soaks", "S200")); }
        [TestMethod] public void ReverseSoundExTest068() { Assert.IsTrue(ReverseSoundExTest("gogllle", "E240")); }
        [TestMethod] public void ReverseSoundExTest069() { Assert.IsTrue(ReverseSoundExTest("peotone", "E350")); }
        [TestMethod] public void ReverseSoundExTest070() { Assert.IsTrue(ReverseSoundExTest("Sharp", "P610")); }
        [TestMethod] public void ReverseSoundExTest071() { Assert.IsTrue(ReverseSoundExTest("mawer", "R600")); }
        [TestMethod] public void ReverseSoundExTest072() { Assert.IsTrue(ReverseSoundExTest("Morasca", "A620")); }
        [TestMethod] public void ReverseSoundExTest073() { Assert.IsTrue(ReverseSoundExTest("ticknor", "R256")); }
        [TestMethod] public void ReverseSoundExTest074() { Assert.IsTrue(ReverseSoundExTest("beaverdale", "E163")); }
        [TestMethod] public void ReverseSoundExTest075() { Assert.IsTrue(ReverseSoundExTest("caledonianew", "W435")); }
        [TestMethod] public void ReverseSoundExTest076() { Assert.IsTrue(ReverseSoundExTest("wellnessdicke", "E452")); }
        [TestMethod] public void ReverseSoundExTest077() { Assert.IsTrue(ReverseSoundExTest("Rodin", "N350")); }
        [TestMethod] public void ReverseSoundExTest078() { Assert.IsTrue(ReverseSoundExTest("bluffer", "R416")); }
        [TestMethod] public void ReverseSoundExTest079() { Assert.IsTrue(ReverseSoundExTest("joey", "Y000")); }
        [TestMethod] public void ReverseSoundExTest080() { Assert.IsTrue(ReverseSoundExTest("unbekannter", "R512")); }
        [TestMethod] public void ReverseSoundExTest081() { Assert.IsTrue(ReverseSoundExTest("Baylor", "R460")); }
        [TestMethod] public void ReverseSoundExTest082() { Assert.IsTrue(ReverseSoundExTest("striplib", "B361")); }
        [TestMethod] public void ReverseSoundExTest083() { Assert.IsTrue(ReverseSoundExTest("boquete", "E230")); }
        [TestMethod] public void ReverseSoundExTest084() { Assert.IsTrue(ReverseSoundExTest("geylang", "G452")); }
        [TestMethod] public void ReverseSoundExTest085() { Assert.IsTrue(ReverseSoundExTest("Lavi", "I100")); }
        [TestMethod] public void ReverseSoundExTest086() { Assert.IsTrue(ReverseSoundExTest("moldovans", "S431")); }
        [TestMethod] public void ReverseSoundExTest087() { Assert.IsTrue(ReverseSoundExTest("linq", "Q520")); }
        [TestMethod] public void ReverseSoundExTest088() { Assert.IsTrue(ReverseSoundExTest("Kenworthy", "Y563")); }
        [TestMethod] public void ReverseSoundExTest089() { Assert.IsTrue(ReverseSoundExTest("Steckman", "N325")); }
        [TestMethod] public void ReverseSoundExTest090() { Assert.IsTrue(ReverseSoundExTest("czechoslovakian", "N224")); }
        [TestMethod] public void ReverseSoundExTest091() { Assert.IsTrue(ReverseSoundExTest("marmora", "A656")); }
        [TestMethod] public void ReverseSoundExTest092() { Assert.IsTrue(ReverseSoundExTest("Carvill", "L614")); }
        [TestMethod] public void ReverseSoundExTest093() { Assert.IsTrue(ReverseSoundExTest("chihiro", "O600")); }
        [TestMethod] public void ReverseSoundExTest094() { Assert.IsTrue(ReverseSoundExTest("hctc", "C232")); }
        [TestMethod] public void ReverseSoundExTest095() { Assert.IsTrue(ReverseSoundExTest("nolde", "E430")); }
        [TestMethod] public void ReverseSoundExTest096() { Assert.IsTrue(ReverseSoundExTest("aerosolized", "D624")); }
        [TestMethod] public void ReverseSoundExTest097() { Assert.IsTrue(ReverseSoundExTest("canterbury", "Y536")); }
        [TestMethod] public void ReverseSoundExTest098() { Assert.IsTrue(ReverseSoundExTest("jss", "S000")); }
        [TestMethod] public void ReverseSoundExTest099() { Assert.IsTrue(ReverseSoundExTest("rmn", "N500")); }
        [TestMethod] public void ReverseSoundExTest100() { Assert.IsTrue(ReverseSoundExTest("mazlish", "H242")); }
        [TestMethod] public void ReverseSoundExTest101() { Assert.IsTrue(ReverseSoundExTest("faites", "S320")); }
        [TestMethod] public void ReverseSoundExTest102() { Assert.IsTrue(ReverseSoundExTest("foyer", "R600")); }
        [TestMethod] public void ReverseSoundExTest103() { Assert.IsTrue(ReverseSoundExTest("ductions", "S235")); }
        [TestMethod] public void ReverseSoundExTest104() { Assert.IsTrue(ReverseSoundExTest("Rambo", "O510")); }
        [TestMethod] public void ReverseSoundExTest105() { Assert.IsTrue(ReverseSoundExTest("Curnutte", "E653")); }
        [TestMethod] public void ReverseSoundExTest106() { Assert.IsTrue(ReverseSoundExTest("Feltus", "S432")); }
        [TestMethod] public void ReverseSoundExTest107() { Assert.IsTrue(ReverseSoundExTest("forbairt", "T616")); }
        [TestMethod] public void ReverseSoundExTest108() { Assert.IsTrue(ReverseSoundExTest("southerners", "S365")); }
        [TestMethod] public void ReverseSoundExTest109() { Assert.IsTrue(ReverseSoundExTest("hypnotists", "S153")); }
        [TestMethod] public void ReverseSoundExTest110() { Assert.IsTrue(ReverseSoundExTest("euphony", "Y150")); }
        [TestMethod] public void ReverseSoundExTest111() { Assert.IsTrue(ReverseSoundExTest("mhpa", "A100")); }
        [TestMethod] public void ReverseSoundExTest112() { Assert.IsTrue(ReverseSoundExTest("matteotti", "I330")); }
        [TestMethod] public void ReverseSoundExTest113() { Assert.IsTrue(ReverseSoundExTest("Klande", "E453")); }
        [TestMethod] public void ReverseSoundExTest114() { Assert.IsTrue(ReverseSoundExTest("Trudgeon", "N632")); }
        [TestMethod] public void ReverseSoundExTest115() { Assert.IsTrue(ReverseSoundExTest("schoolhill", "L440")); }
        [TestMethod] public void ReverseSoundExTest116() { Assert.IsTrue(ReverseSoundExTest("equalizer", "R242")); }
        [TestMethod] public void ReverseSoundExTest117() { Assert.IsTrue(ReverseSoundExTest("xnet", "T530")); }
        [TestMethod] public void ReverseSoundExTest118() { Assert.IsTrue(ReverseSoundExTest("Thell", "L400")); }
        [TestMethod] public void ReverseSoundExTest119() { Assert.IsTrue(ReverseSoundExTest("Canel", "L540")); }
        [TestMethod] public void ReverseSoundExTest120() { Assert.IsTrue(ReverseSoundExTest("vmetro", "O536")); }
        [TestMethod] public void ReverseSoundExTest121() { Assert.IsTrue(ReverseSoundExTest("burgtheater", "R623")); }
        [TestMethod] public void ReverseSoundExTest122() { Assert.IsTrue(ReverseSoundExTest("Berlinger", "R645")); }
        [TestMethod] public void ReverseSoundExTest123() { Assert.IsTrue(ReverseSoundExTest("crehan", "N650")); }
        [TestMethod] public void ReverseSoundExTest124() { Assert.IsTrue(ReverseSoundExTest("abysses", "S122")); }
        [TestMethod] public void ReverseSoundExTest125() { Assert.IsTrue(ReverseSoundExTest("Hipolito", "O143")); }
        [TestMethod] public void ReverseSoundExTest126() { Assert.IsTrue(ReverseSoundExTest("splintered", "D145")); }
        [TestMethod] public void ReverseSoundExTest127() { Assert.IsTrue(ReverseSoundExTest("maintenace", "E535")); }
        [TestMethod] public void ReverseSoundExTest128() { Assert.IsTrue(ReverseSoundExTest("decency", "Y252")); }
        [TestMethod] public void ReverseSoundExTest129() { Assert.IsTrue(ReverseSoundExTest("quantz", "Z532")); }
        [TestMethod] public void ReverseSoundExTest130() { Assert.IsTrue(ReverseSoundExTest("wette", "E300")); }
        [TestMethod] public void ReverseSoundExTest131() { Assert.IsTrue(ReverseSoundExTest("Feary", "Y600")); }
        [TestMethod] public void ReverseSoundExTest132() { Assert.IsTrue(ReverseSoundExTest("Cuchiara", "A260")); }
        [TestMethod] public void ReverseSoundExTest133() { Assert.IsTrue(ReverseSoundExTest("Arbon", "N615")); }
        [TestMethod] public void ReverseSoundExTest134() { Assert.IsTrue(ReverseSoundExTest("shyness", "S520")); }
        [TestMethod] public void ReverseSoundExTest135() { Assert.IsTrue(ReverseSoundExTest("Salin", "N450")); }
        [TestMethod] public void ReverseSoundExTest136() { Assert.IsTrue(ReverseSoundExTest("Zicafoose", "E212")); }
        [TestMethod] public void ReverseSoundExTest137() { Assert.IsTrue(ReverseSoundExTest("Menn", "N500")); }
        [TestMethod] public void ReverseSoundExTest138() { Assert.IsTrue(ReverseSoundExTest("funker", "R526")); }
        [TestMethod] public void ReverseSoundExTest139() { Assert.IsTrue(ReverseSoundExTest("santillan", "N534")); }
        [TestMethod] public void ReverseSoundExTest140() { Assert.IsTrue(ReverseSoundExTest("punani", "I550")); }
        [TestMethod] public void ReverseSoundExTest141() { Assert.IsTrue(ReverseSoundExTest("basa", "A200")); }
        [TestMethod] public void ReverseSoundExTest142() { Assert.IsTrue(ReverseSoundExTest("bluefin", "N415")); }
        [TestMethod] public void ReverseSoundExTest143() { Assert.IsTrue(ReverseSoundExTest("cc", "C000")); }
        [TestMethod] public void ReverseSoundExTest144() { Assert.IsTrue(ReverseSoundExTest("zipgenius", "S125")); }
        [TestMethod] public void ReverseSoundExTest145() { Assert.IsTrue(ReverseSoundExTest("Kirchen", "N625")); }
        [TestMethod] public void ReverseSoundExTest146() { Assert.IsTrue(ReverseSoundExTest("commentaar", "R553")); }
        [TestMethod] public void ReverseSoundExTest147() { Assert.IsTrue(ReverseSoundExTest("expansive", "E215")); }
        [TestMethod] public void ReverseSoundExTest148() { Assert.IsTrue(ReverseSoundExTest("castlebar", "R234")); }
        [TestMethod] public void ReverseSoundExTest149() { Assert.IsTrue(ReverseSoundExTest("lft", "T130")); }
        [TestMethod] public void ReverseSoundExTest150() { Assert.IsTrue(ReverseSoundExTest("robla", "A140")); }
        [TestMethod] public void ReverseSoundExTest151() { Assert.IsTrue(ReverseSoundExTest("zarontin", "N653")); }
        [TestMethod] public void ReverseSoundExTest152() { Assert.IsTrue(ReverseSoundExTest("nawc", "C200")); }
        [TestMethod] public void ReverseSoundExTest153() { Assert.IsTrue(ReverseSoundExTest("resolvconf", "F241")); }
        [TestMethod] public void ReverseSoundExTest154() { Assert.IsTrue(ReverseSoundExTest("networker", "R362")); }
        [TestMethod] public void ReverseSoundExTest155() { Assert.IsTrue(ReverseSoundExTest("airlins", "S645")); }
        [TestMethod] public void ReverseSoundExTest156() { Assert.IsTrue(ReverseSoundExTest("Piskel", "L240")); }
        [TestMethod] public void ReverseSoundExTest157() { Assert.IsTrue(ReverseSoundExTest("hilson", "N425")); }
        [TestMethod] public void ReverseSoundExTest158() { Assert.IsTrue(ReverseSoundExTest("deco", "O200")); }
        [TestMethod] public void ReverseSoundExTest159() { Assert.IsTrue(ReverseSoundExTest("cents", "S532")); }
        [TestMethod] public void ReverseSoundExTest160() { Assert.IsTrue(ReverseSoundExTest("award", "D630")); }
        [TestMethod] public void ReverseSoundExTest161() { Assert.IsTrue(ReverseSoundExTest("reykjanes", "S252")); }
        [TestMethod] public void ReverseSoundExTest162() { Assert.IsTrue(ReverseSoundExTest("perona", "A650")); }
        [TestMethod] public void ReverseSoundExTest163() { Assert.IsTrue(ReverseSoundExTest("epistle", "E123")); }
        [TestMethod] public void ReverseSoundExTest164() { Assert.IsTrue(ReverseSoundExTest("insound", "D525")); }
        [TestMethod] public void ReverseSoundExTest165() { Assert.IsTrue(ReverseSoundExTest("qantas", "S532")); }
        [TestMethod] public void ReverseSoundExTest166() { Assert.IsTrue(ReverseSoundExTest("wholey", "Y400")); }
        [TestMethod] public void ReverseSoundExTest167() { Assert.IsTrue(ReverseSoundExTest("aragona", "A625")); }
        [TestMethod] public void ReverseSoundExTest168() { Assert.IsTrue(ReverseSoundExTest("Vancheri", "I526")); }
        [TestMethod] public void ReverseSoundExTest169() { Assert.IsTrue(ReverseSoundExTest("allocution", "N423")); }
        [TestMethod] public void ReverseSoundExTest170() { Assert.IsTrue(ReverseSoundExTest("volodya", "A430")); }
        [TestMethod] public void ReverseSoundExTest171() { Assert.IsTrue(ReverseSoundExTest("enunciate", "E552")); }
        [TestMethod] public void ReverseSoundExTest172() { Assert.IsTrue(ReverseSoundExTest("uuuu", "U000")); }
        [TestMethod] public void ReverseSoundExTest173() { Assert.IsTrue(ReverseSoundExTest("Louato", "O300")); }
        [TestMethod] public void ReverseSoundExTest174() { Assert.IsTrue(ReverseSoundExTest("Marquitta", "A623")); }
        [TestMethod] public void ReverseSoundExTest175() { Assert.IsTrue(ReverseSoundExTest("surmountable", "E655")); }
        [TestMethod] public void ReverseSoundExTest176() { Assert.IsTrue(ReverseSoundExTest("gaultier", "R436")); }
        [TestMethod] public void ReverseSoundExTest177() { Assert.IsTrue(ReverseSoundExTest("dafoe", "E100")); }
        [TestMethod] public void ReverseSoundExTest178() { Assert.IsTrue(ReverseSoundExTest("Claudio", "O430")); }
        [TestMethod] public void ReverseSoundExTest179() { Assert.IsTrue(ReverseSoundExTest("ritva", "A310")); }
        [TestMethod] public void ReverseSoundExTest180() { Assert.IsTrue(ReverseSoundExTest("spunky", "Y152")); }
        [TestMethod] public void ReverseSoundExTest181() { Assert.IsTrue(ReverseSoundExTest("npov", "V110")); }
        [TestMethod] public void ReverseSoundExTest182() { Assert.IsTrue(ReverseSoundExTest("eurythmics", "S635")); }
        [TestMethod] public void ReverseSoundExTest183() { Assert.IsTrue(ReverseSoundExTest("skittish", "H320")); }
        [TestMethod] public void ReverseSoundExTest184() { Assert.IsTrue(ReverseSoundExTest("scooter", "R360")); }
        [TestMethod] public void ReverseSoundExTest185() { Assert.IsTrue(ReverseSoundExTest("unfermented", "D516")); }
        [TestMethod] public void ReverseSoundExTest186() { Assert.IsTrue(ReverseSoundExTest("kerridge", "E632")); }
        [TestMethod] public void ReverseSoundExTest187() { Assert.IsTrue(ReverseSoundExTest("scenography", "Y526")); }
        [TestMethod] public void ReverseSoundExTest188() { Assert.IsTrue(ReverseSoundExTest("sahalee", "E400")); }
        [TestMethod] public void ReverseSoundExTest189() { Assert.IsTrue(ReverseSoundExTest("spooktacular", "R123")); }
        [TestMethod] public void ReverseSoundExTest190() { Assert.IsTrue(ReverseSoundExTest("boissons", "S252")); }
        [TestMethod] public void ReverseSoundExTest191() { Assert.IsTrue(ReverseSoundExTest("arbete", "E613")); }
        [TestMethod] public void ReverseSoundExTest192() { Assert.IsTrue(ReverseSoundExTest("Norrick", "K620")); }
        [TestMethod] public void ReverseSoundExTest193() { Assert.IsTrue(ReverseSoundExTest("Sonnier", "R560")); }
        [TestMethod] public void ReverseSoundExTest194() { Assert.IsTrue(ReverseSoundExTest("gnomeui", "I550")); }
        [TestMethod] public void ReverseSoundExTest195() { Assert.IsTrue(ReverseSoundExTest("milian", "N450")); }
        [TestMethod] public void ReverseSoundExTest196() { Assert.IsTrue(ReverseSoundExTest("blackplanetcom", "M421")); }
        [TestMethod] public void ReverseSoundExTest197() { Assert.IsTrue(ReverseSoundExTest("tuned", "D530")); }
        [TestMethod] public void ReverseSoundExTest198() { Assert.IsTrue(ReverseSoundExTest("Salone", "E450")); }
        [TestMethod] public void ReverseSoundExTest199() { Assert.IsTrue(ReverseSoundExTest("marathon", "N635")); }
        [TestMethod] public void ReverseSoundExTest200() { Assert.IsTrue(ReverseSoundExTest("layoffs", "S120")); }
        [TestMethod] public void ReverseSoundExTest201() { Assert.IsTrue(ReverseSoundExTest("hotek", "K320")); }
        [TestMethod] public void ReverseSoundExTest202() { Assert.IsTrue(ReverseSoundExTest("emme", "E500")); }
        [TestMethod] public void ReverseSoundExTest203() { Assert.IsTrue(ReverseSoundExTest("amarasinghe", "E562")); }
        [TestMethod] public void ReverseSoundExTest204() { Assert.IsTrue(ReverseSoundExTest("midas", "S320")); }
        [TestMethod] public void ReverseSoundExTest205() { Assert.IsTrue(ReverseSoundExTest("inhaltsangabe", "E543")); }
        [TestMethod] public void ReverseSoundExTest206() { Assert.IsTrue(ReverseSoundExTest("smow", "W500")); }
        [TestMethod] public void ReverseSoundExTest207() { Assert.IsTrue(ReverseSoundExTest("policing", "G425")); }
        [TestMethod] public void ReverseSoundExTest208() { Assert.IsTrue(ReverseSoundExTest("usmf", "F251")); }
        [TestMethod] public void ReverseSoundExTest209() { Assert.IsTrue(ReverseSoundExTest("inferred", "D516")); }
        [TestMethod] public void ReverseSoundExTest210() { Assert.IsTrue(ReverseSoundExTest("Eaglen", "N245")); }
        [TestMethod] public void ReverseSoundExTest211() { Assert.IsTrue(ReverseSoundExTest("dralle", "E640")); }
        [TestMethod] public void ReverseSoundExTest212() { Assert.IsTrue(ReverseSoundExTest("kalmus", "S452")); }
        [TestMethod] public void ReverseSoundExTest213() { Assert.IsTrue(ReverseSoundExTest("nork", "K620")); }
        [TestMethod] public void ReverseSoundExTest214() { Assert.IsTrue(ReverseSoundExTest("Waterston", "N362")); }
        [TestMethod] public void ReverseSoundExTest215() { Assert.IsTrue(ReverseSoundExTest("penalised", "D542")); }
        [TestMethod] public void ReverseSoundExTest216() { Assert.IsTrue(ReverseSoundExTest("Lupacchino", "O125")); }
        [TestMethod] public void ReverseSoundExTest217() { Assert.IsTrue(ReverseSoundExTest("getgid", "D323")); }
        [TestMethod] public void ReverseSoundExTest218() { Assert.IsTrue(ReverseSoundExTest("kever", "R160")); }
        [TestMethod] public void ReverseSoundExTest219() { Assert.IsTrue(ReverseSoundExTest("pallavicini", "I412")); }
        [TestMethod] public void ReverseSoundExTest220() { Assert.IsTrue(ReverseSoundExTest("Pais", "S200")); }
        [TestMethod] public void ReverseSoundExTest221() { Assert.IsTrue(ReverseSoundExTest("youghiogheny", "Y225")); }
        [TestMethod] public void ReverseSoundExTest222() { Assert.IsTrue(ReverseSoundExTest("Catherina", "A365")); }
        [TestMethod] public void ReverseSoundExTest223() { Assert.IsTrue(ReverseSoundExTest("Givant", "T153")); }
        [TestMethod] public void ReverseSoundExTest224() { Assert.IsTrue(ReverseSoundExTest("koffi", "I100")); }
        [TestMethod] public void ReverseSoundExTest225() { Assert.IsTrue(ReverseSoundExTest("troutbeck", "K631")); }
        [TestMethod] public void ReverseSoundExTest226() { Assert.IsTrue(ReverseSoundExTest("moreelse", "E642")); }
        [TestMethod] public void ReverseSoundExTest227() { Assert.IsTrue(ReverseSoundExTest("seacrest", "T262")); }
        [TestMethod] public void ReverseSoundExTest228() { Assert.IsTrue(ReverseSoundExTest("ufj", "J120")); }
        [TestMethod] public void ReverseSoundExTest229() { Assert.IsTrue(ReverseSoundExTest("dereferences", "S616")); }
        [TestMethod] public void ReverseSoundExTest230() { Assert.IsTrue(ReverseSoundExTest("sarena", "A650")); }
        [TestMethod] public void ReverseSoundExTest231() { Assert.IsTrue(ReverseSoundExTest("Kurt", "T630")); }
        [TestMethod] public void ReverseSoundExTest232() { Assert.IsTrue(ReverseSoundExTest("comanche", "E552")); }
        [TestMethod] public void ReverseSoundExTest233() { Assert.IsTrue(ReverseSoundExTest("chersoness", "S625")); }
        [TestMethod] public void ReverseSoundExTest234() { Assert.IsTrue(ReverseSoundExTest("cd", "D300")); }
        [TestMethod] public void ReverseSoundExTest235() { Assert.IsTrue(ReverseSoundExTest("merzky", "Y620")); }
        [TestMethod] public void ReverseSoundExTest236() { Assert.IsTrue(ReverseSoundExTest("Nordsiek", "K632")); }
        [TestMethod] public void ReverseSoundExTest237() { Assert.IsTrue(ReverseSoundExTest("samus", "S520")); }
        [TestMethod] public void ReverseSoundExTest238() { Assert.IsTrue(ReverseSoundExTest("tougher", "R260")); }
        [TestMethod] public void ReverseSoundExTest239() { Assert.IsTrue(ReverseSoundExTest("monodoc", "C532")); }
        [TestMethod] public void ReverseSoundExTest240() { Assert.IsTrue(ReverseSoundExTest("deepings", "S152")); }
        [TestMethod] public void ReverseSoundExTest241() { Assert.IsTrue(ReverseSoundExTest("datel", "L340")); }
        [TestMethod] public void ReverseSoundExTest242() { Assert.IsTrue(ReverseSoundExTest("Stockett", "T323")); }
        [TestMethod] public void ReverseSoundExTest243() { Assert.IsTrue(ReverseSoundExTest("bryum", "M650")); }
        [TestMethod] public void ReverseSoundExTest244() { Assert.IsTrue(ReverseSoundExTest("surveyed", "D613")); }
        [TestMethod] public void ReverseSoundExTest245() { Assert.IsTrue(ReverseSoundExTest("microcephaly", "Y262")); }
        [TestMethod] public void ReverseSoundExTest246() { Assert.IsTrue(ReverseSoundExTest("trimoxazole", "E652")); }
        [TestMethod] public void ReverseSoundExTest247() { Assert.IsTrue(ReverseSoundExTest("bastide", "E233")); }
        [TestMethod] public void ReverseSoundExTest248() { Assert.IsTrue(ReverseSoundExTest("lipo", "O100")); }
        [TestMethod] public void ReverseSoundExTest249() { Assert.IsTrue(ReverseSoundExTest("Bosket", "T230")); }
        [TestMethod] public void ReverseSoundExTest250() { Assert.IsTrue(ReverseSoundExTest("oroms", "S652")); }
        [TestMethod] public void ReverseSoundExTest251() { Assert.IsTrue(ReverseSoundExTest("vandenburg", "G535")); }
        [TestMethod] public void ReverseSoundExTest252() { Assert.IsTrue(ReverseSoundExTest("wirtschaftsforschung", "G632")); }
        [TestMethod] public void ReverseSoundExTest253() { Assert.IsTrue(ReverseSoundExTest("lilypond", "D415")); }
        [TestMethod] public void ReverseSoundExTest254() { Assert.IsTrue(ReverseSoundExTest("mouthfeel", "L314")); }
        [TestMethod] public void ReverseSoundExTest255() { Assert.IsTrue(ReverseSoundExTest("wwwunibancocombr", "R515")); }
        [TestMethod] public void ReverseSoundExTest256() { Assert.IsTrue(ReverseSoundExTest("Worster", "R623")); }
        [TestMethod] public void ReverseSoundExTest257() { Assert.IsTrue(ReverseSoundExTest("Ahmad", "D530")); }
        [TestMethod] public void ReverseSoundExTest258() { Assert.IsTrue(ReverseSoundExTest("sweetser", "R326")); }
        [TestMethod] public void ReverseSoundExTest259() { Assert.IsTrue(ReverseSoundExTest("vsepr", "R216")); }
        [TestMethod] public void ReverseSoundExTest260() { Assert.IsTrue(ReverseSoundExTest("dput", "T130")); }
        [TestMethod] public void ReverseSoundExTest261() { Assert.IsTrue(ReverseSoundExTest("austlit", "T234")); }
        [TestMethod] public void ReverseSoundExTest262() { Assert.IsTrue(ReverseSoundExTest("Clemen", "N455")); }
        [TestMethod] public void ReverseSoundExTest263() { Assert.IsTrue(ReverseSoundExTest("phrva", "A610")); }
        [TestMethod] public void ReverseSoundExTest264() { Assert.IsTrue(ReverseSoundExTest("weipa", "A100")); }
        [TestMethod] public void ReverseSoundExTest265() { Assert.IsTrue(ReverseSoundExTest("Schrantz", "Z653")); }
        [TestMethod] public void ReverseSoundExTest266() { Assert.IsTrue(ReverseSoundExTest("meany", "Y500")); }
        [TestMethod] public void ReverseSoundExTest267() { Assert.IsTrue(ReverseSoundExTest("hodgepodge", "E321")); }
        [TestMethod] public void ReverseSoundExTest268() { Assert.IsTrue(ReverseSoundExTest("knuble", "E514")); }
        [TestMethod] public void ReverseSoundExTest269() { Assert.IsTrue(ReverseSoundExTest("caniglia", "A524")); }
        [TestMethod] public void ReverseSoundExTest270() { Assert.IsTrue(ReverseSoundExTest("blowjobsasics", "S421")); }
        [TestMethod] public void ReverseSoundExTest271() { Assert.IsTrue(ReverseSoundExTest("flyjacket", "T422")); }
        [TestMethod] public void ReverseSoundExTest272() { Assert.IsTrue(ReverseSoundExTest("galatian", "N435")); }
        [TestMethod] public void ReverseSoundExTest273() { Assert.IsTrue(ReverseSoundExTest("hotsel", "L324")); }
        [TestMethod] public void ReverseSoundExTest274() { Assert.IsTrue(ReverseSoundExTest("autorun", "N365")); }
        [TestMethod] public void ReverseSoundExTest275() { Assert.IsTrue(ReverseSoundExTest("cocoon", "N250")); }
        [TestMethod] public void ReverseSoundExTest276() { Assert.IsTrue(ReverseSoundExTest("kooks", "S200")); }
        [TestMethod] public void ReverseSoundExTest277() { Assert.IsTrue(ReverseSoundExTest("endocrinol", "L532")); }
        [TestMethod] public void ReverseSoundExTest278() { Assert.IsTrue(ReverseSoundExTest("mesages", "S222")); }
        [TestMethod] public void ReverseSoundExTest279() { Assert.IsTrue(ReverseSoundExTest("Disney", "Y250")); }
        [TestMethod] public void ReverseSoundExTest280() { Assert.IsTrue(ReverseSoundExTest("speedline", "E134")); }
        [TestMethod] public void ReverseSoundExTest281() { Assert.IsTrue(ReverseSoundExTest("gabaldon", "N143")); }
        [TestMethod] public void ReverseSoundExTest282() { Assert.IsTrue(ReverseSoundExTest("margaux", "X622")); }
        [TestMethod] public void ReverseSoundExTest283() { Assert.IsTrue(ReverseSoundExTest("housecalls", "S224")); }
        [TestMethod] public void ReverseSoundExTest284() { Assert.IsTrue(ReverseSoundExTest("siltation", "N433")); }
        [TestMethod] public void ReverseSoundExTest285() { Assert.IsTrue(ReverseSoundExTest("automatic", "C353")); }
        [TestMethod] public void ReverseSoundExTest286() { Assert.IsTrue(ReverseSoundExTest("freakshow", "W620")); }
        [TestMethod] public void ReverseSoundExTest287() { Assert.IsTrue(ReverseSoundExTest("gorojovsky", "Y621")); }
        [TestMethod] public void ReverseSoundExTest288() { Assert.IsTrue(ReverseSoundExTest("milwaukie", "E420")); }
        [TestMethod] public void ReverseSoundExTest289() { Assert.IsTrue(ReverseSoundExTest("wwwgap", "P210")); }
        [TestMethod] public void ReverseSoundExTest290() { Assert.IsTrue(ReverseSoundExTest("autm", "M350")); }
        [TestMethod] public void ReverseSoundExTest291() { Assert.IsTrue(ReverseSoundExTest("borromini", "I655")); }
        [TestMethod] public void ReverseSoundExTest292() { Assert.IsTrue(ReverseSoundExTest("zpp", "P100")); }
        [TestMethod] public void ReverseSoundExTest293() { Assert.IsTrue(ReverseSoundExTest("Penovich", "H512")); }
        [TestMethod] public void ReverseSoundExTest294() { Assert.IsTrue(ReverseSoundExTest("domine", "E550")); }
        [TestMethod] public void ReverseSoundExTest295() { Assert.IsTrue(ReverseSoundExTest("caves", "S120")); }
        [TestMethod] public void ReverseSoundExTest296() { Assert.IsTrue(ReverseSoundExTest("uato", "O300")); }
        [TestMethod] public void ReverseSoundExTest297() { Assert.IsTrue(ReverseSoundExTest("tiltonsville", "E435")); }
        [TestMethod] public void ReverseSoundExTest298() { Assert.IsTrue(ReverseSoundExTest("Ken", "N500")); }
        [TestMethod] public void ReverseSoundExTest299() { Assert.IsTrue(ReverseSoundExTest("Delonais", "S452")); }
        [TestMethod] public void ReverseSoundExTest300() { Assert.IsTrue(ReverseSoundExTest("conniption", "N513")); }
        [TestMethod] public void ReverseSoundExTest301() { Assert.IsTrue(ReverseSoundExTest("Wenske", "E520")); }
        [TestMethod] public void ReverseSoundExTest302() { Assert.IsTrue(ReverseSoundExTest("cautery", "Y360")); }
        [TestMethod] public void ReverseSoundExTest303() { Assert.IsTrue(ReverseSoundExTest("barbourville", "E616")); }
        [TestMethod] public void ReverseSoundExTest304() { Assert.IsTrue(ReverseSoundExTest("departamentos", "S163")); }
        [TestMethod] public void ReverseSoundExTest305() { Assert.IsTrue(ReverseSoundExTest("weaponry", "Y156")); }
        [TestMethod] public void ReverseSoundExTest306() { Assert.IsTrue(ReverseSoundExTest("Haggett", "T230")); }
        [TestMethod] public void ReverseSoundExTest307() { Assert.IsTrue(ReverseSoundExTest("martinville", "E635")); }
        [TestMethod] public void ReverseSoundExTest308() { Assert.IsTrue(ReverseSoundExTest("stina", "A350")); }
        [TestMethod] public void ReverseSoundExTest309() { Assert.IsTrue(ReverseSoundExTest("Rubottom", "M135")); }
        [TestMethod] public void ReverseSoundExTest310() { Assert.IsTrue(ReverseSoundExTest("Soyke", "E200")); }
        [TestMethod] public void ReverseSoundExTest311() { Assert.IsTrue(ReverseSoundExTest("corse", "E620")); }
        [TestMethod] public void ReverseSoundExTest312() { Assert.IsTrue(ReverseSoundExTest("totalling", "G345")); }
        [TestMethod] public void ReverseSoundExTest313() { Assert.IsTrue(ReverseSoundExTest("kuppam", "M150")); }
        [TestMethod] public void ReverseSoundExTest314() { Assert.IsTrue(ReverseSoundExTest("ftpadmin", "N313")); }
        [TestMethod] public void ReverseSoundExTest315() { Assert.IsTrue(ReverseSoundExTest("Forst", "T623")); }
        [TestMethod] public void ReverseSoundExTest316() { Assert.IsTrue(ReverseSoundExTest("Ashauer", "R260")); }
        [TestMethod] public void ReverseSoundExTest317() { Assert.IsTrue(ReverseSoundExTest("ashtanga", "A235")); }
        [TestMethod] public void ReverseSoundExTest318() { Assert.IsTrue(ReverseSoundExTest("alonissos", "S452")); }
        [TestMethod] public void ReverseSoundExTest319() { Assert.IsTrue(ReverseSoundExTest("Chimilio", "O540")); }
        [TestMethod] public void ReverseSoundExTest320() { Assert.IsTrue(ReverseSoundExTest("deafbazon", "N125")); }
        [TestMethod] public void ReverseSoundExTest321() { Assert.IsTrue(ReverseSoundExTest("psmb", "B251")); }
        [TestMethod] public void ReverseSoundExTest322() { Assert.IsTrue(ReverseSoundExTest("Ferraraccio", "O662")); }
        [TestMethod] public void ReverseSoundExTest323() { Assert.IsTrue(ReverseSoundExTest("fractionated", "D623")); }
        [TestMethod] public void ReverseSoundExTest324() { Assert.IsTrue(ReverseSoundExTest("rrd", "D300")); }
        [TestMethod] public void ReverseSoundExTest325() { Assert.IsTrue(ReverseSoundExTest("luminosities", "S552")); }
        [TestMethod] public void ReverseSoundExTest326() { Assert.IsTrue(ReverseSoundExTest("Platzer", "R432")); }
        [TestMethod] public void ReverseSoundExTest327() { Assert.IsTrue(ReverseSoundExTest("modulator", "R343")); }
        [TestMethod] public void ReverseSoundExTest328() { Assert.IsTrue(ReverseSoundExTest("tyneside", "E523")); }
        [TestMethod] public void ReverseSoundExTest329() { Assert.IsTrue(ReverseSoundExTest("nonuser", "R526")); }
        [TestMethod] public void ReverseSoundExTest330() { Assert.IsTrue(ReverseSoundExTest("haspel", "L214")); }
        [TestMethod] public void ReverseSoundExTest331() { Assert.IsTrue(ReverseSoundExTest("cortex", "X632")); }
        [TestMethod] public void ReverseSoundExTest332() { Assert.IsTrue(ReverseSoundExTest("vechicle", "E224")); }
        [TestMethod] public void ReverseSoundExTest333() { Assert.IsTrue(ReverseSoundExTest("epinions", "S155")); }
        [TestMethod] public void ReverseSoundExTest334() { Assert.IsTrue(ReverseSoundExTest("wwwusmintgov", "V255")); }
        [TestMethod] public void ReverseSoundExTest335() { Assert.IsTrue(ReverseSoundExTest("katies", "S320")); }
        [TestMethod] public void ReverseSoundExTest336() { Assert.IsTrue(ReverseSoundExTest("aminosalicylic", "C552")); }
        [TestMethod] public void ReverseSoundExTest337() { Assert.IsTrue(ReverseSoundExTest("mmegi", "I200")); }
        [TestMethod] public void ReverseSoundExTest338() { Assert.IsTrue(ReverseSoundExTest("sbir", "R160")); }
        [TestMethod] public void ReverseSoundExTest339() { Assert.IsTrue(ReverseSoundExTest("learned", "D653")); }
        [TestMethod] public void ReverseSoundExTest340() { Assert.IsTrue(ReverseSoundExTest("supris", "S162")); }
        [TestMethod] public void ReverseSoundExTest341() { Assert.IsTrue(ReverseSoundExTest("mozarteum", "M263")); }
        [TestMethod] public void ReverseSoundExTest342() { Assert.IsTrue(ReverseSoundExTest("selzer", "R426")); }
        [TestMethod] public void ReverseSoundExTest343() { Assert.IsTrue(ReverseSoundExTest("tmug", "G520")); }
        [TestMethod] public void ReverseSoundExTest344() { Assert.IsTrue(ReverseSoundExTest("Kisto", "O230")); }
        [TestMethod] public void ReverseSoundExTest345() { Assert.IsTrue(ReverseSoundExTest("iib", "B100")); }
        [TestMethod] public void ReverseSoundExTest346() { Assert.IsTrue(ReverseSoundExTest("wwwincredimail", "L526")); }
        [TestMethod] public void ReverseSoundExTest347() { Assert.IsTrue(ReverseSoundExTest("izpack", "K212")); }
        [TestMethod] public void ReverseSoundExTest348() { Assert.IsTrue(ReverseSoundExTest("gaymovie", "E510")); }
        [TestMethod] public void ReverseSoundExTest349() { Assert.IsTrue(ReverseSoundExTest("Buchholz", "Z242")); }
        [TestMethod] public void ReverseSoundExTest350() { Assert.IsTrue(ReverseSoundExTest("culcairn", "N426")); }
        [TestMethod] public void ReverseSoundExTest351() { Assert.IsTrue(ReverseSoundExTest("barys", "S620")); }
        [TestMethod] public void ReverseSoundExTest352() { Assert.IsTrue(ReverseSoundExTest("burets", "S632")); }
        [TestMethod] public void ReverseSoundExTest353() { Assert.IsTrue(ReverseSoundExTest("Sorce", "E620")); }
        [TestMethod] public void ReverseSoundExTest354() { Assert.IsTrue(ReverseSoundExTest("chimique", "E520")); }
        [TestMethod] public void ReverseSoundExTest355() { Assert.IsTrue(ReverseSoundExTest("kitada", "A330")); }
        [TestMethod] public void ReverseSoundExTest356() { Assert.IsTrue(ReverseSoundExTest("Engeman", "N525")); }
        [TestMethod] public void ReverseSoundExTest357() { Assert.IsTrue(ReverseSoundExTest("raveendran", "N153")); }
        [TestMethod] public void ReverseSoundExTest358() { Assert.IsTrue(ReverseSoundExTest("Bendele", "E534")); }
        [TestMethod] public void ReverseSoundExTest359() { Assert.IsTrue(ReverseSoundExTest("Pawlitschek", "K432")); }
        [TestMethod] public void ReverseSoundExTest360() { Assert.IsTrue(ReverseSoundExTest("hogfather", "R213")); }
        [TestMethod] public void ReverseSoundExTest361() { Assert.IsTrue(ReverseSoundExTest("eyedrum", "M365")); }
        [TestMethod] public void ReverseSoundExTest362() { Assert.IsTrue(ReverseSoundExTest("Ferrara", "A660")); }
        [TestMethod] public void ReverseSoundExTest363() { Assert.IsTrue(ReverseSoundExTest("zhuh", "H000")); }
        [TestMethod] public void ReverseSoundExTest364() { Assert.IsTrue(ReverseSoundExTest("zodiak", "K320")); }
        [TestMethod] public void ReverseSoundExTest365() { Assert.IsTrue(ReverseSoundExTest("pchcom", "M225")); }
        [TestMethod] public void ReverseSoundExTest366() { Assert.IsTrue(ReverseSoundExTest("conferees", "S516")); }
        [TestMethod] public void ReverseSoundExTest367() { Assert.IsTrue(ReverseSoundExTest("Decillis", "S242")); }
        [TestMethod] public void ReverseSoundExTest368() { Assert.IsTrue(ReverseSoundExTest("downloar", "R546")); }
        [TestMethod] public void ReverseSoundExTest369() { Assert.IsTrue(ReverseSoundExTest("shard", "D630")); }
        [TestMethod] public void ReverseSoundExTest370() { Assert.IsTrue(ReverseSoundExTest("fajr", "R260")); }
        [TestMethod] public void ReverseSoundExTest371() { Assert.IsTrue(ReverseSoundExTest("quisque", "E200")); }
        [TestMethod] public void ReverseSoundExTest372() { Assert.IsTrue(ReverseSoundExTest("winterizing", "G536")); }
        [TestMethod] public void ReverseSoundExTest373() { Assert.IsTrue(ReverseSoundExTest("referate", "E163")); }
        [TestMethod] public void ReverseSoundExTest374() { Assert.IsTrue(ReverseSoundExTest("nuxone", "E250")); }
        [TestMethod] public void ReverseSoundExTest375() { Assert.IsTrue(ReverseSoundExTest("Racheal", "L240")); }
        [TestMethod] public void ReverseSoundExTest376() { Assert.IsTrue(ReverseSoundExTest("bizben", "N215")); }
        [TestMethod] public void ReverseSoundExTest377() { Assert.IsTrue(ReverseSoundExTest("musictalk", "K223")); }
        [TestMethod] public void ReverseSoundExTest378() { Assert.IsTrue(ReverseSoundExTest("ogoal", "L240")); }
        [TestMethod] public void ReverseSoundExTest379() { Assert.IsTrue(ReverseSoundExTest("Skoff", "F100")); }
        [TestMethod] public void ReverseSoundExTest380() { Assert.IsTrue(ReverseSoundExTest("Seehusen", "N250")); }
        [TestMethod] public void ReverseSoundExTest381() { Assert.IsTrue(ReverseSoundExTest("Reim", "M500")); }
        [TestMethod] public void ReverseSoundExTest382() { Assert.IsTrue(ReverseSoundExTest("Yoh", "H000")); }
        [TestMethod] public void ReverseSoundExTest383() { Assert.IsTrue(ReverseSoundExTest("gapi", "I100")); }
        [TestMethod] public void ReverseSoundExTest384() { Assert.IsTrue(ReverseSoundExTest("Brightbill", "L623")); }
        [TestMethod] public void ReverseSoundExTest385() { Assert.IsTrue(ReverseSoundExTest("shuey", "Y000")); }
        [TestMethod] public void ReverseSoundExTest386() { Assert.IsTrue(ReverseSoundExTest("posium", "M250")); }
        [TestMethod] public void ReverseSoundExTest387() { Assert.IsTrue(ReverseSoundExTest("Falknor", "R425")); }
        [TestMethod] public void ReverseSoundExTest388() { Assert.IsTrue(ReverseSoundExTest("ucat", "T230")); }
        [TestMethod] public void ReverseSoundExTest389() { Assert.IsTrue(ReverseSoundExTest("properspace", "E616")); }
        [TestMethod] public void ReverseSoundExTest390() { Assert.IsTrue(ReverseSoundExTest("showimg", "G520")); }
        [TestMethod] public void ReverseSoundExTest391() { Assert.IsTrue(ReverseSoundExTest("Montecillo", "O532")); }
        [TestMethod] public void ReverseSoundExTest392() { Assert.IsTrue(ReverseSoundExTest("sajak", "K220")); }
        [TestMethod] public void ReverseSoundExTest393() { Assert.IsTrue(ReverseSoundExTest("maturbation", "N361")); }
        [TestMethod] public void ReverseSoundExTest394() { Assert.IsTrue(ReverseSoundExTest("Lettie", "E300")); }
        [TestMethod] public void ReverseSoundExTest395() { Assert.IsTrue(ReverseSoundExTest("clauss", "S420")); }
        [TestMethod] public void ReverseSoundExTest396() { Assert.IsTrue(ReverseSoundExTest("scheiber", "R160")); }
        [TestMethod] public void ReverseSoundExTest397() { Assert.IsTrue(ReverseSoundExTest("matp", "P310")); }
        [TestMethod] public void ReverseSoundExTest398() { Assert.IsTrue(ReverseSoundExTest("mervtormel", "L613")); }
        [TestMethod] public void ReverseSoundExTest399() { Assert.IsTrue(ReverseSoundExTest("guanahani", "I550")); }
        [TestMethod] public void ReverseSoundExTest400() { Assert.IsTrue(ReverseSoundExTest("citement", "T355")); }
        [TestMethod] public void ReverseSoundExTest401() { Assert.IsTrue(ReverseSoundExTest("immu", "U500")); }
        [TestMethod] public void ReverseSoundExTest402() { Assert.IsTrue(ReverseSoundExTest("virulence", "E645")); }
        [TestMethod] public void ReverseSoundExTest403() { Assert.IsTrue(ReverseSoundExTest("kussa", "A200")); }
        [TestMethod] public void ReverseSoundExTest404() { Assert.IsTrue(ReverseSoundExTest("gso", "O000")); }
        [TestMethod] public void ReverseSoundExTest405() { Assert.IsTrue(ReverseSoundExTest("webviajes", "S122")); }
        [TestMethod] public void ReverseSoundExTest406() { Assert.IsTrue(ReverseSoundExTest("ldwork", "K362")); }
        [TestMethod] public void ReverseSoundExTest407() { Assert.IsTrue(ReverseSoundExTest("verses", "S622")); }
        [TestMethod] public void ReverseSoundExTest408() { Assert.IsTrue(ReverseSoundExTest("sondes", "S532")); }
        [TestMethod] public void ReverseSoundExTest409() { Assert.IsTrue(ReverseSoundExTest("freshpair", "R621")); }
        [TestMethod] public void ReverseSoundExTest410() { Assert.IsTrue(ReverseSoundExTest("licorne", "E265")); }
        [TestMethod] public void ReverseSoundExTest411() { Assert.IsTrue(ReverseSoundExTest("Vanis", "S520")); }
        [TestMethod] public void ReverseSoundExTest412() { Assert.IsTrue(ReverseSoundExTest("Buena", "A500")); }
        [TestMethod] public void ReverseSoundExTest413() { Assert.IsTrue(ReverseSoundExTest("Tauares", "S620")); }
        [TestMethod] public void ReverseSoundExTest414() { Assert.IsTrue(ReverseSoundExTest("ikus", "S220")); }
        [TestMethod] public void ReverseSoundExTest415() { Assert.IsTrue(ReverseSoundExTest("genrebox", "X561")); }
        [TestMethod] public void ReverseSoundExTest416() { Assert.IsTrue(ReverseSoundExTest("rth", "H300")); }
        [TestMethod] public void ReverseSoundExTest417() { Assert.IsTrue(ReverseSoundExTest("Spaun", "N150")); }
        [TestMethod] public void ReverseSoundExTest418() { Assert.IsTrue(ReverseSoundExTest("wiersbe", "E621")); }
        [TestMethod] public void ReverseSoundExTest419() { Assert.IsTrue(ReverseSoundExTest("dad", "D300")); }
        [TestMethod] public void ReverseSoundExTest420() { Assert.IsTrue(ReverseSoundExTest("tus", "S200")); }
        [TestMethod] public void ReverseSoundExTest421() { Assert.IsTrue(ReverseSoundExTest("Weidert", "T363")); }
        [TestMethod] public void ReverseSoundExTest422() { Assert.IsTrue(ReverseSoundExTest("rijke", "E200")); }
        [TestMethod] public void ReverseSoundExTest423() { Assert.IsTrue(ReverseSoundExTest("fischbein", "N215")); }
        [TestMethod] public void ReverseSoundExTest424() { Assert.IsTrue(ReverseSoundExTest("fbeye", "E000")); }
        [TestMethod] public void ReverseSoundExTest425() { Assert.IsTrue(ReverseSoundExTest("hagerty", "Y263")); }
        [TestMethod] public void ReverseSoundExTest426() { Assert.IsTrue(ReverseSoundExTest("Hollendonner", "R453")); }
        [TestMethod] public void ReverseSoundExTest427() { Assert.IsTrue(ReverseSoundExTest("Huitzacua", "A322")); }
        [TestMethod] public void ReverseSoundExTest428() { Assert.IsTrue(ReverseSoundExTest("subjunctive", "E125")); }
        [TestMethod] public void ReverseSoundExTest429() { Assert.IsTrue(ReverseSoundExTest("implored", "D514")); }
        [TestMethod] public void ReverseSoundExTest430() { Assert.IsTrue(ReverseSoundExTest("pompeius", "S512")); }
        [TestMethod] public void ReverseSoundExTest431() { Assert.IsTrue(ReverseSoundExTest("afleet", "T143")); }
        [TestMethod] public void ReverseSoundExTest432() { Assert.IsTrue(ReverseSoundExTest("iacc", "C200")); }
        [TestMethod] public void ReverseSoundExTest433() { Assert.IsTrue(ReverseSoundExTest("sabalos", "S142")); }
        [TestMethod] public void ReverseSoundExTest434() { Assert.IsTrue(ReverseSoundExTest("Abdi", "I130")); }
        [TestMethod] public void ReverseSoundExTest435() { Assert.IsTrue(ReverseSoundExTest("microinsurance", "E265")); }
        [TestMethod] public void ReverseSoundExTest436() { Assert.IsTrue(ReverseSoundExTest("audiobook", "K312")); }
        [TestMethod] public void ReverseSoundExTest437() { Assert.IsTrue(ReverseSoundExTest("fulpmes", "S415")); }
        [TestMethod] public void ReverseSoundExTest438() { Assert.IsTrue(ReverseSoundExTest("registreren", "N223")); }
        [TestMethod] public void ReverseSoundExTest439() { Assert.IsTrue(ReverseSoundExTest("megapath", "H213")); }
        [TestMethod] public void ReverseSoundExTest440() { Assert.IsTrue(ReverseSoundExTest("prestidigitation", "N623")); }
        [TestMethod] public void ReverseSoundExTest441() { Assert.IsTrue(ReverseSoundExTest("wby", "Y100")); }
        [TestMethod] public void ReverseSoundExTest442() { Assert.IsTrue(ReverseSoundExTest("vorschau", "U620")); }
        [TestMethod] public void ReverseSoundExTest443() { Assert.IsTrue(ReverseSoundExTest("Albertha", "A416")); }
        [TestMethod] public void ReverseSoundExTest444() { Assert.IsTrue(ReverseSoundExTest("aspalpha", "A214")); }
        [TestMethod] public void ReverseSoundExTest445() { Assert.IsTrue(ReverseSoundExTest("Belden", "N435")); }
        [TestMethod] public void ReverseSoundExTest446() { Assert.IsTrue(ReverseSoundExTest("deterministic", "C365")); }
        [TestMethod] public void ReverseSoundExTest447() { Assert.IsTrue(ReverseSoundExTest("philosophique", "E421")); }
        [TestMethod] public void ReverseSoundExTest448() { Assert.IsTrue(ReverseSoundExTest("kleinen", "N455")); }
        [TestMethod] public void ReverseSoundExTest449() { Assert.IsTrue(ReverseSoundExTest("logouri", "I260")); }
        [TestMethod] public void ReverseSoundExTest450() { Assert.IsTrue(ReverseSoundExTest("xbl", "L140")); }
        [TestMethod] public void ReverseSoundExTest451() { Assert.IsTrue(ReverseSoundExTest("iz", "Z200")); }
        [TestMethod] public void ReverseSoundExTest452() { Assert.IsTrue(ReverseSoundExTest("throckmorton", "N625")); }
        [TestMethod] public void ReverseSoundExTest453() { Assert.IsTrue(ReverseSoundExTest("condesa", "A532")); }
        [TestMethod] public void ReverseSoundExTest454() { Assert.IsTrue(ReverseSoundExTest("Mook", "K200")); }
        [TestMethod] public void ReverseSoundExTest455() { Assert.IsTrue(ReverseSoundExTest("medseek", "K322")); }
        [TestMethod] public void ReverseSoundExTest456() { Assert.IsTrue(ReverseSoundExTest("chugalug", "G242")); }
        [TestMethod] public void ReverseSoundExTest457() { Assert.IsTrue(ReverseSoundExTest("olms", "S452")); }
        [TestMethod] public void ReverseSoundExTest458() { Assert.IsTrue(ReverseSoundExTest("bogo", "O200")); }
        [TestMethod] public void ReverseSoundExTest459() { Assert.IsTrue(ReverseSoundExTest("essing", "G252")); }
        [TestMethod] public void ReverseSoundExTest460() { Assert.IsTrue(ReverseSoundExTest("rarden", "N635")); }
        [TestMethod] public void ReverseSoundExTest461() { Assert.IsTrue(ReverseSoundExTest("mittlere", "E346")); }
        [TestMethod] public void ReverseSoundExTest462() { Assert.IsTrue(ReverseSoundExTest("Borsa", "A620")); }
        [TestMethod] public void ReverseSoundExTest463() { Assert.IsTrue(ReverseSoundExTest("Ainslie", "E524")); }
        [TestMethod] public void ReverseSoundExTest464() { Assert.IsTrue(ReverseSoundExTest("Ganska", "A520")); }
        [TestMethod] public void ReverseSoundExTest465() { Assert.IsTrue(ReverseSoundExTest("miv", "V100")); }
        [TestMethod] public void ReverseSoundExTest466() { Assert.IsTrue(ReverseSoundExTest("concessions", "S522")); }
        [TestMethod] public void ReverseSoundExTest467() { Assert.IsTrue(ReverseSoundExTest("distinguished", "D235")); }
        [TestMethod] public void ReverseSoundExTest468() { Assert.IsTrue(ReverseSoundExTest("cano", "O500")); }
        [TestMethod] public void ReverseSoundExTest469() { Assert.IsTrue(ReverseSoundExTest("plumper", "R451")); }
        [TestMethod] public void ReverseSoundExTest470() { Assert.IsTrue(ReverseSoundExTest("mindoro", "O536")); }
        [TestMethod] public void ReverseSoundExTest471() { Assert.IsTrue(ReverseSoundExTest("cephalopod", "D141")); }
        [TestMethod] public void ReverseSoundExTest472() { Assert.IsTrue(ReverseSoundExTest("Klunk", "K452")); }
        [TestMethod] public void ReverseSoundExTest473() { Assert.IsTrue(ReverseSoundExTest("Bumbrey", "Y516")); }
        [TestMethod] public void ReverseSoundExTest474() { Assert.IsTrue(ReverseSoundExTest("causeless", "S242")); }
        [TestMethod] public void ReverseSoundExTest475() { Assert.IsTrue(ReverseSoundExTest("Lothrop", "P361")); }
        [TestMethod] public void ReverseSoundExTest476() { Assert.IsTrue(ReverseSoundExTest("bodystyles", "S323")); }
        [TestMethod] public void ReverseSoundExTest477() { Assert.IsTrue(ReverseSoundExTest("beaatiality", "Y343")); }
        [TestMethod] public void ReverseSoundExTest478() { Assert.IsTrue(ReverseSoundExTest("Bobrowski", "I162")); }
        [TestMethod] public void ReverseSoundExTest479() { Assert.IsTrue(ReverseSoundExTest("erudition", "N633")); }
        [TestMethod] public void ReverseSoundExTest480() { Assert.IsTrue(ReverseSoundExTest("huttner", "R356")); }
        [TestMethod] public void ReverseSoundExTest481() { Assert.IsTrue(ReverseSoundExTest("wwwaskjeevescom", "M212")); }
        [TestMethod] public void ReverseSoundExTest482() { Assert.IsTrue(ReverseSoundExTest("Duross", "S620")); }
        [TestMethod] public void ReverseSoundExTest483() { Assert.IsTrue(ReverseSoundExTest("Colemen", "N455")); }
        [TestMethod] public void ReverseSoundExTest484() { Assert.IsTrue(ReverseSoundExTest("Duncomb", "B525")); }
        [TestMethod] public void ReverseSoundExTest485() { Assert.IsTrue(ReverseSoundExTest("tripe", "E610")); }
        [TestMethod] public void ReverseSoundExTest486() { Assert.IsTrue(ReverseSoundExTest("dorrigo", "O620")); }
        [TestMethod] public void ReverseSoundExTest487() { Assert.IsTrue(ReverseSoundExTest("Mascall", "L240")); }
        [TestMethod] public void ReverseSoundExTest488() { Assert.IsTrue(ReverseSoundExTest("jetplane", "E314")); }
        [TestMethod] public void ReverseSoundExTest489() { Assert.IsTrue(ReverseSoundExTest("nswrl", "L264")); }
        [TestMethod] public void ReverseSoundExTest490() { Assert.IsTrue(ReverseSoundExTest("didates", "S332")); }
        [TestMethod] public void ReverseSoundExTest491() { Assert.IsTrue(ReverseSoundExTest("Jena", "A500")); }
        [TestMethod] public void ReverseSoundExTest492() { Assert.IsTrue(ReverseSoundExTest("kctu", "U300")); }
        [TestMethod] public void ReverseSoundExTest493() { Assert.IsTrue(ReverseSoundExTest("cualquiera", "A426")); }
        [TestMethod] public void ReverseSoundExTest494() { Assert.IsTrue(ReverseSoundExTest("plutella", "A434")); }
        [TestMethod] public void ReverseSoundExTest495() { Assert.IsTrue(ReverseSoundExTest("Liebig", "G120")); }
        [TestMethod] public void ReverseSoundExTest496() { Assert.IsTrue(ReverseSoundExTest("Llorens", "S652")); }
        [TestMethod] public void ReverseSoundExTest497() { Assert.IsTrue(ReverseSoundExTest("mraz", "Z620")); }
        [TestMethod] public void ReverseSoundExTest498() { Assert.IsTrue(ReverseSoundExTest("shadyac", "C320")); }
        [TestMethod] public void ReverseSoundExTest499() { Assert.IsTrue(ReverseSoundExTest("lossphentermine", "E215")); }
        [TestMethod] public void ReverseSoundExTest500() { Assert.IsTrue(ReverseSoundExTest("Dreith", "H630")); }
        [TestMethod] public void ReverseSoundExTest501() { Assert.IsTrue(ReverseSoundExTest("Windsor", "R532")); }

    }
}