//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Element34.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Element34.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2000 {
            get {
                object obj = ResourceManager.GetObject("Access2000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2003 {
            get {
                object obj = ResourceManager.GetObject("Access2003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2007 {
            get {
                object obj = ResourceManager.GetObject("Access2007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2010 {
            get {
                object obj = ResourceManager.GetObject("Access2010", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2016 {
            get {
                object obj = ResourceManager.GetObject("Access2016", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2019 {
            get {
                object obj = ResourceManager.GetObject("Access2019", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Format
        ///// &quot;pattern&quot; &quot;replacement at start of word&quot; &quot;replacement before a vowel&quot; &quot;replacement in other cases&quot;
        ///
        ///// Vowels
        ///
        ///&quot;a&quot; &quot;0&quot; &quot;&quot; &quot;&quot;
        ///&quot;e&quot; &quot;0&quot; &quot;&quot; &quot;&quot;
        ///&quot;i&quot; &quot;0&quot; &quot;&quot; &quot;&quot;
        ///&quot;o&quot; &quot;0&quot; &quot;&quot; &quot;&quot;
        ///&quot;u&quot; &quot;0&quot; &quot;&quot; &quot;&quot;
        ///
        ///// Consonants
        ///
        ///&quot;b&quot; &quot;7&quot; &quot;7&quot; &quot;7&quot;
        ///&quot;d&quot; &quot;3&quot; &quot;3&quot; &quot;3&quot;
        ///&quot;f&quot; &quot;7&quot; &quot;7&quot; &quot;7&quot;
        ///&quot;g&quot; &quot;5&quot; &quot;5&quot; &quot;5&quot;
        ///&quot;h&quot; &quot;5&quot; &quot;5&quot; &quot;&quot;
        ///&quot;k&quot; &quot;5&quot; &quot;5&quot; &quot;5&quot;
        ///&quot;l&quot; &quot;8&quot; &quot;8&quot; &quot;8&quot;
        ///&quot;m&quot; &quot;6&quot; &quot;6&quot; &quot;6&quot;
        ///&quot;n&quot; &quot;6&quot; &quot;6&quot; &quot;6&quot;
        ///&quot;p&quot; &quot;7&quot; &quot;7&quot; &quo....
        /// </summary>
        internal static string DMrules {
            get {
                return ResourceManager.GetString("DMrules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Element34 {
            get {
                object obj = ResourceManager.GetObject("Element34", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..
        /// </summary>
        internal static string Lorem_Ipsum {
            get {
                return ResourceManager.GetString("Lorem_Ipsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ArrayOfanyType xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///	&lt;anyType xmlns:d2p1=&quot;http://www.w3.org/2001/XMLSchema&quot; i:type=&quot;d2p1:string&quot;&gt;a&lt;/anyType&gt;
        ///	&lt;anyType xmlns:d2p1=&quot;http://www.w3.org/2001/XMLSchema&quot; i:type=&quot;d2p1:string&quot;&gt;abaft&lt;/anyType&gt;
        ///	&lt;anyType xmlns:d2p1=&quot;http://www.w3.org/2001/XMLSchema&quot; i:type=&quot;d2p1:string&quot;&gt;abafter&lt;/anyType&gt;
        ///	&lt;anyType xmlns:d2p1=&quot;http://www.w3.org/2001/XMLSchema&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stopWordList {
            get {
                return ResourceManager.GetString("stopWordList", resourceCulture);
            }
        }
    }
}
