//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Element34.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Element34.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2000 {
            get {
                object obj = ResourceManager.GetObject("Access2000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2003 {
            get {
                object obj = ResourceManager.GetObject("Access2003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2007 {
            get {
                object obj = ResourceManager.GetObject("Access2007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2010 {
            get {
                object obj = ResourceManager.GetObject("Access2010", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2016 {
            get {
                object obj = ResourceManager.GetObject("Access2016", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Access2019 {
            get {
                object obj = ResourceManager.GetObject("Access2019", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Format
        ///// &quot;pattern&quot; &quot;replacement at start of word&quot; &quot;replacement before a vowel&quot; &quot;replacement in other cases&quot;
        ///
        ///// Vowels
        ///
        ///&quot;a&quot; &quot;0&quot; &quot;&quot; &quot;&quot;
        ///&quot;e&quot; &quot;0&quot; &quot;&quot; &quot;&quot;
        ///&quot;i&quot; &quot;0&quot; &quot;&quot; &quot;&quot;
        ///&quot;o&quot; &quot;0&quot; &quot;&quot; &quot;&quot;
        ///&quot;u&quot; &quot;0&quot; &quot;&quot; &quot;&quot;
        ///
        ///// Consonants
        ///
        ///&quot;b&quot; &quot;7&quot; &quot;7&quot; &quot;7&quot;
        ///&quot;d&quot; &quot;3&quot; &quot;3&quot; &quot;3&quot;
        ///&quot;f&quot; &quot;7&quot; &quot;7&quot; &quot;7&quot;
        ///&quot;g&quot; &quot;5&quot; &quot;5&quot; &quot;5&quot;
        ///&quot;h&quot; &quot;5&quot; &quot;5&quot; &quot;&quot;
        ///&quot;k&quot; &quot;5&quot; &quot;5&quot; &quot;5&quot;
        ///&quot;l&quot; &quot;8&quot; &quot;8&quot; &quot;8&quot;
        ///&quot;m&quot; &quot;6&quot; &quot;6&quot; &quot;6&quot;
        ///&quot;n&quot; &quot;6&quot; &quot;6&quot; &quot;6&quot;
        ///&quot;p&quot; &quot;7&quot; &quot;7&quot; &quo....
        /// </summary>
        internal static string DMrules {
            get {
                return ResourceManager.GetString("DMrules", resourceCulture);
            }
        }
    }
}
